-- Truncate catálogo PHB (ordem FK-safe)
-- Lote C: updated for phb_option_def/value unificado

TRUNCATE TABLE
  rpg.phb_eldritch_invocation,
  rpg.phb_class_ability_boost,
  rpg.phb_resource_grant,
  rpg.phb_combat_modifier,
  rpg.phb_subclass_progression,
  rpg.phb_subclass_spellcasting,
  rpg.phb_subclass_prepared_spell,
  rpg.phb_subclass_feature,
  rpg.phb_spell_class,
  rpg.phb_class_skill_pool,
  rpg.phb_class_feature,
  rpg.phb_starting_item,
  rpg.phb_starting_package,
  rpg.phb_class_spellcasting,
  rpg.phb_class_proficiency,
  rpg.phb_class_progression,
  rpg.phb_background_ability_option,
  rpg.phb_background_skill,
  rpg.phb_background_language,
  rpg.phb_background_tool_option,
  rpg.phb_spell_grant,
  rpg.phb_species_trait,
  rpg.phb_tool,
  rpg.phb_armor,
  rpg.phb_tool_category,
  rpg.phb_armor_category,
  rpg.phb_weapon,
  rpg.phb_weapon_mastery,
  rpg.phb_weapon_property_link,
  rpg.phb_item,
  rpg.phb_subclass,
  rpg.phb_class,
  rpg.phb_spell_slot_by_level,
  rpg.phb_spell_slot_pattern,
  rpg.phb_background,
  rpg.phb_species,
  rpg.phb_spell,
  rpg.phb_spell_school,
  rpg.phb_feat_benefit,
  rpg.phb_feat,
  rpg.phb_weapon_property,
  rpg.phb_fighting_style,
  rpg.phb_skill,
  rpg.phb_ability,
  rpg.phb_language,
  rpg.phb_alignment,
  rpg.phb_source_citation,
  rpg.phb_option_value,
  rpg.phb_option_def,
  rpg.phb_spell_source,
  rpg.phb_resource_definition,
  rpg.phb_background_boost_option,
  rpg.phb_character_level
RESTART IDENTITY CASCADE;
