-- Armas avançadas Grim Hollow (Cap. 5)

INSERT INTO rpg.phb_item (slug, item_type, name, cost, weight, description, properties)
VALUES
  ('catchpole', 'weapon'::rpg.item_type, 'Forquilha de Captura', '{"text":"500 PO"}'::jsonb, '2,5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["hafted","reach","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"entangling"}'::jsonb),
  ('cavalry-flail', 'weapon'::rpg.item_type, 'Mangual de Cavalaria', '{"text":"500 PO"}'::jsonb, '1,5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["momentum"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"swift","momentumDice":"1d12"}'::jsonb),
  ('cavalry-hammer', 'weapon'::rpg.item_type, 'Martelo de Cavalaria', '{"text":"500 PO"}'::jsonb, '1,5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["armor-piercing","momentum"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"slow","momentumDice":"1d12"}'::jsonb),
  ('cavalry-pick', 'weapon'::rpg.item_type, 'Picareta de Cavalaria', '{"text":"500 PO"}'::jsonb, '1,5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["armor-piercing","momentum"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"sap","momentumDice":"1d12"}'::jsonb),
  ('chakram', 'weapon'::rpg.item_type, 'Chakram', '{"text":"500 PO"}'::jsonb, '500 g', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["finesse","light","thrown"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"returning","range":{"normal":45,"max":180}}'::jsonb),
  ('claymore', 'weapon'::rpg.item_type, 'Claymore', '{"text":"500 PO"}'::jsonb, '3,5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["heavy","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"brutal"}'::jsonb),
  ('double-blade', 'weapon'::rpg.item_type, 'Lâmina Dupla', '{"text":"500 PO"}'::jsonb, '2,5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["double","momentum","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"set","momentumDice":"1d10"}'::jsonb),
  ('double-spear', 'weapon'::rpg.item_type, 'Lança Dupla', '{"text":"500 PO"}'::jsonb, '2 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["double","momentum","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"set","momentumDice":"1d10"}'::jsonb),
  ('elite-rapier', 'weapon'::rpg.item_type, 'Rapieira de Elite', '{"text":"500 PO"}'::jsonb, '1 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["finesse"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"swift"}'::jsonb),
  ('fighting-chain', 'weapon'::rpg.item_type, 'Corrente de Combate', '{"text":"500 PO"}'::jsonb, '1,5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["double","finesse","reach","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"disarming"}'::jsonb),
  ('fighting-chain-brutal', 'weapon'::rpg.item_type, 'Corrente de Combate, Brutal', '{"text":"750 PO"}'::jsonb, '3 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["double","finesse","reach","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"brutal"}'::jsonb),
  ('fighting-chain-hook', 'weapon'::rpg.item_type, 'Corrente de Combate, Gancho', '{"text":"500 PO"}'::jsonb, '1,5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["damage","double","finesse","reach","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"entangling","damageTypes":["Piercing"]}'::jsonb),
  ('fighting-chain-sickle', 'weapon'::rpg.item_type, 'Corrente de Combate, Foice', '{"text":"500 PO"}'::jsonb, '1,5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["damage","double","finesse","reach","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"entangling","damageTypes":["Slashing"]}'::jsonb),
  ('gladiator-net', 'weapon'::rpg.item_type, 'Rede de Gladiador', '{"text":"350 PO"}'::jsonb, '2,5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["thrown"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"entangling","range":{"normal":15,"max":45}}'::jsonb),
  ('guardian-poleaxe', 'weapon'::rpg.item_type, 'Bordão-Machado Guardião', '{"text":"750 PO"}'::jsonb, '4,5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["damage","hafted","heavy","reach","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"set","damageTypes":["Piercing"]}'::jsonb),
  ('knightly-lance', 'weapon'::rpg.item_type, 'Lança de Cavaleiro', '{"text":"500 PO"}'::jsonb, '3 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["momentum","reach","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"set","momentumDice":"2d10"}'::jsonb),
  ('knightly-sword', 'weapon'::rpg.item_type, 'Espada de Cavaleiro', '{"text":"750 PO"}'::jsonb, '1,5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["versatile"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"defending","versatileDamage":"1d10"}'::jsonb),
  ('military-fork', 'weapon'::rpg.item_type, 'Forquilha Militar', '{"text":"500 PO"}'::jsonb, '4 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["hafted","heavy","reach","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"disarming"}'::jsonb),
  ('parrying-dagger', 'weapon'::rpg.item_type, 'Adaga de Aparar', '{"text":"350 PO"}'::jsonb, '500 g', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["finesse","light","thrown"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"disarming","range":{"normal":30,"max":90}}'::jsonb),
  ('polearm', 'weapon'::rpg.item_type, 'Arma de Haste', '{"text":"500 PO"}'::jsonb, '6 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["hafted","heavy","reach","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"set"}'::jsonb),
  ('punching-dagger', 'weapon'::rpg.item_type, 'Adaga de Soco', '{"text":"300 PO"}'::jsonb, '500 g', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["armor-piercing","finesse","light"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"defending"}'::jsonb),
  ('returning-club', 'weapon'::rpg.item_type, 'Clava Retornável', '{"text":"300 PO"}'::jsonb, '1 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["light","thrown"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"returning","range":{"normal":30,"max":90}}'::jsonb),
  ('sabre', 'weapon'::rpg.item_type, 'Sabre', '{"text":"500 PO"}'::jsonb, '1 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["finesse"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"swift"}'::jsonb),
  ('sheathed-staff', 'weapon'::rpg.item_type, 'Bordão Embainhado', '{"text":"500 PO"}'::jsonb, '3 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["double","versatile"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"topple","versatileDamage":"1d8"}'::jsonb),
  ('side-handle-baton', 'weapon'::rpg.item_type, 'Bastão de Cabo Lateral', '{"text":"500 PO"}'::jsonb, '1 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["finesse","light"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"swift"}'::jsonb),
  ('wrath-axe', 'weapon'::rpg.item_type, 'Machado da Ira', '{"text":"750 PO"}'::jsonb, '6 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["hafted","momentum","heavy","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"brutal","momentumDice":"2d8"}'::jsonb),
  ('wrath-maul', 'weapon'::rpg.item_type, 'Malho da Ira', '{"text":"750 PO"}'::jsonb, '7,5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["hafted","momentum","heavy","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"brutal","momentumDice":"2d8"}'::jsonb),
  ('arbalest', 'weapon'::rpg.item_type, 'Arcobalista', '{"text":"750 PO"}'::jsonb, '10 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["heavy","two-handed","loading","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"range":{"normal":120,"max":450}}'::jsonb),
  ('blackpowder-pistol', 'weapon'::rpg.item_type, 'Pistola de Pólvora', '{"text":"200 PO"}'::jsonb, '2 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["blackpowder","light","loading","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"vex","range":{"normal":30,"max":120}}'::jsonb),
  ('blackpowder-rifle', 'weapon'::rpg.item_type, 'Rifle de Pólvora', '{"text":"500 PO"}'::jsonb, '5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["blackpowder","two-handed","loading","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"slow","range":{"normal":120,"max":450}}'::jsonb),
  ('blunderbuss-grim-hollow', 'weapon'::rpg.item_type, 'Bacamarte', '{"text":"750 PO"}'::jsonb, '5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["blackpowder","cumbersome","two-handed","loading","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"scatter","range":{"normal":45,"max":135}}'::jsonb),
  ('blunderbuss-hand', 'weapon'::rpg.item_type, 'Bacamarte de Mão', '{"text":"500 PO"}'::jsonb, '2 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["blackpowder","loading","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"scatter","range":{"normal":22.5,"max":90}}'::jsonb),
  ('composite-longbow', 'weapon'::rpg.item_type, 'Arco Longo Composto', '{"text":"750 PO"}'::jsonb, '1 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["heavy","two-handed","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"range":{"normal":300,"max":900}}'::jsonb),
  ('composite-shortbow', 'weapon'::rpg.item_type, 'Arco Curto Composto', '{"text":"400 PO"}'::jsonb, '1 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["two-handed","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"range":{"normal":150,"max":600}}'::jsonb),
  ('dragon-pistol', 'weapon'::rpg.item_type, 'Pistola Dragão', '{"text":"350 PO"}'::jsonb, '2 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["blackpowder","loading","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"scatter"}'::jsonb),
  ('dragon-rifle', 'weapon'::rpg.item_type, 'Rifle Dragão', '{"text":"750 PO"}'::jsonb, '2 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["blackpowder","loading","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"scatter"}'::jsonb),
  ('flame-bellows', 'weapon'::rpg.item_type, 'Fole de Chamas', '{"text":"750 PO"}'::jsonb, '5,5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["cumbersome","magazine","two-handed","loading","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"scatter","magazine":"20"}'::jsonb),
  ('repeater-crossbow', 'weapon'::rpg.item_type, 'Besta Repetidora', '{"text":"750 PO"}'::jsonb, '3,5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["magazine","repeater","two-handed","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"slow","range":{"normal":120,"max":450},"magazine":"6"}'::jsonb),
  ('repeater-crossbow-hand', 'weapon'::rpg.item_type, 'Besta Repetidora de Mão', '{"text":"500 PO"}'::jsonb, '1,5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["magazine","repeater","light","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"vex","range":{"normal":45,"max":180},"magazine":"3"}'::jsonb),
  ('repeater-crossbow-heavy', 'weapon'::rpg.item_type, 'Besta Repetidora Pesada', '{"text":"1,000 PO"}'::jsonb, '10 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["magazine","repeater","heavy","two-handed","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"range":{"normal":150,"max":600},"magazine":"9"}'::jsonb),
  ('repeater-needler', 'weapon'::rpg.item_type, 'Agulheiro Repetidor', '{"text":"500 PO"}'::jsonb, '1,5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["magazine","repeater","light","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"vex","range":{"normal":45,"max":180},"magazine":"6"}'::jsonb),
  ('repeater-slinger', 'weapon'::rpg.item_type, 'Funda Repetidora', '{"text":"750 PO"}'::jsonb, '4,5 kg', 'Arma avançada de Grim Hollow. Sem proficiência em Armas Avançadas, você tem Desvantagem nos ataques. Propriedades marcadas com * e maestrias exigem o talento Proficiência em Armas Avançadas (Estilo de Luta ou talento Geral a partir do nível 8).', '{"propertyIds":["magazine","repeater","two-handed","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"advanced-weapon","ddbKind":"weapons","advancedRequirement":{"kind":"advanced-weapon","proficiencySlug":"armas-avancadas","featSlug":"advanced-weapon-proficiency","fightingStyleSlug":"advanced-weapon-proficiency","disadvantageWithoutProficiency":true,"specialPropertiesRequireProficiency":true,"masteryRequiresAdvancedProficiency":true},"masteryId":"slow","range":{"normal":120,"max":450},"magazine":"9"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  cost = EXCLUDED.cost,
  weight = EXCLUDED.weight,
  description = EXCLUDED.description,
  properties = EXCLUDED.properties,
  item_type = EXCLUDED.item_type;

INSERT INTO rpg.phb_weapon (item_id, category, damage, damage_type, mastery_id)
VALUES
  ((SELECT id FROM rpg.phb_item WHERE slug = 'catchpole'), 'advanced'::rpg.weapon_category, '1d6', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'entangling')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'cavalry-flail'), 'advanced'::rpg.weapon_category, '1d8', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'swift')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'cavalry-hammer'), 'advanced'::rpg.weapon_category, '1d8', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'slow')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'cavalry-pick'), 'advanced'::rpg.weapon_category, '1d8', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'sap')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'chakram'), 'advanced'::rpg.weapon_category, '1d6', 'Cortante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'returning')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'claymore'), 'advanced'::rpg.weapon_category, '2d6', 'Cortante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'brutal')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'double-blade'), 'advanced'::rpg.weapon_category, '1d6', 'Cortante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'set')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'double-spear'), 'advanced'::rpg.weapon_category, '1d6', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'set')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'elite-rapier'), 'advanced'::rpg.weapon_category, '1d8', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'swift')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain'), 'advanced'::rpg.weapon_category, '1d4', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'disarming')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-brutal'), 'advanced'::rpg.weapon_category, '1d6', 'Cortante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'brutal')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-hook'), 'advanced'::rpg.weapon_category, '1d4', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'entangling')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-sickle'), 'advanced'::rpg.weapon_category, '1d4', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'entangling')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'gladiator-net'), 'advanced'::rpg.weapon_category, '1d6', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'entangling')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'guardian-poleaxe'), 'advanced'::rpg.weapon_category, '1d10', 'Cortante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'set')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'knightly-lance'), 'advanced'::rpg.weapon_category, '2d6', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'set')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'knightly-sword'), 'advanced'::rpg.weapon_category, '1d8', 'Cortante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'defending')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'military-fork'), 'advanced'::rpg.weapon_category, '2d6', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'disarming')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'parrying-dagger'), 'advanced'::rpg.weapon_category, '1d4', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'disarming')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'polearm'), 'advanced'::rpg.weapon_category, '1d12', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'set')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'punching-dagger'), 'advanced'::rpg.weapon_category, '1d4', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'defending')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'returning-club'), 'advanced'::rpg.weapon_category, '1d4', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'returning')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'sabre'), 'advanced'::rpg.weapon_category, '1d8', 'Cortante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'swift')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'sheathed-staff'), 'advanced'::rpg.weapon_category, '1d6', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'topple')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'side-handle-baton'), 'advanced'::rpg.weapon_category, '1d4', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'swift')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-axe'), 'advanced'::rpg.weapon_category, '2d6', 'Cortante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'brutal')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-maul'), 'advanced'::rpg.weapon_category, '2d6', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'brutal')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'arbalest'), 'advanced'::rpg.weapon_category, '2d6', 'Perfurante', NULL),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-pistol'), 'advanced'::rpg.weapon_category, '2d4', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'vex')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-rifle'), 'advanced'::rpg.weapon_category, '2d6', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'slow')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-grim-hollow'), 'advanced'::rpg.weapon_category, '2d6', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'scatter')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-hand'), 'advanced'::rpg.weapon_category, '2d4', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'scatter')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'composite-longbow'), 'advanced'::rpg.weapon_category, '1d8', 'Perfurante', NULL),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'composite-shortbow'), 'advanced'::rpg.weapon_category, '1d6', 'Perfurante', NULL),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'dragon-pistol'), 'advanced'::rpg.weapon_category, '2d4', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'scatter')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'dragon-rifle'), 'advanced'::rpg.weapon_category, '2d6', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'scatter')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'flame-bellows'), 'advanced'::rpg.weapon_category, '2d6', 'Fire', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'scatter')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow'), 'advanced'::rpg.weapon_category, '1d8', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'slow')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-hand'), 'advanced'::rpg.weapon_category, '1d6', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'vex')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-heavy'), 'advanced'::rpg.weapon_category, '1d10', 'Perfurante', NULL),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-needler'), 'advanced'::rpg.weapon_category, '1 Piercing', 'null', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'vex')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-slinger'), 'advanced'::rpg.weapon_category, '1d8', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'slow'))
ON CONFLICT (item_id) DO UPDATE SET
  category = EXCLUDED.category,
  damage = EXCLUDED.damage,
  damage_type = EXCLUDED.damage_type,
  mastery_id = EXCLUDED.mastery_id;

INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'catchpole'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'hafted')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'catchpole'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'reach')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'catchpole'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'cavalry-flail'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'momentum')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'cavalry-hammer'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'armor-piercing')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'cavalry-hammer'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'momentum')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'cavalry-pick'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'armor-piercing')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'cavalry-pick'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'momentum')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'chakram'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'chakram'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'light')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'chakram'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'thrown')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'claymore'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'heavy')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'claymore'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'double-blade'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'double')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'double-blade'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'momentum')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'double-blade'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'double-spear'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'double')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'double-spear'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'momentum')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'double-spear'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'elite-rapier'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'double')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'reach')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-brutal'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'double')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-brutal'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-brutal'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'reach')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-brutal'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-hook'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'damage')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-hook'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'double')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-hook'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-hook'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'reach')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-hook'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-sickle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'damage')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-sickle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'double')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-sickle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-sickle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'reach')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-sickle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'gladiator-net'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'thrown')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'guardian-poleaxe'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'damage')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'guardian-poleaxe'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'hafted')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'guardian-poleaxe'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'heavy')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'guardian-poleaxe'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'reach')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'guardian-poleaxe'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'knightly-lance'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'momentum')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'knightly-lance'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'reach')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'knightly-lance'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'knightly-sword'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'versatile')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'military-fork'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'hafted')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'military-fork'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'heavy')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'military-fork'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'reach')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'military-fork'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'parrying-dagger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'parrying-dagger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'light')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'parrying-dagger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'thrown')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'polearm'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'hafted')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'polearm'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'heavy')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'polearm'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'reach')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'polearm'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'punching-dagger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'armor-piercing')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'punching-dagger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'punching-dagger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'light')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'returning-club'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'light')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'returning-club'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'thrown')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'sabre'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'sheathed-staff'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'double')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'sheathed-staff'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'versatile')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'side-handle-baton'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'side-handle-baton'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'light')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-axe'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'hafted')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-axe'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'momentum')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-axe'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'heavy')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-axe'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-maul'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'hafted')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-maul'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'momentum')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-maul'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'heavy')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-maul'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'arbalest'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'heavy')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'arbalest'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'arbalest'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'loading')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'arbalest'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-pistol'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'blackpowder')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-pistol'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'light')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-pistol'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'loading')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-pistol'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-rifle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'blackpowder')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-rifle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-rifle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'loading')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-rifle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-grim-hollow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'blackpowder')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-grim-hollow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'cumbersome')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-grim-hollow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-grim-hollow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'loading')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-grim-hollow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-hand'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'blackpowder')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-hand'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'loading')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-hand'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'composite-longbow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'heavy')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'composite-longbow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'composite-longbow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'composite-shortbow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'composite-shortbow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'dragon-pistol'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'blackpowder')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'dragon-pistol'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'loading')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'dragon-pistol'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'dragon-rifle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'blackpowder')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'dragon-rifle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'loading')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'dragon-rifle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'flame-bellows'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'cumbersome')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'flame-bellows'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'magazine')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'flame-bellows'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'flame-bellows'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'loading')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'flame-bellows'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'magazine')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'repeater')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-hand'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'magazine')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-hand'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'repeater')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-hand'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'light')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-hand'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-heavy'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'magazine')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-heavy'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'repeater')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-heavy'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'heavy')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-heavy'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-heavy'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-needler'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'magazine')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-needler'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'repeater')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-needler'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'light')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-needler'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-slinger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'magazine')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-slinger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'repeater')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-slinger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-slinger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
