-- Equipamento avançado Grim Hollow (Cap. 5) — gear, focos, upgrades, venenos

INSERT INTO rpg.phb_item (slug, item_type, name, cost, weight, description, properties)
VALUES
  ('blessed-stake', 'gear'::rpg.item_type, 'Estaca Abençoada', '{"text":"250 PO"}'::jsonb, '50 g', 'A Estaca Abençoada é ferramenta indispensável no arsenal de caçadores de vampiros. Este estoque de madeira, com cerca de 30 cm, foi abençoado por um servo de um Arquisserafim em cerimônia especial. Como ação Atacar, quem empunha pode fazer um ataque corpo a corpo usando Força. Contra a maioria dos inimigos, causa 1d4 de dano Perfurante. Contra um Vampiro com as condições Atordoado ou Incapacitado, um ataque bem-sucedido com a Estaca Abençoada mata o Vampiro. Se o Vampiro tiver ND 10 ou inferior, desintegra-se instantaneamente. Se for mais poderoso, o corpo permanece intacto por um ano antes de virar pó. Se a estaca for removida antes disso, o Vampiro ressurge com 1 Ponto de Vida.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"weapon-like-gear","ddbKind":"adventuring-gear","advancedRequirement":{"kind":"none"},"weaponLike":true}'::jsonb),
  ('breath-of-beleth-poison', 'gear'::rpg.item_type, 'Veneno Sopro de Beleth', '{"text":"150 PO"}'::jsonb, '125 g', 'Batizado com o nome do Arquidaemônio do Medo, este veneno provoca alucinações extremas que evocam os piores temores da vítima. O veneno é aerossolizado: basta respirá-lo para sofrer os efeitos. Nas raras ocasiões em que foi usado, pessoas em salas lotadas pularam de janelas ou até se mataram por puro terror. Dizem que até a Síndicate Ébano o proibiu por ser perigoso demais, extravagante e chamativo — embora rumores afirmem que ainda empregam uma versão mais fraca em interrogatórios. Sopro de Beleth (inalado). Uma criatura que respira e está no mesmo espaço que um recipiente aberto do veneno deve passar em uma salvaguarda de Constituição CD 15 ou recebe a condição Envenenado por 1 minuto. Enquanto Envenenado assim, a criatura tem a condição Amedrontado e é Hostil a todas as criaturas que possa ver. Se uma criatura se mover para até 1,5 m de uma criatura Envenenada assim, a Envenenada deve usar a ação Correr no turno para se afastar. Se não puder, deve usar a ação Atacar contra a criatura adjacente.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"poison","ddbKind":"adventuring-gear","advancedRequirement":{"kind":"none"}}'::jsonb),
  ('concealed-blade', 'gear'::rpg.item_type, 'Lâmina Oculta', '{"text":"50 PO"}'::jsonb, '1 kg', 'A Lâmina Oculta é uma adaga embutida em um mecanismo escondido em uma braçadeira ou manopla. Ao rolar Iniciativa, você pode fazer um teste de Destreza (Enganação) oposto aos testes de Sabedoria (Percepção) dos outros. Você tem Vantagem no primeiro ataque do primeiro turno de combate contra qualquer inimigo que falhou no teste.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"weapon-like-gear","ddbKind":"adventuring-gear","advancedRequirement":{"kind":"none"},"weaponLike":true}'::jsonb),
  ('fire-bomb', 'gear'::rpg.item_type, 'Bomba Incendiária', '{"text":"100 PO"}'::jsonb, '250 g', 'Você pode arremessar uma Bomba Incendiária usando a ação Atacar. Escolha um espaço que possa ver em até 6 m. Uma criatura nesse espaço deve fazer uma salvaguarda de Destreza CD 15. Em falha, a criatura sofre 2d6 de dano Cortante e 4d6 de dano de Fogo e fica em Chamas. Criaturas adjacentes ao espaço atacado sofrem metade desse dano e não ficam em Chamas.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"adventuring-gear","ddbKind":"adventuring-gear","advancedRequirement":{"kind":"none"}}'::jsonb),
  ('grappling-gun', 'gear'::rpg.item_type, 'Pistola de Gancho', '{"text":"200 PO"}'::jsonb, '1,5 kg', 'A Pistola de Gancho dispara um gancho preso a uma corda em até 45 m; o gancho se fixa com um teste bem-sucedido de Destreza (Acrobacia) CD 10. Além disso, se estiver caindo, você pode usar uma Reação para disparar a pistola em uma superfície fixável e interromper a queda. Ainda é preciso passar no teste para garantir que o gancho prenda em um objeto sólido; em caso de sucesso, você para de cair.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"adventuring-gear","ddbKind":"adventuring-gear","advancedRequirement":{"kind":"none"}}'::jsonb),
  ('hunters-armor', 'other'::rpg.item_type, 'Armadura de Caçador', '{"text":"+500 PO"}'::jsonb, NULL, 'A Armadura de Caçador é favorita de caçadores de monstros por toda Etharis. Qualquer tipo de armadura pode ser construído como Armadura de Caçador pagando o custo extra indicado. Reforça as áreas vitais com fios de adamantina e mithral para transformar golpes devastadores em ferimentos comuns. Se um golpe causaria uma Ferida Grave, role 1d20. Em 11 ou mais, o golpe não inflige Ferida Grave.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"armor-upgrade","ddbKind":"adventuring-gear","advancedRequirement":{"kind":"armor-upgrade","notesPt":"Modificador de +500 PO aplicado a qualquer tipo de armadura."},"catalogUpgrade":{"appliesTo":"armor","costModifierText":"+500 PO"}}'::jsonb),
  ('iron-net', 'gear'::rpg.item_type, 'Rede de Ferro', '{"text":"150 PO"}'::jsonb, '10 kg', 'Esta rede é feita de minúsculos anéis de ferro entrelaçados. Funciona como uma Rede normal, com as seguintes alterações: alcance da Rede de Ferro é 3 m; a CD do teste de Força (Atletismo) para escapar é 15; a Rede de Ferro tem CA 13 e 15 PV.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"adventuring-gear","ddbKind":"adventuring-gear","advancedRequirement":{"kind":"none"}}'::jsonb),
  ('mastercraft-instrument', 'other'::rpg.item_type, 'Instrumento Magistral', '{"text":"+250 PO"}'::jsonb, NULL, 'Estes instrumentos musicais não são apenas obra dos melhores luthiers e artesãos de Etharis: trazem embelezamentos secretos e inovações que enriquecem a performance. Se você for proficiente no instrumento e tiver Bônus de Proficiência de pelo menos +4, todos os testes de Carisma (Atuação) feitos com um Instrumento Magistral têm Vantagem.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"tool-instrument-upgrade","ddbKind":"adventuring-gear","advancedRequirement":{"kind":"instrument","minProficiencyBonus":4,"notesPt":"Vantagem em Performance exige proficiência no instrumento e bônus de proficiência +4."},"catalogUpgrade":{"appliesTo":"musical-instrument","costModifierText":"+250 PO"}}'::jsonb),
  ('noisemaker', 'gear'::rpg.item_type, 'Gerador de Barulho', '{"text":"50 PO"}'::jsonb, '2,5 kg', 'Este pequeno dispositivo mecânico é especialidade de artesãos gnômicos. Como ação Utilizar, você pode arremessar o Gerador de Barulho em um espaço em até 18 m. Ao pousar, emite um barulho alto — choque musical, assobio, zumbido etc., conforme o criador. O som pode ser ouvido em até 750 m. Uma criatura com Inteligência 3 ou menos em até 18 m quando o dispositivo dispara deve passar em uma salvaguarda de Sabedoria CD 10. Em falha, recebe a condição Amedrontado por 1 minuto. Como ação Influenciar, outra criatura que a Amedrontada possa ver ou ouvir pode fazer um teste de Sabedoria (Lidar com Animais) ou Carisma (Persuasão) CD 20. Em sucesso, a condição Amedrontado termina naquela criatura.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"adventuring-gear","ddbKind":"adventuring-gear","advancedRequirement":{"kind":"none"}}'::jsonb),
  ('prosthetics', 'gear'::rpg.item_type, 'Próteses', '{"text":"500 PO"}'::jsonb, '5 kg', 'A guerra brutal e os monstros ferozes de Etharis deixam muitos com Feridas Graves, incluindo membros perdidos e outras lesões debilitantes. Engenheiros e artesãos do mundo avançaram muito em ajudar essas pessoas com Próteses. Quando uma criatura com Ferida Grave usa uma Prótese, ignora as penalidades impostas pela Ferida Grave enquanto usar uma Prótese que substitua a parte perdida ou ferida. Algumas Próteses podem ser encantadas com magia, ganhando poderes adicionais. Regras para Próteses Mágicas estão no Grim Hollow Campaign Guide.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"prosthetic","ddbKind":"adventuring-gear","advancedRequirement":{"kind":"none"}}'::jsonb),
  ('seeing-glass', 'gear'::rpg.item_type, 'Espelho da Visão', '{"text":"300 PO"}'::jsonb, '1,5 kg', 'Este espelho de mão de prata ornamentado traz um motivo de rosas murchas. O reflexo sempre mostra a forma verdadeira de qualquer criatura vista nele, como se o observador tivesse Visão Verdadeira. Se o Espelho da Visão for apontado a um vampiro, o vidro estilhaça-se imediatamente e é destruído.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"adventuring-gear","ddbKind":"adventuring-gear","advancedRequirement":{"kind":"none"}}'::jsonb),
  ('shadowsteel-focus', 'focus'::rpg.item_type, 'Foco de Aço-sombrio', '{"text":"500 PO"}'::jsonb, NULL, 'Um Foco de Aço-sombrio é um Foco de Conjuração que contém alguma quantidade de Aço-sombrio. Qualquer Foco de Conjuração pode ser feito como Foco de Aço-sombrio. Não há benefício em usar um Foco de Aço-sombrio em vez de um Foco de Conjuração comum; porém, um conjurador com os talentos Adepto de Aço-sombrio e Mestre de Aço-sombrio pode obter os benefícios associados a esses talentos ao usar um Foco de Aço-sombrio.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"spellcasting-focus","ddbKind":"adventuring-gear","advancedRequirement":{"kind":"feat-benefits","featSlugs":["shadowsteel-adept","shadowsteel-master"],"notesPt":"Funciona como foco de conjuração sem treino extra; benefícios dos talentos Shadowsteel exigem os feats homônimos."},"spellcastingFocus":true}'::jsonb),
  ('smoke-bomb', 'gear'::rpg.item_type, 'Bomba de Fumaça', '{"text":"50 PO"}'::jsonb, '1,5 kg', 'Como ação Utilizar, você pode arremessar este frasco de vidro fumegante em um espaço em até 9 m. Ao quebrar, a mistura cria uma esfera de fumaça de 3 m de raio. A área fica Fortemente Obscurecida. A fumaça dura 1d4 + 2 rodadas, ou metade desse tempo em área ventosa.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"adventuring-gear","ddbKind":"adventuring-gear","advancedRequirement":{"kind":"none"}}'::jsonb),
  ('stitching-needle', 'gear'::rpg.item_type, 'Agulha de Costura', '{"text":"250 PO"}'::jsonb, '25 g', 'Esta agulha de ferro negro perfura a pele com facilidade. Se a boca de uma criatura for costurada com uma Agulha de Costura, ela perde a capacidade de falar e de conjurar magias com componentes verbais. A criatura ganha telepatia com alcance de 18 m. Costurar a boca de uma criatura consentente, inconsciente ou incapacitada leva 10 minutos. Remover os pontos leva 1 minuto.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"adventuring-gear","ddbKind":"adventuring-gear","advancedRequirement":{"kind":"none"}}'::jsonb),
  ('watchers-candle', 'gear'::rpg.item_type, 'Vela do Vigia', '{"text":"250 PO"}'::jsonb, '125 g', 'Esta vela cônica preta não pode ser acesa manualmente. Quando um Celestial, Feérico, Infernal ou Morto-vivo chega a até 36 m da vela, o pavio acende com chama roxa. Depois de acesa, queima por uma hora e não pode ser usada novamente. Velas do Vigia não funcionam se estiverem embaladas ou guardadas em um recipiente.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"adventuring-gear","ddbKind":"adventuring-gear","advancedRequirement":{"kind":"none"}}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  cost = EXCLUDED.cost,
  weight = EXCLUDED.weight,
  description = EXCLUDED.description,
  properties = EXCLUDED.properties,
  item_type = EXCLUDED.item_type;
