-- Cap.6 — notas de combate por boon (SSOT; gerado por scripts/generate-cap6-boon-combat-notes-seed.mjs)

INSERT INTO rpg.phb_transformation_boon_combat_note (boon_id, name_pt, economy, note_pt)
VALUES
  ('aberrant-form', 'Aberrant Form', ARRAY[]::text[], NULL),
  ('aberrant-mutation', 'Aberrant Mutation', ARRAY['bonus', 'action']::text[], 'Casca Quitinosa / Membros Eldritch / Forma Viscosa — toggle stateful (mutationSlug); 1 min declare.'),
  ('abyssal-resistance', 'Bênção do estágio 4: Resistência Abissal', ARRAY[]::text[], NULL),
  ('acolyte-of-undeath', 'Acolyte of Undeath', ARRAY['reaction']::text[], NULL),
  ('adept-of-the-green-sisterhood', 'Adept of the Green Sisterhood', ARRAY['action']::text[], NULL),
  ('adept-of-the-red-sisterhood', 'Adept of the Red Sisterhood', ARRAY['action']::text[], NULL),
  ('adept-of-the-sea-sisterhood', 'Adept of the Sea Sisterhood', ARRAY['action']::text[], NULL),
  ('angelic-wings', 'Angelic Wings', ARRAY['bonus', 'action']::text[], NULL),
  ('aura-of-awakening', 'Aura of Awakening', ARRAY['reaction']::text[], NULL),
  ('aura-of-holy-purge', 'Aura of Holy Purge', ARRAY['reaction']::text[], NULL),
  ('aura-of-righteous-mercy', 'Aura of Righteous Mercy', ARRAY['reaction']::text[], NULL),
  ('beguilers-charm', 'Beguiler’s Charm', ARRAY['action']::text[], NULL),
  ('bestial-vigor', 'Bestial Vigor', ARRAY[]::text[], '+nível em PV máx. (+1/nível). Em forma híbrida: 5 PV temp. no início de cada turno (declare na mesa).'),
  ('binding-curse', 'Binding Curse', ARRAY['bonus', 'action']::text[], NULL),
  ('bow-of-celestial-domination', 'Bow of Celestial Domination', ARRAY['action']::text[], NULL),
  ('bow-of-celestial-judgement', 'Bow of Celestial Judgement', ARRAY['bonus', 'action']::text[], NULL),
  ('call-of-unmaking', 'Call of Unmaking', ARRAY['bonus', 'action']::text[], NULL),
  ('celestial-form', 'Celestial Form', ARRAY[]::text[], NULL),
  ('cleanse-affliction', 'Cleanse Affliction', ARRAY[]::text[], NULL),
  ('constricting-tendrils', 'Constricting Tendrils', ARRAY['bonus', 'action']::text[], NULL),
  ('corrosive-membrane', 'Corrosive Membrane', ARRAY[]::text[], NULL),
  ('corrupting-magic', 'Corrupting Magic', ARRAY[]::text[], NULL),
  ('cursed-claw', 'Cursed Claw', ARRAY['bonus', 'action']::text[], NULL),
  ('daemonic-brand', 'Bênção do estágio 2: Marca Demoníaca', ARRAY['bonus', 'action']::text[], NULL),
  ('devilish-contractor', 'Bênção do estágio 1: Contratante Diabólico', ARRAY[]::text[], NULL),
  ('devilish-subcontractor', 'Bênção do estágio 3: Subcontratante Diabólico', ARRAY[]::text[], NULL),
  ('divine-clemency', 'Divine Clemency', ARRAY['reaction']::text[], NULL),
  ('draining-flight', 'Draining Flight', ARRAY['bonus', 'action']::text[], NULL),
  ('dreams-and-nightmares', 'Dreams and Nightmares', ARRAY['bonus', 'action']::text[], NULL),
  ('dual-nature', 'Dual Nature', ARRAY[]::text[], NULL),
  ('efficient-killer', 'Efficient Killer', ARRAY[]::text[], NULL),
  ('elastic-limbs', 'Elastic Limbs', ARRAY[]::text[], NULL),
  ('eldritch-aberration', 'Eldritch Aberration', ARRAY[]::text[], NULL),
  ('eldritch-concentration', 'Eldritch Concentration', ARRAY[]::text[], NULL),
  ('eldritch-omniscience', 'Eldritch Omniscience', ARRAY['reaction', 'action']::text[], NULL),
  ('elemental-affinity', 'Elemental Affinity', ARRAY['reaction']::text[], NULL),
  ('elemental-mastery', 'Elemental Mastery', ARRAY['reaction']::text[], NULL),
  ('elemental-surge', 'Elemental Surge', ARRAY['bonus', 'action']::text[], NULL),
  ('engulf', 'Engulf', ARRAY['action']::text[], NULL),
  ('enhanced-contract', 'Bênção do estágio 2: Contrato Aprimorado', ARRAY[]::text[], NULL),
  ('ethereal-phasing', 'Ethereal Phasing', ARRAY[]::text[], NULL),
  ('evil-eye', 'Evil Eye', ARRAY['action']::text[], NULL),
  ('eyes-of-the-night', 'Eyes of the Night', ARRAY[]::text[], NULL),
  ('fanged-bite', 'Fanged Bite', ARRAY['action']::text[], NULL),
  ('fey-form', 'Fey Form', ARRAY[]::text[], NULL),
  ('fiendish-soul', 'Bênção do estágio 1: Alma Corruptora', ARRAY[]::text[], NULL),
  ('final-fzeg-bloodline', 'Final Fzeg Bloodline', ARRAY['action']::text[], NULL),
  ('final-soman-bloodline', 'Final Soman Bloodline', ARRAY[]::text[], NULL),
  ('final-strigoi-bloodline', 'Final Strigoi Bloodline', ARRAY['bonus', 'reaction', 'action']::text[], NULL),
  ('fzeg-bloodline', 'Fzeg Bloodline', ARRAY['bonus', 'action']::text[], NULL),
  ('ghastly-touch', 'Ghastly Touch', ARRAY[]::text[], NULL),
  ('grandmothers-curse', 'Grandmother’s Curse', ARRAY[]::text[], NULL),
  ('grave-touched-soul', 'Grave-Touched Soul', ARRAY[]::text[], NULL),
  ('greater-magic-tricks', 'Greater Magic Tricks', ARRAY[]::text[], NULL),
  ('hag-form', 'Hag Form', ARRAY[]::text[], NULL),
  ('haunting-flight', 'Haunting Flight', ARRAY['bonus', 'action']::text[], NULL),
  ('holy-strikes', 'Holy Strikes', ARRAY[]::text[], NULL),
  ('hunters-focus', 'Hunter’s Focus', ARRAY['bonus', 'action']::text[], NULL),
  ('hybrid-bear-form', 'Hybrid Bear Form', ARRAY['bonus', 'action']::text[], NULL),
  ('hybrid-form-affinity', 'Hybrid Form Affinity', ARRAY[]::text[], NULL),
  ('hybrid-rat-form', 'Hybrid Rat Form', ARRAY['bonus', 'action']::text[], NULL),
  ('hybrid-wolf-form', 'Hybrid Wolf Form', ARRAY['bonus', 'action']::text[], NULL),
  ('illusionary-cloak', 'Illusionary Cloak', ARRAY['bonus', 'action']::text[], NULL),
  ('improved-fanged-bite', 'Improved Fanged Bite', ARRAY['bonus', 'action']::text[], NULL),
  ('incorporeal-movement', 'Incorporeal Movement', ARRAY['action']::text[], NULL),
  ('infernal-smite', 'Bênção do estágio 1: Punição Infernal', ARRAY[]::text[], NULL),
  ('infernal-summons', 'Bênção do estágio 4: Convocação Infernal', ARRAY['action']::text[], NULL),
  ('inhuman-reflexes', 'Inhuman Reflexes', ARRAY[]::text[], NULL),
  ('iron-pelt', 'Iron Pelt', ARRAY[]::text[], NULL),
  ('kindred-form', 'Kindred Form', ARRAY[]::text[], NULL),
  ('legion-of-slime', 'Legion of Slime', ARRAY['bonus', 'reaction', 'action']::text[], NULL),
  ('lich-magica', 'Lich Magica', ARRAY['bonus', 'action']::text[], NULL),
  ('lord-of-undeath', 'Lord of Undeath', ARRAY[]::text[], NULL),
  ('magic-resistance', 'Magic Resistance', ARRAY[]::text[], NULL),
  ('magic-tricks', 'Magic Tricks', ARRAY[]::text[], NULL),
  ('master-of-many', 'Master of Many', ARRAY[]::text[], NULL),
  ('master-of-the-green-sisterhood', 'Master of the Green Sisterhood', ARRAY['action']::text[], NULL),
  ('master-of-the-red-sisterhood', 'Master of the Red Sisterhood', ARRAY['bonus', 'action']::text[], NULL),
  ('master-of-the-sea-sisterhood', 'Master of the Sea Sisterhood', ARRAY['bonus', 'action']::text[], NULL),
  ('master-of-undeath', 'Master of Undeath', ARRAY['reaction', 'action']::text[], NULL),
  ('memori-lichdom', 'Memori Lichdom', ARRAY['bonus', 'reaction', 'action']::text[], NULL),
  ('mimic-object', 'Mimic Object', ARRAY['reaction', 'action']::text[], NULL),
  ('mist-form', 'Mist Form', ARRAY['reaction', 'action']::text[], NULL),
  ('mutable-corpus', 'Mutable Corpus', ARRAY['action']::text[], NULL),
  ('ooze-form', 'Ooze Form', ARRAY['bonus', 'action']::text[], NULL),
  ('overwhelming-brand', 'Bênção do estágio 3: Marca Avassaladora', ARRAY['action']::text[], NULL),
  ('paralyzing-touch', 'Paralyzing Touch', ARRAY[]::text[], NULL),
  ('poisonous-mutations', 'Poisonous Mutations', ARRAY[]::text[], NULL),
  ('possession', 'Possession', ARRAY['bonus', 'action']::text[], NULL),
  ('primeval-body', 'Primeval Body', ARRAY[]::text[], NULL),
  ('primordial-aura', 'Primordial Aura', ARRAY['bonus', 'action']::text[], NULL),
  ('primordial-form', 'Primordial Form', ARRAY[]::text[], NULL),
  ('protective-wings', 'Protective Wings', ARRAY['reaction']::text[], NULL),
  ('regeneration', 'Regeneration', ARRAY[]::text[], NULL),
  ('sacred-retribution', 'Sacred Retribution', ARRAY['reaction', 'action']::text[], NULL),
  ('sangromancy-specialist', 'Sangromancy Specialist', ARRAY[]::text[], NULL),
  ('savage-instincts', 'Savage Instincts', ARRAY[]::text[], NULL),
  ('servant-of-the-autumn-court', 'Servant of the Autumn Court', ARRAY['bonus', 'action']::text[], NULL),
  ('servant-of-the-spring-court', 'Servant of the Spring Court', ARRAY['bonus', 'action']::text[], NULL),
  ('servant-of-the-summer-court', 'Servant of the Summer Court', ARRAY['bonus', 'action']::text[], NULL),
  ('servant-of-the-winter-court', 'Servant of the Winter Court', ARRAY['bonus', 'action']::text[], NULL),
  ('shadowsteel-absorption', 'Shadowsteel Absorption', ARRAY[]::text[], NULL),
  ('shadowsteel-arcane-vessel', 'Shadowsteel Arcane Vessel', ARRAY[]::text[], NULL),
  ('shadowsteel-caster', 'Shadowsteel Caster', ARRAY[]::text[], NULL),
  ('shadowsteel-curser', 'Shadowsteel Curser', ARRAY[]::text[], NULL),
  ('shadowsteel-fury', 'Shadowsteel Fury', ARRAY['bonus', 'action']::text[], NULL),
  ('shadowsteel-weapon', 'Shadowsteel Weapon', ARRAY[]::text[], NULL),
  ('shadowsteel-weapon-master', 'Shadowsteel Weapon Master', ARRAY[]::text[], NULL),
  ('shapeshifters-savagery', 'Shapeshifter’s Savagery', ARRAY[]::text[], NULL),
  ('slimy-mien', 'Slimy Mien', ARRAY[]::text[], NULL),
  ('soman-bloodline', 'Soman Bloodline', ARRAY[]::text[], NULL),
  ('soul-shattering-attack', 'Soul-Shattering Attack', ARRAY[]::text[], NULL),
  ('spectral-form', 'Spectral Form', ARRAY[]::text[], NULL),
  ('strigoi-bloodline', 'Strigoi Bloodline', ARRAY['bonus', 'action']::text[], NULL),
  ('terrifying-visage', 'Terrifying Visage', ARRAY[]::text[], NULL),
  ('the-green-sisterhood', 'The Green Sisterhood', ARRAY['action']::text[], NULL),
  ('the-red-sisterhood', 'The Red Sisterhood', ARRAY[]::text[], NULL),
  ('the-sea-sisterhood', 'The Sea Sisterhood', ARRAY['action']::text[], NULL),
  ('tooth-and-claw', 'Tooth and Claw', ARRAY['bonus', 'action']::text[], NULL),
  ('twilight-glamour', 'Twilight Glamour', ARRAY['bonus', 'action']::text[], NULL),
  ('two-faced', 'Two-Faced', ARRAY['action']::text[], NULL),
  ('ultimate-brand', 'Bênção do estágio 4: Marca Suprema', ARRAY['reaction', 'action']::text[], NULL),
  ('undead-form', 'Undead Form', ARRAY[]::text[], NULL),
  ('undead-resilience', 'Undead Resilience', ARRAY[]::text[], NULL),
  ('unholy-healing', 'Unholy Healing', ARRAY['action']::text[], NULL),
  ('viscous-durability', 'Viscous Durability', ARRAY[]::text[], NULL),
  ('writhing-tendrils', 'Writhing Tendrils', ARRAY['bonus', 'reaction', 'action']::text[], NULL)
ON CONFLICT (boon_id) DO UPDATE SET
  name_pt = EXCLUDED.name_pt,
  economy = EXCLUDED.economy,
  note_pt = EXCLUDED.note_pt;
