-- Cap.6 — notas de combate por boon (SSOT; gerado por scripts/generate/cap6-boon-combat-notes-seed.mjs)

INSERT INTO rpg.phb_combat_note (source_kind, boon_id, name_pt, economy, note)
VALUES
  ('transformation_boon'::rpg.combat_note_source, 'aberrant-form', 'Aberrant Form', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'aberrant-mutation', 'Aberrant Mutation', ARRAY['bonus', 'action']::text[], 'Casca Quitinosa / Membros Eldritch / Forma Viscosa — toggle stateful (mutationSlug); 1 min declare.'),
  ('transformation_boon'::rpg.combat_note_source, 'abyssal-resistance', 'Bênção do estágio 4: Resistência Abissal', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'acolyte-of-undeath', 'Acolyte of Undeath', ARRAY['reaction']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'adept-of-the-green-sisterhood', 'Adept of the Green Sisterhood', ARRAY['action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'adept-of-the-red-sisterhood', 'Adept of the Red Sisterhood', ARRAY['action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'adept-of-the-sea-sisterhood', 'Adept of the Sea Sisterhood', ARRAY['action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'angelic-wings', 'Angelic Wings', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'aura-of-awakening', 'Aura of Awakening', ARRAY['reaction']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'aura-of-holy-purge', 'Aura of Holy Purge', ARRAY['reaction']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'aura-of-righteous-mercy', 'Aura of Righteous Mercy', ARRAY['reaction']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'beguilers-charm', 'Beguiler’s Charm', ARRAY['action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'bestial-vigor', 'Bestial Vigor', ARRAY[]::text[], '+nível em PV máx. (+1/nível). Em forma híbrida: 5 PV temp. no início de cada turno (declare na mesa).'),
  ('transformation_boon'::rpg.combat_note_source, 'binding-curse', 'Binding Curse', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'bow-of-celestial-domination', 'Bow of Celestial Domination', ARRAY['action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'bow-of-celestial-judgement', 'Bow of Celestial Judgement', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'call-of-unmaking', 'Call of Unmaking', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'celestial-form', 'Celestial Form', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'cleanse-affliction', 'Cleanse Affliction', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'constricting-tendrils', 'Constricting Tendrils', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'corrosive-membrane', 'Corrosive Membrane', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'corrupting-magic', 'Corrupting Magic', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'cursed-claw', 'Cursed Claw', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'daemonic-brand', 'Bênção do estágio 2: Marca Demoníaca', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'devilish-contractor', 'Bênção do estágio 1: Contratante Diabólico', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'devilish-subcontractor', 'Bênção do estágio 3: Subcontratante Diabólico', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'divine-clemency', 'Divine Clemency', ARRAY['reaction']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'draining-flight', 'Draining Flight', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'dreams-and-nightmares', 'Dreams and Nightmares', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'dual-nature', 'Dual Nature', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'efficient-killer', 'Efficient Killer', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'elastic-limbs', 'Elastic Limbs', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'eldritch-aberration', 'Eldritch Aberration', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'eldritch-concentration', 'Eldritch Concentration', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'eldritch-omniscience', 'Eldritch Omniscience', ARRAY['reaction', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'elemental-affinity', 'Elemental Affinity', ARRAY['reaction']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'elemental-mastery', 'Elemental Mastery', ARRAY['reaction']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'elemental-surge', 'Elemental Surge', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'engulf', 'Engulf', ARRAY['action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'enhanced-contract', 'Bênção do estágio 2: Contrato Aprimorado', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'ethereal-phasing', 'Ethereal Phasing', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'evil-eye', 'Evil Eye', ARRAY['action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'eyes-of-the-night', 'Eyes of the Night', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'fanged-bite', 'Fanged Bite', ARRAY['action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'fey-form', 'Fey Form', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'fiendish-soul', 'Bênção do estágio 1: Alma Corruptora', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'final-fzeg-bloodline', 'Final Fzeg Bloodline', ARRAY['action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'final-soman-bloodline', 'Final Soman Bloodline', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'final-strigoi-bloodline', 'Final Strigoi Bloodline', ARRAY['bonus', 'reaction', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'fzeg-bloodline', 'Fzeg Bloodline', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'ghastly-touch', 'Ghastly Touch', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'grandmothers-curse', 'Grandmother’s Curse', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'grave-touched-soul', 'Grave-Touched Soul', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'greater-magic-tricks', 'Greater Magic Tricks', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'hag-form', 'Hag Form', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'haunting-flight', 'Haunting Flight', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'holy-strikes', 'Holy Strikes', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'hunters-focus', 'Hunter’s Focus', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'hybrid-bear-form', 'Hybrid Bear Form', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'hybrid-form-affinity', 'Hybrid Form Affinity', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'hybrid-rat-form', 'Hybrid Rat Form', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'hybrid-wolf-form', 'Hybrid Wolf Form', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'illusionary-cloak', 'Illusionary Cloak', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'improved-fanged-bite', 'Improved Fanged Bite', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'incorporeal-movement', 'Incorporeal Movement', ARRAY['action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'infernal-smite', 'Bênção do estágio 1: Punição Infernal', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'infernal-summons', 'Bênção do estágio 4: Convocação Infernal', ARRAY['action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'inhuman-reflexes', 'Inhuman Reflexes', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'iron-pelt', 'Iron Pelt', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'kindred-form', 'Kindred Form', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'legion-of-slime', 'Legion of Slime', ARRAY['bonus', 'reaction', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'lich-magica', 'Lich Magica', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'lord-of-undeath', 'Lord of Undeath', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'magic-resistance', 'Magic Resistance', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'magic-tricks', 'Magic Tricks', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'master-of-many', 'Master of Many', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'master-of-the-green-sisterhood', 'Master of the Green Sisterhood', ARRAY['action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'master-of-the-red-sisterhood', 'Master of the Red Sisterhood', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'master-of-the-sea-sisterhood', 'Master of the Sea Sisterhood', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'master-of-undeath', 'Master of Undeath', ARRAY['reaction', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'memori-lichdom', 'Memori Lichdom', ARRAY['bonus', 'reaction', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'mimic-object', 'Mimic Object', ARRAY['reaction', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'mist-form', 'Mist Form', ARRAY['reaction', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'mutable-corpus', 'Mutable Corpus', ARRAY['action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'ooze-form', 'Ooze Form', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'overwhelming-brand', 'Bênção do estágio 3: Marca Avassaladora', ARRAY['action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'paralyzing-touch', 'Paralyzing Touch', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'poisonous-mutations', 'Poisonous Mutations', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'possession', 'Possession', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'primeval-body', 'Primeval Body', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'primordial-aura', 'Primordial Aura', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'primordial-form', 'Primordial Form', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'protective-wings', 'Protective Wings', ARRAY['reaction']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'regeneration', 'Regeneration', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'sacred-retribution', 'Sacred Retribution', ARRAY['reaction', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'sangromancy-specialist', 'Sangromancy Specialist', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'savage-instincts', 'Savage Instincts', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'servant-of-the-autumn-court', 'Servant of the Autumn Court', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'servant-of-the-spring-court', 'Servant of the Spring Court', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'servant-of-the-summer-court', 'Servant of the Summer Court', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'servant-of-the-winter-court', 'Servant of the Winter Court', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'shadowsteel-absorption', 'Shadowsteel Absorption', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'shadowsteel-arcane-vessel', 'Shadowsteel Arcane Vessel', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'shadowsteel-caster', 'Shadowsteel Caster', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'shadowsteel-curser', 'Shadowsteel Curser', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'shadowsteel-fury', 'Shadowsteel Fury', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'shadowsteel-weapon', 'Shadowsteel Weapon', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'shadowsteel-weapon-master', 'Shadowsteel Weapon Master', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'shapeshifters-savagery', 'Shapeshifter’s Savagery', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'slimy-mien', 'Slimy Mien', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'soman-bloodline', 'Soman Bloodline', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'soul-shattering-attack', 'Soul-Shattering Attack', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'spectral-form', 'Spectral Form', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'strigoi-bloodline', 'Strigoi Bloodline', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'terrifying-visage', 'Terrifying Visage', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'the-green-sisterhood', 'The Green Sisterhood', ARRAY['action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'the-red-sisterhood', 'The Red Sisterhood', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'the-sea-sisterhood', 'The Sea Sisterhood', ARRAY['action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'tooth-and-claw', 'Tooth and Claw', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'twilight-glamour', 'Twilight Glamour', ARRAY['bonus', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'two-faced', 'Two-Faced', ARRAY['action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'ultimate-brand', 'Bênção do estágio 4: Marca Suprema', ARRAY['reaction', 'action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'undead-form', 'Undead Form', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'undead-resilience', 'Undead Resilience', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'unholy-healing', 'Unholy Healing', ARRAY['action']::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'viscous-durability', 'Viscous Durability', ARRAY[]::text[], NULL),
  ('transformation_boon'::rpg.combat_note_source, 'writhing-tendrils', 'Writhing Tendrils', ARRAY['bonus', 'reaction', 'action']::text[], NULL)
ON CONFLICT (boon_id)
WHERE (source_kind = 'transformation_boon'::rpg.combat_note_source)
DO UPDATE SET
  name_pt = EXCLUDED.name_pt,
  economy = EXCLUDED.economy,
  note = EXCLUDED.note;
