-- Seed rpg.phb_item (catálogo PHB Cap. 6 — loja / inventário)
-- Fonte de verdade de preços: cost->>'text' aqui (não properties.variants nem patches).
-- Categorias “Varia” (pais) ficam com cost NULL; variantes filhas têm preço.

INSERT INTO rpg.phb_item (slug, item_type, name, cost, weight, description, properties)
VALUES
  ('dagger', 'weapon'::rpg.item_type, 'Adaga', '{"text":"2 PO"}'::jsonb, '0,5 kg', NULL, '{"propertyIds":["finesse","thrown","light"],"masteryId":"nick","range":{"normal":6,"max":18}}'::jsonb),
  ('javelin', 'weapon'::rpg.item_type, 'Azagaia', '{"text":"5 PP"}'::jsonb, '1 kg', NULL, '{"propertyIds":["thrown"],"masteryId":"slow","range":{"normal":9,"max":36}}'::jsonb),
  ('quarterstaff', 'weapon'::rpg.item_type, 'Cajado', '{"text":"2 PP"}'::jsonb, '2 kg', NULL, '{"propertyIds":["versatile"],"masteryId":"topple"}'::jsonb),
  ('club', 'weapon'::rpg.item_type, 'Clava', '{"text":"1 PP"}'::jsonb, '1 kg', NULL, '{"propertyIds":["light"],"masteryId":"slow"}'::jsonb),
  ('greatclub', 'weapon'::rpg.item_type, 'Clava Grande', '{"text":"2 PP"}'::jsonb, '5 kg', NULL, '{"propertyIds":["two-handed"],"masteryId":"push"}'::jsonb),
  ('sickle', 'weapon'::rpg.item_type, 'Foice', '{"text":"1 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":["light"],"masteryId":"nick"}'::jsonb),
  ('spear', 'weapon'::rpg.item_type, 'Lança', '{"text":"1 PO"}'::jsonb, '1,5 kg', NULL, '{"propertyIds":["thrown","versatile"],"masteryId":"sap","range":{"normal":6,"max":18}}'::jsonb),
  ('mace', 'weapon'::rpg.item_type, 'Maça', '{"text":"5 PO"}'::jsonb, '2 kg', NULL, '{"propertyIds":[],"masteryId":"sap"}'::jsonb),
  ('handaxe', 'weapon'::rpg.item_type, 'Machadinha', '{"text":"5 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":["thrown","light"],"masteryId":"vex","range":{"normal":6,"max":18}}'::jsonb),
  ('light-hammer', 'weapon'::rpg.item_type, 'Martelo Leve', '{"text":"2 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":["thrown","light"],"masteryId":"nick","range":{"normal":6,"max":18}}'::jsonb),
  ('shortbow', 'weapon'::rpg.item_type, 'Arco Curto', '{"text":"25 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":["two-handed","ammunition"],"masteryId":"vex","range":{"normal":24,"max":96}}'::jsonb),
  ('light-crossbow', 'weapon'::rpg.item_type, 'Besta Leve', '{"text":"25 PO"}'::jsonb, '2,5 kg', NULL, '{"propertyIds":["two-handed","ammunition","loading"],"masteryId":"slow","range":{"normal":24,"max":96}}'::jsonb),
  ('dart', 'weapon'::rpg.item_type, 'Dardo', '{"text":"5 PC"}'::jsonb, '150 g', NULL, '{"propertyIds":["finesse","thrown"],"masteryId":"vex","range":{"normal":6,"max":18}}'::jsonb),
  ('sling', 'weapon'::rpg.item_type, 'Funda', '{"text":"1 PP"}'::jsonb, '—', NULL, '{"propertyIds":["ammunition"],"masteryId":"slow","range":{"normal":9,"max":36}}'::jsonb),
  ('halberd', 'weapon'::rpg.item_type, 'Alabarda', '{"text":"20 PO"}'::jsonb, '3 kg', NULL, '{"propertyIds":["two-handed","reach","heavy"],"masteryId":"cleave"}'::jsonb),
  ('whip', 'weapon'::rpg.item_type, 'Chicote', '{"text":"2 PO"}'::jsonb, '1,5 kg', NULL, '{"propertyIds":["finesse","reach"],"masteryId":"slow"}'::jsonb),
  ('scimitar', 'weapon'::rpg.item_type, 'Cimitarra', '{"text":"25 PO"}'::jsonb, '1,5 kg', NULL, '{"propertyIds":["finesse","light"],"masteryId":"nick"}'::jsonb),
  ('shortsword', 'weapon'::rpg.item_type, 'Espada Curta', '{"text":"10 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":["finesse","light"],"masteryId":"vex"}'::jsonb),
  ('greatsword', 'weapon'::rpg.item_type, 'Espada Grande', '{"text":"50 PO"}'::jsonb, '3 kg', NULL, '{"propertyIds":["two-handed","heavy"],"masteryId":"graze"}'::jsonb),
  ('longsword', 'weapon'::rpg.item_type, 'Espada Longa', '{"text":"15 PO"}'::jsonb, '1,5 kg', NULL, '{"propertyIds":["versatile"],"masteryId":"sap"}'::jsonb),
  ('glaive', 'weapon'::rpg.item_type, 'Glaive', '{"text":"20 PO"}'::jsonb, '3 kg', NULL, '{"propertyIds":["two-handed","reach","heavy"],"masteryId":"graze"}'::jsonb),
  ('lance', 'weapon'::rpg.item_type, 'Lança de Montaria', '{"text":"10 PO"}'::jsonb, '3 kg', NULL, '{"propertyIds":["two-handed","reach","heavy"],"masteryId":"topple"}'::jsonb),
  ('pike', 'weapon'::rpg.item_type, 'Lança Longa', '{"text":"5 PO"}'::jsonb, '9 kg', NULL, '{"propertyIds":["two-handed","reach","heavy"],"masteryId":"push"}'::jsonb),
  ('morningstar', 'weapon'::rpg.item_type, 'Maça Estrela', '{"text":"15 PO"}'::jsonb, '2 kg', NULL, '{"propertyIds":[],"masteryId":"sap"}'::jsonb),
  ('battleaxe', 'weapon'::rpg.item_type, 'Machado de Batalha', '{"text":"10 PO"}'::jsonb, '2,5 kg', NULL, '{"propertyIds":["versatile"],"masteryId":"topple"}'::jsonb),
  ('greataxe', 'weapon'::rpg.item_type, 'Machado Grande', '{"text":"30 PO"}'::jsonb, '3,5 kg', NULL, '{"propertyIds":["two-handed","heavy"],"masteryId":"cleave"}'::jsonb),
  ('maul', 'weapon'::rpg.item_type, 'Malho', '{"text":"10 PO"}'::jsonb, '5 kg', NULL, '{"propertyIds":["two-handed","heavy"],"masteryId":"topple"}'::jsonb),
  ('flail', 'weapon'::rpg.item_type, 'Mangual', '{"text":"10 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":[],"masteryId":"sap"}'::jsonb),
  ('warhammer', 'weapon'::rpg.item_type, 'Martelo de Guerra', '{"text":"15 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":["versatile"],"masteryId":"push"}'::jsonb),
  ('war-pick', 'weapon'::rpg.item_type, 'Picareta de Guerra', '{"text":"5 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":["versatile"],"masteryId":"sap"}'::jsonb),
  ('rapier', 'weapon'::rpg.item_type, 'Rapieira', '{"text":"25 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":["finesse"],"masteryId":"vex"}'::jsonb),
  ('trident', 'weapon'::rpg.item_type, 'Tridente', '{"text":"5 PO"}'::jsonb, '2 kg', NULL, '{"propertyIds":["thrown","versatile"],"masteryId":"topple","range":{"normal":6,"max":18}}'::jsonb),
  ('longbow', 'weapon'::rpg.item_type, 'Arco Longo', '{"text":"50 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":["two-handed","ammunition","heavy"],"masteryId":"slow","range":{"normal":45,"max":180}}'::jsonb),
  ('hand-crossbow', 'weapon'::rpg.item_type, 'Besta de Mão', '{"text":"75 PO"}'::jsonb, '1,5 kg', NULL, '{"propertyIds":["light","ammunition","loading"],"masteryId":"vex","range":{"normal":9,"max":36}}'::jsonb),
  ('heavy-crossbow', 'weapon'::rpg.item_type, 'Besta Pesada', '{"text":"50 PO"}'::jsonb, '9 kg', NULL, '{"propertyIds":["two-handed","ammunition","heavy","loading"],"masteryId":"push","range":{"normal":30,"max":120}}'::jsonb),
  ('musket', 'weapon'::rpg.item_type, 'Mosquete', '{"text":"500 PO"}'::jsonb, '5 kg', NULL, '{"propertyIds":["two-handed","ammunition","loading"],"masteryId":"slow","range":{"normal":12,"max":36}}'::jsonb),
  ('pistol', 'weapon'::rpg.item_type, 'Pistola', '{"text":"250 PO"}'::jsonb, '1,5 kg', NULL, '{"propertyIds":["ammunition","loading"],"masteryId":"vex","range":{"normal":9,"max":27}}'::jsonb),
  ('blowgun', 'weapon'::rpg.item_type, 'Zarabatana', '{"text":"10 PO"}'::jsonb, '0,5 kg', NULL, '{"propertyIds":["ammunition","loading"],"masteryId":"vex"}'::jsonb),
  ('padded', 'armor'::rpg.item_type, 'Acolchoada', '{"text":"5 PO"}'::jsonb, '4 kg', NULL, '{"acFormula":{"type":"dex-plus-base","base":11},"propertyIds":["stealth-disadvantage"]}'::jsonb),
  ('leather', 'armor'::rpg.item_type, 'Couro', '{"text":"10 PO"}'::jsonb, '5 kg', NULL, '{"acFormula":{"type":"dex-plus-base","base":11},"propertyIds":[]}'::jsonb),
  ('studded-leather', 'armor'::rpg.item_type, 'Couro Batido', '{"text":"45 PO"}'::jsonb, '6,5 kg', NULL, '{"acFormula":{"type":"dex-plus-base","base":12},"propertyIds":[]}'::jsonb),
  ('hide', 'armor'::rpg.item_type, 'Gibão de Peles', '{"text":"10 PO"}'::jsonb, '6 kg', NULL, '{"acFormula":{"type":"dex-plus-base","base":12,"dexMax":2},"propertyIds":[]}'::jsonb),
  ('chain-shirt', 'armor'::rpg.item_type, 'Cota de Malha Parcial', '{"text":"50 PO"}'::jsonb, '10 kg', NULL, '{"acFormula":{"type":"dex-plus-base","base":13,"dexMax":2},"propertyIds":[]}'::jsonb),
  ('scale-mail', 'armor'::rpg.item_type, 'Loriga de Escamas', '{"text":"50 PO"}'::jsonb, '22 kg', NULL, '{"acFormula":{"type":"dex-plus-base","base":14,"dexMax":2},"propertyIds":["stealth-disadvantage"]}'::jsonb),
  ('breastplate', 'armor'::rpg.item_type, 'Couraça', '{"text":"400 PO"}'::jsonb, '10 kg', NULL, '{"acFormula":{"type":"dex-plus-base","base":14,"dexMax":2},"propertyIds":[]}'::jsonb),
  ('half-plate', 'armor'::rpg.item_type, 'Meia-Placa', '{"text":"750 PO"}'::jsonb, '20 kg', NULL, '{"acFormula":{"type":"dex-plus-base","base":15,"dexMax":2},"propertyIds":["stealth-disadvantage"]}'::jsonb),
  ('ring-mail', 'armor'::rpg.item_type, 'Cota de Anéis', '{"text":"30 PO"}'::jsonb, '20 kg', NULL, '{"acFormula":{"type":"fixed","base":14},"propertyIds":["stealth-disadvantage"]}'::jsonb),
  ('chain-mail', 'armor'::rpg.item_type, 'Cota de Malha', '{"text":"75 PO"}'::jsonb, '27 kg', NULL, '{"acFormula":{"type":"fixed","base":16},"propertyIds":["stealth-disadvantage","strength-requirement"]}'::jsonb),
  ('splint', 'armor'::rpg.item_type, 'Armadura de Talas', '{"text":"200 PO"}'::jsonb, '30 kg', NULL, '{"acFormula":{"type":"fixed","base":17},"propertyIds":["stealth-disadvantage","strength-requirement"]}'::jsonb),
  ('plate', 'armor'::rpg.item_type, 'Placas', '{"text":"1.500 PO"}'::jsonb, '32 kg', NULL, '{"acFormula":{"type":"fixed","base":18},"propertyIds":["stealth-disadvantage","strength-requirement"]}'::jsonb),
  ('shield', 'armor'::rpg.item_type, 'Escudo', '{"text":"10 PO"}'::jsonb, '3 kg', NULL, '{"acFormula":{"type":"shield-bonus","bonus":2},"propertyIds":["shield-ac-bonus"]}'::jsonb),
  -- Barding (PHB Cap. 6): custo ×4 e peso ×2 da armadura base; loja/montaria
  ('barding-padded', 'other'::rpg.item_type, 'Barding — Acolchoada', '{"text":"20 PO"}'::jsonb, '8 kg', 'Armadura de montaria (custo e peso ×2 da armadura correspondente).', '{"kind":"barding","baseArmorSlug":"padded"}'::jsonb),
  ('barding-leather', 'other'::rpg.item_type, 'Barding — Couro', '{"text":"40 PO"}'::jsonb, '10 kg', 'Armadura de montaria (custo e peso ×2 da armadura correspondente).', '{"kind":"barding","baseArmorSlug":"leather"}'::jsonb),
  ('barding-studded-leather', 'other'::rpg.item_type, 'Barding — Couro Batido', '{"text":"180 PO"}'::jsonb, '13 kg', 'Armadura de montaria (custo e peso ×2 da armadura correspondente).', '{"kind":"barding","baseArmorSlug":"studded-leather"}'::jsonb),
  ('barding-hide', 'other'::rpg.item_type, 'Barding — Gibão de Peles', '{"text":"40 PO"}'::jsonb, '12 kg', 'Armadura de montaria (custo e peso ×2 da armadura correspondente).', '{"kind":"barding","baseArmorSlug":"hide"}'::jsonb),
  ('barding-chain-shirt', 'other'::rpg.item_type, 'Barding — Cota de Malha Parcial', '{"text":"200 PO"}'::jsonb, '20 kg', 'Armadura de montaria (custo e peso ×2 da armadura correspondente).', '{"kind":"barding","baseArmorSlug":"chain-shirt"}'::jsonb),
  ('barding-scale-mail', 'other'::rpg.item_type, 'Barding — Loriga de Escamas', '{"text":"200 PO"}'::jsonb, '44 kg', 'Armadura de montaria (custo e peso ×2 da armadura correspondente).', '{"kind":"barding","baseArmorSlug":"scale-mail"}'::jsonb),
  ('barding-breastplate', 'other'::rpg.item_type, 'Barding — Couraça', '{"text":"1.600 PO"}'::jsonb, '20 kg', 'Armadura de montaria (custo e peso ×2 da armadura correspondente).', '{"kind":"barding","baseArmorSlug":"breastplate"}'::jsonb),
  ('barding-half-plate', 'other'::rpg.item_type, 'Barding — Meia-Placa', '{"text":"3.000 PO"}'::jsonb, '40 kg', 'Armadura de montaria (custo e peso ×2 da armadura correspondente).', '{"kind":"barding","baseArmorSlug":"half-plate"}'::jsonb),
  ('barding-ring-mail', 'other'::rpg.item_type, 'Barding — Cota de Anéis', '{"text":"120 PO"}'::jsonb, '40 kg', 'Armadura de montaria (custo e peso ×2 da armadura correspondente).', '{"kind":"barding","baseArmorSlug":"ring-mail"}'::jsonb),
  ('barding-chain-mail', 'other'::rpg.item_type, 'Barding — Cota de Malha', '{"text":"300 PO"}'::jsonb, '54 kg', 'Armadura de montaria (custo e peso ×2 da armadura correspondente).', '{"kind":"barding","baseArmorSlug":"chain-mail"}'::jsonb),
  ('barding-splint', 'other'::rpg.item_type, 'Barding — Armadura de Talas', '{"text":"800 PO"}'::jsonb, '60 kg', 'Armadura de montaria (custo e peso ×2 da armadura correspondente).', '{"kind":"barding","baseArmorSlug":"splint"}'::jsonb),
  ('barding-plate', 'other'::rpg.item_type, 'Barding — Placas', '{"text":"6.000 PO"}'::jsonb, '64 kg', 'Armadura de montaria (custo e peso ×2 da armadura correspondente).', '{"kind":"barding","baseArmorSlug":"plate"}'::jsonb),
  ('acido', 'gear'::rpg.item_type, 'Ácido', '{"text":"25 PO"}'::jsonb, '0,5 kg', 'Ao executar a ação Atacar, você pode substituir um', NULL),
  ('agua-benta', 'gear'::rpg.item_type, 'Água Benta', '{"text":"25 PO"}'::jsonb, '0,5 kg', 'Ao executar a ação Atacar, você pode substituir um de', NULL),
  ('algibeira', 'gear'::rpg.item_type, 'Algibeira', '{"text":"5 PP"}'::jsonb, '0,5 kg', 'Uma Algibeira comporta até 3 kg em um volume de 6', NULL),
  ('aljava', 'gear'::rpg.item_type, 'Aljava', '{"text":"1 PO"}'::jsonb, '0,5 kg', 'Uma Aljava armazena até 20 Flechas.', NULL),
  ('antitoxina', 'gear'::rpg.item_type, 'Antitoxina', '{"text":"50 PO"}'::jsonb, '—', 'Como uma Ação Bônus, você pode beber um frasco de', NULL),
  ('apito-sinalizador', 'gear'::rpg.item_type, 'Apito Sinalizador', '{"text":"5 PC"}'::jsonb, '—', 'Quando soprado como uma ação Usar Objeto, um', NULL),
  ('ariete-portavel', 'gear'::rpg.item_type, 'Aríete Portável', '{"text":"4 PO"}'::jsonb, '16,5 kg', 'Você pode usar um Aríete Portável para arrombar', NULL),
  ('armadilha-de-caca', 'gear'::rpg.item_type, 'Armadilha de Caça', '{"text":"5 PO"}'::jsonb, '12,5 kg', 'Como uma ação Usar Objeto, você pode armar uma', NULL),
  ('arpeu', 'gear'::rpg.item_type, 'Arpéu', '{"text":"2 PO"}'::jsonb, '2 kg', 'Como uma ação Usar Objeto, você pode arremessar um', NULL),
  ('balde', 'gear'::rpg.item_type, 'Balde', '{"text":"5 PC"}'::jsonb, '1 kg', 'Um Balde armazena até 0,3 metro cúbico de conteúdo.', NULL),
  ('baliza', 'gear'::rpg.item_type, 'Baliza', '{"text":"5 PC"}'::jsonb, '3,5 kg', 'Uma Baliza tem 3 metros de comprimento. Você pode', NULL),
  ('barril', 'gear'::rpg.item_type, 'Barril', '{"text":"2 PO"}'::jsonb, '35 kg', 'Um Barril armazena até 160 litros de líquido ou até', NULL),
  ('bau', 'gear'::rpg.item_type, 'Baú', '{"text":"5 PO"}'::jsonb, '12,5 kg', 'Um Baú armazena até 0,35 metros cúbicos (ou 350', NULL),
  ('bolsa-de-componentes', 'gear'::rpg.item_type, 'Bolsa de Componentes', '{"text":"25 PO"}'::jsonb, '1 kg', 'Uma Bolsa de Componentes é à prova d’água e cheia', NULL),
  ('cadeado', 'gear'::rpg.item_type, 'Cadeado', '{"text":"10 PO"}'::jsonb, '0,5 kg', 'Um Cadeado vem com uma chave. Sem a chave, uma', NULL),
  ('caixa-para-fogo', 'gear'::rpg.item_type, 'Caixa para Fogo', '{"text":"5 PP"}'::jsonb, '0,5 kg', 'Uma Caixa para Fogo é um pequeno recipiente contendo pedra de sílex, aço contra fogo e material muito', NULL),
  ('caneta-tinteiro', 'gear'::rpg.item_type, 'Caneta Tinteiro', '{"text":"2 PC"}'::jsonb, '—', 'Usando Tinta, uma Caneta Tinteiro é usada para escrever ou desenhar.', NULL),
  ('cantil-cheio', 'gear'::rpg.item_type, 'Cantil (cheio)', '{"text":"2 PP"}'::jsonb, '2,5 kg', 'Um Cantil comporta até 2 litros. Se você não beber', NULL),
  ('cesta', 'gear'::rpg.item_type, 'Cesta', '{"text":"4 PP"}'::jsonb, '1 kg', 'Uma Cesta armazena até 20 quilos dentro de 60 centímetros cúbicos.', NULL),
  ('cobertor', 'gear'::rpg.item_type, 'Cobertor', '{"text":"5 PP"}'::jsonb, '1,5 kg', 'Enquanto estiver envolto em um cobertor, você tem', NULL),
  ('corda', 'gear'::rpg.item_type, 'Corda', '{"text":"1 PO"}'::jsonb, '2,5 kg', 'Como uma ação Usar Objeto, você pode dar um nó em', NULL),
  ('cordao', 'gear'::rpg.item_type, 'Cordão', '{"text":"1 PP"}'::jsonb, '—', 'Um cordão tem 3 metros de comprimento. Você pode', NULL),
  ('corrente', 'gear'::rpg.item_type, 'Corrente', '{"text":"5 PO"}'::jsonb, '5 kg', 'Como uma ação Usar Objeto, você pode enrolar uma', NULL),
  ('escada', 'gear'::rpg.item_type, 'Escada', '{"text":"1 PP"}'::jsonb, '12,5 kg', 'Uma Escada tem 3 metros de altura. Você deve escalar', NULL),
  ('esferas-de-metal', 'gear'::rpg.item_type, 'Esferas de Metal', '{"text":"1 PO"}'::jsonb, '1 kg (saco)', 'Como uma ação Usar Objeto, você pode derramar', NULL),
  ('espelho', 'gear'::rpg.item_type, 'Espelho', '{"text":"5 PO"}'::jsonb, '250 g', 'Um espelho de aço portátil é prático tanto para uso', NULL),
  ('estacas-de-ferro', 'gear'::rpg.item_type, 'Estacas de Ferro', '{"text":"1 PO"}'::jsonb, '2,5 kg', 'Estacas de Ferro vêm em pacotes de dez. Como uma', NULL),
  ('estojo-mapa-ou-pergaminho', 'gear'::rpg.item_type, 'Estojo, Mapa ou Pergaminho', '{"text":"1 PO"}'::jsonb, '0,5 kg', 'Um Estojo de Mapa ou Pergaminho armazena até 10', NULL),
  ('estojo-virote-de-besta', 'gear'::rpg.item_type, 'Estojo, Virote de Besta', '{"text":"1 PO"}'::jsonb, '0,5 kg', 'Um Estojo de Virotes de Besta armazena até 20', NULL),
  ('estrepes', 'gear'::rpg.item_type, 'Estrepes', '{"text":"1 PO"}'::jsonb, '1 kg (saco)', 'Como uma ação Usar Objeto, você pode espalhar', NULL),
  ('foco-arcano', 'focus'::rpg.item_type, 'Foco Arcano', NULL, 'Varia', 'Categoria: escolha uma variante (cristal, orbe, bastão, cajado ou varinha).', '{"catalogGroup":true}'::jsonb),
  ('foco-druidico', 'focus'::rpg.item_type, 'Foco Druídico', NULL, 'Varia', 'Categoria: escolha uma variante (ramo de visco, cajado de madeira ou varinha de teixo).', '{"catalogGroup":true}'::jsonb),
  ('fogo-alquimico', 'gear'::rpg.item_type, 'Fogo Alquímico', '{"text":"50 PO"}'::jsonb, '0,5 kg', 'Ao executar a ação Atacar, você pode substituir um de', NULL),
  ('frasco', 'gear'::rpg.item_type, 'Frasco', '{"text":"1 PO"}'::jsonb, '—', 'Um Frasco armazena até 150 mililitros.', NULL),
  ('garrafa-de-vidro-1-litro', 'gear'::rpg.item_type, 'Garrafa de Vidro (1 litro)', '{"text":"2 PO"}'::jsonb, '1 kg', 'Uma Garrafa de Vidro armazena até 1 litro.', NULL),
  ('grilhoes', 'gear'::rpg.item_type, 'Grilhões', '{"text":"2 PO"}'::jsonb, '3 kg', 'Como uma ação Usar Objeto, você pode usar Grilhões', NULL),
  ('jarro-4-litros', 'gear'::rpg.item_type, 'Jarro (4 litros)', '{"text":"2 PC"}'::jsonb, '2 kg', 'Um Jarro armazena até 4 litros.', NULL),
  ('kit-de-artista', 'gear'::rpg.item_type, 'Kit de Artista', '{"text":"40 PO"}'::jsonb, '29 kg', 'Um Kit de Artista contém os seguintes itens: Caixa', NULL),
  ('kit-de-assaltante', 'gear'::rpg.item_type, 'Kit de Assaltante', '{"text":"16 PO"}'::jsonb, '21 kg', 'Um Kit de Assaltante contém os seguintes itens: Caixa', NULL),
  ('kit-de-aventureiro', 'gear'::rpg.item_type, 'Kit de Aventureiro', '{"text":"10 PO"}'::jsonb, '27,5 kg', 'Um Kit de Aventureiro contém os seguintes itens: Caixa para Fogo, Cantil, Corda, Mochila, 2 potes de Óleo,', NULL),
  ('kit-de-curandeiro', 'gear'::rpg.item_type, 'Kit de Curandeiro', '{"text":"5 PO"}'::jsonb, '1,5 kg', 'Um Kit de Curandeiro tem dez usos. Como uma ação', NULL),
  ('kit-de-diplomata', 'gear'::rpg.item_type, 'Kit de Diplomata', '{"text":"39 PO"}'::jsonb, '19,5 kg', 'Um Kit de Diplomata contém os seguintes itens: Baú,', NULL),
  ('kit-de-erudito', 'gear'::rpg.item_type, 'Kit de Erudito', '{"text":"40 PO"}'::jsonb, '11 kg', 'Um Kit de Erudito contém os seguintes itens: Caixa', NULL),
  ('kit-de-escalada', 'gear'::rpg.item_type, 'Kit de Escalada', '{"text":"25 PO"}'::jsonb, '6 kg', 'Um Kit de Escalada inclui arnês, luvas, pítons e ponteiras de bota. Como uma ação Usar Objeto, você pode', NULL),
  ('kit-de-explorador-de-masmorras', 'gear'::rpg.item_type, 'Kit de Explorador de Masmorras', '{"text":"12 PO"}'::jsonb, '27,5 kg', 'Um Kit de Explorador de Masmorras contém os', NULL),
  ('kit-de-sacerdote', 'gear'::rpg.item_type, 'Kit de Sacerdote', '{"text":"33 PO"}'::jsonb, '14,5 kg', 'Um Kit de Sacerdote contém os seguintes itens: Água', NULL),
  ('lampada', 'gear'::rpg.item_type, 'Lâmpada', '{"text":"5 PP"}'::jsonb, '0,5 kg', 'Uma Lâmpada usa Óleo para combustão para emitir', NULL),
  ('lanterna-coberta', 'gear'::rpg.item_type, 'Lanterna Coberta', '{"text":"5 PO"}'::jsonb, '1 kg', 'Uma Lanterna Coberta usa Óleo para combustão para', NULL),
  ('lanterna-foca-facho', 'gear'::rpg.item_type, 'Lanterna Foca-facho', '{"text":"10 PO"}'::jsonb, '1 kg', 'Uma Lanterna Foca-Facho usa Óleo como combustão', NULL),
  ('livro', 'gear'::rpg.item_type, 'Livro', '{"text":"25 PO"}'::jsonb, '2,5 kg', 'Um livro contém texto de ficção ou não-ficção. Se você', NULL),
  ('luneta', 'gear'::rpg.item_type, 'Luneta', '{"text":"1.000 PO"}'::jsonb, '0,5 kg', 'Objetos vistos através de uma Luneta são ampliados', NULL),
  ('lupa', 'gear'::rpg.item_type, 'Lupa', '{"text":"100 PO"}'::jsonb, '—', 'Uma Lupa concede Vantagem em qualquer teste de', NULL),
  ('mapa', 'gear'::rpg.item_type, 'Mapa', '{"text":"1 PO"}'::jsonb, '—', 'Se consultar um mapa detalhado, você obtém um', NULL),
  ('mochila', 'gear'::rpg.item_type, 'Mochila', '{"text":"2 PO"}'::jsonb, '2,5 kg', 'Uma Mochila armazena até 15 quilos dentro de 30', NULL),
  ('municao', 'gear'::rpg.item_type, 'Munição', NULL, 'Varia', 'Categoria: escolha flechas, virotes, balas ou agulhas.', '{"catalogGroup":true}'::jsonb),
  ('oleo', 'gear'::rpg.item_type, 'Óleo', '{"text":"1 PP"}'::jsonb, '0,5 kg', 'Você pode cobrir uma criatura, objeto ou área com', NULL),
  ('pa', 'gear'::rpg.item_type, 'Pá', '{"text":"2 PO"}'::jsonb, '2,5 kg', 'Trabalhando por 1 hora, você pode usar uma Pá para', NULL),
  ('papel', 'gear'::rpg.item_type, 'Papel', '{"text":"2 PP"}'::jsonb, '—', 'Uma folha de papel pode comportar cerca de 250 palavras escritas à mão.', NULL),
  ('pe-de-cabra', 'gear'::rpg.item_type, 'Pé de Cabra', '{"text":"2 PO"}'::jsonb, '2,5 kg', 'Usar um Pé de Cabra concede a você Vantagem em', NULL),
  ('perfume', 'gear'::rpg.item_type, 'Perfume', '{"text":"5 PO"}'::jsonb, '—', 'O perfume vem em um frasco de 120 mililitros. Por 1', NULL),
  ('pergaminho', 'gear'::rpg.item_type, 'Pergaminho', '{"text":"1 PP"}'::jsonb, '—', 'Uma folha de pergaminho pode comportar cerca de', NULL),
  ('pergaminho-magico-1-circulo', 'gear'::rpg.item_type, 'Pergaminho Mágico (1º Círculo)', '{"text":"50 PO"}'::jsonb, '—', 'Uma folha de pergaminho pode comportar cerca de', NULL),
  ('pergaminho-magico-truque', 'gear'::rpg.item_type, 'Pergaminho Mágico (Truque)', '{"text":"30 PO"}'::jsonb, '—', 'Uma folha de pergaminho pode comportar cerca de', NULL),
  ('pocao-de-cura', 'gear'::rpg.item_type, 'Poção de Cura', '{"text":"50 PO"}'::jsonb, '250 g', 'Esta poção é um item mágico. Como uma Ação Bônus,', NULL),
  ('pote', 'gear'::rpg.item_type, 'Pote', '{"text":"2 PC"}'::jsonb, '0,5 kg', 'Um Frasco armazena até meio litro.', NULL),
  ('pote-ferro', 'gear'::rpg.item_type, 'Pote, Ferro', '{"text":"2 PO"}'::jsonb, '5 kg', 'Um Frasco armazena até meio litro.', NULL),
  ('racoes', 'gear'::rpg.item_type, 'Rações', '{"text":"5 PP"}'::jsonb, '1 kg', 'As rações consistem em alimentos prontos para viagem, incluindo biscoito duro, carne seca, frutas secas e', NULL),
  ('rede', 'gear'::rpg.item_type, 'Rede', '{"text":"1 PO"}'::jsonb, '1,5 kg', 'Ao executar a ação Atacar, você pode substituir um', NULL),
  ('roldana-e-polias', 'gear'::rpg.item_type, 'Roldana e Polias', '{"text":"1 PO"}'::jsonb, '2,5 kg', 'Roldana e Polias permitem içar até quatro vezes o peso', NULL),
  ('roupas-fantasia', 'gear'::rpg.item_type, 'Roupas, Fantasia', '{"text":"5 PO"}'::jsonb, '2 kg', 'Roupas Finas são feitas de tecidos caros e adornadas', NULL),
  ('roupas-finas', 'gear'::rpg.item_type, 'Roupas, Finas', '{"text":"15 PO"}'::jsonb, '3 kg', 'Roupas Finas são feitas de tecidos caros e adornadas', NULL),
  ('roupas-viagem', 'gear'::rpg.item_type, 'Roupas, Viagem', '{"text":"2 PO"}'::jsonb, '2 kg', 'Roupas de Viagem são roupas resistentes projetadas', NULL),
  ('saca', 'gear'::rpg.item_type, 'Saca', '{"text":"1 PC"}'::jsonb, '250 g', 'Uma Saca armazena até 15 kg dentro de 30 centímetros cúbicos.', NULL),
  ('saco-de-dormir', 'gear'::rpg.item_type, 'Saco de Dormir', '{"text":"1 PO"}'::jsonb, '3,5 kg', 'Um Saco de Dormir acomoda uma criatura Pequena', NULL),
  ('simbolo-sagrado', 'gear'::rpg.item_type, 'Símbolo Sagrado', NULL, 'Varia', 'Categoria: escolha amuleto, emblema ou relicário.', '{"catalogGroup":true}'::jsonb),
  ('sino', 'gear'::rpg.item_type, 'Sino', '{"text":"1 PO"}'::jsonb, '—', 'Quando tocado como uma ação Usar Objeto, um Sino', NULL),
  ('tenda', 'gear'::rpg.item_type, 'Tenda', '{"text":"2 PO"}'::jsonb, '10 kg', 'Uma Tenda acomoda para dormir até duas criaturas', NULL),
  ('tinta', 'gear'::rpg.item_type, 'Tinta', '{"text":"10 PO"}'::jsonb, '—', 'A tinta vem em uma garrafa de 30 mililitros, que', NULL),
  ('tocha', 'gear'::rpg.item_type, 'Tocha', '{"text":"1 PC"}'::jsonb, '0,5 kg', 'Uma Tocha entra em combustão por 1 hora, emitindo', NULL),
  ('vela', 'gear'::rpg.item_type, 'Vela', '{"text":"1 PC"}'::jsonb, '—', 'Por 1 hora, uma Vela acesa emite Luz Plena em um raio', NULL),
  ('tunica', 'gear'::rpg.item_type, 'Túnica', '{"text":"1 PO"}'::jsonb, '2 kg', 'Uma Túnica tem significado vocacional ou cerimonial.', NULL),
  ('veneno-basico', 'gear'::rpg.item_type, 'Veneno Básico', '{"text":"100 PO"}'::jsonb, '—', 'Como uma Ação Bônus, você pode usar um frasco', NULL),
  ('ferramentas-de-carpinteiro', 'tool'::rpg.item_type, 'Ferramentas de Carpinteiro', '{"text":"8 PO"}'::jsonb, '3 kg', 'Selar ou abrir uma porta ou recipiente (CD 20)', '{"attribute":"Força","crafting":"Aríete Portável, Baliza, Barril, Baú, Cajado, Clava,\nClava Grande, Escada, Tocha","variants":null}'::jsonb),
  ('ferramentas-de-cartografo', 'tool'::rpg.item_type, 'Ferramentas de Cartógrafo', '{"text":"15 PO"}'::jsonb, '3 kg', 'Elaborar o mapa de uma pequena área (CD 15)', '{"attribute":"Sabedoria","crafting":"Mapa","variants":null}'::jsonb),
  ('ferramentas-de-coureiro', 'tool'::rpg.item_type, 'Ferramentas de Coureiro', '{"text":"5 PO"}'::jsonb, '2,5 kg', 'Moldar a estética de um item de couro (CD 10)', '{"attribute":"Destreza","crafting":"Algibeira, Aljava, Armadura de Couro, Armadura\nde Couro Batido, Cantil, Chicote, Estojo de Mapa ou\nPergaminho, Estojo de Virotes de Besta, Funda, Gibão de\nPeles, Mochila, Pergaminho","variants":null}'::jsonb),
  ('ferramentas-de-entalhador', 'tool'::rpg.item_type, 'Ferramentas de Entalhador', '{"text":"1 PO"}'::jsonb, '2,5 kg', 'Entalhar um padrão em madeira (CD 10)', '{"attribute":"Destreza","crafting":"Armas à Distância (exceto Funda, Mosquete e\nPistola), Cajado, Caneta Tinteiro, Clava, Clava Grande,\nDardos, Flechas, Foco Arcano, Foco Druídico, Virotes","variants":null}'::jsonb),
  ('ferramentas-de-ferreiro', 'tool'::rpg.item_type, 'Ferramentas de Ferreiro', '{"text":"20 PO"}'::jsonb, '4 kg', 'Forçar a abertura de uma porta ou recipiente (CD 20)', '{"attribute":"Força","crafting":"qualquer arma Corpo a Corpo (exceto Cajado,\nChicote, Clava, Clava Grande), armadura Média (exceto\nGibão de Peles), armadura Pesada, Arpéu e Gancho, Balas\nde Arma de Fogo, Balas de Funda, Balde, Corrente, Esferas\nde Metal, Estacas de Ferro, Estrepes, Panela de Ferro, Pé de\nCabra","variants":null}'::jsonb),
  ('ferramentas-de-funileiro', 'tool'::rpg.item_type, 'Ferramentas de Funileiro', '{"text":"50 PO"}'::jsonb, '5 kg', 'Monte um item Minúsculo composto de sucata,
que se desfaz em 1 minuto (CD 20)', '{"attribute":"Destreza","crafting":"Apito Sinalizador, Armadilha de Caça, Cadeado\nou Fechadura, Caixa para Fogo, Espelho, Grilhões, Lanterna\nCoberta, Lanterna Foca-Facho, Mosquete, Pá, Pistola,Pote,\nSino","variants":null}'::jsonb),
  ('ferramentas-de-joalheiro', 'tool'::rpg.item_type, 'Ferramentas de Joalheiro', '{"text":"25 PO"}'::jsonb, '1 kg', 'Discernir o valor de uma gema (CD 15)', '{"attribute":"Inteligência","crafting":"Foco Arcano, Símbolo Sagrado","variants":null}'::jsonb),
  ('ferramentas-de-oleiro', 'tool'::rpg.item_type, 'Ferramentas de Oleiro', '{"text":"10 PO"}'::jsonb, '1,5 kg', 'Discernir como um objeto de cerâmica foi
manuseado nas últimas 24 horas (CD 15)', '{"attribute":"Inteligência","crafting":"Jarro, Lâmpada","variants":null}'::jsonb),
  ('ferramentas-de-pedreiro', 'tool'::rpg.item_type, 'Ferramentas de Pedreiro', '{"text":"10 PO"}'::jsonb, '4 kg', 'Cinzelar um símbolo ou buraco na pedra (CD 10)', '{"attribute":"Força","crafting":"Roldana e Polias","variants":null}'::jsonb),
  ('ferramentas-de-sapateiro', 'tool'::rpg.item_type, 'Ferramentas de Sapateiro', '{"text":"5 PO"}'::jsonb, '2,5 kg', 'Modificar calçado para conceder Vantagem no
próximo teste de Destreza (Acrobacia) do usuário (CD 10)', '{"attribute":"Destreza","crafting":"Kit de Escalada","variants":null}'::jsonb),
  ('ferramentas-de-tecelao', 'tool'::rpg.item_type, 'Ferramentas de Tecelão', '{"text":"1 PO"}'::jsonb, '2,5 kg', 'Reparar um rasgo em uma roupa (CD 10) ou
costurar um ornamento Minúsculo (CD 10)', '{"attribute":"Destreza","crafting":"Armadura Acolchoada, Cesta, Cobertor, Saco de\nDormir, Roupas Finas, Rede, Túnica, Corda, Saca, Cordão,\nTenda, Roupas de Viagem","variants":null}'::jsonb),
  ('ferramentas-de-vidreiro', 'tool'::rpg.item_type, 'Ferramentas de Vidreiro', '{"text":"30 PO"}'::jsonb, '2,5 kg', 'Discernir como um objeto de vidro foi
manuseado nas últimas 24 horas (CD 15)', '{"attribute":"Inteligência","crafting":"Frasco, Jarro, Luneta, Lupa","variants":null}'::jsonb),
  ('suprimentos-de-alquimista', 'tool'::rpg.item_type, 'Suprimentos de Alquimista', '{"text":"50 PO"}'::jsonb, '4 kg', 'Identificar uma substância (CD 15) ou iniciar um
incêndio (CD 15)', '{"attribute":"Inteligência","crafting":"Ácido, Bolsa de Componentes, Fogo Alquímico,\nÓleo, Papel, Perfume","variants":null}'::jsonb),
  ('suprimentos-de-caligrafo', 'tool'::rpg.item_type, 'Suprimentos de Calígrafo', '{"text":"10 PO"}'::jsonb, '2,5 kg', 'Escrever texto com uma caligrafia que protege
contra falsificação (CD 15)', '{"attribute":"Destreza","crafting":"Pergaminho Mágico, Tinta","variants":null}'::jsonb),
  ('suprimentos-de-cervejeiro', 'tool'::rpg.item_type, 'Suprimentos de Cervejeiro', '{"text":"20 PO"}'::jsonb, '4,5 kg', 'Detectar bebida envenenada (CD 15) ou
identificar álcool (CD 10)', '{"attribute":"Inteligência","crafting":"Antitoxina","variants":null}'::jsonb),
  ('suprimentos-de-pintor', 'tool'::rpg.item_type, 'Suprimentos de Pintor', '{"text":"10 PO"}'::jsonb, '2,5 kg', 'Fazer uma pintura reconhecível de algo que você
viu (CD 10)', '{"attribute":"Sabedoria","crafting":"Foco Druídico, Símbolo Sagrado","variants":null}'::jsonb),
  ('utensilios-de-cozinheiro', 'tool'::rpg.item_type, 'Utensílios de Cozinheiro', '{"text":"1 PO"}'::jsonb, '4 kg', 'Melhorar o sabor dos alimentos (CD 10) ou
detectar alimentos estragados ou envenenados (CD 15)', '{"attribute":"Sabedoria","crafting":"Rações","variants":null}'::jsonb),
  ('ferramentas-de-ladrao', 'tool'::rpg.item_type, 'Ferramentas de Ladrão', '{"text":"25 PO"}'::jsonb, '0,5 kg', 'Abrir uma fechadura (CD 15) ou desarmar uma
armadilha (CD 15)', '{"attribute":"Destreza","crafting":null,"variants":null}'::jsonb),
  ('ferramentas-de-navegador', 'tool'::rpg.item_type, 'Ferramentas de Navegador', '{"text":"25 PO"}'::jsonb, '1 kg', 'Traçar uma rota (CD 10) ou determinar a posição
observando as estrelas (CD 15)', '{"attribute":"Sabedoria","crafting":null,"variants":null}'::jsonb),
  ('instrumento-musical', 'tool'::rpg.item_type, 'Instrumento Musical', NULL, 'Varia', 'Categoria: escolha um instrumento concreto (alaúde, flauta, etc.).', '{"attribute":"Carisma","crafting":null,"catalogGroup":true}'::jsonb),
  ('kit-de-disfarce', 'tool'::rpg.item_type, 'Kit de Disfarce', '{"text":"25 PO"}'::jsonb, '1,5 kg', 'Aplicar maquiagem (CD 10)', '{"attribute":"Carisma","crafting":"Fantasia","variants":null}'::jsonb),
  ('kit-de-falsificacao', 'tool'::rpg.item_type, 'Kit de Falsificação', '{"text":"15 PO"}'::jsonb, '2,5 kg', 'Imitar 10 ou menos palavras escritas de outra
pessoa (CD 15) ou duplicar um selo de cera (CD 20)', '{"attribute":"Destreza","crafting":null,"variants":null}'::jsonb),
  ('kit-de-herbalismo', 'tool'::rpg.item_type, 'Kit de Herbalismo', '{"text":"5 PO"}'::jsonb, '1,5 kg', 'Identificar uma planta (CD 10)', '{"attribute":"Inteligência","crafting":"Antitoxina, Kit de Curandeiro, Poção de Cura, Vela","variants":null}'::jsonb),
  ('kit-de-jogos', 'tool'::rpg.item_type, 'Kit de Jogos', NULL, '—', 'Categoria: escolha dados, xadrez-do-dragão, baralho ou ante dos três dragões.', '{"attribute":"Sabedoria","crafting":null,"catalogGroup":true}'::jsonb),
  ('kit-de-veneno', 'tool'::rpg.item_type, 'Kit de Veneno', '{"text":"50 PO"}'::jsonb, '1 kg', 'Detectar um objeto envenenado (CD 10)', '{"attribute":"Inteligência","crafting":"Veneno Básico","variants":null}'::jsonb),

  -- Variantes: foco arcano
  ('cristal', 'focus'::rpg.item_type, 'Cristal', '{"text":"10 PO"}'::jsonb, '0,5 kg', 'Foco Arcano.', '{"variantOf":"foco-arcano"}'::jsonb),
  ('orbe', 'focus'::rpg.item_type, 'Orbe', '{"text":"20 PO"}'::jsonb, '1,5 kg', 'Foco Arcano.', '{"variantOf":"foco-arcano"}'::jsonb),
  ('bastao', 'focus'::rpg.item_type, 'Bastão', '{"text":"10 PO"}'::jsonb, '1 kg', 'Foco Arcano.', '{"variantOf":"foco-arcano"}'::jsonb),
  ('cajado-arcano', 'focus'::rpg.item_type, 'Cajado (Foco Arcano)', '{"text":"5 PO"}'::jsonb, '2 kg', 'Foco Arcano; também conta como Cajado (arma).', '{"variantOf":"foco-arcano","alsoWeaponSlug":"quarterstaff"}'::jsonb),
  ('varinha', 'focus'::rpg.item_type, 'Varinha', '{"text":"10 PO"}'::jsonb, '0,5 kg', 'Foco Arcano.', '{"variantOf":"foco-arcano"}'::jsonb),

  -- Variantes: foco druídico
  ('ramo-de-visco', 'focus'::rpg.item_type, 'Ramo de Visco', '{"text":"1 PO"}'::jsonb, '—', 'Foco Druídico.', '{"variantOf":"foco-druidico"}'::jsonb),
  ('cajado-de-madeira', 'focus'::rpg.item_type, 'Cajado de Madeira', '{"text":"5 PO"}'::jsonb, '2 kg', 'Foco Druídico; também conta como Cajado (arma).', '{"variantOf":"foco-druidico","alsoWeaponSlug":"quarterstaff"}'::jsonb),
  ('varinha-de-teixo', 'focus'::rpg.item_type, 'Varinha de Teixo', '{"text":"10 PO"}'::jsonb, '0,5 kg', 'Foco Druídico.', '{"variantOf":"foco-druidico"}'::jsonb),

  -- Variantes: símbolo sagrado
  ('amuleto', 'focus'::rpg.item_type, 'Amuleto', '{"text":"5 PO"}'::jsonb, '0,5 kg', 'Símbolo Sagrado (usado ou empunhado).', '{"variantOf":"simbolo-sagrado","wornOrHeld":true}'::jsonb),
  ('emblema', 'focus'::rpg.item_type, 'Emblema', '{"text":"5 PO"}'::jsonb, '—', 'Símbolo Sagrado (em tecido ou Escudo).', '{"variantOf":"simbolo-sagrado","borneOnFabricOrShield":true}'::jsonb),
  ('relicario', 'focus'::rpg.item_type, 'Relicário', '{"text":"5 PO"}'::jsonb, '1 kg', 'Símbolo Sagrado (empunhado).', '{"variantOf":"simbolo-sagrado","held":true}'::jsonb),

  -- Variantes: munição (pacote inclui estojo/aljava adequado)
  ('flechas', 'gear'::rpg.item_type, 'Flechas (20)', '{"text":"1 PO"}'::jsonb, '0,5 kg', '20 flechas; inclui Aljava.', '{"variantOf":"municao","amount":20,"storageSlug":"aljava"}'::jsonb),
  ('virotes', 'gear'::rpg.item_type, 'Virotes (20)', '{"text":"1 PO"}'::jsonb, '0,75 kg', '20 virotes; inclui Estojo de Virotes.', '{"variantOf":"municao","amount":20,"storageSlug":"estojo-virote-de-besta"}'::jsonb),
  ('balas-arma-de-fogo', 'gear'::rpg.item_type, 'Balas, Arma de Fogo (10)', '{"text":"3 PO"}'::jsonb, '1 kg', '10 balas de arma de fogo; inclui Algibeira.', '{"variantOf":"municao","amount":10,"storageSlug":"algibeira"}'::jsonb),
  ('balas-de-funda', 'gear'::rpg.item_type, 'Balas, Funda (20)', '{"text":"4 PC"}'::jsonb, '0,75 kg', '20 balas de funda; inclui Algibeira.', '{"variantOf":"municao","amount":20,"storageSlug":"algibeira"}'::jsonb),
  ('agulhas', 'gear'::rpg.item_type, 'Agulhas (50)', '{"text":"1 PO"}'::jsonb, '0,5 kg', '50 agulhas de sopro; inclui Algibeira.', '{"variantOf":"municao","amount":50,"storageSlug":"algibeira"}'::jsonb),

  -- Variantes: instrumentos (slugs alinhados a S060 / backgrounds)
  ('gaita-de-foles', 'tool'::rpg.item_type, 'Gaita de Foles', '{"text":"30 PO"}'::jsonb, '3 kg', 'Instrumento musical.', '{"variantOf":"instrumento-musical","attribute":"Carisma"}'::jsonb),
  ('tambor', 'tool'::rpg.item_type, 'Tambor', '{"text":"6 PO"}'::jsonb, '1,5 kg', 'Instrumento musical.', '{"variantOf":"instrumento-musical","attribute":"Carisma"}'::jsonb),
  ('salterio', 'tool'::rpg.item_type, 'Saltério', '{"text":"25 PO"}'::jsonb, '5 kg', 'Instrumento musical.', '{"variantOf":"instrumento-musical","attribute":"Carisma"}'::jsonb),
  ('flauta', 'tool'::rpg.item_type, 'Flauta', '{"text":"2 PO"}'::jsonb, '0,5 kg', 'Instrumento musical.', '{"variantOf":"instrumento-musical","attribute":"Carisma"}'::jsonb),
  ('trompa', 'tool'::rpg.item_type, 'Trompa', '{"text":"3 PO"}'::jsonb, '1 kg', 'Instrumento musical.', '{"variantOf":"instrumento-musical","attribute":"Carisma"}'::jsonb),
  ('alaude', 'tool'::rpg.item_type, 'Alaúde', '{"text":"35 PO"}'::jsonb, '1 kg', 'Instrumento musical.', '{"variantOf":"instrumento-musical","attribute":"Carisma"}'::jsonb),
  ('lira', 'tool'::rpg.item_type, 'Lira', '{"text":"30 PO"}'::jsonb, '1 kg', 'Instrumento musical.', '{"variantOf":"instrumento-musical","attribute":"Carisma"}'::jsonb),
  ('flauta-de-pan', 'tool'::rpg.item_type, 'Flauta de Pã', '{"text":"12 PO"}'::jsonb, '1 kg', 'Instrumento musical.', '{"variantOf":"instrumento-musical","attribute":"Carisma"}'::jsonb),
  ('charamela', 'tool'::rpg.item_type, 'Charamela', '{"text":"2 PO"}'::jsonb, '0,5 kg', 'Instrumento musical.', '{"variantOf":"instrumento-musical","attribute":"Carisma"}'::jsonb),
  ('viola', 'tool'::rpg.item_type, 'Viola', '{"text":"30 PO"}'::jsonb, '0,5 kg', 'Instrumento musical.', '{"variantOf":"instrumento-musical","attribute":"Carisma"}'::jsonb),

  -- Variantes: kits de jogos (preços PHB: dados 1 PP, baralho 5 PP)
  ('conjunto-de-dados', 'tool'::rpg.item_type, 'Conjunto de Dados', '{"text":"1 PP"}'::jsonb, '—', 'Kit de jogos.', '{"variantOf":"kit-de-jogos","attribute":"Sabedoria"}'::jsonb),
  ('xadrez-do-dragao', 'tool'::rpg.item_type, 'Xadrez-do-Dragão', '{"text":"1 PO"}'::jsonb, '0,25 kg', 'Kit de jogos.', '{"variantOf":"kit-de-jogos","attribute":"Sabedoria"}'::jsonb),
  ('baralho', 'tool'::rpg.item_type, 'Baralho', '{"text":"5 PP"}'::jsonb, '—', 'Kit de jogos.', '{"variantOf":"kit-de-jogos","attribute":"Sabedoria"}'::jsonb),
  ('ante-dos-tres-dragoes', 'tool'::rpg.item_type, 'Ante dos Três Dragões', '{"text":"1 PO"}'::jsonb, '—', 'Kit de jogos.', '{"variantOf":"kit-de-jogos","attribute":"Sabedoria"}'::jsonb),

  -- Pergaminhos mágicos 2º–9º (venda = 2× custo de scriba PHB)
  ('pergaminho-magico-2-circulo', 'gear'::rpg.item_type, 'Pergaminho Mágico (2º Círculo)', '{"text":"200 PO"}'::jsonb, '—', 'Pergaminho mágico genérico de 2º círculo.', NULL),
  ('pergaminho-magico-3-circulo', 'gear'::rpg.item_type, 'Pergaminho Mágico (3º Círculo)', '{"text":"300 PO"}'::jsonb, '—', 'Pergaminho mágico genérico de 3º círculo.', NULL),
  ('pergaminho-magico-4-circulo', 'gear'::rpg.item_type, 'Pergaminho Mágico (4º Círculo)', '{"text":"2.000 PO"}'::jsonb, '—', 'Pergaminho mágico genérico de 4º círculo.', NULL),
  ('pergaminho-magico-5-circulo', 'gear'::rpg.item_type, 'Pergaminho Mágico (5º Círculo)', '{"text":"3.000 PO"}'::jsonb, '—', 'Pergaminho mágico genérico de 5º círculo.', NULL),
  ('pergaminho-magico-6-circulo', 'gear'::rpg.item_type, 'Pergaminho Mágico (6º Círculo)', '{"text":"20.000 PO"}'::jsonb, '—', 'Pergaminho mágico genérico de 6º círculo.', NULL),
  ('pergaminho-magico-7-circulo', 'gear'::rpg.item_type, 'Pergaminho Mágico (7º Círculo)', '{"text":"25.000 PO"}'::jsonb, '—', 'Pergaminho mágico genérico de 7º círculo.', NULL),
  ('pergaminho-magico-8-circulo', 'gear'::rpg.item_type, 'Pergaminho Mágico (8º Círculo)', '{"text":"30.000 PO"}'::jsonb, '—', 'Pergaminho mágico genérico de 8º círculo.', NULL),
  ('pergaminho-magico-9-circulo', 'gear'::rpg.item_type, 'Pergaminho Mágico (9º Círculo)', '{"text":"100.000 PO"}'::jsonb, '—', 'Pergaminho mágico genérico de 9º círculo.', NULL),

  -- Montarias / animais
  ('camelo', 'other'::rpg.item_type, 'Camelo', '{"text":"50 PO"}'::jsonb, '—', 'Montaria.', '{"kind":"mount","carryingCapacityLb":450}'::jsonb),
  ('elefante', 'other'::rpg.item_type, 'Elefante', '{"text":"200 PO"}'::jsonb, '—', 'Montaria.', '{"kind":"mount","carryingCapacityLb":1320}'::jsonb),
  ('cavalo-de-carga', 'other'::rpg.item_type, 'Cavalo de Carga', '{"text":"50 PO"}'::jsonb, '—', 'Montaria.', '{"kind":"mount","carryingCapacityLb":540}'::jsonb),
  ('cavalo-de-montaria', 'other'::rpg.item_type, 'Cavalo de Montaria', '{"text":"75 PO"}'::jsonb, '—', 'Montaria.', '{"kind":"mount","carryingCapacityLb":480}'::jsonb),
  ('mastim', 'other'::rpg.item_type, 'Mastim', '{"text":"25 PO"}'::jsonb, '—', 'Animal.', '{"kind":"mount","carryingCapacityLb":195}'::jsonb),
  ('mula', 'other'::rpg.item_type, 'Mula', '{"text":"8 PO"}'::jsonb, '—', 'Montaria.', '{"kind":"mount","carryingCapacityLb":420}'::jsonb),
  ('ponei', 'other'::rpg.item_type, 'Pônei', '{"text":"30 PO"}'::jsonb, '—', 'Montaria.', '{"kind":"mount","carryingCapacityLb":225}'::jsonb),
  ('cavalo-de-guerra', 'other'::rpg.item_type, 'Cavalo de Guerra', '{"text":"400 PO"}'::jsonb, '—', 'Montaria.', '{"kind":"mount","carryingCapacityLb":540}'::jsonb),

  -- Arnês / selas / veículos puxados
  ('carruagem', 'gear'::rpg.item_type, 'Carruagem', '{"text":"100 PO"}'::jsonb, '300 kg', 'Veículo puxado.', '{"kind":"drawn-vehicle"}'::jsonb),
  ('carroca', 'gear'::rpg.item_type, 'Carroça', '{"text":"15 PO"}'::jsonb, '100 kg', 'Veículo puxado.', '{"kind":"drawn-vehicle"}'::jsonb),
  ('carro-de-guerra', 'gear'::rpg.item_type, 'Carro de Guerra', '{"text":"250 PO"}'::jsonb, '50 kg', 'Veículo puxado (chariot).', '{"kind":"drawn-vehicle"}'::jsonb),
  ('racao-animal-por-dia', 'gear'::rpg.item_type, 'Ração Animal (por dia)', '{"text":"5 PC"}'::jsonb, '5 kg', 'Alimento para montaria (1 dia).', '{"kind":"mount-feed","billing":"per-day"}'::jsonb),
  ('sela-exotica', 'gear'::rpg.item_type, 'Sela Exótica', '{"text":"60 PO"}'::jsonb, '20 kg', 'Sela.', '{"kind":"saddle"}'::jsonb),
  ('sela-militar', 'gear'::rpg.item_type, 'Sela Militar', '{"text":"20 PO"}'::jsonb, '15 kg', 'Sela.', '{"kind":"saddle"}'::jsonb),
  ('sela-de-montaria', 'gear'::rpg.item_type, 'Sela de Montaria', '{"text":"10 PO"}'::jsonb, '12,5 kg', 'Sela.', '{"kind":"saddle"}'::jsonb),
  ('treno', 'gear'::rpg.item_type, 'Trenó', '{"text":"20 PO"}'::jsonb, '150 kg', 'Veículo puxado.', '{"kind":"drawn-vehicle"}'::jsonb),
  ('estabulo-por-dia', 'other'::rpg.item_type, 'Estábulo (por dia)', '{"text":"5 PP"}'::jsonb, '—', 'Hospedagem de montaria por dia.', '{"kind":"service","billing":"per-day"}'::jsonb),
  ('vagao', 'gear'::rpg.item_type, 'Vagão', '{"text":"35 PO"}'::jsonb, '200 kg', 'Veículo puxado.', '{"kind":"drawn-vehicle"}'::jsonb),

  -- Veículos grandes (ar / água)
  ('aeronave', 'other'::rpg.item_type, 'Aeronave', '{"text":"40.000 PO"}'::jsonb, '—', 'Veículo grande.', '{"kind":"large-vehicle","speed":"8 mph","crew":10,"passengers":20,"cargoTons":1,"ac":13,"hp":300}'::jsonb),
  ('galera', 'other'::rpg.item_type, 'Galera', '{"text":"30.000 PO"}'::jsonb, '—', 'Veículo grande.', '{"kind":"large-vehicle","speed":"4 mph","crew":80,"cargoTons":150,"ac":15,"hp":500,"damageThreshold":20}'::jsonb),
  ('barco-de-quilla', 'other'::rpg.item_type, 'Barco de Quilha', '{"text":"3.000 PO"}'::jsonb, '—', 'Veículo grande.', '{"kind":"large-vehicle","speed":"1 mph","crew":1,"passengers":6,"cargoTons":0.5,"ac":15,"hp":100,"damageThreshold":10}'::jsonb),
  ('navio-longo', 'other'::rpg.item_type, 'Navio Longo', '{"text":"10.000 PO"}'::jsonb, '—', 'Veículo grande.', '{"kind":"large-vehicle","speed":"3 mph","crew":40,"passengers":150,"cargoTons":10,"ac":15,"hp":300,"damageThreshold":15}'::jsonb),
  ('bote', 'other'::rpg.item_type, 'Bote', '{"text":"50 PO"}'::jsonb, '50 kg', 'Veículo grande (pode ser carregado).', '{"kind":"large-vehicle","speed":"1.5 mph","crew":1,"passengers":3,"ac":11,"hp":50}'::jsonb),
  ('navio-a-vela', 'other'::rpg.item_type, 'Navio a Vela', '{"text":"10.000 PO"}'::jsonb, '—', 'Veículo grande.', '{"kind":"large-vehicle","speed":"2 mph","crew":20,"passengers":20,"cargoTons":100,"ac":15,"hp":300,"damageThreshold":15}'::jsonb),
  ('navio-de-guerra', 'other'::rpg.item_type, 'Navio de Guerra', '{"text":"25.000 PO"}'::jsonb, '—', 'Veículo grande.', '{"kind":"large-vehicle","speed":"2.5 mph","crew":60,"passengers":60,"cargoTons":200,"ac":15,"hp":500,"damageThreshold":20}'::jsonb),

  -- Serviços (preço unitário em cost; billing em properties)
  ('estilo-de-vida-miseravel', 'other'::rpg.item_type, 'Estilo de Vida — Miserável', NULL, '—', 'Grátis; sobrevive de caridade.', '{"kind":"service","billing":"per-day","lifestyle":"wretched"}'::jsonb),
  ('estilo-de-vida-sordido', 'other'::rpg.item_type, 'Estilo de Vida — Sórdido', '{"text":"1 PP"}'::jsonb, '—', 'Custo diário de manutenção.', '{"kind":"service","billing":"per-day","lifestyle":"squalid"}'::jsonb),
  ('estilo-de-vida-pobre', 'other'::rpg.item_type, 'Estilo de Vida — Pobre', '{"text":"2 PP"}'::jsonb, '—', 'Custo diário de manutenção.', '{"kind":"service","billing":"per-day","lifestyle":"poor"}'::jsonb),
  ('estilo-de-vida-modesto', 'other'::rpg.item_type, 'Estilo de Vida — Modesto', '{"text":"1 PO"}'::jsonb, '—', 'Custo diário de manutenção.', '{"kind":"service","billing":"per-day","lifestyle":"modest"}'::jsonb),
  ('estilo-de-vida-confortavel', 'other'::rpg.item_type, 'Estilo de Vida — Confortável', '{"text":"2 PO"}'::jsonb, '—', 'Custo diário de manutenção.', '{"kind":"service","billing":"per-day","lifestyle":"comfortable"}'::jsonb),
  ('estilo-de-vida-rico', 'other'::rpg.item_type, 'Estilo de Vida — Rico', '{"text":"4 PO"}'::jsonb, '—', 'Custo diário de manutenção.', '{"kind":"service","billing":"per-day","lifestyle":"wealthy"}'::jsonb),
  ('estilo-de-vida-aristocratico', 'other'::rpg.item_type, 'Estilo de Vida — Aristocrático', '{"text":"10 PO"}'::jsonb, '—', 'Custo diário de manutenção.', '{"kind":"service","billing":"per-day","lifestyle":"aristocratic"}'::jsonb),
  ('cerveja-caneca', 'other'::rpg.item_type, 'Cerveja (caneca)', '{"text":"4 PC"}'::jsonb, '—', 'Comida/bebida.', '{"kind":"service"}'::jsonb),
  ('pao', 'other'::rpg.item_type, 'Pão', '{"text":"2 PC"}'::jsonb, '—', 'Comida/bebida.', '{"kind":"service"}'::jsonb),
  ('queijo-cunha', 'other'::rpg.item_type, 'Queijo (cunha)', '{"text":"1 PP"}'::jsonb, '—', 'Comida/bebida.', '{"kind":"service"}'::jsonb),
  ('estadia-sordida', 'other'::rpg.item_type, 'Estadia na Estalagem — Sórdida', '{"text":"7 PC"}'::jsonb, '—', 'Hospedagem por dia.', '{"kind":"service","billing":"per-day"}'::jsonb),
  ('estadia-pobre', 'other'::rpg.item_type, 'Estadia na Estalagem — Pobre', '{"text":"1 PP"}'::jsonb, '—', 'Hospedagem por dia.', '{"kind":"service","billing":"per-day"}'::jsonb),
  ('estadia-modesta', 'other'::rpg.item_type, 'Estadia na Estalagem — Modesta', '{"text":"5 PP"}'::jsonb, '—', 'Hospedagem por dia.', '{"kind":"service","billing":"per-day"}'::jsonb),
  ('estadia-confortavel', 'other'::rpg.item_type, 'Estadia na Estalagem — Confortável', '{"text":"8 PP"}'::jsonb, '—', 'Hospedagem por dia.', '{"kind":"service","billing":"per-day"}'::jsonb),
  ('estadia-rica', 'other'::rpg.item_type, 'Estadia na Estalagem — Rica', '{"text":"2 PO"}'::jsonb, '—', 'Hospedagem por dia.', '{"kind":"service","billing":"per-day"}'::jsonb),
  ('estadia-aristocratica', 'other'::rpg.item_type, 'Estadia na Estalagem — Aristocrática', '{"text":"4 PO"}'::jsonb, '—', 'Hospedagem por dia.', '{"kind":"service","billing":"per-day"}'::jsonb),
  ('refeicao-sordida', 'other'::rpg.item_type, 'Refeição — Sórdida', '{"text":"1 PC"}'::jsonb, '—', 'Refeição.', '{"kind":"service"}'::jsonb),
  ('refeicao-pobre', 'other'::rpg.item_type, 'Refeição — Pobre', '{"text":"2 PC"}'::jsonb, '—', 'Refeição.', '{"kind":"service"}'::jsonb),
  ('refeicao-modesta', 'other'::rpg.item_type, 'Refeição — Modesta', '{"text":"1 PP"}'::jsonb, '—', 'Refeição.', '{"kind":"service"}'::jsonb),
  ('refeicao-confortavel', 'other'::rpg.item_type, 'Refeição — Confortável', '{"text":"2 PP"}'::jsonb, '—', 'Refeição.', '{"kind":"service"}'::jsonb),
  ('refeicao-rica', 'other'::rpg.item_type, 'Refeição — Rica', '{"text":"3 PP"}'::jsonb, '—', 'Refeição.', '{"kind":"service"}'::jsonb),
  ('refeicao-aristocratica', 'other'::rpg.item_type, 'Refeição — Aristocrática', '{"text":"6 PP"}'::jsonb, '—', 'Refeição.', '{"kind":"service"}'::jsonb),
  ('vinho-comum', 'other'::rpg.item_type, 'Vinho — Comum (garrafa)', '{"text":"2 PP"}'::jsonb, '—', 'Bebida.', '{"kind":"service"}'::jsonb),
  ('vinho-fino', 'other'::rpg.item_type, 'Vinho — Fino (garrafa)', '{"text":"10 PO"}'::jsonb, '—', 'Bebida.', '{"kind":"service"}'::jsonb),
  ('viagem-carroca-entre-cidades', 'other'::rpg.item_type, 'Viagem de Carroça (entre cidades)', '{"text":"3 PC"}'::jsonb, '—', 'Preço por milha.', '{"kind":"service","billing":"per-mile"}'::jsonb),
  ('viagem-carroca-na-cidade', 'other'::rpg.item_type, 'Viagem de Carroça (na cidade)', '{"text":"1 PC"}'::jsonb, '—', 'Preço por milha.', '{"kind":"service","billing":"per-mile"}'::jsonb),
  ('pedagio', 'other'::rpg.item_type, 'Pedágio (estrada ou portão)', '{"text":"1 PC"}'::jsonb, '—', 'Pedágio.', '{"kind":"service"}'::jsonb),
  ('passagem-de-navio', 'other'::rpg.item_type, 'Passagem de Navio', '{"text":"1 PP"}'::jsonb, '—', 'Preço por milha.', '{"kind":"service","billing":"per-mile"}'::jsonb),
  ('servo-habilidoso', 'other'::rpg.item_type, 'Servo Habilidoso', '{"text":"2 PO"}'::jsonb, '—', 'Contratação por dia.', '{"kind":"service","billing":"per-day"}'::jsonb),
  ('servo-nao-treinado', 'other'::rpg.item_type, 'Servo Não Treinado', '{"text":"2 PP"}'::jsonb, '—', 'Contratação por dia.', '{"kind":"service","billing":"per-day"}'::jsonb),
  ('mensageiro', 'other'::rpg.item_type, 'Mensageiro', '{"text":"2 PC"}'::jsonb, '—', 'Preço por milha.', '{"kind":"service","billing":"per-mile"}'::jsonb),
  ('servico-de-magia-truque', 'other'::rpg.item_type, 'Serviço de Magia — Truque', '{"text":"30 PO"}'::jsonb, '—', 'Conjuração contratada (+ componentes caros).', '{"kind":"service","spellLevel":0}'::jsonb),
  ('servico-de-magia-1', 'other'::rpg.item_type, 'Serviço de Magia — 1º Círculo', '{"text":"50 PO"}'::jsonb, '—', 'Conjuração contratada (+ componentes caros).', '{"kind":"service","spellLevel":1}'::jsonb),
  ('servico-de-magia-2', 'other'::rpg.item_type, 'Serviço de Magia — 2º Círculo', '{"text":"200 PO"}'::jsonb, '—', 'Conjuração contratada (+ componentes caros).', '{"kind":"service","spellLevel":2}'::jsonb),
  ('servico-de-magia-3', 'other'::rpg.item_type, 'Serviço de Magia — 3º Círculo', '{"text":"300 PO"}'::jsonb, '—', 'Conjuração contratada (+ componentes caros).', '{"kind":"service","spellLevel":3}'::jsonb),
  ('servico-de-magia-4-5', 'other'::rpg.item_type, 'Serviço de Magia — 4º–5º Círculo', '{"text":"2.000 PO"}'::jsonb, '—', 'Conjuração contratada (+ componentes caros).', '{"kind":"service","spellLevel":"4-5"}'::jsonb),
  ('servico-de-magia-6-8', 'other'::rpg.item_type, 'Serviço de Magia — 6º–8º Círculo', '{"text":"20.000 PO"}'::jsonb, '—', 'Conjuração contratada (+ componentes caros).', '{"kind":"service","spellLevel":"6-8"}'::jsonb),
  ('servico-de-magia-9', 'other'::rpg.item_type, 'Serviço de Magia — 9º Círculo', '{"text":"100.000 PO"}'::jsonb, '—', 'Conjuração contratada (+ componentes caros).', '{"kind":"service","spellLevel":9}'::jsonb);
