-- Seed rpg.phb_background
-- Gerado automaticamente — não editar à mão

INSERT INTO rpg.phb_background (slug, name, description, feat_id, source_citation_id, equipment_gold_option, tool_proficiency_description, tool_proficiency_kind, tool_item_id, tool_category_id)
VALUES
  ('acolyte', 'Acólito', 'Você se dedicou ao serviço em um templo, localizado em uma aldeia ou em um bosque sagrado, onde realizava ritos em homenagem a um deus ou panteão. Sob a orientação de um sacerdote, você estudou religião e, graças à sua devoção, aprendeu a canalizar um pouco do poder divino para o seu local de culto e para as pessoas que ali oravam.', (SELECT id FROM rpg.phb_feat WHERE slug = 'magic-initiate'), (SELECT id FROM rpg.phb_source_citation WHERE slug = 'phb-2024-pt:ch4:177-185'), 50, 'Suprimentos de Calígrafo', 'fixed', (SELECT id FROM rpg.phb_item WHERE slug = 'suprimentos-de-caligrafo'), NULL),
  ('wanderer', 'Andarilho', 'Você cresceu nas ruas cercado por rejeitados igualmente malfadados, alguns deles amigos e outros rivais. Você dormia onde podia e fazia bicos por comida. Às vezes, quando a fome se tornava insuportável, você recorria ao furto. Ainda assim, você nunca perdeu seu orgulho e nunca abandonou a esperança. O destino ainda não terminou com você.', (SELECT id FROM rpg.phb_feat WHERE slug = 'lucky'), (SELECT id FROM rpg.phb_source_citation WHERE slug = 'phb-2024-pt:ch4:177-185'), 50, 'Ferramentas de Ladrão', 'fixed', (SELECT id FROM rpg.phb_item WHERE slug = 'ferramentas-de-ladrao'), NULL),
  ('artisan', 'Artesão', 'Você começou a limpar o chão e esfregar balcões na oficina de um artesão por alguns trocados por dia assim que ficou forte o suficiente para carregar um balde. Ao se tornar aprendiz, aprendeu a fabricar artesanatos básicos e a lidar com clientes exigentes, desenvolvendo também um olhar aguçado para detalhes.', (SELECT id FROM rpg.phb_feat WHERE slug = 'artisan'), (SELECT id FROM rpg.phb_source_citation WHERE slug = 'phb-2024-pt:ch4:177-185'), 50, 'Escolha um tipo de Ferramentas de Artesão (veja o capítulo 6)', 'choice', NULL, (SELECT id FROM rpg.phb_tool_category WHERE slug = 'artisan')),
  ('entertainer', 'Artista', 'Você passou a juventude em feiras e festivais itinerantes, fazendo bicos para músicos e acrobatas em troca de aulas. Aprendeu a andar na corda bamba, tocar alaúde de um jeito distinto e recitar poesia com dicção impecável. Até hoje, prospera com aplausos e anseia pelo palco.', (SELECT id FROM rpg.phb_feat WHERE slug = 'musician'), (SELECT id FROM rpg.phb_source_citation WHERE slug = 'phb-2024-pt:ch4:177-185'), 50, 'Escolha um tipo de Instrumento Musical (veja o capítulo 6)', 'choice', NULL, (SELECT id FROM rpg.phb_tool_category WHERE slug = 'instrument')),
  ('charlatan', 'Charlatão', 'Assim que você atingiu a idade para pedir uma cerveja, escolheu seu banquinho favorito em cada taverna a quinze quilômetros de onde nasceu. Ao percorrer o circuito de bares e botequins, aprendeu a lidar com os infelizes em busca de mentiras reconfortantes — talvez uma poção falsa ou registros de ancestralidade forjados.', (SELECT id FROM rpg.phb_feat WHERE slug = 'skilled'), (SELECT id FROM rpg.phb_source_citation WHERE slug = 'phb-2024-pt:ch4:177-185'), 50, 'Kit de Falsificação', 'fixed', (SELECT id FROM rpg.phb_item WHERE slug = 'kit-de-falsificacao'), NULL),
  ('criminal', 'Criminoso', 'Você sobrevivia em becos escuros, furtando pessoas ou assaltando lojas. Talvez fizesse parte de uma pequena gangue de criminosos que se protegiam mutuamente, ou fosse um lobo solitário, enfrentando a guilda dos ladrões locais e os criminosos mais temíveis.', (SELECT id FROM rpg.phb_feat WHERE slug = 'alert'), (SELECT id FROM rpg.phb_source_citation WHERE slug = 'phb-2024-pt:ch4:177-185'), 50, 'Ferramentas de Ladrão', 'fixed', (SELECT id FROM rpg.phb_item WHERE slug = 'ferramentas-de-ladrao'), NULL),
  ('hermit', 'Eremita', 'Você passou seus primeiros anos isolado em uma cabana ou mosteiro localizado bem além dos arredores do povoado mais próximo. Naqueles dias, seus únicos companheiros eram as criaturas da floresta e aqueles que ocasionalmente faziam uma visita para trazer suprimentos e notícias do mundo externo. A solidão permitia que você passasse muitas horas ponderando os mistérios da criação.', (SELECT id FROM rpg.phb_feat WHERE slug = 'healer'), (SELECT id FROM rpg.phb_source_citation WHERE slug = 'phb-2024-pt:ch4:177-185'), 50, 'Kit de Herbalismo', 'fixed', (SELECT id FROM rpg.phb_item WHERE slug = 'kit-de-herbalismo'), NULL),
  ('scribe', 'Escriba', 'Você passou anos de formação em um scriptorium, um mosteiro dedicado à preservação do conhecimento ou uma agência governamental, onde aprendeu a escrever com uma mão firme e produzir textos finamente escritos. Talvez você tenha escrito documentos governamentais ou copiado tomos de literatura. Você pode ter alguma habilidade como escritor de poesia, narrativa ou pesquisa acadêmica. Acima de tudo, você tem uma atenção cuidadosa aos detalhes, o que lhe ajuda a evitar a introdução de erros aos documentos que você copia e cria.', (SELECT id FROM rpg.phb_feat WHERE slug = 'skilled'), (SELECT id FROM rpg.phb_source_citation WHERE slug = 'phb-2024-pt:ch4:177-185'), 50, 'Suprimentos de Calígrafo', 'fixed', (SELECT id FROM rpg.phb_item WHERE slug = 'suprimentos-de-caligrafo'), NULL),
  ('farmer', 'Fazendeiro', 'Você cresceu perto da terra. Os anos cuidando de animais e cultivando a terra o recompensaram com paciência e boa saúde. Você tem um grande apreço pela generosidade da natureza, juntamente com um respeito saudável pela ira dela.', (SELECT id FROM rpg.phb_feat WHERE slug = 'tough'), (SELECT id FROM rpg.phb_source_citation WHERE slug = 'phb-2024-pt:ch4:177-185'), 50, 'Ferramentas de Carpinteiro', 'fixed', (SELECT id FROM rpg.phb_item WHERE slug = 'ferramentas-de-carpinteiro'), NULL),
  ('guard', 'Guarda', 'Seus pés doem quando você se lembra das incontáveis horas que passou em seu posto na torre. Você foi treinado para manter um olho atento para o que ocorria do lado fora da muralha, observando saqueadores vasculhando a floresta próxima, e seu outro olho voltado para dentro da muralha, procurando por assaltantes e encrenqueiros.', (SELECT id FROM rpg.phb_feat WHERE slug = 'alert'), (SELECT id FROM rpg.phb_source_citation WHERE slug = 'phb-2024-pt:ch4:177-185'), 50, 'Escolha um tipo de Kit de Jogos (veja o capítulo 6)', 'choice', NULL, (SELECT id FROM rpg.phb_tool_category WHERE slug = 'kit')),
  ('guide', 'Guia', 'Você cresceu ao ar livre, longe de terras povoadas. Sua casa ficava em qualquer lugar que você escolhesse para estender seu saco de dormir. Há maravilhas na natureza — monstros estranhos, florestas e riachos intocados, ruínas imensas de grandes salões outrora pisados por gigantes — e você aprendeu a se defender enquanto as explorava. De tempos em tempos, você guiava sacerdotes da natureza amigáveis que o instruíam nos fundamentos de canalizar a magia da natureza.', (SELECT id FROM rpg.phb_feat WHERE slug = 'magic-initiate'), (SELECT id FROM rpg.phb_source_citation WHERE slug = 'phb-2024-pt:ch4:177-185'), 50, 'Ferramentas de Cartógrafo', 'fixed', (SELECT id FROM rpg.phb_item WHERE slug = 'ferramentas-de-cartografo'), NULL),
  ('sailor', 'Marinheiro', 'Você viveu como um marinheiro, com o vento nas costas e os conveses balançando sob seus pés. Você já se sentou em bancos de bar em mais portos de escala do que consegue se lembrar, enfrentou grandes tempestades e trocou histórias com pessoas que vivem sob as ondas.', (SELECT id FROM rpg.phb_feat WHERE slug = 'tavern-brawler'), (SELECT id FROM rpg.phb_source_citation WHERE slug = 'phb-2024-pt:ch4:177-185'), 50, 'Ferramentas de Navegador', 'fixed', (SELECT id FROM rpg.phb_item WHERE slug = 'ferramentas-de-navegador'), NULL),
  ('merchant', 'Mercador', 'Você foi aprendiz de um comerciante, mestre de caravanas ou lojista, aprendendo os fundamentos do comércio. Com ele, viajou bastante e ganhou a vida comprando e vendendo as matérias-primas que os artesãos precisam para praticar seu ofício, ou trabalhos acabados de tais artesãos. Você pode ter transportado mercadorias de um lugar para outro (por navio, carroça ou caravana) ou comprado de comerciantes viajantes e vendido em sua própria loja.', (SELECT id FROM rpg.phb_feat WHERE slug = 'lucky'), (SELECT id FROM rpg.phb_source_citation WHERE slug = 'phb-2024-pt:ch4:177-185'), 50, 'Ferramentas de Navegador', 'fixed', (SELECT id FROM rpg.phb_item WHERE slug = 'ferramentas-de-navegador'), NULL),
  ('noble', 'Nobre', 'Você foi criado em um castelo, cercado por riqueza, poder e privilégio. Sua família de aristocratas menores garantiu que você recebesse uma educação de primeira categoria, com conteúdos que você apreciava e outros dos quais se ressentia. Seu tempo no castelo, especialmente as muitas horas que passou observando sua família na corte, também lhe ensinou muito sobre liderança.', (SELECT id FROM rpg.phb_feat WHERE slug = 'skilled'), (SELECT id FROM rpg.phb_source_citation WHERE slug = 'phb-2024-pt:ch4:177-185'), 50, 'Escolha um tipo de Kit de Jogos (veja o capítulo 6)', 'choice', NULL, (SELECT id FROM rpg.phb_tool_category WHERE slug = 'kit')),
  ('sage', 'Sábio', 'Você passou seus anos de formação viajando entre mansões e mosteiros, realizando vários bicos e serviços em troca de acesso às bibliotecas desses locais. Suas noites se resumiram a estudar livros e pergaminhos, aprendendo a sabedoria do multiverso — até mesmo os rudimentos da magia — e, agora, sua mente anseia por mais.', (SELECT id FROM rpg.phb_feat WHERE slug = 'magic-initiate'), (SELECT id FROM rpg.phb_source_citation WHERE slug = 'phb-2024-pt:ch4:177-185'), 50, 'Suprimentos de Calígrafo', 'fixed', (SELECT id FROM rpg.phb_item WHERE slug = 'suprimentos-de-caligrafo'), NULL),
  ('soldier', 'Soldado', 'Você começou a treinar para a guerra assim que atingiu a idade adulta e tem poucas lembranças preciosas da vida antes de pegar em armas. A batalha está em seu sangue. Às vezes, você se pega realizando reflexivamente os exercícios básicos de luta que aprendeu primeiro. Por fim, você coloca esse treinamento em prática no campo de batalha, protegendo o reino por meio da guerra.', (SELECT id FROM rpg.phb_feat WHERE slug = 'savage-attacker'), (SELECT id FROM rpg.phb_source_citation WHERE slug = 'phb-2024-pt:ch4:177-185'), 50, 'Escolha um tipo de Kit de Jogos (veja o capítulo 6)', 'choice', NULL, (SELECT id FROM rpg.phb_tool_category WHERE slug = 'kit'));
