-- Seed rpg.phb_subclass_prepared_spell
-- Gerado automaticamente — não editar à mão

INSERT INTO rpg.phb_subclass_prepared_spell (subclass_id, unlock_level, spell_id, terrain_id)
VALUES
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'archfey'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'acalmar-emocoes'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'archfey'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'fogo-das-fadas'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'archfey'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'forca-espectral'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'archfey'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'passo-nebuloso'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'archfey'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'sono'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'archfey'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'crescimento-de-plantas'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'archfey'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'piscar'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'archfey'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'dominar-fera'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'archfey'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'invisibilidade-maior'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'archfey'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'dominar-pessoa'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'archfey'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'similaridade'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'celestial'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'auxilio'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'celestial'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'chama-sagrada'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'celestial'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'curar-ferimentos'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'celestial'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'luz'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'celestial'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'raio-guia'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'celestial'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'restauracao-menor'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'celestial'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'luz-do-dia'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'celestial'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'revivificar'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'celestial'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'defensor-da-fe'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'celestial'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'muralha-de-fogo'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'celestial'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'convocar-celestial'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'celestial'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'restauracao-maior'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'great-old-one'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'detectar-pensamentos'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'great-old-one'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'forca-espectral'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'great-old-one'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'gargalhada-nefasta-de-tasha'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'great-old-one'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'sussurros-dissonantes'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'great-old-one'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'clarividencia'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'great-old-one'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'fome-de-hadar'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'great-old-one'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'confusao'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'great-old-one'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'invocar-aberracao'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'great-old-one'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'modificar-memoria'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'great-old-one'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'telecinese'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'fiend'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'comando'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'fiend'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'maos-flamejantes'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'fiend'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'raio-ardente'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'fiend'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'sugestao'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'fiend'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'bola-de-fogo'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'fiend'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'nuvem-fetida'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'fiend'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'escudo-ardente'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'fiend'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'muralha-de-fogo'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'fiend'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'missao'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'fiend'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'praga-de-insetos'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'life'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'auxilio'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'life'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'bencao'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'life'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'curar-ferimentos'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'life'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'restauracao-menor'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'life'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'palavra-curativa-em-massa'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'life'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'revivificar'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'life'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'aura-de-vida'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'life'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'protecao-contra-a-morte'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'life'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'curar-ferimentos-em-massa'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'life'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'restauracao-maior'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'light'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'fogo-das-fadas'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'light'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'maos-flamejantes'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'light'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'raio-ardente'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'light'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'ver-o-invisivel'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'light'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'bola-de-fogo'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'light'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'luz-do-dia'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'light'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'muralha-de-fogo'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'light'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'olho-arcano'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'light'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'coluna-de-chamas'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'light'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'videncia'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'trickery'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'disfarcar-se'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'trickery'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'enfeiticar-pessoa'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'trickery'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'invisibilidade'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'trickery'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'passo-sem-rastro'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'trickery'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'indetectavel'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'trickery'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'padrao-hipnotico'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'trickery'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'confusao'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'trickery'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'porta-dimensional'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'trickery'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'dominar-pessoa'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'trickery'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'modificar-memoria'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'war'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'arma-espiritual'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'war'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'arma-magica'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'war'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'escudo-da-fe'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'war'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'raio-guia'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'war'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'guardioes-espirituais'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'war'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'manto-do-cruzado'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'war'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'escudo-ardente'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'war'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'movimentacao-livre'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'war'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'golpe-de-arco'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'war'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'paralisar-monstro'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'maos-flamejantes'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'arid')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'turvar'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'arid')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'raio-de-fogo'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'arid')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'bola-de-fogo'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'arid')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'muralha-de-fogo'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'arid')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'malogro'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'arid')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'muralha-de-pedra'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'arid')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'coluna-de-chamas'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'arid')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'videncia'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'arid')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'nevoa-obscurecente'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'polar')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'paralisar-pessoa'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'polar')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'raio-de-gelo'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'polar')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'nevasca'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'polar')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'lentidao'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'polar')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'cone-de-frio'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'polar')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'tempestade-glacial'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'polar')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'comunhao-com-a-natureza'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'polar')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'passo-arboreo'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'polar')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'passo-nebuloso'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'temperate')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'toque-chocante'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'temperate')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'sono'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'temperate')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'relampago'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'temperate')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'crescimento-de-plantas'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'temperate')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'movimentacao-livre'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'temperate')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'moldar-rochas'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'temperate')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'comunhao-com-a-natureza'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'temperate')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'muralha-de-pedra'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'temperate')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'bolha-acida'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'tropical')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'rajada-de-veneno'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'tropical')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'teia'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'tropical')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'nuvem-fetida'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'tropical')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'polimorfia'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'tropical')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'praga-de-insetos'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'tropical')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'muralha-de-espinhos'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'tropical')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'nevoa-mortal'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'tropical')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'land'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'passo-arboreo'), (SELECT id FROM rpg.phb_druid_land_terrain WHERE slug = 'tropical')),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'moon'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'curar-ferimentos'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'moon'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'fagulha-estelar'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'moon'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'raio-lunar'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'moon'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'invocar-animais'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'moon'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'fonte-do-luar'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'moon'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'curar-ferimentos-em-massa'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'sea'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'despedacar'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'sea'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'lufada-de-vento'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'sea'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'nevoa-obscurecente'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'sea'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'onda-trovejante'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'sea'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'raio-de-gelo'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'sea'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'relampago'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'sea'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'respirar-na-agua'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'sea'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'controlar-agua'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'sea'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'tempestade-glacial'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'sea'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'invocar-elemental'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'sea'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'paralisar-monstro'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'aberrant'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'acalmar-emocoes'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'aberrant'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'bracos-de-hadar'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'aberrant'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'detectar-pensamentos'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'aberrant'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'sussurros-dissonantes'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'aberrant'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'talho-mental'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'aberrant'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'fome-de-hadar'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'aberrant'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'remeter'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'aberrant'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'invocar-aberracao'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'aberrant'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'tentaculos-negros-de-evard'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'aberrant'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'ligacao-telepatica-de-rary'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'aberrant'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'telecinese'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'draconic'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'alterar-se'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'draconic'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'comando'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'draconic'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'orbe-cromatico'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'draconic'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'sopro-de-dragao'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'draconic'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'medo'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'draconic'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'voo'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'draconic'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'enfeiticar-monstro'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'draconic'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'olho-arcano'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'draconic'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'invocar-dragao'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'draconic'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'lendas-e-historias'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'clockwork'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'alarme'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'clockwork'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'auxilio'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'clockwork'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'protecao-contra-o-bem-e-o-mal'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'clockwork'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'restauracao-menor'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'clockwork'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'dissipar-magia'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'clockwork'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'protecao-contra-energia'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'clockwork'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'invocar-constructo'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'clockwork'), 7, (SELECT id FROM rpg.phb_spell WHERE slug = 'movimentacao-livre'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'clockwork'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'muralha-de-energia'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'clockwork'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'restauracao-maior'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'fey-wanderer'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'enfeiticar-pessoa'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'fey-wanderer'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'passo-nebuloso'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'fey-wanderer'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'convocar-feerico'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'fey-wanderer'), 13, (SELECT id FROM rpg.phb_spell WHERE slug = 'porta-dimensional'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'fey-wanderer'), 17, (SELECT id FROM rpg.phb_spell WHERE slug = 'despistar'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'gloom-stalker'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'disfarcar-se'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'gloom-stalker'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'corda-extradimensional'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'gloom-stalker'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'medo'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'gloom-stalker'), 13, (SELECT id FROM rpg.phb_spell WHERE slug = 'invisibilidade-maior'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'gloom-stalker'), 17, (SELECT id FROM rpg.phb_spell WHERE slug = 'similaridade'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'ancients'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'falar-com-animais'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'ancients'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'golpe-constritor'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'ancients'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'passo-nebuloso'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'ancients'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'raio-lunar'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'ancients'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'crescimento-de-plantas'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'ancients'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'protecao-contra-energia'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'ancients'), 13, (SELECT id FROM rpg.phb_spell WHERE slug = 'pele-rocha'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'ancients'), 13, (SELECT id FROM rpg.phb_spell WHERE slug = 'tempestade-glacial'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'ancients'), 17, (SELECT id FROM rpg.phb_spell WHERE slug = 'comunhao-com-a-natureza'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'ancients'), 17, (SELECT id FROM rpg.phb_spell WHERE slug = 'passo-arboreo'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'devotion'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'escudo-da-fe'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'devotion'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'protecao-contra-o-bem-e-o-mal'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'devotion'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'auxilio'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'devotion'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'zona-da-verdade'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'devotion'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'dissipar-magia'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'devotion'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'sinal-de-esperanca'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'devotion'), 13, (SELECT id FROM rpg.phb_spell WHERE slug = 'defensor-da-fe'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'devotion'), 13, (SELECT id FROM rpg.phb_spell WHERE slug = 'movimentacao-livre'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'devotion'), 17, (SELECT id FROM rpg.phb_spell WHERE slug = 'coluna-de-chamas'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'devotion'), 17, (SELECT id FROM rpg.phb_spell WHERE slug = 'comunhao'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'glory'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'heroismo'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'glory'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'raio-guia'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'glory'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'aprimorar-atributo'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'glory'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'arma-magica'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'glory'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'celeridade'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'glory'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'protecao-contra-energia'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'glory'), 13, (SELECT id FROM rpg.phb_spell WHERE slug = 'compulsao'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'glory'), 13, (SELECT id FROM rpg.phb_spell WHERE slug = 'movimentacao-livre'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'glory'), 17, (SELECT id FROM rpg.phb_spell WHERE slug = 'lendas-e-historias'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'glory'), 17, (SELECT id FROM rpg.phb_spell WHERE slug = 'presenca-regia-de-yolande'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'vengeance'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'marca-do-predador'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'vengeance'), 3, (SELECT id FROM rpg.phb_spell WHERE slug = 'perdicao'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'vengeance'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'paralisar-pessoa'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'vengeance'), 5, (SELECT id FROM rpg.phb_spell WHERE slug = 'passo-nebuloso'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'vengeance'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'celeridade'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'vengeance'), 9, (SELECT id FROM rpg.phb_spell WHERE slug = 'protecao-contra-energia'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'vengeance'), 13, (SELECT id FROM rpg.phb_spell WHERE slug = 'banimento'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'vengeance'), 13, (SELECT id FROM rpg.phb_spell WHERE slug = 'porta-dimensional'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'vengeance'), 17, (SELECT id FROM rpg.phb_spell WHERE slug = 'paralisar-monstro'), NULL),
  ((SELECT id FROM rpg.phb_subclass WHERE slug = 'vengeance'), 17, (SELECT id FROM rpg.phb_spell WHERE slug = 'videncia'), NULL)
ON CONFLICT ON CONSTRAINT uq_subclass_prepared_spell DO NOTHING;
