-- Seed rpg.phb_background_ability_option
-- Gerado automaticamente — não editar à mão

INSERT INTO rpg.phb_background_ability_option (background_id, ability_id, sort_order)
VALUES
  ((SELECT id FROM rpg.phb_background WHERE slug = 'acolyte'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 1),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'acolyte'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 2),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'acolyte'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'wanderer'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 1),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'wanderer'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 2),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'wanderer'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'artisan'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'artisan'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 2),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'artisan'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 3),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'entertainer'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'entertainer'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 2),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'entertainer'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'charlatan'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 1),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'charlatan'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 2),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'charlatan'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'criminal'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 1),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'criminal'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 2),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'criminal'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 3),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'hermit'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 1),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'hermit'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 2),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'hermit'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'scribe'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 1),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'scribe'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 2),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'scribe'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 3),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'farmer'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'farmer'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 2),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'farmer'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 3),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'guard'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'guard'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 2),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'guard'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 3),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'guide'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 1),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'guide'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 2),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'guide'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 3),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'sailor'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'sailor'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 2),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'sailor'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 3),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'merchant'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 1),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'merchant'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 2),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'merchant'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'noble'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'noble'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 2),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'noble'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'sage'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 1),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'sage'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 2),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'sage'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 3),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'soldier'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'soldier'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 2),
  ((SELECT id FROM rpg.phb_background WHERE slug = 'soldier'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 3);
