-- Seed rpg.phb_species_trait
-- Gerado automaticamente — não editar à mão

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'aasimar'), 'Resistência Celestial', 'Você tem Resistência a dano Necrótico e Radiante.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'aasimar'), 'Visão no Escuro', 'Você tem Visão no Escuro com um alcance de 18 metros.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'aasimar'), 'Mãos Curativas', 'Você executa uma ação Usar Magia, toca uma criatura e joga um número de d4s igual ao seu Bônus de Proficiência. A criatura restaura número de Pontos de Vida igual ao total jogado. Após usar esse traço, você não pode usá-lo novamente até completar um Descanso Longo.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'aasimar'), 'Portador da Luz', 'Você conhece o truque Luz. Carisma é seu atributo de conjuração para isso.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'aasimar'), 'Revelação Celestial', 'No nível 3 de personagem, você pode se transformar como uma Ação Bônus usando uma das opções abaixo (escolha a opção cada vez que você se transformar). A transformação se mantém por 1 minuto ou até você a encerrar (nenhuma ação é necessária). Uma vez que você se transforma, não pode fazê-lo novamente até completar um Descanso Longo. Uma vez em cada um dos seus turnos, até que a transformação termine, você pode infligir dano adicional a um alvo ao causar dano a ele com um ataque ou uma magia. O dano adicional é igual ao seu Bônus de Proficiência, e o tipo de dano adicional é Necrótico para Manto Necrótico ou Radiante para Asas Celestiais e Transfiguração Radiante. Aqui estão as opções de transformação: Asas Celestiais. Duas asas espectrais brotam em suas costas temporariamente. Até que a transformação se encerre, você tem um Deslocamento de Voo igual ao seu Deslocamento. Manto Necrótico. Seus olhos se tornam brevemente poças de escuridão, e asas que não voam brotam em suas costas temporariamente. Criaturas que não sejam seus aliados a até 3 metros de você devem ser bem-sucedidas em uma salvaguarda de Carisma (CD 8 + seu modificador de Carisma e seu Bônus de Proficiência) ou têm a condição Amedrontado até o final do seu próximo turno. Transfiguração Radiante. Luz abrasadora irradia temporariamente de seus olhos e boca. Pela duração da transformação, você emite Luz Plena em um raio de 3 metros e Meia-luz por mais 3 metros, e no fim de cada um de seus turnos, cada criatura a até 3 metros de você sofre dano Radiante igual ao seu Bônus de Proficiência.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'dwarf'), 'Visão no Escuro', 'Você tem Visão no Escuro com um alcance de 36 metros.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'dwarf'), 'Resistência a Toxinas', 'Você tem Resistência a Dano Venenoso. Você também tem Vantagem nas salvaguardas que realizar para evitar ou encerrar a condição Envenenado.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'dwarf'), 'Tenacidade Anã', 'Seus Pontos de Vida máximos aumentam em 1, e novamente em 1, sempre que você atinge um nível de personagem.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'dwarf'), 'Conhecimento de Pedras', 'Como uma Ação Bônus, você adquire Sismiconsciência com um alcance de 18 metros por 10 minutos. Você deve estar em, ou tocar, uma superfície de pedra para usar a Sismiconsciência. A pedra pode ser natural ou trabalhada. Você pode usar essa Ação Bônus um número de vezes igual ao seu Bônus de Proficiência, e você restaura todos os usos gastos quando completa um Descanso Longo.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'dragonborn'), 'Herança Dracônica', 'Sua linhagem deriva de um progenitor dracônico. Escolha o tipo de dragão da tabela Herança Dracônica. Sua escolha afeta suas características de Ataque de Sopro e Resistência a Dano, bem como sua aparência.', 'dragon_ancestry'::rpg.species_choice_kind) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'dragonborn'), 'Ataque de Sopro', 'Ao executar a ação Atacar no seu turno, você pode substituir um de seus ataques por uma emissão de energia mágica em um Cone de 4,5 metros ou em uma Linha de 9 metros de comprimento e 1,5 metros de largura (escolha a forma a cada vez). Cada criatura nessa área deve realizar uma salvaguarda de Destreza (CD 8 + seu modificador de Constituição e seu Bônus de Proficiência). Se falhar, uma criatura sofre 1d10 pontos de dano do tipo determinado por seu traço Herança Dracônica. Em caso de sucesso, uma criatura sofre metade do dano. Esse dano aumenta em 1d10 quando você atinge os níveis de personagem 5 (2d10), 11 (3d10) e 17 (4d10). Você pode usar esse Ataque de Sopro um número de vezes igual ao seu Bônus de Proficiência, e você restaura todos os usos gastos quando completa um Descanso Longo.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'dragonborn'), 'Resistência a Dano', 'Você tem Resistência ao tipo de dano determinado por seu traço Herança Dracônica.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'dragonborn'), 'Visão no Escuro', 'Você tem Visão no Escuro com um alcance de 18 metros.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'dragonborn'), 'Voo Dracônico', 'No nível 5 do personagem, você pode canalizar magia dracônica para beneficiar de um voo temporário. Como uma Ação Bônus, você cria asas espectrais nas costas que duram 10 minutos ou até que você as retraia (nenhuma ação é necessária) ou tem a condição Incapacitado. Pela duração, você tem um Deslocamento de Voo igual ao seu Deslocamento. Suas asas parecem feitas da mesma energia que o seu Ataque de Sopro. Após usar esse traço, você não pode usá-lo novamente até completar um Descanso Longo.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'elf'), 'Visão no Escuro', 'Você tem Visão no Escuro com um alcance de 18 metros.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'elf'), 'Linhagem Élfica', 'Você é de uma linhagem que lhe concede habilidades sobrenaturais. Escolha uma linhagem da tabela Linhagem Élfica. Você adquire o benefício de nível 1 dessa linhagem. Ao atingir os níveis 3 e 5, você aprende uma magia de círculo superior, conforme indicado na tabela. Essa magia está sempre preparada e pode ser conjurada uma vez sem usar um espaço de magia, restaurando essa capacidade ao completar um Descanso Longo. Além disso, você pode conjurá-la usando qualquer espaço de magia apropriado que possua. Inteligência, Sabedoria ou Carisma é seu atributo de conjuração para as magias que você conjura com este traço (escolha o atributo quando selecionar a linhagem).', 'elf_lineage'::rpg.species_choice_kind) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'elf'), 'Ancestralidade Feérica', 'Você tem Vantagem ao realizar salvaguardas para evitar ou encerrar a condição Enfeitiçado.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'elf'), 'Sentidos Aguçados', 'Você tem proficiência na perícia Intuição, Percepção ou Sobrevivência.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'elf'), 'Transe', 'Você pode completar um Descanso Longo em 4 horas ao meditar, sem a necessidade de dormir, mantendo a consciência, e magia não pode forçá-lo a dormir.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'gnome'), 'Visão no Escuro', 'Você tem Visão no Escuro com um alcance de 18 metros.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'gnome'), 'Astúcia de Gnomo', 'Você tem Vantagem em salvaguardas de Inteligência, Sabedoria e Carisma.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'gnome'), 'Linhagem Gnômica', 'Você pertence a uma linhagem que lhe confere habilidades sobrenaturais. Escolha uma das seguintes opções; sua escolha determina se Inteligência, Sabedoria ou Carisma é seu atributo de conjuração para as magias desse traço (escolha o atributo quando selecionar a linhagem): Gnomo das Rochas. Você conhece os truques Prestidigitação Arcana e Reparar. Além disso, você pode gastar 10 minutos conjurando Prestidigitação Arcana para fabricar um dispositivo mecânico minúsculo (CA 5, 1 PV), como um brinquedo, isqueiro mecânico ou caixa de música. Ao fabricar o dispositivo, você determina a função dele escolhendo um efeito de Prestidigitação Arcana; o dispositivo produz esse efeito sempre que você ou outra criatura executa uma Ação Bônus para ativá-lo com um toque. Se o efeito escolhido tiver opções possíveis, você escolhe uma dessas opções para o dispositivo ao fabricá-lo. Por exemplo, se você escolher o efeito de Brincar com Fogo da magia, você determina se o dispositivo acende ou extingue fogo; o dispositivo não faz ambas as coisas. Você pode ter três desses dispositivos ao mesmo tempo, e cada um se desfaz 8 horas após ser fabricado ou quando você o desmonta com um toque como uma ação Usar Objeto. Gnomo do Bosque. Você conhece o truque Ilusão Menor. Você também sempre tem a magia Falar com Animais preparada. É possível conjurá-la sem um espaço de magia um número de vezes igual ao seu Bônus de Proficiência, e você restaura todos os usos gastos quando completa um Descanso Longo. Você também pode usar qualquer espaço de magia que tiver para conjurá-la.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'goliath'), 'Ancestralidade Gigante', 'Você é descendente de Gigantes. Escolha um dos seguintes benefícios — um benefício sobrenatural de sua ancestralidade; você pode usar o benefício escolhido um número de vezes igual ao seu Bônus de Proficiência, e você restaura todos os usos gastos quando completa um Descanso Longo: Arrepio do Gelo (Gigante do Gelo). Ao atingir um alvo com uma jogada de ataque e causar dano a ele, você também pode infligir 1d6 pontos de dano Gélido a esse alvo e reduzir o Deslocamento dele em 3 metros até o início do seu próximo turno. Queimadura de Fogo (Gigante de Fogo). Ao atingir um alvo com uma jogada de ataque e causar dano a ele, você também pode causar 1d10 pontos de dano Ígneo a esse alvo. Resistência da Pedra (Gigante da Pedra). Ao sofrer dano, pode executar uma Reação para jogar 1d12. Adicione seu modificador de Constituição ao número obtido e reduza o dano desse total. Salto da Nuvem (Gigante das Nuvens). Como uma Ação Bônus, você se teleporta magicamente até 9 metros para um espaço desocupado à sua vista. Tombo da Colina (Gigante da Colina). Ao atingir uma criatura Grande ou menor com uma jogada de ataque e causar dano a ela, você pode impor a esse alvo a condição Caído. Trovão da Tempestade (Gigante da Tempestade). Ao sofrer dano de uma criatura a até 18 metros de você, você pode executar uma Reação para causar 1d8 pontos de dano Trovejante a essa criatura.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'goliath'), 'Forma Grande', 'A partir do nível 5 de personagem, você pode alterar seu tamanho para Grande como uma Ação Bônus se estiver em um espaço grande o suficiente. Essa transformação se mantém por 10 minutos ou até que você a encerrar (nenhuma ação é necessária). Pela duração, você tem Vantagem em testes de Força, e seu Deslocamento aumenta em 3 metros. Após usar este traço, você não pode utilizá-lo novamente até completar um Descanso Longo.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'goliath'), 'Porte Poderoso', 'Você tem Vantagem em qualquer teste de atributo que realizar para encerrar a condição Imobilizado. Você também conta como um tamanho maior ao determinar sua capacidade de carga.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'human'), 'Eficiente', 'Você adquire Inspiração Heroica sempre que completar um Descanso Longo.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'human'), 'Hábil', 'Você adquire proficiência em uma perícia à sua escolha.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'human'), 'Versátil', 'Você adquire um talento de Origem à sua escolha (veja o capítulo 5). Habilidoso é recomendado.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'orc'), 'Pico de Adrenalina', 'Você pode executar a ação Correr como uma Ação Bônus. Ao executar isso, você adquire um número de Pontos de Vida Temporários igual ao seu Bônus de Proficiência. Você pode usar este traço um número de vezes igual ao seu Bônus de Proficiência, e você restaura todos os usos gastos quando completa um Descanso Curto ou Longo.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'orc'), 'Visão no Escuro', 'Você tem Visão no Escuro com um alcance de 36 metros.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'orc'), 'Vigor Implacável', 'Ao ser reduzido a 0 Pontos de Vida, mas não morto imediatamente, você fica com 1 Ponto de Vida. Após usar este traço, você não pode fazê-lo novamente até completar um Descanso Longo.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'halfling'), 'Corajoso', 'Você tem Vantagem nas salvaguardas que realizar para evitar ou encerrar a condição Amedrontado.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'halfling'), 'Agilidade Pequenina', 'Você pode se mover pelo espaço de qualquer criatura que seja um tamanho maior que você, mas você não pode parar no mesmo espaço.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'halfling'), 'Sorte', 'Ao tirar 1 no D20 de um Teste de D20, você pode jogar novamente o dado e deve usar a nova jogada.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'halfling'), 'Furtividade Natural', 'Você pode executar a ação Esconder mesmo quando estiver encoberto apenas por uma criatura que seja pelo menos um tamanho maior que você.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'tiefling'), 'Visão no Escuro', 'Você tem Visão no Escuro com um alcance de 18 metros.', NULL) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'tiefling'), 'Legado Ínfero', 'Você é o portador de um legado que lhe confere poderes sobrenaturais. Escolha um legado da tabela Legados Ínferos. Você adquire o benefício de nível 1 do legado escolhido. Ao atingir os níveis de personagem 3 e 5, você aprende magias de círculo superior, conforme indicado na tabela. Essas magias estão sempre preparadas e podem ser conjuradas uma vez sem usar um espaço de magia, sendo restauradas quando completa um Descanso Longo. Além disso, você pode conjurá-las utilizando qualquer espaço de magia que possua do círculo correspondente. Atributos como Inteligência, Sabedoria ou Carisma servem como seu atributo de conjuração para essas magias (escolha um atributo ao selecionar o legado).', 'infernal_legacy'::rpg.species_choice_kind) ON CONFLICT (species_id, name) DO NOTHING;

INSERT INTO rpg.phb_species_trait (species_id, name, description, choice_kind) VALUES ((SELECT id FROM rpg.phb_species WHERE slug = 'tiefling'), 'Presença Sobrenatural', 'Você conhece o truque Taumaturgia. Ao conjurar com este traço, a magia usa o mesmo atributo de conjuração que você usa para sua Característica Legado Ínfero.', NULL) ON CONFLICT (species_id, name) DO NOTHING;
