-- Seed rpg.phb_item
-- Gerado automaticamente — não editar à mão

INSERT INTO rpg.phb_item (slug, item_type, name, cost, weight, description, properties)
VALUES
  ('dagger', 'weapon'::rpg.item_type, 'Adaga', '{"text":"2 PO"}'::jsonb, '0,5 kg', NULL, '{"propertyIds":["finesse","thrown","light"],"masteryId":"nick","range":{"normal":6,"max":18}}'::jsonb),
  ('javelin', 'weapon'::rpg.item_type, 'Azagaia', '{"text":"5 PP"}'::jsonb, '1 kg', NULL, '{"propertyIds":["thrown"],"masteryId":"slow","range":{"normal":9,"max":36}}'::jsonb),
  ('quarterstaff', 'weapon'::rpg.item_type, 'Cajado', '{"text":"2 PP"}'::jsonb, '2 kg', NULL, '{"propertyIds":["versatile"],"masteryId":"topple"}'::jsonb),
  ('club', 'weapon'::rpg.item_type, 'Clava', '{"text":"1 PP"}'::jsonb, '1 kg', NULL, '{"propertyIds":["light"],"masteryId":"slow"}'::jsonb),
  ('greatclub', 'weapon'::rpg.item_type, 'Clava Grande', '{"text":"2 PP"}'::jsonb, '5 kg', NULL, '{"propertyIds":["two-handed"],"masteryId":"push"}'::jsonb),
  ('sickle', 'weapon'::rpg.item_type, 'Foice', '{"text":"1 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":["light"],"masteryId":"nick"}'::jsonb),
  ('spear', 'weapon'::rpg.item_type, 'Lança', '{"text":"1 PO"}'::jsonb, '1,5 kg', NULL, '{"propertyIds":["thrown","versatile"],"masteryId":"sap","range":{"normal":6,"max":18}}'::jsonb),
  ('mace', 'weapon'::rpg.item_type, 'Maça', '{"text":"5 PO"}'::jsonb, '2 kg', NULL, '{"propertyIds":[],"masteryId":"sap"}'::jsonb),
  ('handaxe', 'weapon'::rpg.item_type, 'Machadinha', '{"text":"5 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":["thrown","light"],"masteryId":"vex","range":{"normal":6,"max":18}}'::jsonb),
  ('light-hammer', 'weapon'::rpg.item_type, 'Martelo Leve', '{"text":"2 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":["thrown","light"],"masteryId":"nick","range":{"normal":6,"max":18}}'::jsonb),
  ('shortbow', 'weapon'::rpg.item_type, 'Arco Curto', '{"text":"25 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":["two-handed","ammunition"],"masteryId":"vex","range":{"normal":24,"max":96}}'::jsonb),
  ('light-crossbow', 'weapon'::rpg.item_type, 'Besta Leve', '{"text":"25 PO"}'::jsonb, '2,5 kg', NULL, '{"propertyIds":["two-handed","ammunition","loading"],"masteryId":"slow","range":{"normal":24,"max":96}}'::jsonb),
  ('dart', 'weapon'::rpg.item_type, 'Dardo', '{"text":"5 PC"}'::jsonb, '150 g', NULL, '{"propertyIds":["finesse","thrown"],"masteryId":"vex","range":{"normal":6,"max":18}}'::jsonb),
  ('sling', 'weapon'::rpg.item_type, 'Funda', '{"text":"1 PP"}'::jsonb, '—', NULL, '{"propertyIds":["ammunition"],"masteryId":"slow","range":{"normal":9,"max":36}}'::jsonb),
  ('halberd', 'weapon'::rpg.item_type, 'Alabarda', '{"text":"20 PO"}'::jsonb, '3 kg', NULL, '{"propertyIds":["two-handed","reach","heavy"],"masteryId":"cleave"}'::jsonb),
  ('whip', 'weapon'::rpg.item_type, 'Chicote', '{"text":"2 PO"}'::jsonb, '1,5 kg', NULL, '{"propertyIds":["finesse","reach"],"masteryId":"slow"}'::jsonb),
  ('scimitar', 'weapon'::rpg.item_type, 'Cimitarra', '{"text":"25 PO"}'::jsonb, '1,5 kg', NULL, '{"propertyIds":["finesse","light"],"masteryId":"nick"}'::jsonb),
  ('shortsword', 'weapon'::rpg.item_type, 'Espada Curta', '{"text":"10 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":["finesse","light"],"masteryId":"vex"}'::jsonb),
  ('greatsword', 'weapon'::rpg.item_type, 'Espada Grande', '{"text":"50 PO"}'::jsonb, '3 kg', NULL, '{"propertyIds":["two-handed","heavy"],"masteryId":"graze"}'::jsonb),
  ('longsword', 'weapon'::rpg.item_type, 'Espada Longa', '{"text":"15 PO"}'::jsonb, '1,5 kg', NULL, '{"propertyIds":["versatile"],"masteryId":"sap"}'::jsonb),
  ('glaive', 'weapon'::rpg.item_type, 'Glaive', '{"text":"20 PO"}'::jsonb, '3 kg', NULL, '{"propertyIds":["two-handed","reach","heavy"],"masteryId":"graze"}'::jsonb),
  ('lance', 'weapon'::rpg.item_type, 'Lança de Montaria', '{"text":"10 PO"}'::jsonb, '3 kg', NULL, '{"propertyIds":["two-handed","reach","heavy"],"masteryId":"topple"}'::jsonb),
  ('pike', 'weapon'::rpg.item_type, 'Lança Longa', '{"text":"5 PO"}'::jsonb, '9 kg', NULL, '{"propertyIds":["two-handed","reach","heavy"],"masteryId":"push"}'::jsonb),
  ('morningstar', 'weapon'::rpg.item_type, 'Maça Estrela', '{"text":"15 PO"}'::jsonb, '2 kg', NULL, '{"propertyIds":[],"masteryId":"sap"}'::jsonb),
  ('battleaxe', 'weapon'::rpg.item_type, 'Machado de Batalha', '{"text":"10 PO"}'::jsonb, '2,5 kg', NULL, '{"propertyIds":["versatile"],"masteryId":"topple"}'::jsonb),
  ('greataxe', 'weapon'::rpg.item_type, 'Machado Grande', '{"text":"30 PO"}'::jsonb, '3,5 kg', NULL, '{"propertyIds":["two-handed","heavy"],"masteryId":"cleave"}'::jsonb),
  ('maul', 'weapon'::rpg.item_type, 'Malho', '{"text":"10 PO"}'::jsonb, '5 kg', NULL, '{"propertyIds":["two-handed","heavy"],"masteryId":"topple"}'::jsonb),
  ('flail', 'weapon'::rpg.item_type, 'Mangual', '{"text":"10 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":[],"masteryId":"sap"}'::jsonb),
  ('warhammer', 'weapon'::rpg.item_type, 'Martelo de Guerra', '{"text":"15 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":["versatile"],"masteryId":"push"}'::jsonb),
  ('war-pick', 'weapon'::rpg.item_type, 'Picareta de Guerra', '{"text":"5 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":["versatile"],"masteryId":"sap"}'::jsonb),
  ('rapier', 'weapon'::rpg.item_type, 'Rapieira', '{"text":"25 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":["finesse"],"masteryId":"vex"}'::jsonb),
  ('trident', 'weapon'::rpg.item_type, 'Tridente', '{"text":"5 PO"}'::jsonb, '2 kg', NULL, '{"propertyIds":["thrown","versatile"],"masteryId":"topple","range":{"normal":6,"max":18}}'::jsonb),
  ('longbow', 'weapon'::rpg.item_type, 'Arco Longo', '{"text":"50 PO"}'::jsonb, '1 kg', NULL, '{"propertyIds":["two-handed","ammunition","heavy"],"masteryId":"slow","range":{"normal":45,"max":180}}'::jsonb),
  ('hand-crossbow', 'weapon'::rpg.item_type, 'Besta de Mão', '{"text":"75 PO"}'::jsonb, '1,5 kg', NULL, '{"propertyIds":["light","ammunition","loading"],"masteryId":"vex","range":{"normal":9,"max":36}}'::jsonb),
  ('heavy-crossbow', 'weapon'::rpg.item_type, 'Besta Pesada', '{"text":"50 PO"}'::jsonb, '9 kg', NULL, '{"propertyIds":["two-handed","ammunition","heavy","loading"],"masteryId":"push","range":{"normal":30,"max":120}}'::jsonb),
  ('musket', 'weapon'::rpg.item_type, 'Mosquete', '{"text":"500 PO"}'::jsonb, '5 kg', NULL, '{"propertyIds":["two-handed","ammunition","loading"],"masteryId":"slow","range":{"normal":12,"max":36}}'::jsonb),
  ('pistol', 'weapon'::rpg.item_type, 'Pistola', '{"text":"250 PO"}'::jsonb, '1,5 kg', NULL, '{"propertyIds":["ammunition","loading"],"masteryId":"vex","range":{"normal":9,"max":27}}'::jsonb),
  ('blowgun', 'weapon'::rpg.item_type, 'Zarabatana', '{"text":"10 PO"}'::jsonb, '0,5 kg', NULL, '{"propertyIds":["ammunition","loading"],"masteryId":"vex"}'::jsonb),
  ('padded', 'armor'::rpg.item_type, 'Acolchoada', '{"text":"5 PO"}'::jsonb, '4 kg', NULL, '{"acFormula":{"type":"dex-plus-base","base":11},"propertyIds":["stealth-disadvantage"]}'::jsonb),
  ('leather', 'armor'::rpg.item_type, 'Couro', '{"text":"10 PO"}'::jsonb, '5 kg', NULL, '{"acFormula":{"type":"dex-plus-base","base":11},"propertyIds":[]}'::jsonb),
  ('studded-leather', 'armor'::rpg.item_type, 'Couro Batido', '{"text":"45 PO"}'::jsonb, '6,5 kg', NULL, '{"acFormula":{"type":"dex-plus-base","base":12},"propertyIds":[]}'::jsonb),
  ('hide', 'armor'::rpg.item_type, 'Gibão de Peles', '{"text":"10 PO"}'::jsonb, '6 kg', NULL, '{"acFormula":{"type":"dex-plus-base","base":12,"dexMax":2},"propertyIds":[]}'::jsonb),
  ('chain-shirt', 'armor'::rpg.item_type, 'Cota de Malha Parcial', '{"text":"50 PO"}'::jsonb, '10 kg', NULL, '{"acFormula":{"type":"dex-plus-base","base":13,"dexMax":2},"propertyIds":[]}'::jsonb),
  ('scale-mail', 'armor'::rpg.item_type, 'Loriga de Escamas', '{"text":"50 PO"}'::jsonb, '22 kg', NULL, '{"acFormula":{"type":"dex-plus-base","base":14,"dexMax":2},"propertyIds":["stealth-disadvantage"]}'::jsonb),
  ('breastplate', 'armor'::rpg.item_type, 'Couraça Peitoral', '{"text":"400 PO"}'::jsonb, '10 kg', NULL, '{"acFormula":{"type":"dex-plus-base","base":14,"dexMax":2},"propertyIds":[]}'::jsonb),
  ('half-plate', 'armor'::rpg.item_type, 'Placas Parcial', '{"text":"750 PO"}'::jsonb, '20 kg', NULL, '{"acFormula":{"type":"dex-plus-base","base":15,"dexMax":2},"propertyIds":["stealth-disadvantage"]}'::jsonb),
  ('ring-mail', 'armor'::rpg.item_type, 'Cota de Anéis', '{"text":"30 PO"}'::jsonb, '20 kg', NULL, '{"acFormula":{"type":"fixed","base":14},"propertyIds":["stealth-disadvantage"]}'::jsonb),
  ('chain-mail', 'armor'::rpg.item_type, 'Cota de Malha', '{"text":"75 PO"}'::jsonb, '27 kg', NULL, '{"acFormula":{"type":"fixed","base":16},"propertyIds":["stealth-disadvantage","strength-requirement"]}'::jsonb),
  ('splint', 'armor'::rpg.item_type, 'Armadura de Talas', '{"text":"200 PO"}'::jsonb, '30 kg', NULL, '{"acFormula":{"type":"fixed","base":17},"propertyIds":["stealth-disadvantage","strength-requirement"]}'::jsonb),
  ('plate', 'armor'::rpg.item_type, 'Placas', '{"text":"1.500 PO"}'::jsonb, '32 kg', NULL, '{"acFormula":{"type":"fixed","base":18},"propertyIds":["stealth-disadvantage","strength-requirement"]}'::jsonb),
  ('shield', 'armor'::rpg.item_type, 'Escudo', '{"text":"10 PO"}'::jsonb, '3 kg', NULL, '{"acFormula":{"type":"shield-bonus","bonus":2},"propertyIds":["shield-ac-bonus"]}'::jsonb),
  ('acido', 'gear'::rpg.item_type, 'Ácido', '{"text":"25 PO"}'::jsonb, '0,5 kg', 'Ao executar a ação Atacar, você pode substituir um', NULL),
  ('agua-benta', 'gear'::rpg.item_type, 'Água Benta', '{"text":"25 PO"}'::jsonb, '0,5 kg', 'Ao executar a ação Atacar, você pode substituir um de', NULL),
  ('algibeira', 'gear'::rpg.item_type, 'Algibeira', '{"text":"5 PP"}'::jsonb, '0,5 kg', 'Uma Algibeira comporta até 3 kg em um volume de 6', NULL),
  ('aljava', 'gear'::rpg.item_type, 'Aljava', '{"text":"1 PO"}'::jsonb, '0,5 kg', 'Uma Aljava armazena até 20 Flechas.', NULL),
  ('antitoxina', 'gear'::rpg.item_type, 'Antitoxina', '{"text":"50 PO"}'::jsonb, '—', 'Como uma Ação Bônus, você pode beber um frasco de', NULL),
  ('apito-sinalizador', 'gear'::rpg.item_type, 'Apito Sinalizador', '{"text":"5 PC"}'::jsonb, '—', 'Quando soprado como uma ação Usar Objeto, um', NULL),
  ('ariete-portavel', 'gear'::rpg.item_type, 'Aríete Portável', '{"text":"4 PO"}'::jsonb, '16,5 kg', 'Você pode usar um Aríete Portável para arrombar', NULL),
  ('armadilha-de-caca', 'gear'::rpg.item_type, 'Armadilha de Caça', '{"text":"5 PO"}'::jsonb, '12,5 kg', 'Como uma ação Usar Objeto, você pode armar uma', NULL),
  ('arpeu', 'gear'::rpg.item_type, 'Arpéu', '{"text":"2 PO"}'::jsonb, '2 kg', 'Como uma ação Usar Objeto, você pode arremessar um', NULL),
  ('balde', 'gear'::rpg.item_type, 'Balde', '{"text":"5 PC"}'::jsonb, '1 kg', 'Um Balde armazena até 0,3 metro cúbico de conteúdo.', NULL),
  ('baliza', 'gear'::rpg.item_type, 'Baliza', '{"text":"5 PC"}'::jsonb, '3,5 kg', 'Uma Baliza tem 3 metros de comprimento. Você pode', NULL),
  ('barril', 'gear'::rpg.item_type, 'Barril', '{"text":"2 PO"}'::jsonb, '35 kg', 'Um Barril armazena até 160 litros de líquido ou até', NULL),
  ('bau', 'gear'::rpg.item_type, 'Baú', '{"text":"5 PO"}'::jsonb, '12,5 kg', 'Um Baú armazena até 0,35 metros cúbicos (ou 350', NULL),
  ('bolsa-de-componentes', 'gear'::rpg.item_type, 'Bolsa de Componentes', '{"text":"25 PO"}'::jsonb, '1 kg', 'Uma Bolsa de Componentes é à prova d’água e cheia', NULL),
  ('cadeado', 'gear'::rpg.item_type, 'Cadeado', '{"text":"10 PO"}'::jsonb, '0,5 kg', 'Um Cadeado vem com uma chave. Sem a chave, uma', NULL),
  ('caixa-para-fogo', 'gear'::rpg.item_type, 'Caixa para Fogo', '{"text":"5 PP"}'::jsonb, '0,5 kg', 'Uma Caixa para Fogo é um pequeno recipiente contendo pedra de sílex, aço contra fogo e material muito', NULL),
  ('caneta-tinteiro', 'gear'::rpg.item_type, 'Caneta Tinteiro', '{"text":"2 PC"}'::jsonb, '—', 'Usando Tinta, uma Caneta Tinteiro é usada para escrever ou desenhar.', NULL),
  ('cantil-cheio', 'gear'::rpg.item_type, 'Cantil (cheio)', '{"text":"2 PP"}'::jsonb, '2,5 kg', 'Um Cantil comporta até 2 litros. Se você não beber', NULL),
  ('cesta', 'gear'::rpg.item_type, 'Cesta', '{"text":"4 PP"}'::jsonb, '1 kg', 'Uma Cesta armazena até 20 quilos dentro de 60 centímetros cúbicos.', NULL),
  ('cobertor', 'gear'::rpg.item_type, 'Cobertor', '{"text":"5 PP"}'::jsonb, '1,5 kg', 'Enquanto estiver envolto em um cobertor, você tem', NULL),
  ('corda', 'gear'::rpg.item_type, 'Corda', '{"text":"1 PO"}'::jsonb, '2,5 kg', 'Como uma ação Usar Objeto, você pode dar um nó em', NULL),
  ('cordao', 'gear'::rpg.item_type, 'Cordão', '{"text":"1 PP"}'::jsonb, '—', 'Um cordão tem 3 metros de comprimento. Você pode', NULL),
  ('corrente', 'gear'::rpg.item_type, 'Corrente', '{"text":"5 PO"}'::jsonb, '5 kg', 'Como uma ação Usar Objeto, você pode enrolar uma', NULL),
  ('escada', 'gear'::rpg.item_type, 'Escada', '{"text":"1 PP"}'::jsonb, '12,5 kg', 'Uma Escada tem 3 metros de altura. Você deve escalar', NULL),
  ('esferas-de-metal', 'gear'::rpg.item_type, 'Esferas de Metal', '{"text":"1 PO"}'::jsonb, '1 kg (saco)', 'Como uma ação Usar Objeto, você pode derramar', NULL),
  ('espelho', 'gear'::rpg.item_type, 'Espelho', '{"text":"5 PO"}'::jsonb, '250 g', 'Um espelho de aço portátil é prático tanto para uso', NULL),
  ('estacas-de-ferro', 'gear'::rpg.item_type, 'Estacas de Ferro', '{"text":"1 PO"}'::jsonb, '2,5 kg', 'Estacas de Ferro vêm em pacotes de dez. Como uma', NULL),
  ('estojo-mapa-ou-pergaminho', 'gear'::rpg.item_type, 'Estojo, Mapa ou Pergaminho', '{"text":"1 PO"}'::jsonb, '0,5 kg', 'Um Estojo de Mapa ou Pergaminho armazena até 10', NULL),
  ('estojo-virote-de-besta', 'gear'::rpg.item_type, 'Estojo, Virote de Besta', '{"text":"1 PO"}'::jsonb, '0,5 kg', 'Um Estojo de Virotes de Besta armazena até 20', NULL),
  ('estrepes', 'gear'::rpg.item_type, 'Estrepes', '{"text":"1 PO"}'::jsonb, '1 kg (saco)', 'Como uma ação Usar Objeto, você pode espalhar', NULL),
  ('foco-arcano', 'focus'::rpg.item_type, 'Foco Arcano', '{"text":"Varia"}'::jsonb, 'Varia', 'Um Foco Arcano assume uma das formas na tabela', NULL),
  ('foco-druidico', 'focus'::rpg.item_type, 'Foco Druídico', '{"text":"Varia"}'::jsonb, 'Varia', 'Um Foco Druídico assume uma das formas apresentadas na tabela Foco Druídico e é esculpido, amarrado', NULL),
  ('fogo-alquimico', 'gear'::rpg.item_type, 'Fogo Alquímico', '{"text":"50 PO"}'::jsonb, '0,5 kg', 'Ao executar a ação Atacar, você pode substituir um de', NULL),
  ('frasco', 'gear'::rpg.item_type, 'Frasco', '{"text":"1 PO"}'::jsonb, '—', 'Um Frasco armazena até 150 mililitros.', NULL),
  ('garrafa-de-vidro-1-litro', 'gear'::rpg.item_type, 'Garrafa de Vidro (1 litro)', '{"text":"2 PO"}'::jsonb, '1 kg', 'Uma Garrafa de Vidro armazena até 1 litro.', NULL),
  ('grilhoes', 'gear'::rpg.item_type, 'Grilhões', '{"text":"2 PO"}'::jsonb, '3 kg', 'Como uma ação Usar Objeto, você pode usar Grilhões', NULL),
  ('jarro-4-litros', 'gear'::rpg.item_type, 'Jarro (4 litros)', '{"text":"2 PC"}'::jsonb, '2 kg', 'Um Jarro armazena até 4 litros.', NULL),
  ('kit-de-artista', 'gear'::rpg.item_type, 'Kit de Artista', '{"text":"40 PO"}'::jsonb, '29 kg', 'Um Kit de Artista contém os seguintes itens: Caixa', NULL),
  ('kit-de-assaltante', 'gear'::rpg.item_type, 'Kit de Assaltante', '{"text":"16 PO"}'::jsonb, '21 kg', 'Um Kit de Assaltante contém os seguintes itens: Caixa', NULL),
  ('kit-de-aventureiro', 'gear'::rpg.item_type, 'Kit de Aventureiro', '{"text":"10 PO"}'::jsonb, '27,5 kg', 'Um Kit de Aventureiro contém os seguintes itens: Caixa para Fogo, Cantil, Corda, Mochila, 2 potes de Óleo,', NULL),
  ('kit-de-curandeiro', 'gear'::rpg.item_type, 'Kit de Curandeiro', '{"text":"5 PO"}'::jsonb, '1,5 kg', 'Um Kit de Curandeiro tem dez usos. Como uma ação', NULL),
  ('kit-de-diplomata', 'gear'::rpg.item_type, 'Kit de Diplomata', '{"text":"39 PO"}'::jsonb, '19,5 kg', 'Um Kit de Diplomata contém os seguintes itens: Baú,', NULL),
  ('kit-de-erudito', 'gear'::rpg.item_type, 'Kit de Erudito', '{"text":"40 PO"}'::jsonb, '11 kg', 'Um Kit de Erudito contém os seguintes itens: Caixa', NULL),
  ('kit-de-escalada', 'gear'::rpg.item_type, 'Kit de Escalada', '{"text":"25 PO"}'::jsonb, '6 kg', 'Um Kit de Escalada inclui arnês, luvas, pítons e ponteiras de bota. Como uma ação Usar Objeto, você pode', NULL),
  ('kit-de-explorador-de-masmorras', 'gear'::rpg.item_type, 'Kit de Explorador de Masmorras', '{"text":"12 PO"}'::jsonb, '27,5 kg', 'Um Kit de Explorador de Masmorras contém os', NULL),
  ('kit-de-sacerdote', 'gear'::rpg.item_type, 'Kit de Sacerdote', '{"text":"33 PO"}'::jsonb, '14,5 kg', 'Um Kit de Sacerdote contém os seguintes itens: Água', NULL),
  ('lampada', 'gear'::rpg.item_type, 'Lâmpada', '{"text":"5 PP"}'::jsonb, '0,5 kg', 'Uma Lâmpada usa Óleo para combustão para emitir', NULL),
  ('lanterna-coberta', 'gear'::rpg.item_type, 'Lanterna Coberta', '{"text":"5 PO"}'::jsonb, '1 kg', 'Uma Lanterna Coberta usa Óleo para combustão para', NULL),
  ('lanterna-foca-facho', 'gear'::rpg.item_type, 'Lanterna Foca-facho', '{"text":"10 PO"}'::jsonb, '1 kg', 'Uma Lanterna Foca-Facho usa Óleo como combustão', NULL),
  ('livro', 'gear'::rpg.item_type, 'Livro', '{"text":"25 PO"}'::jsonb, '2,5 kg', 'Um livro contém texto de ficção ou não-ficção. Se você', NULL),
  ('luneta', 'gear'::rpg.item_type, 'Luneta', '{"text":"1.000 PO"}'::jsonb, '0,5 kg', 'Objetos vistos através de uma Luneta são ampliados', NULL),
  ('lupa', 'gear'::rpg.item_type, 'Lupa', '{"text":"100 PO"}'::jsonb, '—', 'Uma Lupa concede Vantagem em qualquer teste de', NULL),
  ('mapa', 'gear'::rpg.item_type, 'Mapa', '{"text":"1 PO"}'::jsonb, '—', 'Se consultar um mapa detalhado, você obtém um', NULL),
  ('mochila', 'gear'::rpg.item_type, 'Mochila', '{"text":"2 PO"}'::jsonb, '2,5 kg', 'Uma Mochila armazena até 15 quilos dentro de 30', NULL),
  ('municao', 'gear'::rpg.item_type, 'Munição', '{"text":"Varia"}'::jsonb, 'Varia', 'Munição é exigida por uma arma que tenha a propriedade Munição. A descrição de uma arma detalha o tipo', NULL),
  ('oleo', 'gear'::rpg.item_type, 'Óleo', '{"text":"1 PP"}'::jsonb, '0,5 kg', 'Você pode cobrir uma criatura, objeto ou área com', NULL),
  ('pa', 'gear'::rpg.item_type, 'Pá', '{"text":"2 PO"}'::jsonb, '2,5 kg', 'Trabalhando por 1 hora, você pode usar uma Pá para', NULL),
  ('papel', 'gear'::rpg.item_type, 'Papel', '{"text":"2 PP"}'::jsonb, '—', 'Uma folha de papel pode comportar cerca de 250 palavras escritas à mão.', NULL),
  ('pe-de-cabra', 'gear'::rpg.item_type, 'Pé de Cabra', '{"text":"2 PO"}'::jsonb, '2,5 kg', 'Usar um Pé de Cabra concede a você Vantagem em', NULL),
  ('perfume', 'gear'::rpg.item_type, 'Perfume', '{"text":"5 PO"}'::jsonb, '—', 'O perfume vem em um frasco de 120 mililitros. Por 1', NULL),
  ('pergaminho', 'gear'::rpg.item_type, 'Pergaminho', '{"text":"1 PP"}'::jsonb, '—', 'Uma folha de pergaminho pode comportar cerca de', NULL),
  ('pergaminho-magico-1-circulo', 'gear'::rpg.item_type, 'Pergaminho Mágico (1º Círculo)', '{"text":"50 PO"}'::jsonb, '—', 'Uma folha de pergaminho pode comportar cerca de', NULL),
  ('pergaminho-magico-truque', 'gear'::rpg.item_type, 'Pergaminho Mágico (Truque)', '{"text":"30 PO"}'::jsonb, '—', 'Uma folha de pergaminho pode comportar cerca de', NULL),
  ('pocao-de-cura', 'gear'::rpg.item_type, 'Poção de Cura', '{"text":"50 PO"}'::jsonb, '250 g', 'Esta poção é um item mágico. Como uma Ação Bônus,', NULL),
  ('pote', 'gear'::rpg.item_type, 'Pote', '{"text":"2 PC"}'::jsonb, '0,5 kg', 'Um Frasco armazena até meio litro.', NULL),
  ('pote-ferro', 'gear'::rpg.item_type, 'Pote, Ferro', '{"text":"2 PO"}'::jsonb, '5 kg', 'Um Frasco armazena até meio litro.', NULL),
  ('racoes', 'gear'::rpg.item_type, 'Rações', '{"text":"5 PP"}'::jsonb, '1 kg', 'As rações consistem em alimentos prontos para viagem, incluindo biscoito duro, carne seca, frutas secas e', NULL),
  ('rede', 'gear'::rpg.item_type, 'Rede', '{"text":"1 PO"}'::jsonb, '1,5 kg', 'Ao executar a ação Atacar, você pode substituir um', NULL),
  ('roldana-e-polias', 'gear'::rpg.item_type, 'Roldana e Polias', '{"text":"1 PO"}'::jsonb, '2,5 kg', 'Roldana e Polias permitem içar até quatro vezes o peso', NULL),
  ('roupas-fantasia', 'gear'::rpg.item_type, 'Roupas, Fantasia', '{"text":"5 PO"}'::jsonb, '2 kg', 'Roupas Finas são feitas de tecidos caros e adornadas', NULL),
  ('roupas-finas', 'gear'::rpg.item_type, 'Roupas, Finas', '{"text":"15 PO"}'::jsonb, '3 kg', 'Roupas Finas são feitas de tecidos caros e adornadas', NULL),
  ('roupas-viagem', 'gear'::rpg.item_type, 'Roupas, Viagem', '{"text":"2 PO"}'::jsonb, '2 kg', 'Roupas de Viagem são roupas resistentes projetadas', NULL),
  ('saca', 'gear'::rpg.item_type, 'Saca', '{"text":"1 PC"}'::jsonb, '250 g', 'Uma Saca armazena até 15 kg dentro de 30 centímetros cúbicos.', NULL),
  ('saco-de-dormir', 'gear'::rpg.item_type, 'Saco de Dormir', '{"text":"1 PO"}'::jsonb, '3,5 kg', 'Um Saco de Dormir acomoda uma criatura Pequena', NULL),
  ('simbolo-sagrado', 'gear'::rpg.item_type, 'Símbolo Sagrado', '{"text":"Varia"}'::jsonb, 'Varia', 'Um Símbolo Sagrado assume uma das formas na tabela', NULL),
  ('sino', 'gear'::rpg.item_type, 'Sino', '{"text":"1 PO"}'::jsonb, '—', 'Quando tocado como uma ação Usar Objeto, um Sino', NULL),
  ('tenda', 'gear'::rpg.item_type, 'Tenda', '{"text":"2 PO"}'::jsonb, '10 kg', 'Uma Tenda acomoda para dormir até duas criaturas', NULL),
  ('tinta', 'gear'::rpg.item_type, 'Tinta', '{"text":"10 PO"}'::jsonb, '—', 'A tinta vem em uma garrafa de 30 mililitros, que', NULL),
  ('tocha', 'gear'::rpg.item_type, 'Tocha', '{"text":"1 PC"}'::jsonb, '0,5 kg', 'Uma Tocha entra em combustão por 1 hora, emitindo', NULL),
  ('vela', 'gear'::rpg.item_type, 'Vela', '{"text":"1 PC"}'::jsonb, '—', 'Por 1 hora, uma Vela acesa emite Luz Plena em um raio', NULL),
  ('tunica', 'gear'::rpg.item_type, 'Túnica', '{"text":"1 PO"}'::jsonb, '2 kg', 'Uma Túnica tem significado vocacional ou cerimonial.', NULL),
  ('veneno-basico', 'gear'::rpg.item_type, 'Veneno Básico', '{"text":"100 PO"}'::jsonb, '—', 'Como uma Ação Bônus, você pode usar um frasco', NULL),
  ('ferramentas-de-carpinteiro', 'tool'::rpg.item_type, 'Ferramentas de Carpinteiro', '{"text":"8 PO"}'::jsonb, '3 kg', 'Selar ou abrir uma porta ou recipiente (CD 20)', '{"attribute":"Força","crafting":"Aríete Portável, Baliza, Barril, Baú, Cajado, Clava,\nClava Grande, Escada, Tocha","variants":null}'::jsonb),
  ('ferramentas-de-cartografo', 'tool'::rpg.item_type, 'Ferramentas de Cartógrafo', '{"text":"15 PO"}'::jsonb, '3 kg', 'Elaborar o mapa de uma pequena área (CD 15)', '{"attribute":"Sabedoria","crafting":"Mapa","variants":null}'::jsonb),
  ('ferramentas-de-coureiro', 'tool'::rpg.item_type, 'Ferramentas de Coureiro', '{"text":"5 PO"}'::jsonb, '2,5 kg', 'Moldar a estética de um item de couro (CD 10)', '{"attribute":"Destreza","crafting":"Algibeira, Aljava, Armadura de Couro, Armadura\nde Couro Batido, Cantil, Chicote, Estojo de Mapa ou\nPergaminho, Estojo de Virotes de Besta, Funda, Gibão de\nPeles, Mochila, Pergaminho","variants":null}'::jsonb),
  ('ferramentas-de-entalhador', 'tool'::rpg.item_type, 'Ferramentas de Entalhador', '{"text":"1 PO"}'::jsonb, '2,5 kg', 'Entalhar um padrão em madeira (CD 10)', '{"attribute":"Destreza","crafting":"Armas à Distância (exceto Funda, Mosquete e\nPistola), Cajado, Caneta Tinteiro, Clava, Clava Grande,\nDardos, Flechas, Foco Arcano, Foco Druídico, Virotes","variants":null}'::jsonb),
  ('ferramentas-de-ferreiro', 'tool'::rpg.item_type, 'Ferramentas de Ferreiro', '{"text":"20 PO"}'::jsonb, '4 kg', 'Forçar a abertura de uma porta ou recipiente (CD 20)', '{"attribute":"Força","crafting":"qualquer arma Corpo a Corpo (exceto Cajado,\nChicote, Clava, Clava Grande), armadura Média (exceto\nGibão de Peles), armadura Pesada, Arpéu e Gancho, Balas\nde Arma de Fogo, Balas de Funda, Balde, Corrente, Esferas\nde Metal, Estacas de Ferro, Estrepes, Panela de Ferro, Pé de\nCabra","variants":null}'::jsonb),
  ('ferramentas-de-funileiro', 'tool'::rpg.item_type, 'Ferramentas de Funileiro', '{"text":"50 PO"}'::jsonb, '5 kg', 'Monte um item Minúsculo composto de sucata,
que se desfaz em 1 minuto (CD 20)', '{"attribute":"Destreza","crafting":"Apito Sinalizador, Armadilha de Caça, Cadeado\nou Fechadura, Caixa para Fogo, Espelho, Grilhões, Lanterna\nCoberta, Lanterna Foca-Facho, Mosquete, Pá, Pistola,Pote,\nSino","variants":null}'::jsonb),
  ('ferramentas-de-joalheiro', 'tool'::rpg.item_type, 'Ferramentas de Joalheiro', '{"text":"25 PO"}'::jsonb, '1 kg', 'Discernir o valor de uma gema (CD 15)', '{"attribute":"Inteligência","crafting":"Foco Arcano, Símbolo Sagrado","variants":null}'::jsonb),
  ('ferramentas-de-oleiro', 'tool'::rpg.item_type, 'Ferramentas de Oleiro', '{"text":"10 PO"}'::jsonb, '1,5 kg', 'Discernir como um objeto de cerâmica foi
manuseado nas últimas 24 horas (CD 15)', '{"attribute":"Inteligência","crafting":"Jarro, Lâmpada","variants":null}'::jsonb),
  ('ferramentas-de-pedreiro', 'tool'::rpg.item_type, 'Ferramentas de Pedreiro', '{"text":"10 PO"}'::jsonb, '4 kg', 'Cinzelar um símbolo ou buraco na pedra (CD 10)', '{"attribute":"Força","crafting":"Roldana e Polias","variants":null}'::jsonb),
  ('ferramentas-de-sapateiro', 'tool'::rpg.item_type, 'Ferramentas de Sapateiro', '{"text":"5 PO"}'::jsonb, '2,5 kg', 'Modificar calçado para conceder Vantagem no
próximo teste de Destreza (Acrobacia) do usuário (CD 10)', '{"attribute":"Destreza","crafting":"Kit de Escalada","variants":null}'::jsonb),
  ('ferramentas-de-tecelao', 'tool'::rpg.item_type, 'Ferramentas de Tecelão', '{"text":"1 PO"}'::jsonb, '2,5 kg', 'Reparar um rasgo em uma roupa (CD 10) ou
costurar um ornamento Minúsculo (CD 10)', '{"attribute":"Destreza","crafting":"Armadura Acolchoada, Cesta, Cobertor, Saco de\nDormir, Roupas Finas, Rede, Túnica, Corda, Saca, Cordão,\nTenda, Roupas de Viagem","variants":null}'::jsonb),
  ('ferramentas-de-vidreiro', 'tool'::rpg.item_type, 'Ferramentas de Vidreiro', '{"text":"30 PO"}'::jsonb, '2,5 kg', 'Discernir como um objeto de vidro foi
manuseado nas últimas 24 horas (CD 15)', '{"attribute":"Inteligência","crafting":"Frasco, Jarro, Luneta, Lupa","variants":null}'::jsonb),
  ('suprimentos-de-alquimista', 'tool'::rpg.item_type, 'Suprimentos de Alquimista', '{"text":"50 PO"}'::jsonb, '4 kg', 'Identificar uma substância (CD 15) ou iniciar um
incêndio (CD 15)', '{"attribute":"Inteligência","crafting":"Ácido, Bolsa de Componentes, Fogo Alquímico,\nÓleo, Papel, Perfume","variants":null}'::jsonb),
  ('suprimentos-de-caligrafo', 'tool'::rpg.item_type, 'Suprimentos de Calígrafo', '{"text":"10 PO"}'::jsonb, '2,5 kg', 'Escrever texto com uma caligrafia que protege
contra falsificação (CD 15)', '{"attribute":"Destreza","crafting":"Pergaminho Mágico, Tinta","variants":null}'::jsonb),
  ('suprimentos-de-cervejeiro', 'tool'::rpg.item_type, 'Suprimentos de Cervejeiro', '{"text":"20 PO"}'::jsonb, '4,5 kg', 'Detectar bebida envenenada (CD 15) ou
identificar álcool (CD 10)', '{"attribute":"Inteligência","crafting":"Antitoxina","variants":null}'::jsonb),
  ('suprimentos-de-pintor', 'tool'::rpg.item_type, 'Suprimentos de Pintor', '{"text":"10 PO"}'::jsonb, '2,5 kg', 'Fazer uma pintura reconhecível de algo que você
viu (CD 10)', '{"attribute":"Sabedoria","crafting":"Foco Druídico, Símbolo Sagrado","variants":null}'::jsonb),
  ('utensilios-de-cozinheiro', 'tool'::rpg.item_type, 'Utensílios de Cozinheiro', '{"text":"1 PO"}'::jsonb, '4 kg', 'Melhorar o sabor dos alimentos (CD 10) ou
detectar alimentos estragados ou envenenados (CD 15)', '{"attribute":"Sabedoria","crafting":"Rações","variants":null}'::jsonb),
  ('ferramentas-de-ladrao', 'tool'::rpg.item_type, 'Ferramentas de Ladrão', '{"text":"25 PO"}'::jsonb, '0,5 kg', 'Abrir uma fechadura (CD 15) ou desarmar uma
armadilha (CD 15)', '{"attribute":"Destreza","crafting":null,"variants":null}'::jsonb),
  ('ferramentas-de-navegador', 'tool'::rpg.item_type, 'Ferramentas de Navegador', '{"text":"25 PO"}'::jsonb, '1 kg', 'Traçar uma rota (CD 10) ou determinar a posição
observando as estrelas (CD 15)', '{"attribute":"Sabedoria","crafting":null,"variants":null}'::jsonb),
  ('instrumento-musical', 'tool'::rpg.item_type, 'Instrumento Musical', '{"text":"Varia"}'::jsonb, 'Varia', 'Tocar uma música conhecida (CD 10) ou
improvisar uma música (CD 15)', '{"attribute":"Carisma","crafting":null,"variants":"Alaúde (35 PO, 1 kg), Flauta (2 PO, 0,5 kg), Flauta\nde Pan (12 PO, 1 kg), Gaita de Foles (30 PO, 3 kg), Lira\n(30 PO, 1 kg), Oboé (2 PO, 0,5 kg), Tambor (6 PO, 1,5 kg),\nTrombeta (3 PO, 1 kg), Violino (30 PO, 0,5 kg), Xilofone (25\nPO, 5 kg)"}'::jsonb),
  ('kit-de-disfarce', 'tool'::rpg.item_type, 'Kit de Disfarce', '{"text":"25 PO"}'::jsonb, '1,5 kg', 'Aplicar maquiagem (CD 10)', '{"attribute":"Carisma","crafting":"Fantasia","variants":null}'::jsonb),
  ('kit-de-falsificacao', 'tool'::rpg.item_type, 'Kit de Falsificação', '{"text":"15 PO"}'::jsonb, '2,5 kg', 'Imitar 10 ou menos palavras escritas de outra
pessoa (CD 15) ou duplicar um selo de cera (CD 20)', '{"attribute":"Destreza","crafting":null,"variants":null}'::jsonb),
  ('kit-de-herbalismo', 'tool'::rpg.item_type, 'Kit de Herbalismo', '{"text":"5 PO"}'::jsonb, '1,5 kg', 'Identificar uma planta (CD 10)', '{"attribute":"Inteligência","crafting":"Antitoxina, Kit de Curandeiro, Poção de Cura, Vela","variants":null}'::jsonb),
  ('kit-de-jogos', 'tool'::rpg.item_type, 'Kit de Jogos', '{"text":"Varia"}'::jsonb, '—', 'Discernir se alguém está trapaceando (CD 10) ou
ganhar o jogo (CD 20)', '{"attribute":"Sabedoria","crafting":null,"variants":"Dados (1 PP), Xadrez-do-Dragão (1 PO), Baralho\n(5 PP), Conjunto do Jogo dos Três Dragões (1 PO)"}'::jsonb),
  ('kit-de-veneno', 'tool'::rpg.item_type, 'Kit de Veneno', '{"text":"50 PO"}'::jsonb, '1 kg', 'Detectar um objeto envenenado (CD 10)', '{"attribute":"Inteligência","crafting":"Veneno Básico","variants":null}'::jsonb);
