import type { StrikeOption } from '../../strike-option';

export const BLOOD_HOUND_STRIKE_OPTIONS: readonly StrikeOption[] = [
  {
    slug: 'bewitching-strike',
    name: 'Golpe Enfeitiçante',
    subclassSlug: 'blood-hound',
    resourceSlug: 'blood-strike',
    tableAction: 'blood-strike',
    costDice: '1d8',
    extraDice: '2d6',
    extraDiceL18: '4d6',
    damageType: 'psychic',
    saveAbility: 'sabedoria',
    onFailCondition: null,
    onFailPendingKind: null,
    onHitPendingKind: null,
    replacesAttackWithSave: false,
    secondaryDice: null,
    secondaryDiceL18: null,
    ignoreTargetArmor: false,
    ignoreDamageResistance: false,
    addsArenaEffect: false,
    arenaEffectSlug: null,
    noteOnly: true,
  },
  {
    slug: 'bloodboil-strike',
    name: 'Golpe Ferver-Sangue',
    subclassSlug: 'blood-hound',
    resourceSlug: 'blood-strike',
    tableAction: 'blood-strike',
    costDice: '1d6',
    extraDice: '2d6',
    extraDiceL18: '4d6',
    damageType: 'fire',
    saveAbility: null,
    onFailCondition: null,
    onFailPendingKind: null,
    onHitPendingKind: null,
    replacesAttackWithSave: false,
    secondaryDice: null,
    secondaryDiceL18: null,
    ignoreTargetArmor: false,
    ignoreDamageResistance: true,
    addsArenaEffect: false,
    arenaEffectSlug: null,
    noteOnly: false,
  },
  {
    slug: 'bloodshard-strike',
    name: 'Golpe Estilhaço-Sangue',
    subclassSlug: 'blood-hound',
    resourceSlug: 'blood-strike',
    tableAction: 'blood-strike',
    costDice: '1d8',
    extraDice: '0',
    extraDiceL18: '0',
    damageType: 'piercing',
    saveAbility: null,
    onFailCondition: null,
    onFailPendingKind: null,
    onHitPendingKind: null,
    replacesAttackWithSave: true,
    secondaryDice: '1d6',
    secondaryDiceL18: '3d6',
    ignoreTargetArmor: false,
    ignoreDamageResistance: false,
    addsArenaEffect: false,
    arenaEffectSlug: null,
    noteOnly: false,
  },
  {
    slug: 'constraining-strike',
    name: 'Golpe Constritor',
    subclassSlug: 'blood-hound',
    resourceSlug: 'blood-strike',
    tableAction: 'blood-strike',
    costDice: '1d8',
    extraDice: '2d6',
    extraDiceL18: '4d6',
    damageType: 'acid',
    saveAbility: null,
    onFailCondition: null,
    onFailPendingKind: null,
    onHitPendingKind: 'blood-constrain',
    replacesAttackWithSave: false,
    secondaryDice: null,
    secondaryDiceL18: null,
    ignoreTargetArmor: false,
    ignoreDamageResistance: false,
    addsArenaEffect: false,
    arenaEffectSlug: null,
    noteOnly: false,
  },
  {
    slug: 'exiling-strike',
    name: 'Golpe do Exílio',
    subclassSlug: 'blood-hound',
    resourceSlug: 'blood-strike',
    tableAction: 'blood-strike',
    costDice: '1d10',
    extraDice: '0',
    extraDiceL18: '2d6',
    damageType: 'radiant',
    saveAbility: 'carisma',
    onFailCondition: 'incapacitated',
    onFailPendingKind: 'blood-exile',
    onHitPendingKind: null,
    replacesAttackWithSave: false,
    secondaryDice: null,
    secondaryDiceL18: null,
    ignoreTargetArmor: false,
    ignoreDamageResistance: false,
    addsArenaEffect: false,
    arenaEffectSlug: null,
    noteOnly: false,
  },
  {
    slug: 'hunting-strike',
    name: 'Golpe da Caça',
    subclassSlug: 'blood-hound',
    resourceSlug: 'blood-strike',
    tableAction: 'blood-strike',
    costDice: '1d4',
    extraDice: '1d6',
    extraDiceL18: '3d6',
    damageType: 'slashing',
    saveAbility: null,
    onFailCondition: null,
    onFailPendingKind: null,
    onHitPendingKind: null,
    replacesAttackWithSave: false,
    secondaryDice: null,
    secondaryDiceL18: null,
    ignoreTargetArmor: true,
    ignoreDamageResistance: false,
    addsArenaEffect: false,
    arenaEffectSlug: null,
    noteOnly: false,
  },
  {
    slug: 'shadowblood-strike',
    name: 'Golpe Sangue-Sombra',
    subclassSlug: 'blood-hound',
    resourceSlug: 'blood-strike',
    tableAction: 'blood-strike',
    costDice: '1d6',
    extraDice: '2d6',
    extraDiceL18: '4d6',
    damageType: 'necrotic',
    saveAbility: null,
    onFailCondition: null,
    onFailPendingKind: null,
    onHitPendingKind: null,
    replacesAttackWithSave: false,
    secondaryDice: null,
    secondaryDiceL18: null,
    ignoreTargetArmor: false,
    ignoreDamageResistance: false,
    addsArenaEffect: true,
    arenaEffectSlug: 'magical_darkness',
    noteOnly: false,
  },
  {
    slug: 'thunderblood-strike',
    name: 'Golpe Sangue-Trovão',
    subclassSlug: 'blood-hound',
    resourceSlug: 'blood-strike',
    tableAction: 'blood-strike',
    costDice: '1d4',
    extraDice: '2d6',
    extraDiceL18: '4d6',
    damageType: 'thunder',
    saveAbility: 'forca',
    onFailCondition: 'prone',
    onFailPendingKind: null,
    onHitPendingKind: null,
    replacesAttackWithSave: false,
    secondaryDice: null,
    secondaryDiceL18: null,
    ignoreTargetArmor: false,
    ignoreDamageResistance: false,
    addsArenaEffect: false,
    arenaEffectSlug: null,
    noteOnly: false,
  },
  {
    slug: 'withering-strike',
    name: 'Golpe Definhante',
    subclassSlug: 'blood-hound',
    resourceSlug: 'blood-strike',
    tableAction: 'blood-strike',
    costDice: '1d6',
    extraDice: '2d6',
    extraDiceL18: '4d6',
    damageType: 'necrotic',
    saveAbility: 'constituicao',
    onFailCondition: null,
    onFailPendingKind: 'blood-withering',
    onHitPendingKind: null,
    replacesAttackWithSave: false,
    secondaryDice: null,
    secondaryDiceL18: null,
    ignoreTargetArmor: false,
    ignoreDamageResistance: false,
    addsArenaEffect: false,
    arenaEffectSlug: null,
    noteOnly: false,
  },
];
