import type { SubclassTableAction } from '../../catalog/subclass-table-action';

/** Seeds `combat/C00*` — Psi Warrior table actions. */
export const FIXTURE_PSI_ACTIONS: readonly SubclassTableAction[] = [
  {
    subclassSlug: 'psi-warrior',
    slug: 'protective-field',
    name: 'Campo Protetor',
    unlockLevel: 3,
    alwaysSpendsPool: true,
    rollsPoolDie: true,
    spendsOnlyOnSuccess: false,
  },
  {
    subclassSlug: 'psi-warrior',
    slug: 'telekinetic-movement',
    name: 'Movimento Telecinético',
    unlockLevel: 3,
    freeResourceSlug: 'telekinetic-movement',
    alwaysSpendsPool: false,
    rollsPoolDie: false,
    spendsOnlyOnSuccess: false,
  },
  {
    subclassSlug: 'psi-warrior',
    slug: 'psychic-leap',
    name: 'Salto com Impulsão Psíquica',
    unlockLevel: 7,
    freeResourceSlug: 'psychic-leap',
    alwaysSpendsPool: false,
    rollsPoolDie: false,
    spendsOnlyOnSuccess: false,
  },
  {
    subclassSlug: 'psi-warrior',
    slug: 'mental-guard',
    name: 'Resguardo Mental',
    unlockLevel: 10,
    alwaysSpendsPool: true,
    rollsPoolDie: false,
    spendsOnlyOnSuccess: false,
  },
  {
    subclassSlug: 'psi-warrior',
    slug: 'energy-bulwark',
    name: 'Baluarte de Energia',
    unlockLevel: 15,
    freeResourceSlug: 'energy-bulwark',
    alwaysSpendsPool: false,
    rollsPoolDie: false,
    spendsOnlyOnSuccess: false,
  },
  {
    subclassSlug: 'psi-warrior',
    slug: 'telekinetic-master',
    name: 'Mestre Telecinético',
    unlockLevel: 18,
    freeResourceSlug: 'telekinetic-master',
    alwaysSpendsPool: false,
    rollsPoolDie: false,
    spendsOnlyOnSuccess: false,
  },
];

/** Seeds `combat/C00*` — Soulknife table actions. */
export const FIXTURE_SOULKNIFE_ACTIONS: readonly SubclassTableAction[] = [
  {
    subclassSlug: 'soulknife',
    slug: 'psi-bolstered-knack',
    name: 'Aptidão Reforçada Psiquicamente',
    unlockLevel: 3,
    alwaysSpendsPool: false,
    rollsPoolDie: true,
    spendsOnlyOnSuccess: true,
  },
  {
    subclassSlug: 'soulknife',
    slug: 'psychic-whispers',
    name: 'Sussurros Psíquicos',
    unlockLevel: 3,
    freeResourceSlug: 'psychic-whispers',
    alwaysSpendsPool: false,
    rollsPoolDie: true,
    spendsOnlyOnSuccess: false,
    repeatPoolCost: 1,
  },
  {
    subclassSlug: 'soulknife',
    slug: 'guided-strike',
    name: 'Golpes Teleguiados',
    unlockLevel: 9,
    alwaysSpendsPool: false,
    rollsPoolDie: true,
    spendsOnlyOnSuccess: true,
  },
  {
    subclassSlug: 'soulknife',
    slug: 'psychic-teleport',
    name: 'Teleporte Psíquico',
    unlockLevel: 9,
    alwaysSpendsPool: false,
    rollsPoolDie: true,
    spendsOnlyOnSuccess: false,
    alwaysPoolCost: 1,
  },
  {
    subclassSlug: 'soulknife',
    slug: 'psychic-veil',
    name: 'Véu Psíquico',
    unlockLevel: 13,
    freeResourceSlug: 'psychic-veil',
    alwaysSpendsPool: false,
    rollsPoolDie: false,
    spendsOnlyOnSuccess: false,
    repeatPoolCost: 1,
  },
  {
    subclassSlug: 'soulknife',
    slug: 'rend-mind',
    name: 'Rasgar Mente',
    unlockLevel: 17,
    freeResourceSlug: 'rend-mind',
    alwaysSpendsPool: false,
    rollsPoolDie: false,
    spendsOnlyOnSuccess: false,
    repeatPoolCost: 3,
  },
];
