-- Seed: Class economy actions (UI Actions tab)
-- Generated from dnd-front class-action-economy.ts

INSERT INTO rpg.phb_class_economy_action (
  action_id, class_id, subclass_id, name, economy, unlock_level,
  resource_slug, free_resource_slug, always_spends_resource,
  summary, description, table_action, spend_amount, sort_order
) VALUES
('fighter-second-wind', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), NULL, 'Recuperar Fôlego', 'bonus'::rpg.action_economy_bucket, 1, 'secondWind', NULL, false, 'Cura 1d10 + nível de Guerreiro', 'Como Ação Bônus, você pode recuperar pontos de vida iguais a 1d10 + seu nível de Guerreiro. Você tem um número limitado de usos; recupere-os ao terminar um Descanso Curto ou Longo.', 'second-wind', NULL, 1),
('fighter-action-surge', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), NULL, 'Surto de Ação', 'action'::rpg.action_economy_bucket, 2, 'actionSurge', NULL, false, 'Concede uma ação adicional neste turno', 'No seu turno, você pode se esforçar além do normal e ganhar uma Ação adicional. Depois de usar Surto de Ação, você precisa terminar um Descanso Curto ou Longo para usá-lo de novo (em níveis altos, pode ter mais usos).', 'action-surge', NULL, 2),
('fighter-tactical-mind', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), NULL, 'Mente Tática', 'free'::rpg.action_economy_bucket, 2, 'secondWind', NULL, false, 'Ao falhar em teste: +1d10 (gasta Fôlego só se virar sucesso)', 'Quando você falha em um teste de habilidade, você pode gastar um uso de Recuperar Fôlego para rolar 1d10 e somar ao resultado. Se o teste ainda falhar, o uso de Recuperar Fôlego não é gasto.', 'tactical-mind', NULL, 3),
('fighter-indomitable', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), NULL, 'Indomável', 'free'::rpg.action_economy_bucket, 9, 'indomitable', NULL, false, 'Ao falhar salvaguarda: rerrola com +nível', 'Se você falhar em uma salvaguarda, pode rerrolá-la com um bônus igual ao seu nível de Guerreiro. Você deve usar o novo resultado. Usos limitados; recupere-os ao terminar um Descanso Longo. Na ficha, marque a opção Indomável ao rolar a salvaguarda.', NULL, NULL, 4),
('fighter-psi-protective-field', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'psi-warrior'), 'Campo Protetor', 'reaction'::rpg.action_economy_bucket, 3, 'psi-energy-dice', NULL, true, 'Reação: reduz dano com 1 dado psi + INT', 'Quando você ou uma criatura que você possa ver a até 9 metros sofrer dano, use sua Reação e gaste um Dado de Energia Psiônica: reduza o dano pelo resultado do dado + seu modificador de Inteligência. Sempre gasta um dado (não tem uso gratuito).', 'psi:protective-field', NULL, 5),
('fighter-psi-telekinetic-movement', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'psi-warrior'), 'Movimento Telecinético', 'action'::rpg.action_economy_bucket, 3, 'psi-energy-dice', 'telekinetic-movement', false, '1× gratuito por descanso; depois gasta 1 dado psi', 'Mova um objeto solto ou uma criatura voluntária conforme a característica. O primeiro uso após um Descanso Curto ou Longo é gratuito; usos extras gastam um Dado de Energia Psiônica.', 'psi:telekinetic-movement', NULL, 6),
('fighter-psi-psychic-leap', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'psi-warrior'), 'Salto com Impulsão Psíquica', 'bonus'::rpg.action_economy_bucket, 7, 'psi-energy-dice', 'psychic-leap', false, '1× gratuito por descanso; voo = 2× deslocamento', 'Como Ação Bônus, você ganha Deslocamento de Voo igual ao dobro do seu Deslocamento até o fim do turno. O primeiro uso após um Descanso Curto ou Longo é gratuito; depois, gaste um Dado de Energia Psiônica.', 'psi:psychic-leap', NULL, 7),
('fighter-psi-mental-guard', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'psi-warrior'), 'Resguardo Mental', 'free'::rpg.action_economy_bucket, 10, 'psi-energy-dice', NULL, true, 'Gasta 1 dado: encerra Amedrontado/Enfeitiçado', 'Gaste um Dado de Energia Psiônica (nenhuma ação) para encerrar em você todos os efeitos que causam as condições Amedrontado ou Enfeitiçado. Sempre gasta um dado.', 'psi:mental-guard', NULL, 8),
('fighter-psi-energy-bulwark', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'psi-warrior'), 'Baluarte de Energia', 'bonus'::rpg.action_economy_bucket, 15, 'psi-energy-dice', 'energy-bulwark', false, '1× gratuito por descanso longo; Cobertura Parcial', 'Conceda Cobertura Parcial por 1 minuto a até o seu modificador de Inteligência em criaturas (mínimo 1). O primeiro uso após um Descanso Longo é gratuito; depois, gaste um Dado de Energia Psiônica.', 'psi:energy-bulwark', NULL, 9),
('fighter-psi-telekinetic-master', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'psi-warrior'), 'Mestre Telecinético', 'free'::rpg.action_economy_bucket, 18, 'psi-energy-dice', 'telekinetic-master', false, '1× gratuito por descanso longo; Telecinese', 'Conjure Telecinese sem espaço nem componentes (INT é o atributo). O primeiro uso após um Descanso Longo é gratuito; depois, gaste um Dado de Energia Psiônica.', 'psi:telekinetic-master', NULL, 10),
('fighter-bm-lunging-attack', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'battle-master'), 'Ataque Estendido', 'bonus'::rpg.action_economy_bucket, 3, 'superiority-dice', NULL, false, 'Manobra: Correr e potencializar ataque', 'Manobra do Mestre de Batalha. Gaste um dado de superioridade para potencializar um ataque com alcance ou movimento extra conforme a manobra escolhida (veja o texto completo da manobra na aba de poderes).', NULL, NULL, 11),
('fighter-bm-rally', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'battle-master'), 'Reunir', 'bonus'::rpg.action_economy_bucket, 3, 'superiority-dice', NULL, false, 'Manobra: PV temporários a um aliado', 'Como Ação Bônus, gaste um dado de superioridade para conceder pontos de vida temporários a um aliado. O aliado ganha PV temporários iguais ao resultado do dado + seu modificador de Carisma.', NULL, NULL, 12),
('fighter-bm-feinting-attack', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'battle-master'), 'Ataque Fintado', 'bonus'::rpg.action_economy_bucket, 3, 'superiority-dice', NULL, false, 'Manobra: Vantagem no próximo ataque', 'Como Ação Bônus, gaste um dado de superioridade para fintar: você ganha Vantagem no próximo ataque contra o alvo neste turno e adiciona o dado ao dano se acertar.', NULL, NULL, 13),
('fighter-bm-parry', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'battle-master'), 'Aparar', 'reaction'::rpg.action_economy_bucket, 3, 'superiority-dice', NULL, false, 'Manobra: reduzir dano corpo a corpo', 'Quando você é atingido por um ataque corpo a corpo, use sua Reação e gaste um dado de superioridade para reduzir o dano sofrido pelo resultado do dado + seu modificador de Destreza.', NULL, NULL, 14),
('fighter-bm-riposte', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'battle-master'), 'Repostagem', 'reaction'::rpg.action_economy_bucket, 3, 'superiority-dice', NULL, false, 'Manobra: contra-ataque ao ser errado', 'Quando uma criatura erra um ataque corpo a corpo contra você, use sua Reação para gastar um dado de superioridade e fazer um ataque com arma contra ela, adicionando o dado ao dano se acertar.', NULL, NULL, 15),
('rogue-cunning-action', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), NULL, 'Ação Ardilosa', 'bonus'::rpg.action_economy_bucket, 2, NULL, NULL, false, 'Correr, Desengajar ou Esconder', NULL, NULL, NULL, 16),
('rogue-uncanny-dodge', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), NULL, 'Esquiva Sobrenatural', 'reaction'::rpg.action_economy_bucket, 5, NULL, NULL, false, 'Metade do dano de um ataque que o acertou', NULL, NULL, NULL, 17),
('rogue-soulknife-second-blade', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'soulknife'), 'Segunda Lâmina Psíquica', 'bonus'::rpg.action_economy_bucket, 3, NULL, NULL, false, 'Ataque com a segunda lâmina (1d4)', NULL, NULL, NULL, 18),
('rogue-psychic-teleportation', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'soulknife'), 'Teleporte Psíquico', 'bonus'::rpg.action_economy_bucket, 9, 'soulknife-psi-dice', NULL, false, 'Teleporte gastando dado psiônico', NULL, NULL, NULL, 19),
('rogue-spell-thief', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'arcane-trickster'), 'Ladrão de Magias', 'reaction'::rpg.action_economy_bucket, 17, 'spell-thief', NULL, false, 'Negar e roubar uma magia', NULL, NULL, NULL, 20),
('barbarian-rage', (SELECT id FROM rpg.phb_class WHERE slug = 'barbarian'), NULL, 'Fúria', 'bonus'::rpg.action_economy_bucket, 1, 'rage', NULL, false, 'Entrar em Fúria', NULL, NULL, NULL, 21),
('barbarian-reckless', (SELECT id FROM rpg.phb_class WHERE slug = 'barbarian'), NULL, 'Ataque Imprudente', 'free'::rpg.action_economy_bucket, 2, NULL, NULL, false, 'No seu turno, ao atacar: Vantagem (e ataques contra você também)', NULL, NULL, NULL, 22),
('monk-flurry', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), NULL, 'Torrente de Golpes', 'bonus'::rpg.action_economy_bucket, 2, 'focusPoints', NULL, false, 'Dois ataques desarmados (gasta Foco)', NULL, NULL, NULL, 23),
('monk-patient-defense', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), NULL, 'Defesa Paciente', 'bonus'::rpg.action_economy_bucket, 2, 'focusPoints', NULL, false, 'Esquivar (gasta Foco)', NULL, NULL, NULL, 24),
('monk-step-of-the-wind', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), NULL, 'Passo do Vento', 'bonus'::rpg.action_economy_bucket, 2, 'focusPoints', NULL, false, 'Correr ou Desengajar; salto dobrado (gasta Foco)', NULL, NULL, NULL, 25),
('monk-stunning-strike', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), NULL, 'Golpe Atordoante', 'free'::rpg.action_economy_bucket, 5, 'focusPoints', NULL, false, 'Ao acertar: tentativa de Atordoar (gasta Foco)', NULL, NULL, NULL, 26),
('monk-deflect', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), NULL, 'Defletir Ataques', 'reaction'::rpg.action_economy_bucket, 3, NULL, NULL, false, 'Reduz dano de ataque corpo a corpo ou à distância', NULL, NULL, NULL, 27),
('monk-slow-fall', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), NULL, 'Queda Lenta', 'reaction'::rpg.action_economy_bucket, 4, NULL, NULL, false, 'Reduz dano de queda', NULL, NULL, NULL, 28),
('monk-hand-of-healing', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'mercy'), 'Mão de Cura', 'action'::rpg.action_economy_bucket, 3, 'focusPoints', NULL, false, 'Cura com Foco', NULL, NULL, NULL, 29),
('monk-shadow-step', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'shadow'), 'Passo da Sombra', 'bonus'::rpg.action_economy_bucket, 6, NULL, NULL, false, 'Teleporte entre sombras', NULL, NULL, NULL, 30),
('bard-inspiration', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), NULL, 'Inspiração Bárdica', 'bonus'::rpg.action_economy_bucket, 1, 'bardicInspiration', NULL, false, 'Conceder o dado a um aliado a até 18 m', NULL, NULL, NULL, 31),
('bard-cutting-words', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'lore'), 'Palavras Cortantes', 'reaction'::rpg.action_economy_bucket, 3, 'bardicInspiration', NULL, false, 'Subtrair o dado de ataque/teste/dano inimigo', NULL, NULL, NULL, 32),
('bard-agile-response', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'dance'), 'Resposta Ágil', 'reaction'::rpg.action_economy_bucket, 6, 'bardicInspiration', NULL, false, '+CA e movimento se o ataque errar', NULL, NULL, NULL, 33),
('bard-combat-inspiration', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'valor'), 'Inspiração de Combate', 'reaction'::rpg.action_economy_bucket, 3, 'bardicInspiration', NULL, false, 'Aliado soma o dado ao dano ou à CA', NULL, NULL, NULL, 34),
('bard-mantle-of-majesty', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'glamour'), 'Manto de Majestade', 'bonus'::rpg.action_economy_bucket, 6, NULL, NULL, false, 'Conjurar Comando sem gastar espaço', NULL, NULL, NULL, 35),
('bard-virtuoso-skill', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'college-of-masks'), 'Habilidade de Virtuoso', 'free'::rpg.action_economy_bucket, 6, 'virtuoso-skill', NULL, true, '1×/turno: Teste d20 com Carisma', 'Uma vez por turno, ao fazer um Teste d20, você pode fazê-lo com Carisma se ainda não usar. Gaste 1 uso (máx. = mod. de Carisma).', 'spend-resource', NULL, 36),
('paladin-lay-on-hands', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), NULL, 'Mãos Consagradas', 'bonus'::rpg.action_economy_bucket, 1, 'layOnHands', NULL, false, 'Cura da reserva (5 × nível)', NULL, NULL, NULL, 37),
('paladin-divine-sense', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), NULL, 'Sentido Divino', 'bonus'::rpg.action_economy_bucket, 1, NULL, NULL, false, 'Detectar celestiais, fiends e mortos-vivos', NULL, NULL, NULL, 38),
('paladin-protective-smite', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'devotion'), 'Destruição Protetora', 'reaction'::rpg.action_economy_bucket, 15, NULL, NULL, false, 'Reduzir dano com a Reação', NULL, NULL, NULL, 39),
('paladin-glorious-defense', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'glory'), 'Defesa Gloriosa', 'reaction'::rpg.action_economy_bucket, 15, NULL, NULL, false, 'Concede CA e contra-ataque', NULL, NULL, NULL, 40),
('ranger-hunters-mark', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), NULL, 'Marca do Predador', 'bonus'::rpg.action_economy_bucket, 1, 'favoredEnemy', NULL, false, 'Marcar alvo (uso gratuito disponível)', NULL, NULL, NULL, 41),
('ranger-natures-veil', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), NULL, 'Véu da Natureza', 'bonus'::rpg.action_economy_bucket, 14, 'naturesVeil', NULL, false, 'Tornar-se Invisível até o fim do próximo turno', NULL, NULL, NULL, 42),
('ranger-primal-companion', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'beast-master'), 'Companheiro Primal', 'bonus'::rpg.action_economy_bucket, 3, NULL, NULL, false, 'Comandar a fera', NULL, NULL, NULL, 43),
('ranger-hunter-defense', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'hunter'), 'Defesa do Caçador Superior', 'reaction'::rpg.action_economy_bucket, 15, NULL, NULL, false, 'Resistência ao dano neste turno', NULL, NULL, NULL, 44),
('ranger-gloom-stalker-dodge', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'gloom-stalker'), 'Esquiva Sombria', 'reaction'::rpg.action_economy_bucket, 15, NULL, NULL, false, 'Desvantagem no ataque e teleporte de 9 m', NULL, NULL, NULL, 45),
('ranger-beastborne-aspect', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'beastborne'), 'Aspecto Bestial (mesa)', 'bonus'::rpg.action_economy_bucket, 3, NULL, NULL, false, 'Tracker de Aspecto Bestial (0–5) na mesa', 'Ajuste o nível de Aspecto Bestial no painel do Guardião (+/− ou Uivo Feral). Benefícios acumulam: Carnificina, Velocidade, Frenesi, Pele, Retaliação. Zera no descanso longo (e após 1 min sem dano na mesa).', NULL, NULL, 46),
('cleric-channel', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), NULL, 'Canalizar Divindade', 'action'::rpg.action_economy_bucket, 2, 'channelDivinity', NULL, false, 'Centelha Divina, Expulsar Mortos-Vivos etc.', NULL, NULL, NULL, 47),
('cleric-warding-flare', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'light'), 'Labareda Protetora', 'reaction'::rpg.action_economy_bucket, 3, 'warding-flare', NULL, false, 'Desvantagem no ataque contra você', NULL, NULL, NULL, 48),
('cleric-war-priest', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'war'), 'Sacerdote da Guerra', 'bonus'::rpg.action_economy_bucket, 3, 'war-priest', NULL, false, 'Ataque com arma como Ação Bônus', NULL, NULL, NULL, 49),
('cleric-guided-strike', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'war'), 'Ataque Direcionado', 'free'::rpg.action_economy_bucket, 3, 'channelDivinity', NULL, false, 'Após errar: +10 no ataque', NULL, NULL, NULL, 50),
('cleric-dragon-majesty', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'dragon-domain'), 'Majestade Dracônica', 'action'::rpg.action_economy_bucket, 3, 'channelDivinity', NULL, true, 'Canalizar: Enfeitiçar ou Amedrontar (9 m)', 'Ação Mágica: apresente o Símbolo Sagrado e gaste Canalizar Divindade. Emanação de 9 m — Enfeitiçado ou Amedrontado (salvaguarda SAB, 1 min).', 'spend-resource', NULL, 51),
('cleric-legendary-aspect', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'dragon-domain'), 'Aspecto Lendário', 'free'::rpg.action_economy_bucket, 17, 'legendary-aspect', NULL, true, 'Ação lendária (Rasgar / Cauda / Asas)', 'Gaste 1 uso para Rasgar, Golpe de Cauda ou Batida de Asas imediatamente após o turno de outra criatura. 3 usos/LR.', 'spend-resource', NULL, 52),
('druid-wild-shape', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), NULL, 'Forma Selvagem', 'bonus'::rpg.action_economy_bucket, 2, 'wildShape', NULL, false, 'Assumir forma de besta', NULL, NULL, NULL, 53),
('druid-lunar-healing', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'moon'), 'Cura Lunar', 'bonus'::rpg.action_economy_bucket, 3, NULL, NULL, false, 'Na Forma Selvagem: gastar slot para curar', NULL, NULL, NULL, 54),
('druid-wrath-of-the-sea', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'sea'), 'Ira do Mar', 'bonus'::rpg.action_economy_bucket, 3, 'wildShape', NULL, false, 'Aura de tempestade', NULL, NULL, NULL, 55),
('druid-city-shape', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'circle-of-the-city'), 'Forma da Cidade', 'bonus'::rpg.action_economy_bucket, 3, 'wildShape', NULL, true, 'Gaste Forma Selvagem: Fundir-se / Passagem / Moldar Rocha', 'Gaste 1 uso de Forma Selvagem para conjurar Fundir-se na Pedra, Passagem ou Moldar Rocha sem espaço de magia (mesa).', 'spend-resource', NULL, 56),
('druid-wall-warp', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'circle-of-the-city'), 'Distorção de Muro', 'reaction'::rpg.action_economy_bucket, 10, 'wall-warp', NULL, true, 'Painel de Muralha de Pedra (1×/LR)', 'Reação: ao ver um ataque causar dano a até 18 m, gaste o uso para erguer um painel 3×3 m (CA 15, 30 PV) até o fim do seu próximo turno.', 'spend-resource', NULL, 57),
('sorcerer-innate-sorcery', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), NULL, 'Ira Feiticeira', 'bonus'::rpg.action_economy_bucket, 1, NULL, NULL, false, '+1 na CD e Vantagem em ataques de truque (1 min)', NULL, NULL, NULL, 58),
('sorcerer-metamagic', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), NULL, 'Metamágica', 'free'::rpg.action_economy_bucket, 2, 'sorceryPoints', NULL, false, 'Ao conjurar: gastar pontos de feitiçaria', NULL, NULL, NULL, 59),
('sorcerer-dragon-wings', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'draconic'), 'Asas Dracônicas', 'bonus'::rpg.action_economy_bucket, 14, NULL, NULL, false, 'Deslocamento de voo', NULL, NULL, NULL, 60),
('sorcerer-heroic-soul', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'heroic-sorcery'), 'Alma Heróica', 'free'::rpg.action_economy_bucket, 3, 'sorceryPoints', NULL, true, 'Início do turno: 1 SP → PV temp. 1d6 + nível', 'No início de cada um dos seus turnos, gaste 1 Ponto de Feitiçaria para ganhar PV temporários iguais a 1d6 + seu nível de Feiticeiro (sem ação).', 'spend-resource', 1, 61),
('sorcerer-mystical-maneuver', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'heroic-sorcery'), 'Manobra Mística', 'bonus'::rpg.action_economy_bucket, 14, 'sorceryPoints', NULL, true, '2 SP após acertar: Cegar / Ruinoso / Ferimento +2d8', 'Ao acertar com arma ou Ataque Desarmado, gaste 2 Pontos de Feitiçaria como Ação Bônus: +2d8 no dano e Cegar, −3 CA ou ferimento sangrando (mesa).', 'spend-resource', 2, 62),
('warlock-magical-cunning', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), NULL, 'Contato Arcano', 'bonus'::rpg.action_economy_bucket, 5, NULL, NULL, false, 'Recupera 1 Slot de Pacto (1×/Descanso Longo)', NULL, NULL, NULL, 63),
('warlock-healing-light', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'celestial'), 'Luz Curativa', 'bonus'::rpg.action_economy_bucket, 3, 'healing-light', NULL, false, 'Cura com reserva de d6s', NULL, NULL, NULL, 64),
('warlock-dark-ones-luck', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'fiend'), 'Sorte do Próprio Inferno', 'free'::rpg.action_economy_bucket, 3, 'dark-ones-own-luck', NULL, false, '+1d10 em teste ou salvaguarda', NULL, NULL, NULL, 65),
('wizard-improved-illusions', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'illusionist'), 'Ilusão Aprimorada', 'bonus'::rpg.action_economy_bucket, 3, NULL, NULL, false, 'Conjurar ilusões como Ação Bônus (sem componente V)', NULL, NULL, NULL, 66),
('wizard-mm-free', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'magic-missile-mage'), 'Mísseis Mágicos Gratuitos', 'action'::rpg.action_economy_bucket, 3, 'magic-missile-free', NULL, true, 'Conjura Mísseis sem espaço (gasta 1 uso)', $mm_free$Na ficha, Conjurar gasta 1 uso gratuito e conjura Mísseis Mágicos sem espaço. Dardos extras e penetração entram na nota de mesa.

Sábio dos Mísseis Mágicos. Adicione a magia Mísseis Mágicos ao seu grimório gratuitamente. Sua expertise nesta magia concede os seguintes benefícios.

Dardos Extra. Quando você conjura Mísseis Mágicos, cria um dardo extra de força mágica. Você cria dois dardos extras no nível 6 de Mago, três dardos extras no nível 10 de Mago e quatro dardos extras no nível 14 de Mago.

Conjuração Livre. Você pode conjurar Mísseis Mágicos sem um espaço de magia. Você pode fazer isso um número de vezes igual ao seu modificador de Inteligência (mínimo de uma vez). Você recupera um uso gasto ao terminar um Descanso Curto e recupera todos os usos gastos ao terminar um Descanso Longo.

Dardos Penetrantes. Seus dardos de Mísseis Mágicos ignoram qualquer efeito, como a magia Escudo, que bloqueie especificamente a magia Mísseis Mágicos.$mm_free$, 'cast:misseis-magicos-free', NULL, 67),
('wizard-mm-versatile', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'magic-missile-mage'), 'Mísseis Versáteis', 'free'::rpg.action_economy_bucket, 6, NULL, NULL, false, 'Ao conjurar: Tombo 1 / Cegar 3 / Atordoar 5 dardos', $mm_vers$Você pode guiar com precisão seus dardos de Mísseis Mágicos para atingir um alvo onde escolher. Quando você conjura Mísseis Mágicos, pode adicionar um dos seguintes efeitos de Míssil Versátil a um alvo atingido pelos dardos. Cada efeito tem um custo, que é o número de dardos que você deve abrir mão para adicionar o efeito ao alvo. Você pode adicionar efeitos diferentes a alvos diferentes, pagando o custo de cada efeito separadamente.

Míssil de Tombo (Custo: 1 Dardo). O alvo deve ser bem-sucedido em uma salvaguarda de Força contra sua CD de magia ou ter a condição Caído.

Míssil Cegante (Custo: 3 Dardos). O alvo deve ser bem-sucedido em uma salvaguarda de Constituição contra sua CD de magia ou ter a condição Cego até o início do seu próximo turno.

Míssil Atordoante (Custo: 5 Dardos). O alvo deve ser bem-sucedido em uma salvaguarda de Constituição contra sua CD de magia ou ter a condição Atordoado até o início do seu próximo turno.$mm_vers$, NULL, NULL, 68),
('wizard-missile-shield', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'magic-missile-mage'), 'Escudo de Mísseis', 'free'::rpg.action_economy_bucket, 10, 'missile-shield', NULL, true, 'Armar para o próximo cast (gasta o uso no cast)', $mm_shield$Arme na ficha antes de conjurar Mísseis Mágicos. O uso é gasto no cast (ou restaure com espaço de 3º+).

Quando você conjura Mísseis Mágicos, pode direcionar os dardos em uma órbita apertada ao seu redor, criando uma Emanação protetora de 3 m originada de você, que dura até 1 minuto.

Você ganha um bônus na sua Classe de Armadura igual ao número de dardos orbitando você (bônus máximo de +5). Sempre que uma criatura a até 36 m errar você com uma jogada de ataque, um dardo atinge o atacante, causando dano normalmente e diminuindo em um o número de dardos orbitando você.

Sempre que a Emanação entrar no espaço de uma criatura que você possa ver e sempre que uma criatura que você possa ver entrar na Emanação ou terminar seu turno nela, você pode atingir o alvo com qualquer número de dardos orbitando você, causando dano normalmente e diminuindo o número de dardos orbitando você. Você só pode causar dano a uma criatura com a Emanação uma vez por turno.

Depois de usar este recurso, você não pode usá-lo novamente até terminar um Descanso Longo. Você também pode restaurar seu uso gastando um espaço de magia de nível 3+ (nenhuma ação necessária).$mm_shield$, 'arm:missile-shield', NULL, 69),
('wizard-giga-missile', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'magic-missile-mage'), 'Giga-Míssil', 'free'::rpg.action_economy_bucket, 14, 'giga-missile', NULL, true, 'Armar para o próximo cast (+mod. INT por dardo)', $mm_giga$Arme na ficha antes de conjurar Mísseis Mágicos. O uso é gasto no cast (ou restaure com espaço de 6º+).

Quando você conjura Mísseis Mágicos, pode aprimorar o dano da magia. Você causa dano de Força extra com cada dardo igual ao seu modificador de Inteligência (mínimo de 1).

Depois de usar este recurso, você não pode usá-lo novamente até terminar um Descanso Longo. Você também pode restaurar seu uso gastando um espaço de magia de nível 6+ (nenhuma ação necessária).$mm_giga$, 'arm:giga-missile', NULL, 70),
('gunslinger-bullet-time', (SELECT id FROM rpg.phb_class WHERE slug = 'gunslinger'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'pistolero'), 'Tempo Bala', 'free'::rpg.action_economy_bucket, 14, NULL, NULL, false, '1×/turno: Vantagem em um ataque à distância com arma', 'Uma vez em cada um dos seus turnos, ao fazer um ataque à distância com arma, você pode ter Vantagem na jogada (mesa).', NULL, NULL, 71)
ON CONFLICT (action_id) DO UPDATE SET
  class_id = EXCLUDED.class_id,
  subclass_id = EXCLUDED.subclass_id,
  name = EXCLUDED.name,
  economy = EXCLUDED.economy,
  unlock_level = EXCLUDED.unlock_level,
  resource_slug = EXCLUDED.resource_slug,
  free_resource_slug = EXCLUDED.free_resource_slug,
  always_spends_resource = EXCLUDED.always_spends_resource,
  summary = EXCLUDED.summary,
  description = EXCLUDED.description,
  table_action = EXCLUDED.table_action,
  spend_amount = EXCLUDED.spend_amount,
  sort_order = EXCLUDED.sort_order;
