-- Seed: Class economy actions (UI Actions tab)
-- Catálogo SSOT com C010 (painel). Recursos mago: C014.

INSERT INTO rpg.phb_class_economy_action (
  action_id, class_id, subclass_id, name, economy, unlock_level,
  resource_slug, free_resource_slug, always_spends_resource,
  summary, description, table_action, spend_amount, sort_order
) VALUES
('fighter-second-wind', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), NULL, 'Recuperar Fôlego', 'bonus'::rpg.action_economy_bucket, 1, 'secondWind', NULL, false, 'Cura 1d10 + nível de Guerreiro', 'Como Ação Bônus, você pode recuperar pontos de vida iguais a 1d10 + seu nível de Guerreiro. Você tem um número limitado de usos; recupere-os ao terminar um Descanso Curto ou Longo.', 'second-wind', NULL, 1),
('fighter-action-surge', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), NULL, 'Surto de Ação', 'action'::rpg.action_economy_bucket, 2, 'actionSurge', NULL, false, 'Concede uma ação adicional neste turno', 'No seu turno, você pode se esforçar além do normal e ganhar uma Ação adicional. Depois de usar Surto de Ação, você precisa terminar um Descanso Curto ou Longo para usá-lo de novo (em níveis altos, pode ter mais usos).', 'action-surge', NULL, 2),
('fighter-tactical-mind', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), NULL, 'Mente Tática', 'free'::rpg.action_economy_bucket, 2, 'secondWind', NULL, false, 'Ao falhar em teste: +1d10 (gasta Fôlego só se virar sucesso)', 'Quando você falha em um teste de habilidade, você pode gastar um uso de Recuperar Fôlego para rolar 1d10 e somar ao resultado. Se o teste ainda falhar, o uso de Recuperar Fôlego não é gasto.', 'tactical-mind', NULL, 3),
('fighter-indomitable', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), NULL, 'Indomável', 'free'::rpg.action_economy_bucket, 9, 'indomitable', NULL, false, 'Ao falhar salvaguarda: rerrola com +nível', 'Se você falhar em uma salvaguarda, pode rerrolá-la com um bônus igual ao seu nível de Guerreiro. Você deve usar o novo resultado. Usos limitados; recupere-os ao terminar um Descanso Longo. Na ficha, marque a opção Indomável ao rolar a salvaguarda.', NULL, NULL, 4),
('fighter-psi-protective-field', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'psi-warrior'), 'Campo Protetor', 'reaction'::rpg.action_economy_bucket, 3, 'psi-energy-dice', NULL, true, 'Reação: reduz dano com 1 dado psi + INT', 'Quando você ou uma criatura que você possa ver a até 9 metros sofrer dano, use sua Reação e gaste um Dado de Energia Psiônica: reduza o dano pelo resultado do dado + seu modificador de Inteligência. Sempre gasta um dado (não tem uso gratuito).', 'psi:protective-field', NULL, 5),
('fighter-psi-telekinetic-movement', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'psi-warrior'), 'Movimento Telecinético', 'action'::rpg.action_economy_bucket, 3, 'psi-energy-dice', 'telekinetic-movement', false, '1× gratuito por descanso; depois gasta 1 dado psi', 'Mova um objeto solto ou uma criatura voluntária conforme a característica. O primeiro uso após um Descanso Curto ou Longo é gratuito; usos extras gastam um Dado de Energia Psiônica.', 'psi:telekinetic-movement', NULL, 6),
('fighter-psi-psychic-leap', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'psi-warrior'), 'Salto com Impulsão Psíquica', 'bonus'::rpg.action_economy_bucket, 7, 'psi-energy-dice', 'psychic-leap', false, '1× gratuito por descanso; voo = 2× deslocamento', 'Como Ação Bônus, você ganha Deslocamento de Voo igual ao dobro do seu Deslocamento até o fim do turno. O primeiro uso após um Descanso Curto ou Longo é gratuito; depois, gaste um Dado de Energia Psiônica.', 'psi:psychic-leap', NULL, 7),
('fighter-psi-mental-guard', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'psi-warrior'), 'Resguardo Mental', 'free'::rpg.action_economy_bucket, 10, 'psi-energy-dice', NULL, true, 'Gasta 1 dado: encerra Amedrontado/Enfeitiçado', 'Gaste um Dado de Energia Psiônica (nenhuma ação) para encerrar em você todos os efeitos que causam as condições Amedrontado ou Enfeitiçado. Sempre gasta um dado.', 'psi:mental-guard', NULL, 8),
('fighter-psi-energy-bulwark', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'psi-warrior'), 'Baluarte de Energia', 'bonus'::rpg.action_economy_bucket, 15, 'psi-energy-dice', 'energy-bulwark', false, '1× gratuito por descanso longo; Cobertura Parcial', 'Conceda Cobertura Parcial por 1 minuto a até o seu modificador de Inteligência em criaturas (mínimo 1). O primeiro uso após um Descanso Longo é gratuito; depois, gaste um Dado de Energia Psiônica.', 'psi:energy-bulwark', NULL, 9),
('fighter-psi-telekinetic-master', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'psi-warrior'), 'Mestre Telecinético', 'free'::rpg.action_economy_bucket, 18, 'psi-energy-dice', 'telekinetic-master', false, '1× gratuito por descanso longo; Telecinese', 'Conjure Telecinese sem espaço nem componentes (INT é o atributo). O primeiro uso após um Descanso Longo é gratuito; depois, gaste um Dado de Energia Psiônica.', 'psi:telekinetic-master', NULL, 10),
('fighter-bm-lunging-attack', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'battle-master'), 'Ataque Estendido', 'bonus'::rpg.action_economy_bucket, 3, 'superiority-dice', NULL, false, 'Manobra: Correr e potencializar ataque', 'Manobra do Mestre de Batalha. Gaste um dado de superioridade para potencializar um ataque com alcance ou movimento extra conforme a manobra escolhida (veja o texto completo da manobra na aba de poderes).', NULL, NULL, 11),
('fighter-bm-rally', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'battle-master'), 'Reunir', 'bonus'::rpg.action_economy_bucket, 3, 'superiority-dice', NULL, false, 'Manobra: PV temporários a um aliado', 'Como Ação Bônus, gaste um dado de superioridade para conceder pontos de vida temporários a um aliado. O aliado ganha PV temporários iguais ao resultado do dado + seu modificador de Carisma.', NULL, NULL, 12),
('fighter-bm-feinting-attack', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'battle-master'), 'Ataque Fintado', 'bonus'::rpg.action_economy_bucket, 3, 'superiority-dice', NULL, false, 'Manobra: Vantagem no próximo ataque', 'Como Ação Bônus, gaste um dado de superioridade para fintar: você ganha Vantagem no próximo ataque contra o alvo neste turno e adiciona o dado ao dano se acertar.', NULL, NULL, 13),
('fighter-bm-parry', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'battle-master'), 'Aparar', 'reaction'::rpg.action_economy_bucket, 3, 'superiority-dice', NULL, false, 'Manobra: reduzir dano corpo a corpo', 'Quando você é atingido por um ataque corpo a corpo, use sua Reação e gaste um dado de superioridade para reduzir o dano sofrido pelo resultado do dado + seu modificador de Destreza.', NULL, NULL, 14),
('fighter-bm-riposte', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'battle-master'), 'Repostagem', 'reaction'::rpg.action_economy_bucket, 3, 'superiority-dice', NULL, false, 'Manobra: contra-ataque ao ser errado', 'Quando uma criatura erra um ataque corpo a corpo contra você, use sua Reação para gastar um dado de superioridade e fazer um ataque com arma contra ela, adicionando o dado ao dano se acertar.', NULL, NULL, 15),
('rogue-cunning-action', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), NULL, 'Ação Ardilosa', 'bonus'::rpg.action_economy_bucket, 2, NULL, NULL, false, 'Correr, Desengajar ou Esconder', NULL, NULL, NULL, 16),
('rogue-uncanny-dodge', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), NULL, 'Esquiva Sobrenatural', 'reaction'::rpg.action_economy_bucket, 5, NULL, NULL, false, 'Metade do dano de um ataque que o acertou', NULL, NULL, NULL, 17),
('rogue-soulknife-second-blade', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'soulknife'), 'Segunda Lâmina Psíquica', 'bonus'::rpg.action_economy_bucket, 3, NULL, NULL, false, 'Ação Bônus: card Lâmina Psíquica (adicional) na ficha', 'Use o card de ataque Lâmina Psíquica (adicional) na aba Ações — 1d4 Psíquico, com Furtivo/Golpe Astuto.', NULL, NULL, 18),
('rogue-soulknife-psi-dice', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'soulknife'), 'Poder Psiônico', 'free'::rpg.action_economy_bucket, 3, 'soulknife-psi-dice', NULL, false, 'Pool de Dados de Energia (Adaga Espiritual)', 'Controle do pool de dados psiônicos na mesa. Gastos vêm das ações Soulknife (Sussurros, Teleporte, Véu, Rasgar Mente, Aptidão, Golpe Teleguiado).', NULL, NULL, 19),
('rogue-psychic-whispers', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'soulknife'), 'Sussurros Psíquicos', 'action'::rpg.action_economy_bucket, 3, 'psychic-whispers', NULL, false, 'Listagem: 1× gratuito / DL (depois dado psi no painel)', 'Aparece na Economia/painel para gastar o uso. Duração da ligação = nota na mesa (sem tracker).', 'psychic-whispers', NULL, 20),
('rogue-psychic-teleportation', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'soulknife'), 'Teleporte Psíquico', 'bonus'::rpg.action_economy_bucket, 9, 'soulknife-psi-dice', NULL, true, 'Teleporte gastando 1 dado psiônico', 'Como Ação Bônus, gaste 1 Dado de Energia: teleporte até (resultado × 3) m para um espaço visível e desocupado.', 'psychic-teleport', NULL, 21),
('rogue-psychic-veil', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'soulknife'), 'Véu Psíquico', 'action'::rpg.action_economy_bucket, 13, 'psychic-veil', NULL, false, '1× gratuito / DL (uso pré-estabelecido; depois 1 dado psi)', 'Uso gratuito no pool psychic-veil; gaste no Usar/painel. Invisível até 1 h = nota na mesa (sem tracker de duração).', 'psychic-veil', NULL, 22),
('rogue-rend-mind', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'soulknife'), 'Rasgar Mente', 'free'::rpg.action_economy_bucket, 17, 'rend-mind', NULL, false, 'Listagem: 1× gratuito (depois 3 dados psi no painel)', 'Aparece na Economia/painel para gastar o uso. Atordoado no alvo = nota/salvaguarda na mesa.', 'rend-mind', NULL, 23),
('rogue-spell-thief', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'arcane-trickster'), 'Ladrão de Magias', 'reaction'::rpg.action_economy_bucket, 17, 'spell-thief', NULL, true, 'Negar e roubar uma magia', 'Como Reação, gaste o uso para negar e roubar uma magia (mesa).', 'spell-thief', NULL, 24),
('rogue-arachnoid-web', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'arachnoid-stalker'), 'Correia / Teia', 'bonus'::rpg.action_economy_bucket, 3, 'arachnoid-web', NULL, true, 'Teias para movimento, objetos, corda ou magia Teia', 'Gaste 1 uso de Correia Aracnóide para criar teia/correia (mesa: posição e condição).', 'arachnoid-web', NULL, 25),
('rogue-stroke-of-luck', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), NULL, 'Golpe de Sorte', 'free'::rpg.action_economy_bucket, 20, 'strokeOfLuck', NULL, false, 'Transforma falha em 20 (1×/DL)', 'Ao falhar em um Teste de D20, transforme o resultado em 20. Marque o gasto na rolagem (ataque, perícia, iniciativa, salvaguarda). Contador na Economia.', NULL, NULL, 26),
('barbarian-rage', (SELECT id FROM rpg.phb_class WHERE slug = 'barbarian'), NULL, 'Fúria', 'bonus'::rpg.action_economy_bucket, 1, 'rage', NULL, false, 'Entrar em Fúria', NULL, NULL, NULL, 21),
('barbarian-reckless', (SELECT id FROM rpg.phb_class WHERE slug = 'barbarian'), NULL, 'Ataque Imprudente', 'free'::rpg.action_economy_bucket, 2, NULL, NULL, false, 'No seu turno, ao atacar: Vantagem (e ataques contra você também)', NULL, NULL, NULL, 22),
('monk-flurry', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), NULL, 'Torrente de Golpes', 'bonus'::rpg.action_economy_bucket, 2, 'focusPoints', NULL, false, 'Dois ataques desarmados (gasta Foco)', NULL, NULL, NULL, 23),
('monk-patient-defense', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), NULL, 'Defesa Paciente', 'bonus'::rpg.action_economy_bucket, 2, 'focusPoints', NULL, false, 'Esquivar (gasta Foco)', NULL, NULL, NULL, 24),
('monk-step-of-the-wind', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), NULL, 'Passos do Vento', 'bonus'::rpg.action_economy_bucket, 2, 'focusPoints', NULL, false, 'Correr ou Desengajar; salto dobrado (gasta Foco)', NULL, NULL, NULL, 25),
('monk-stunning-strike', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), NULL, 'Golpe Atordoante', 'free'::rpg.action_economy_bucket, 5, 'focusPoints', NULL, false, 'Ao acertar: tentativa de Atordoar (gasta Foco)', NULL, NULL, NULL, 26),
('monk-deflect', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), NULL, 'Defletir Ataques', 'reaction'::rpg.action_economy_bucket, 3, NULL, NULL, false, 'Reduz dano de ataque corpo a corpo ou à distância', NULL, NULL, NULL, 27),
('monk-slow-fall', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), NULL, 'Queda Lenta', 'reaction'::rpg.action_economy_bucket, 4, NULL, NULL, false, 'Reduz dano de queda', NULL, NULL, NULL, 28),
('monk-hand-of-healing', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'mercy'), 'Mão de Cura', 'action'::rpg.action_economy_bucket, 3, 'focusPoints', NULL, false, 'Cura com Foco', NULL, NULL, NULL, 29),
('monk-shadow-step', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'shadow'), 'Passo da Sombra', 'bonus'::rpg.action_economy_bucket, 6, NULL, NULL, false, 'Teleporte entre sombras', NULL, NULL, NULL, 30),
('bard-inspiration', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), NULL, 'Inspiração de Bardo', 'bonus'::rpg.action_economy_bucket, 1, 'bardicInspiration', NULL, false, 'Conceder o dado a um aliado a até 18 m', NULL, NULL, NULL, 31),
('bard-cutting-words', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'lore'), 'Palavras de Interrupção', 'reaction'::rpg.action_economy_bucket, 3, 'bardicInspiration', NULL, false, 'Subtrair o dado de ataque/teste/dano inimigo', NULL, NULL, NULL, 32),
('bard-agile-response', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'dance'), 'Movimento Inspirador', 'reaction'::rpg.action_economy_bucket, 6, 'bardicInspiration', NULL, false, 'Reação: mover metade do Deslocamento (você + aliado)', NULL, NULL, NULL, 33),
('bard-combat-inspiration', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'valor'), 'Inspiração em Combate', 'reaction'::rpg.action_economy_bucket, 3, 'bardicInspiration', NULL, false, 'Aliado soma o dado ao dano ou à CA', NULL, NULL, NULL, 34),
('bard-mantle-of-majesty', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'glamour'), 'Manto de Majestade', 'bonus'::rpg.action_economy_bucket, 6, NULL, NULL, false, 'Conjurar Comando sem gastar espaço', NULL, NULL, NULL, 35),
('bard-virtuoso-skill', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'college-of-masks'), 'Habilidade de Virtuoso', 'free'::rpg.action_economy_bucket, 6, 'virtuoso-skill', NULL, true, '1×/turno: Teste d20 com Carisma', 'Uma vez por turno, ao fazer um Teste d20, você pode fazê-lo com Carisma se ainda não usar. Gaste 1 uso (máx. = mod. de Carisma).', 'spend-resource', NULL, 36),
('paladin-lay-on-hands', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), NULL, 'Mãos Consagradas', 'bonus'::rpg.action_economy_bucket, 1, 'layOnHands', NULL, false, 'Cura da reserva (5 × nível)', 'Como Ação Bônus, toque uma criatura e gaste pontos da reserva de Mãos Consagradas para restaurar essa quantidade de PV. A reserva máxima é 5 × seu nível de Paladino; recupere todos os pontos ao terminar um Descanso Longo. Use o painel do Paladino para escolher a quantidade.', 'lay-on-hands', NULL, 37),
('paladin-channel', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), NULL, 'Canalizar Divindade', 'free'::rpg.action_economy_bucket, 3, 'channelDivinity', NULL, false, 'Pool de Canalizar Divindade', 'Controle ± dos usos de Canalizar Divindade. Gastos vêm de Sentido Divino, opções do Juramento e Repudiar Inimigos. Recupere 1 uso num Descanso Curto e todos num Descanso Longo (mais usos em níveis altos).', NULL, NULL, 38),
('paladin-divine-sense', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), NULL, 'Sentido Divino', 'bonus'::rpg.action_economy_bucket, 3, 'channelDivinity', NULL, true, 'Detectar celestiais, ínferos e mortos-vivos', 'Como Ação Bônus, gaste 1 uso de Canalizar Divindade. Por até 10 minutos, você sente a localização de qualquer Celestial, Ínfero ou Morto-Vivo a até 18 m que não esteja sob Cobertura Total, e locais/objetos consagrados ou profanados (como Hallow).', 'divine-sense', NULL, 39),
('paladin-sacred-weapon', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'devotion'), 'Arma Sagrada', 'free'::rpg.action_economy_bucket, 3, 'channelDivinity', NULL, true, 'Na ação Atacar: +Carisma e luz', 'Ao executar a ação Atacar, gaste 1 Canalizar Divindade para imbuir uma arma corpo a corpo que você empunha. Por 10 minutos (ou até usar de novo / largar a arma): some o mod. de Carisma (mín. +1) às jogadas de ataque com ela; nos acertos, o dano pode ser do tipo normal ou Radiante; emite Luz Plena em 6 m e Luz Fraca em +6 m. Você pode encerrar o efeito sem ação.', 'oath-channel', NULL, 40),
('paladin-aura-of-devotion', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'devotion'), 'Aura de Devoção', 'free'::rpg.action_economy_bucket, 7, NULL, NULL, false, 'Imunidade a Enfeitiçado na aura', 'Você e aliados têm Imunidade à condição Enfeitiçado enquanto estiverem em sua Aura de Proteção. Se um aliado Enfeitiçado entrar na aura, a condição não tem efeito enquanto ele permanecer nela.', NULL, NULL, 41),
('paladin-protective-smite', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'devotion'), 'Destruição Protetora', 'free'::rpg.action_economy_bucket, 15, NULL, NULL, false, 'Destruição Divina → Cobertura Parcial na aura', 'Ao conjurar Destruição Divina, você e seus aliados têm Cobertura Parcial enquanto estiverem em sua Aura de Proteção. A aura mantém este benefício até o início do seu próximo turno.', NULL, NULL, 42),
('paladin-holy-nimbus', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'devotion'), 'Resplendor Sagrado', 'bonus'::rpg.action_economy_bucket, 20, 'holy-nimbus', NULL, true, 'Aura sagrada por 10 min (1×/DL)', 'Como Ação Bônus, imbuir a Aura de Proteção por 10 minutos (ou até encerrar). 1×/Descanso Longo (ou gaste um espaço de 5º). Inimigos que iniciam o turno na aura sofrem dano Radiante igual ao mod. de Carisma + PB; a aura tem Luz Plena (luz solar); Vantagem em salvaguardas forçadas por Ínferos ou Mortos-Vivos.', 'spend-resource', NULL, 43),
('paladin-inspiring-smite', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'glory'), 'Destruição Inspiradora', 'bonus'::rpg.action_economy_bucket, 3, 'channelDivinity', NULL, true, 'Após Destruição Divina: rola PV temp', 'Imediatamente após conjurar Destruição Divina, gaste 1 Canalizar Divindade. Role 2d8 + seu nível de Paladino e distribua esses PV temporários entre você e criaturas a até 9 m. O Usar rola o total e aplica na ficha (ajuste se dividir na mesa).', 'inspiring-smite', NULL, 44),
('paladin-peerless-athlete', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'glory'), 'Atleta Inigualável', 'bonus'::rpg.action_economy_bucket, 3, 'channelDivinity', NULL, true, 'Vantagem em Atletismo/Acrobacia (1 h)', 'Como Ação Bônus, gaste 1 Canalizar Divindade. Por 1 hora: Vantagem em testes de Força (Atletismo) e Destreza (Acrobacia); Saltos Longos e em Altura aumentam em 3 m (custa movimento normal).', 'peerless-athlete', NULL, 45),
('paladin-aura-of-alacrity', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'glory'), 'Aura de Vivacidade', 'free'::rpg.action_economy_bucket, 7, NULL, NULL, false, '+3 m de deslocamento (você e aura)', 'Seu Deslocamento aumenta em 3 m. Além disso, quando um aliado entra na Aura de Proteção pela 1ª vez num turno ou inicia o turno nela, o Deslocamento dele aumenta em 3 m até o fim do próximo turno dele.', NULL, NULL, 46),
('paladin-glorious-defense', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'glory'), 'Defesa Gloriosa', 'reaction'::rpg.action_economy_bucket, 15, 'glorious-defense', NULL, false, 'Reação: +CA (Carisma) e possível contra-ataque', 'Quando você ou outra criatura à sua vista a até 3 m é atingida por uma jogada de ataque, use a Reação e gaste 1 uso: conceda bônus à CA do alvo contra esse ataque igual ao seu mod. de Carisma (mín. +1), podendo fazer o ataque errar. Se errar e o atacante estiver no alcance da sua arma, você pode atacar com uma arma como parte desta Reação. Usos = mod. de Carisma (mín. 1)/Descanso Longo — marque no contador ±.', NULL, NULL, 47),
('paladin-living-legend', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'glory'), 'Lenda Viva', 'bonus'::rpg.action_economy_bucket, 20, 'living-legend', NULL, true, 'Presença lendária por 10 min (1×/DL)', 'Como Ação Bônus, receba os benefícios por 10 minutos. 1×/Descanso Longo (ou gaste um espaço de 5º). Carismático: Vantagem em testes de Carisma. Golpe Infalível: 1×/seu turno, ao errar ataque com arma, transforme em acerto. Jogar Novamente a Salvaguarda: se falhar numa salvaguarda, Reação para rerrolar (use o novo resultado).', 'spend-resource', NULL, 48),
('paladin-natures-wrath', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'ancients'), 'A Ira da Natureza', 'action'::rpg.action_economy_bucket, 3, 'channelDivinity', NULL, true, 'Canalizar: videiras Contêm (4,5 m)', 'Como ação Usar Magia, gaste 1 Canalizar Divindade. Cada criatura à sua escolha que você possa ver a até 4,5 m deve passar numa salvaguarda de Força ou fica Contida por 1 minuto. A criatura Contida repete a salvaguarda no fim de cada turno dela, encerrando o efeito em sucesso.', 'oath-channel', NULL, 49),
('paladin-aura-of-warding', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'ancients'), 'Aura de Resistência', 'free'::rpg.action_economy_bucket, 7, NULL, NULL, false, 'Resistência a Necrótico, Psíquico e Radiante', 'Você e aliados têm Resistência a dano Necrótico, Psíquico e Radiante enquanto estiverem em sua Aura de Proteção.', NULL, NULL, 50),
('paladin-undying-sentinel', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'ancients'), 'Sentinela Imortal', 'free'::rpg.action_economy_bucket, 15, 'undying-sentinel', NULL, false, 'A 0 PV: fica com 1 + cura (3× nível)', 'Ao ser reduzido a 0 PV e não morto imediatamente, você fica com 1 PV e recupera PV iguais a 3 × seu nível de Paladino. 1×/Descanso Longo (contador ±). Você também não envelhece magicamente.', NULL, NULL, 51),
('paladin-elder-champion', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'ancients'), 'Campeão Ancestral', 'bonus'::rpg.action_economy_bucket, 20, 'elder-champion', NULL, true, 'Aura ancestral por 1 min (1×/DL)', 'Como Ação Bônus, imbuir a Aura de Proteção por 1 minuto. 1×/Descanso Longo (ou espaço de 5º). Inimigos na aura têm Desvantagem em salvaguardas contra suas magias e Canalizar Divindade; magias de ação podem ser conjuradas como Ação Bônus; no início de cada turno você recupera 10 PV.', 'spend-resource', NULL, 52),
('paladin-vow-of-enmity', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'vengeance'), 'Voto de Inimizade', 'free'::rpg.action_economy_bucket, 3, 'channelDivinity', NULL, true, 'Na ação Atacar: Vantagem vs 1 alvo', 'Ao executar a ação Atacar, gaste 1 Canalizar Divindade e escolha uma criatura à vista a até 9 m. Você tem Vantagem nas jogadas de ataque contra ela por 1 minuto ou até usar de novo. Se ela cair a 0 PV antes do fim, você pode transferir o voto a outra criatura a até 9 m (sem ação).', 'oath-channel', NULL, 53),
('paladin-relentless-avenger', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'vengeance'), 'Vingador Implacável', 'free'::rpg.action_economy_bucket, 7, NULL, NULL, false, 'Ao acertar AO: Desloc. 0 + metade do movimento', 'Ao atingir uma criatura com um Ataque de Oportunidade, você pode reduzir o Deslocamento dela a 0 até o fim do turno atual e então se mover até metade do seu Deslocamento como parte da mesma Reação. Esse movimento não provoca Ataques de Oportunidade.', NULL, NULL, 54),
('paladin-soul-of-vengeance', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'vengeance'), 'Alma Vingativa', 'reaction'::rpg.action_economy_bucket, 15, NULL, NULL, false, 'Reação: ataque vs alvo do Voto', 'Imediatamente após uma criatura sob seu Voto de Inimizade acertar ou errar com uma jogada de ataque, você pode usar a Reação para realizar um ataque corpo a corpo contra ela se estiver ao seu alcance.', NULL, NULL, 55),
('paladin-avenging-angel', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'vengeance'), 'Anjo Vingador', 'bonus'::rpg.action_economy_bucket, 20, 'avenging-angel', NULL, true, 'Voo + aura Amedrontar (10 min)', 'Como Ação Bônus, benefícios por 10 minutos. 1×/Descanso Longo (ou espaço de 5º). Inimigos que iniciam o turno na Aura de Proteção: salvaguarda de Sabedoria ou Amedrontado por 1 min (ou até sofrer dano); ataques contra Amedrontados têm Vantagem. Você ganha Deslocamento de Voo de 18 m e pode pairar.', 'spend-resource', NULL, 56),
('paladin-conjure-beverage', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'oath-of-revelry'), 'Conjurar Bebida', 'action'::rpg.action_economy_bucket, 3, 'channelDivinity', NULL, true, 'Canalizar: canecas com PV temp e Vantagem', 'Como Ação Mágica, gaste 1 Canalizar Divindade para conjurar até o seu mod. de Carisma (mín. 1) canecas de cerveja a até 9 m. Beber como Ação Bônus: PV temporários iguais ao mod. de Carisma e Vantagem em salvaguardas por 1 minuto. Canecas restantes desaparecem ao terminar um Descanso Longo.', 'oath-channel', NULL, 57),
('paladin-aura-of-fellowship', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'oath-of-revelry'), 'Aura de Fraternidade', 'free'::rpg.action_economy_bucket, 7, NULL, NULL, false, '+1d4 dano corpo a corpo na aura', 'Você e aliados causam +1d4 de dano extra em ataques com armas corpo a corpo ou Ataques Desarmados enquanto estiverem na Aura de Proteção. O tipo do dano extra é o mesmo do ataque.', NULL, NULL, 58),
('paladin-reveler', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'oath-of-revelry'), 'Folião', 'reaction'::rpg.action_economy_bucket, 15, 'reveler', NULL, false, 'Reação: Vantagem em Teste d20 (aliado 9 m)', 'Quando você ou um aliado a até 9 m que possa ver ou ouvir você faz um Teste de D20, use a Reação para conceder Vantagem nesse teste. Usos = mod. de Carisma (mín. 1)/Descanso Longo. Se a criatura ainda falhar, este uso não é gasto — marque no contador ±.', NULL, NULL, 59),
('paladin-party-animal', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'oath-of-revelry'), 'Animal de Festa', 'bonus'::rpg.action_economy_bucket, 20, 'party-animal', NULL, true, 'Aura festiva por 10 min (1×/DL)', 'Como Ação Bônus, imbuir a Aura de Proteção por 10 minutos. 1×/Descanso Longo (ou espaço de 5º). Dano da Aura de Fraternidade vira 1d8; no início de cada turno você pode dar Inspiração Heroica a um aliado na aura; imunidade a Cego, Surdo, Exaustão e Envenenado na aura.', 'spend-resource', NULL, 60),
('ranger-hunters-mark', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), NULL, 'Marca do Predador', 'bonus'::rpg.action_economy_bucket, 1, 'favoredEnemy', NULL, false, 'Marcar alvo (uso gratuito disponível)', 'Como Ação Bônus, gaste 1 uso de Inimigo Favorito para conjurar Marca do Predador sem espaço (concentração).', 'hunters-mark-free', NULL, 41),
('ranger-tireless', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), NULL, 'Incansável', 'action'::rpg.action_economy_bucket, 10, 'tireless', NULL, true, 'Ação: PV temporários 1d8 + SAB', 'Como ação, gaste 1 uso para ganhar PV temporários iguais a 1d8 + seu modificador de Sabedoria.', 'tireless', NULL, 40),
('ranger-natures-veil', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), NULL, 'Véu da Natureza', 'bonus'::rpg.action_economy_bucket, 14, 'naturesVeil', NULL, true, 'Tornar-se Invisível até o fim do próximo turno', 'Como Ação Bônus, gaste 1 uso para ficar Invisível até o fim do seu próximo turno.', 'natures-veil', NULL, 42),
('ranger-primal-companion', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'beast-master'), 'Companheiro Primal', 'bonus'::rpg.action_economy_bucket, 3, NULL, NULL, false, 'Comandar a fera', 'Ação Bônus: comande a fera; na ação Atacar você pode sacrificar um ataque para o Golpe da Fera (mesa).', 'primal-companion', NULL, 43),
('ranger-hunter-defense', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'hunter'), 'Defesa do Caçador Superior', 'reaction'::rpg.action_economy_bucket, 15, NULL, NULL, false, 'Resistência ao dano neste turno', 'Quando sofrer dano, use a Reação para ganhar Resistência a esse dano até o fim do turno atual (mesa).', 'hunter-defense', NULL, 44),
('ranger-gloom-stalker-dodge', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'gloom-stalker'), 'Esquiva Sombria', 'reaction'::rpg.action_economy_bucket, 15, NULL, NULL, false, 'Desvantagem no ataque e teleporte de 9 m', 'Quando um atacante que você possa ver erra ou está prestes a acertar: imponha Desvantagem e teleporte até 9 m (mesa).', 'gloom-stalker-dodge', NULL, 45),
('ranger-fey-reinforcements', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'fey-wanderer'), 'Reforços Feéricos', 'action'::rpg.action_economy_bucket, 11, 'fey-reinforcements', NULL, true, 'Convocar Feérico sem espaço (1 min, sem Concentração)', 'Conjure Convocar Feérico sem espaço e sem Concentração (duração 1 minuto nesta conjuração).', 'fey-reinforcements', NULL, 45),
('ranger-misty-wanderer', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'fey-wanderer'), 'Andarilho Nebuloso', 'bonus'::rpg.action_economy_bucket, 15, 'misty-wanderer', NULL, true, 'Passo Nebuloso sem espaço (+1 criatura)', 'Conjure Passo Nebuloso sem espaço; pode levar uma criatura voluntária a 1,5 m.', 'misty-wanderer', NULL, 46),
('ranger-beastborne-aspect', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'beastborne'), 'Aspecto Bestial (mesa)', 'bonus'::rpg.action_economy_bucket, 3, NULL, NULL, false, 'Tracker de Aspecto Bestial (0–5) na mesa', 'Ajuste o nível de Aspecto Bestial no painel do Patrulheiro (+/− ou Uivo Feral). Benefícios acumulam: Carnificina, Velocidade, Frenesi, Pele, Retaliação. Zera no descanso longo (e após 1 min sem dano na mesa).', NULL, NULL, 47),
('cleric-channel', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), NULL, 'Canalizar Divindade', 'action'::rpg.action_economy_bucket, 2, 'channelDivinity', NULL, false, 'Centelha Divina, Expulsar Mortos-Vivos etc.', NULL, NULL, NULL, 47),
('cleric-warding-flare', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'light'), 'Labareda Protetora', 'reaction'::rpg.action_economy_bucket, 3, 'warding-flare', NULL, false, 'Desvantagem no ataque contra você', NULL, NULL, NULL, 48),
('cleric-war-priest', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'war'), 'Sacerdote da Guerra', 'bonus'::rpg.action_economy_bucket, 3, 'war-priest', NULL, false, 'Ataque com arma como Ação Bônus', NULL, NULL, NULL, 49),
('cleric-guided-strike', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'war'), 'Ataque Direcionado', 'free'::rpg.action_economy_bucket, 3, 'channelDivinity', NULL, false, 'Após errar: +10 no ataque', NULL, NULL, NULL, 50),
('cleric-dragon-majesty', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'dragon-domain'), 'Majestade Dracônica', 'action'::rpg.action_economy_bucket, 3, 'channelDivinity', NULL, true, 'Canalizar: Enfeitiçar ou Amedrontar (9 m)', 'Ação Mágica: apresente o Símbolo Sagrado e gaste Canalizar Divindade. Emanação de 9 m — Enfeitiçado ou Amedrontado (salvaguarda SAB, 1 min).', 'spend-resource', NULL, 51),
('cleric-legendary-aspect', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'dragon-domain'), 'Aspecto Lendário', 'free'::rpg.action_economy_bucket, 17, 'legendary-aspect', NULL, true, 'Ação lendária (Rasgar / Cauda / Asas)', 'Gaste 1 uso para Rasgar, Golpe de Cauda ou Batida de Asas imediatamente após o turno de outra criatura. 3 usos/LR.', 'spend-resource', NULL, 52),
('druid-wild-shape', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), NULL, 'Forma Selvagem', 'bonus'::rpg.action_economy_bucket, 2, 'wildShape', NULL, false, 'Assumir forma de besta', NULL, NULL, NULL, 53),
('druid-lunar-healing', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'moon'), 'Cura Lunar', 'bonus'::rpg.action_economy_bucket, 3, NULL, NULL, false, 'Na Forma Selvagem: gastar slot para curar', NULL, NULL, NULL, 54),
('druid-wrath-of-the-sea', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'sea'), 'Ira do Mar', 'bonus'::rpg.action_economy_bucket, 3, 'wildShape', NULL, false, 'Aura de tempestade', NULL, NULL, NULL, 55),
('druid-city-shape', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'circle-of-the-city'), 'Forma da Cidade', 'bonus'::rpg.action_economy_bucket, 3, 'wildShape', NULL, true, 'Gaste Forma Selvagem: Fundir-se / Passagem / Moldar Rocha', 'Gaste 1 uso de Forma Selvagem para conjurar Fundir-se na Pedra, Passagem ou Moldar Rocha sem espaço de magia (mesa).', 'spend-resource', NULL, 56),
('druid-wall-warp', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'circle-of-the-city'), 'Distorção de Muro', 'reaction'::rpg.action_economy_bucket, 10, 'wall-warp', NULL, true, 'Painel de Muralha de Pedra (1×/LR)', 'Reação: ao ver um ataque causar dano a até 18 m, gaste o uso para erguer um painel 3×3 m (CA 15, 30 PV) até o fim do seu próximo turno.', 'spend-resource', NULL, 57),
('sorcerer-innate-sorcery', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), NULL, 'Feitiçaria Inata', 'bonus'::rpg.action_economy_bucket, 1, 'innate-sorcery', NULL, true, '+1 na CD e Vantagem em ataques de magia de Feiticeiro (1 min; 2×/DL)', 'Ação Bônus: libera a magia por 1 minuto. Sem usos (L7+): gaste 2 Pontos de Feitiçaria (Feitiçaria Encarnada).', 'innate-sorcery', NULL, 58),
('sorcerer-metamagic', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), NULL, 'Metamagia', 'free'::rpg.action_economy_bucket, 2, 'sorceryPoints', NULL, false, 'Ao conjurar: gastar pontos nas opções conhecidas (painel / botões)', 'Use as opções de Metamagia conhecidas no painel de combate (não pela linha Usar genérica).', NULL, NULL, 59),
('sorcerer-sorcerous-restoration', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), NULL, 'Restauração Feiticeira', 'free'::rpg.action_economy_bucket, 5, 'sorcerous-restoration', NULL, true, 'Descanso Curto: recupera SP até metade do nível (1×/DL)', 'No Descanso Curto, recupere Pontos de Feitiçaria iguais à metade do seu nível de Feiticeiro (1×/Descanso Longo).', 'sorcerous-restoration', NULL, 63),
('sorcerer-dragon-wings', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'draconic'), 'Asas de Dragão', 'bonus'::rpg.action_economy_bucket, 14, 'dragon-wings', NULL, true, 'Ação Bônus: voo 18 m por 1 h (1×/DL ou 3 SP para restaurar)', 'Como Ação Bônus, asas dracônicas aparecem por 1 hora (Deslocamento de Voo 18 m). Recupera no Descanso Longo ou gastando 3 Pontos de Feitiçaria (sem ação) para restaurar o uso.', 'dragon-wings', NULL, 60),
('sorcerer-heroic-soul', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'heroic-sorcery'), 'Alma Heróica', 'free'::rpg.action_economy_bucket, 3, 'sorceryPoints', NULL, true, 'Início do turno: 1 SP → PV temp. 1d6 + nível', 'No início de cada um dos seus turnos, gaste 1 Ponto de Feitiçaria para ganhar PV temporários iguais a 1d6 + seu nível de Feiticeiro (sem ação).', 'heroic-soul', 1, 61),
('sorcerer-mystical-maneuver', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'heroic-sorcery'), 'Manobra Mística', 'bonus'::rpg.action_economy_bucket, 14, 'sorceryPoints', NULL, true, '2 SP após acertar: Cegar / Ruinoso / Ferimento +2d8', 'Ao acertar com arma ou Ataque Desarmado, gaste 2 Pontos de Feitiçaria como Ação Bônus: +2d8 no dano e Cegar, −3 CA ou ferimento sangrando (mesa).', 'mystical-maneuver', 2, 62),
('sorcerer-warp-implosion', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'aberrant'), 'Implosão de Distorção', 'action'::rpg.action_economy_bucket, 18, 'warp-implosion', NULL, true, 'Usar Magia: teleporte + dano espacial (1×/DL)', 'Como ação Usar Magia, libere a anomalia (teleporte e dano — aplique na mesa). 1 uso; recupera no Descanso Longo.', 'warp-implosion', NULL, 64),
('sorcerer-tides-of-chaos', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'wild-magic'), 'Marés do Caos', 'free'::rpg.action_economy_bucket, 3, 'tides-of-chaos', NULL, true, 'Vantagem em 1 Teste de D20 (1×; recarrega com Surto/DL)', 'Antes de jogar um Teste de D20, ganhe Vantagem. Após usar, precisa conjurar magia de Feiticeiro com espaço ou concluir um Descanso Longo para recuperar (Surto de Magia Selvagem também recarrega).', 'tides-of-chaos', NULL, 77),
('sorcerer-restore-balance', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'clockwork'), 'Restaurar Equilíbrio', 'reaction'::rpg.action_economy_bucket, 3, 'restore-balance', NULL, true, 'Reação: cancela Vantagem/Desvantagem em d20 (usos = CAR)', 'Quando uma criatura à sua vista a até 18 m estiver prestes a jogar um d20 com Vantagem ou Desvantagem, use sua Reação para evitar que o teste seja afetado.', 'restore-balance', NULL, 78),
('sorcerer-bastion-of-law', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'clockwork'), 'Bastião da Lei', 'action'::rpg.action_economy_bucket, 6, 'sorceryPoints', NULL, true, 'Gaste 1–5 SP: conceda N d8 de proteção a aliado (9 m)', 'Como ação Usar Magia, gaste de 1 a 5 Pontos de Feitiçaria para criar proteção (N d8). A criatura protegida pode gastar os dados para reduzir dano. Dura até Descanso Longo ou novo uso.', 'bastion-of-law', NULL, 79),
('sorcerer-bend-luck', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'wild-magic'), 'Distorcer a Sorte', 'reaction'::rpg.action_economy_bucket, 6, 'sorceryPoints', NULL, true, 'Reação: 1 SP → ±1d4 no d20 de outra criatura', 'Imediatamente após outra criatura à sua vista jogar o d20 para um Teste de D20, use Reação e gaste 1 Ponto de Feitiçaria para aplicar +1d4 ou −1d4 (à sua escolha).', 'bend-luck', 1, 80),
('warlock-magical-cunning', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), NULL, 'Astúcia Mágica', 'free'::rpg.action_economy_bucket, 2, 'magical-cunning', NULL, true, 'Recupera metade dos slots de Pacto (rito 1 min; 1×/DL)', NULL, 'magical-cunning', NULL, 63),
('warlock-healing-light', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'celestial'), 'Luz Medicinal', 'bonus'::rpg.action_economy_bucket, 3, 'healing-light', NULL, false, 'Cura com reserva de d6s (1–CAR)', 'Como Ação Bônus, gaste 1 até o seu modificador de Carisma em d6s da reserva de Luz Medicinal para curar uma criatura a até 18 m.', 'healing-light', NULL, 64),
('warlock-dark-ones-luck', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'fiend'), 'A Sorte do Próprio Tenebroso', 'free'::rpg.action_economy_bucket, 6, 'dark-ones-luck', NULL, false, '+1d10 em teste ou salvaguarda', NULL, 'dark-ones-luck', NULL, 65),
('warlock-fey-steps', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'archfey'), 'Passos Feéricos', 'bonus'::rpg.action_economy_bucket, 3, 'fey-steps', NULL, true, 'Passo Nebuloso sem espaço + efeito', NULL, 'fey-step-effect', NULL, 72),
('warlock-beguiling-defenses', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'archfey'), 'Defesas Sedutoras', 'reaction'::rpg.action_economy_bucket, 10, 'beguiling-defenses', NULL, true, 'Reação após ser acertado: metade do dano + psíquico', NULL, 'beguiling-defenses', NULL, 73),
('warlock-clairvoyant-combatant', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'great-old-one'), 'Combatente Clarividente', 'free'::rpg.action_economy_bucket, 6, 'clairvoyant-competitor', NULL, true, 'Ao usar Mente Desperta: link de combate (1× SR/LR)', NULL, 'clairvoyant-combatant', NULL, 74),
('warlock-searing-vengeance', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'celestial'), 'Vingança Calcinante', 'reaction'::rpg.action_economy_bucket, 14, 'searing-vengeance', NULL, true, 'Salvaguarda contra morte (você/aliado 18 m)', NULL, 'searing-vengeance', NULL, 75),
('warlock-hurl-through-hell', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'fiend'), 'Lançar no Inferno', 'free'::rpg.action_economy_bucket, 14, 'hurl-through-hell', NULL, true, 'Ao acertar: envie o alvo aos Infernos (1×/DL)', NULL, 'hurl-through-hell', NULL, 76),
('wizard-improved-illusions', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'illusionist'), 'Ilusão Aprimorada', 'bonus'::rpg.action_economy_bucket, 3, NULL, NULL, false, 'Conjurar ilusões como Ação Bônus (sem componente V)', 'Conjure truques de Ilusão e Imagem Silenciosa como Ação Bônus sem componentes V e com o dobro do alcance.', 'improved-illusions', NULL, 66),
('wizard-arcane-ward-recharge', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'abjurer'), 'Recarregar Proteção Arcana', 'bonus'::rpg.action_economy_bucket, 3, NULL, NULL, false, 'Ação Bônus: gastar slot → Proteção recupera 2× círculo', 'Como Ação Bônus, gaste um espaço de magia: a Proteção Arcana recupera Pontos de Vida iguais ao dobro do círculo do espaço gasto.', 'arcane-ward-recharge', NULL, 72),
('wizard-projected-ward', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'abjurer'), 'Proteção Projetada', 'reaction'::rpg.action_economy_bucket, 6, NULL, NULL, false, 'Reação: sua Proteção absorve dano de aliado a até 9 m', 'Quando uma criatura à sua vista a até 9 m sofrer dano, use sua Reação para que a Proteção Arcana absorva esse dano no lugar dela (conforme o texto da característica).', 'projected-ward', NULL, 73),
('wizard-spell-breaker', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'abjurer'), 'Rompe-Magia (Dissipar)', 'bonus'::rpg.action_economy_bucket, 10, NULL, NULL, false, 'Dissipar Magia como Ação Bônus (+PB no teste)', 'Você sempre tem Contramagia e Dissipar Magia preparadas. Pode conjurar Dissipar Magia como Ação Bônus e soma o Bônus de Proficiência ao teste. Se Dissipar ou Contramagia falharem ao interromper uma magia, o espaço não é gasto.', 'spell-breaker', NULL, 74),
('wizard-third-eye', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'diviner'), 'O Terceiro Olho', 'bonus'::rpg.action_economy_bucket, 10, 'third-eye', NULL, true, 'Ação Bônus: Compreensão / Ver o Invisível / Visão no Escuro', 'Como Ação Bônus, escolha um benefício até o próximo descanso: Compreensão Superior (ler qualquer idioma), Ver o Invisível (sem espaço) ou Visão no Escuro 36 m. 1× por Descanso Curto ou Longo.', 'third-eye', NULL, 75),
('wizard-spectral-summon', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'illusionist'), 'Criaturas Espectrais', 'action'::rpg.action_economy_bucket, 6, 'spectral-summon', NULL, true, 'Convocar Feérico / Invocar Fera (ilusão, PV metade) sem slot', 'Conjure a versão Ilusão de Convocar Feérico ou Invocar Fera sem espaço (PV da criatura pela metade). Após usar qualquer uma sem slot, recupere o uso só no Descanso Longo.', 'spectral-summon', NULL, 76),
('wizard-illusory-self', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'illusionist'), 'Autoimagem Ilusória', 'reaction'::rpg.action_economy_bucket, 10, 'illusory-self', NULL, true, 'Reação ao ser atingido: ataque erra; 1×/Descanso', 'Ao ser atingido por um ataque, use a Reação: duplicata ilusória faz o ataque errar automaticamente. Restaure o uso no Descanso Curto/Longo ou gastando um espaço de 2º+ (sem ação).', 'illusory-self', NULL, 77),
('wizard-illusory-reality', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'illusionist'), 'Realidade Ilusória', 'bonus'::rpg.action_economy_bucket, 14, NULL, NULL, false, 'Ação Bônus: tornar real 1 objeto da ilusão (1 min)', 'Enquanto uma magia de Ilusão conjurada com espaço estiver ativa, como Ação Bônus torne real um objeto inanimado não mágico da ilusão por 1 minuto (não causa dano nem condições).', 'illusory-reality', NULL, 78),
('wizard-overchannel', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'evoker'), 'Sobrecarga', 'free'::rpg.action_economy_bucket, 14, NULL, NULL, false, 'Ao conjurar (1º–5º): dano máximo; usos extras → Necrótico', 'Ao conjurar magia de Mago que causa dano com espaço de 1º a 5º, você pode causar dano máximo nesse turno. A 1ª vez no dia não tem custo; usos seguintes antes do Descanso Longo causam 2d12 Necrótico por círculo (+1d12 a cada uso extra), ignorando Resistência/Imunidade.', 'overchannel', NULL, 79),
('wizard-mm-free', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'magic-missile-mage'), 'Mísseis Mágicos Gratuitos', 'action'::rpg.action_economy_bucket, 3, 'magic-missile-free', NULL, true, 'Conjura Mísseis sem espaço (gasta 1 uso)', $mm_free$Na ficha, Conjurar gasta 1 uso gratuito e conjura Mísseis Mágicos sem espaço. Dardos extras e penetração entram na nota de mesa.

Sábio dos Mísseis Mágicos. Adicione a magia Mísseis Mágicos ao seu grimório gratuitamente. Sua expertise nesta magia concede os seguintes benefícios.

Dardos Extra. Quando você conjura Mísseis Mágicos, cria um dardo extra de força mágica. Você cria dois dardos extras no nível 6 de Mago, três dardos extras no nível 10 de Mago e quatro dardos extras no nível 14 de Mago.

Conjuração Livre. Você pode conjurar Mísseis Mágicos sem um espaço de magia. Você pode fazer isso um número de vezes igual ao seu modificador de Inteligência (mínimo de uma vez). Você recupera um uso gasto ao terminar um Descanso Curto e recupera todos os usos gastos ao terminar um Descanso Longo.

Dardos Penetrantes. Seus dardos de Mísseis Mágicos ignoram qualquer efeito, como a magia Escudo, que bloqueie especificamente a magia Mísseis Mágicos.$mm_free$, 'cast:misseis-magicos-free', NULL, 67),
('wizard-mm-versatile', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'magic-missile-mage'), 'Mísseis Versáteis', 'free'::rpg.action_economy_bucket, 6, NULL, NULL, false, 'Ao conjurar: Tombo 1 / Cegar 3 / Atordoar 5 dardos', $mm_vers$Você pode guiar com precisão seus dardos de Mísseis Mágicos para atingir um alvo onde escolher. Quando você conjura Mísseis Mágicos, pode adicionar um dos seguintes efeitos de Míssil Versátil a um alvo atingido pelos dardos. Cada efeito tem um custo, que é o número de dardos que você deve abrir mão para adicionar o efeito ao alvo. Você pode adicionar efeitos diferentes a alvos diferentes, pagando o custo de cada efeito separadamente.

Míssil de Tombo (Custo: 1 Dardo). O alvo deve ser bem-sucedido em uma salvaguarda de Força contra sua CD de magia ou ter a condição Caído.

Míssil Cegante (Custo: 3 Dardos). O alvo deve ser bem-sucedido em uma salvaguarda de Constituição contra sua CD de magia ou ter a condição Cego até o início do seu próximo turno.

Míssil Atordoante (Custo: 5 Dardos). O alvo deve ser bem-sucedido em uma salvaguarda de Constituição contra sua CD de magia ou ter a condição Atordoado até o início do seu próximo turno.$mm_vers$, NULL, NULL, 68),
('wizard-missile-shield', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'magic-missile-mage'), 'Escudo de Mísseis', 'free'::rpg.action_economy_bucket, 10, 'missile-shield', NULL, true, 'Armar para o próximo cast (gasta o uso no cast)', $mm_shield$Arme na ficha antes de conjurar Mísseis Mágicos. O uso é gasto no cast (ou restaure com espaço de 3º+).

Quando você conjura Mísseis Mágicos, pode direcionar os dardos em uma órbita apertada ao seu redor, criando uma Emanação protetora de 3 m originada de você, que dura até 1 minuto.

Você ganha um bônus na sua Classe de Armadura igual ao número de dardos orbitando você (bônus máximo de +5). Sempre que uma criatura a até 36 m errar você com uma jogada de ataque, um dardo atinge o atacante, causando dano normalmente e diminuindo em um o número de dardos orbitando você.

Sempre que a Emanação entrar no espaço de uma criatura que você possa ver e sempre que uma criatura que você possa ver entrar na Emanação ou terminar seu turno nela, você pode atingir o alvo com qualquer número de dardos orbitando você, causando dano normalmente e diminuindo o número de dardos orbitando você. Você só pode causar dano a uma criatura com a Emanação uma vez por turno.

Depois de usar este recurso, você não pode usá-lo novamente até terminar um Descanso Longo. Você também pode restaurar seu uso gastando um espaço de magia de nível 3+ (nenhuma ação necessária).$mm_shield$, 'arm:missile-shield', NULL, 69),
('wizard-giga-missile', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'magic-missile-mage'), 'Giga-Míssil', 'free'::rpg.action_economy_bucket, 14, 'giga-missile', NULL, true, 'Armar para o próximo cast (+mod. INT por dardo)', $mm_giga$Arme na ficha antes de conjurar Mísseis Mágicos. O uso é gasto no cast (ou restaure com espaço de 6º+).

Quando você conjura Mísseis Mágicos, pode aprimorar o dano da magia. Você causa dano de Força extra com cada dardo igual ao seu modificador de Inteligência (mínimo de 1).

Depois de usar este recurso, você não pode usá-lo novamente até terminar um Descanso Longo. Você também pode restaurar seu uso gastando um espaço de magia de nível 6+ (nenhuma ação necessária).$mm_giga$, 'arm:giga-missile', NULL, 70),
('gunslinger-bullet-time', (SELECT id FROM rpg.phb_class WHERE slug = 'gunslinger'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'pistolero'), 'Tempo Bala', 'free'::rpg.action_economy_bucket, 14, NULL, NULL, false, '1×/turno: Vantagem em um ataque à distância com arma', 'Uma vez em cada um dos seus turnos, ao fazer um ataque à distância com arma, você pode ter Vantagem na jogada (mesa).', NULL, NULL, 71)
ON CONFLICT (action_id) DO UPDATE SET
  class_id = EXCLUDED.class_id,
  subclass_id = EXCLUDED.subclass_id,
  name = EXCLUDED.name,
  economy = EXCLUDED.economy,
  unlock_level = EXCLUDED.unlock_level,
  resource_slug = EXCLUDED.resource_slug,
  free_resource_slug = EXCLUDED.free_resource_slug,
  always_spends_resource = EXCLUDED.always_spends_resource,
  summary = EXCLUDED.summary,
  description = EXCLUDED.description,
  table_action = EXCLUDED.table_action,
  spend_amount = EXCLUDED.spend_amount,
  sort_order = EXCLUDED.sort_order;
