-- Seed: Class panel actions (combat class panels)
-- Generated from dnd-front combat-*-panel.tsx ACTION arrays

DELETE FROM rpg.phb_class_panel_action WHERE panel_key = 'wizard|spell-mastery';

INSERT INTO rpg.phb_class_panel_action (
  panel_key, class_id, subclass_id, slug, name, title, unlock_level,
  resource_slug, section, spends_focus, sort_order
) VALUES
('bard|grant-inspiration', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), NULL, 'grant-inspiration', 'Conceder Inspiração', 'Ação Bônus: gasta 1 Inspiração Bárdica e concede o dado a um aliado a até 18 m', 1, 'bardicInspiration', 'base'::rpg.panel_action_section, false, 1),
('bard|superior-inspiration', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), NULL, 'superior-inspiration', 'Inspiração Superior (+1)', 'Na iniciativa: se estiver sem usos, recupera 1 Inspiração Bárdica (nv. 18+)', 18, NULL, 'base'::rpg.panel_action_section, false, 2),
('bard|lore|cutting-words', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'lore'), 'cutting-words', 'Palavras Cortantes', 'Reação (Conhecimento): gasta 1 Inspiração e subtrai o dado de ataque/teste/dano inimigo', 3, 'bardicInspiration', 'subclass'::rpg.panel_action_section, false, 3),
('bard|glamour|enthralling-performance', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'glamour'), 'enthralling-performance', 'Desempenho Cativante', 'Glamour: gasta 1 Inspiração para PV temporários (2×dado) e movimento por Reação', 3, 'bardicInspiration', 'subclass'::rpg.panel_action_section, false, 4),
('bard|dance|unarmed-dance', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'dance'), 'unarmed-dance', 'Ataque Desarmado (Dança)', 'Dança: ataque desarmado com Carisma + dado de Inspiração (não gasta uso)', 3, NULL, 'subclass'::rpg.panel_action_section, false, 5),
('bard|dance|agile-response', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'dance'), 'agile-response', 'Resposta Ágil', 'Reação (Dança, nv. 6+): gasta 1 Inspiração para +CA e movimento se o ataque errar', 6, 'bardicInspiration', 'subclass'::rpg.panel_action_section, false, 6),
('bard|valor|combat-inspiration', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'valor'), 'combat-inspiration', 'Inspiração de Combate', 'Bravura: o aliado inspirado pode somar o dado ao dano ou à CA (Reação)', 3, 'bardicInspiration', 'subclass'::rpg.panel_action_section, false, 7),
('ranger|hunters-mark-free', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), NULL, 'hunters-mark-free', 'Marca do Predador (gratuita)', NULL, 1, 'favoredEnemy', 'base'::rpg.panel_action_section, false, 1),
('ranger|tireless', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), NULL, 'tireless', 'Incansável', NULL, 10, 'tireless', 'base'::rpg.panel_action_section, false, 2),
('ranger|natures-veil', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), NULL, 'natures-veil', 'Véu da Natureza', NULL, 14, 'naturesVeil', 'base'::rpg.panel_action_section, false, 3),
('ranger|fey-wanderer|fey-reinforcements', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'fey-wanderer'), 'fey-reinforcements', 'Reforços Feéricos', NULL, 11, 'fey-reinforcements', 'subclass'::rpg.panel_action_section, false, 4),
('ranger|fey-wanderer|misty-wanderer', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'fey-wanderer'), 'misty-wanderer', 'Andarilho Nebuloso', NULL, 15, 'misty-wanderer', 'subclass'::rpg.panel_action_section, false, 5),
('ranger|beast-master|primal-companion', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'beast-master'), 'primal-companion', 'Companheiro Primal', NULL, 3, NULL, 'subclass'::rpg.panel_action_section, false, 6),
('sorcerer|use-metamagic-1', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), NULL, 'use-metamagic-1', 'Metamágica (1 pt)', NULL, 2, 'sorceryPoints', 'metamagic'::rpg.panel_action_section, false, 1),
('sorcerer|use-metamagic-2', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), NULL, 'use-metamagic-2', 'Metamágica (2 pts)', NULL, 2, 'sorceryPoints', 'metamagic'::rpg.panel_action_section, false, 2),
('sorcerer|use-metamagic-3', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), NULL, 'use-metamagic-3', 'Metamágica (3 pts)', NULL, 2, 'sorceryPoints', 'metamagic'::rpg.panel_action_section, false, 3),
('sorcerer|innate-sorcery', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), NULL, 'innate-sorcery', 'Ira Feiticeira', NULL, 1, NULL, 'subclass'::rpg.panel_action_section, false, 4),
('sorcerer|sorcerous-restoration', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), NULL, 'sorcerous-restoration', 'Restauração Feiticeira', NULL, 5, NULL, 'subclass'::rpg.panel_action_section, false, 5),
('sorcerer|wild-magic|tides-of-chaos', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'wild-magic'), 'tides-of-chaos', 'Maré de Caos', NULL, 3, NULL, 'subclass'::rpg.panel_action_section, false, 6),
('sorcerer|clockwork|bastion-of-law', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'clockwork'), 'bastion-of-law', 'Baluarte da Ordem', NULL, 6, 'sorceryPoints', 'subclass'::rpg.panel_action_section, false, 7),
('monk|flurry-of-blows', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), NULL, 'flurry-of-blows', 'Torrente de Golpes', NULL, 2, NULL, 'base'::rpg.panel_action_section, true, 1),
('monk|patient-defense', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), NULL, 'patient-defense', 'Defesa Paciente', NULL, 2, NULL, 'base'::rpg.panel_action_section, true, 2),
('monk|step-of-the-wind', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), NULL, 'step-of-the-wind', 'Passo do Vento', NULL, 2, NULL, 'base'::rpg.panel_action_section, true, 3),
('monk|stunning-strike', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), NULL, 'stunning-strike', 'Golpe Atordoante', NULL, 5, NULL, 'base'::rpg.panel_action_section, true, 4),
('monk|open-hand|open-hand-technique', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'open-hand'), 'open-hand-technique', 'Técnica da Mão Espalmada', NULL, 3, NULL, 'subclass'::rpg.panel_action_section, false, 5),
('monk|elements|elemental-blast', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'elements'), 'elemental-blast', 'Explosão Elemental', NULL, 3, NULL, 'subclass'::rpg.panel_action_section, true, 6),
('monk|mercy|hand-of-healing', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'mercy'), 'hand-of-healing', 'Mão de Cura', NULL, 3, NULL, 'subclass'::rpg.panel_action_section, true, 7),
('monk|mercy|hand-of-harm', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'mercy'), 'hand-of-harm', 'Mão de Dolo', NULL, 3, NULL, 'subclass'::rpg.panel_action_section, true, 8),
('monk|shadow|shadow-step', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'shadow'), 'shadow-step', 'Passo da Sombra', NULL, 6, NULL, 'subclass'::rpg.panel_action_section, false, 9),
('cleric|divine-spark-heal', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), NULL, 'divine-spark-heal', 'Centelha: Cura', NULL, 2, 'channelDivinity', 'base'::rpg.panel_action_section, false, 1),
('cleric|divine-spark-damage', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), NULL, 'divine-spark-damage', 'Centelha: Dano', NULL, 2, 'channelDivinity', 'base'::rpg.panel_action_section, false, 2),
('cleric|turn-undead', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), NULL, 'turn-undead', 'Expulsar Mortos-Vivos', NULL, 2, 'channelDivinity', 'base'::rpg.panel_action_section, false, 3),
('cleric|divine-intervention', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), NULL, 'divine-intervention', 'Intervenção Divina', NULL, 10, 'divineIntervention', 'base'::rpg.panel_action_section, false, 4),
('cleric|life|preserve-life', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'life'), 'preserve-life', 'Preservar a Vida', NULL, 3, 'channelDivinity', 'subclass'::rpg.panel_action_section, false, 5),
('cleric|light|radiance-of-dawn', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'light'), 'radiance-of-dawn', 'Brilho do Amanhecer', NULL, 3, 'channelDivinity', 'subclass'::rpg.panel_action_section, false, 6),
('cleric|light|warding-flare', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'light'), 'warding-flare', 'Labareda Protetora', NULL, 3, 'warding-flare', 'subclass'::rpg.panel_action_section, false, 7),
('cleric|light|crown-of-light', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'light'), 'crown-of-light', 'Coroa de Luz', NULL, 17, 'corona-of-light', 'subclass'::rpg.panel_action_section, false, 8),
('cleric|trickery|tricksters-blessing', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'trickery'), 'tricksters-blessing', 'Bênção do Trapaceiro', NULL, 3, NULL, 'subclass'::rpg.panel_action_section, false, 9),
('cleric|trickery|invoke-duplicity', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'trickery'), 'invoke-duplicity', 'Invocar Duplicidade', NULL, 3, 'channelDivinity', 'subclass'::rpg.panel_action_section, false, 10),
('cleric|war|guided-strike', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'war'), 'guided-strike', 'Ataque Direcionado +10', NULL, 3, 'channelDivinity', 'subclass'::rpg.panel_action_section, false, 11),
('cleric|war|war-priest', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'war'), 'war-priest', 'Sacerdote da Guerra', NULL, 3, 'war-priest', 'subclass'::rpg.panel_action_section, false, 12),
('cleric|war|war-gods-blessing', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'war'), 'war-gods-blessing', 'Bênção do Deus da Guerra', NULL, 6, 'channelDivinity', 'subclass'::rpg.panel_action_section, false, 13),
('druid|wild-shape', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), NULL, 'wild-shape', 'Forma Selvagem (1 uso)', NULL, 2, 'wildShape', 'base'::rpg.panel_action_section, false, 1),
('druid|wild-resurgence-slot', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), NULL, 'wild-resurgence-slot', 'Ressurgimento (Forma → Slot 1º)', NULL, 5, 'wildShape', 'base'::rpg.panel_action_section, false, 2),
('druid|wild-resurgence-shape', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), NULL, 'wild-resurgence-shape', 'Ressurgimento (Slot 1º → Forma)', NULL, 5, NULL, 'base'::rpg.panel_action_section, false, 3),
('druid|moon|moon-combat-wild-shape', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'moon'), 'moon-combat-wild-shape', 'Forma Selvagem de Combate', NULL, 3, 'wildShape', 'subclass'::rpg.panel_action_section, false, 4),
('druid|stars|starry-form-archer', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'stars'), 'starry-form-archer', 'Forma Estelar: Arquiro (1d8 Radiante)', NULL, 3, 'wildShape', 'subclass'::rpg.panel_action_section, false, 5),
('druid|stars|starry-form-chalice', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'stars'), 'starry-form-chalice', 'Forma Estelar: Cálice (+Cura)', NULL, 3, 'wildShape', 'subclass'::rpg.panel_action_section, false, 6),
('druid|stars|starry-form-dragon', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'stars'), 'starry-form-dragon', 'Forma Estelar: Dragão (Mín 10)', NULL, 3, 'wildShape', 'subclass'::rpg.panel_action_section, false, 7),
('druid|sea|wrath-of-the-sea', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'sea'), 'wrath-of-the-sea', 'Ira do Mar (Aura de Tempestade)', NULL, 3, 'wildShape', 'subclass'::rpg.panel_action_section, false, 8),
('warlock|magical-cunning', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), NULL, 'magical-cunning', 'Contato Arcano (1 Slot)', NULL, 5, NULL, 'base'::rpg.panel_action_section, false, 1),
('warlock|celestial|healing-light', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'celestial'), 'healing-light', 'Luz Curativa', NULL, 3, 'healing-light', 'subclass'::rpg.panel_action_section, false, 2),
('warlock|fiend|dark-ones-own-luck', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'fiend'), 'dark-ones-own-luck', 'Sorte do Próprio Inferno (+1d10)', NULL, 3, 'dark-ones-own-luck', 'subclass'::rpg.panel_action_section, false, 3),
('warlock|archfey|fey-step-effect', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'archfey'), 'fey-step-effect', 'Passo de Bruma Aprimorado', NULL, 3, NULL, 'subclass'::rpg.panel_action_section, false, 4),
('warlock|great-old-one|awakened-mind', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'great-old-one'), 'awakened-mind', 'Mente Desperta / Hex Psíquico', NULL, 3, NULL, 'subclass'::rpg.panel_action_section, false, 5),
('warlock|fiend|fiendish-resilience', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'fiend'), 'fiendish-resilience', 'Resiliência Ínfera', NULL, 10, NULL, 'subclass'::rpg.panel_action_section, false, 6),
('wizard|abjurer|arcane-ward', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'abjurer'), 'arcane-ward', 'Proteção Arcana', NULL, 3, NULL, 'subclass'::rpg.panel_action_section, false, 1),
('wizard|diviner|portent', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'diviner'), 'portent', 'Rolar Presságio', NULL, 3, NULL, 'subclass'::rpg.panel_action_section, false, 2),
('wizard|evoker|sculpt-spells', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'evoker'), 'sculpt-spells', 'Esculpir Magias', NULL, 6, NULL, 'subclass'::rpg.panel_action_section, false, 3),
('wizard|illusionist|improved-illusions', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'illusionist'), 'improved-illusions', 'Ilusão Aprimorada', NULL, 3, NULL, 'subclass'::rpg.panel_action_section, false, 4),
('paladin|divine-sense', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), NULL, 'divine-sense', 'Sentido Divino', NULL, 3, NULL, 'channel'::rpg.panel_action_section, false, 1),
('paladin|oath-channel', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), NULL, 'oath-channel', 'Canalizar do Juramento', NULL, 3, NULL, 'channel'::rpg.panel_action_section, false, 2),
('paladin|abjure-enemies', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), NULL, 'abjure-enemies', 'Repudiar Inimigos', NULL, 9, NULL, 'channel'::rpg.panel_action_section, false, 3)
ON CONFLICT (panel_key) DO UPDATE SET
  class_id = EXCLUDED.class_id,
  subclass_id = EXCLUDED.subclass_id,
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  unlock_level = EXCLUDED.unlock_level,
  resource_slug = EXCLUDED.resource_slug,
  section = EXCLUDED.section,
  spends_focus = EXCLUDED.spends_focus,
  sort_order = EXCLUDED.sort_order;
