-- Economy actions — Griffon's Saddlebag Book One (piloto: Caminho da Glaciar)

INSERT INTO rpg.phb_class_economy_action (
  action_id, class_id, subclass_id, name, economy, unlock_level,
  resource_slug, free_resource_slug, always_spends_resource,
  summary, description, table_action, spend_amount, sort_order
) VALUES
(
  'barbarian-glacier-rage-extension',
  (SELECT id FROM rpg.phb_class WHERE slug = 'barbarian'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'path-of-the-glacier'),
  'Extensão de Fúria',
  'free'::rpg.action_economy_bucket,
  3,
  'glacier-rage-extension',
  NULL,
  true,
  'Sem ação: estende Fúria (usos = Constituição)',
  'Quando sua Fúria terminaria e você não estiver Inconsciente, pode estendê-la (sem ação). Usos = modificador de Constituição (mín. 1); recupera todos no Descanso Longo.',
  'glacier-rage-extension',
  NULL,
  100
),
(
  'barbarian-glacier-frostbite',
  (SELECT id FROM rpg.phb_class WHERE slug = 'barbarian'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'path-of-the-glacier'),
  'Geladura',
  'free'::rpg.action_economy_bucket,
  3,
  NULL,
  NULL,
  false,
  'Fúria: 1×/turno +1d6 Gélido no acerto de Força',
  'Enquanto a Fúria estiver ativa, uma vez por turno ao acertar com ataque baseado em Força, o alvo sofre 1d6 de dano Gélido extra (2d6 no nível 9; 3d6 no 16). A Velocidade do alvo cai 3 m até o início do seu próximo turno. Mesa — declare no acerto.',
  'frostbite',
  NULL,
  101
),
(
  'barbarian-glacier-cold-fortress-entry',
  (SELECT id FROM rpg.phb_class WHERE slug = 'barbarian'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'path-of-the-glacier'),
  'Fortaleza Gelada (entrada)',
  'free'::rpg.action_economy_bucket,
  6,
  NULL,
  NULL,
  false,
  'Ao entrar em Fúria sem armadura: PV temp. 1d12 + Constituição',
  'Ao entrar em Fúria sem armadura, ganha PV temporários = 1d12 + mod. Constituição por camada de gelo protetora. Mesa — role ao ativar Fúria.',
  'cold-fortress-entry',
  NULL,
  102
),
(
  'barbarian-glacier-cold-fortress-renew',
  (SELECT id FROM rpg.phb_class WHERE slug = 'barbarian'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'path-of-the-glacier'),
  'Fortaleza Gelada (renovar)',
  'bonus'::rpg.action_economy_bucket,
  6,
  NULL,
  NULL,
  false,
  'Ação Bônus em Fúria: gasta 1 DV → PV temp. de novo',
  'Como Ação Bônus em turnos seguintes enquanto a Fúria durar (sem armadura), gaste um Dado de Vida de Bárbaro para ganhar PV temporários = 1d12 + mod. Constituição.',
  'cold-fortress-renew',
  NULL,
  103
),
(
  'barbarian-glacier-avalanche-stomp',
  (SELECT id FROM rpg.phb_class WHERE slug = 'barbarian'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'path-of-the-glacier'),
  'Pisoteio Glacial',
  'action'::rpg.action_economy_bucket,
  14,
  NULL,
  NULL,
  false,
  'Ação Mágica: tremor 4,5 m — salv. de Destreza',
  'Como ação Mágica, pisoteie o chão. Cada criatura escolhida numa Emanação de 4,5 m centrada em você faz salvaguarda de Destreza (CD 8 + mod. de Força + PB). Em falha: dano Contundente = 3d6 + mod. de Força e condição Caído.',
  'avalanche-stomp',
  NULL,
  104
)
ON CONFLICT (action_id) DO UPDATE SET
  class_id = EXCLUDED.class_id,
  subclass_id = EXCLUDED.subclass_id,
  name = EXCLUDED.name,
  economy = EXCLUDED.economy,
  unlock_level = EXCLUDED.unlock_level,
  resource_slug = EXCLUDED.resource_slug,
  free_resource_slug = EXCLUDED.free_resource_slug,
  always_spends_resource = EXCLUDED.always_spends_resource,
  summary = EXCLUDED.summary,
  description = EXCLUDED.description,
  table_action = EXCLUDED.table_action,
  spend_amount = EXCLUDED.spend_amount,
  sort_order = EXCLUDED.sort_order;
