-- Economy actions — Griffon's Saddlebag Book One (11 subclasses restantes)

INSERT INTO rpg.phb_class_economy_action (
  action_id, class_id, subclass_id, name, economy, unlock_level,
  resource_slug, free_resource_slug, always_spends_resource,
  summary, description, table_action, spend_amount, sort_order
) VALUES
-- College of Choreography
('bard-choreography-inspirational-dance', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'college-of-choreography'), 'Dança Inspiradora', 'bonus'::rpg.action_economy_bucket, 3, 'bardicInspiration', NULL, true, 'AB: Inspiração → PV temp. + Reação aliado', 'Ação Bônus: gaste 1 Inspiração Bárdica. Role o dado; aliado à vista ganha PV temporários = resultado + mod. Carisma (mín. 2). Pode usar Reação para mover ou Esquivar.', 'inspirational-dance', NULL, 100),
('bard-choreography-endless-attack', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'college-of-choreography'), 'Dança Infinita (ataque)', 'reaction'::rpg.action_economy_bucket, 14, NULL, NULL, false, 'Reação: ataque em vez de PV temp.', 'Quando criatura ganharia PV temporários de Dança Inspiradora, pode usar Reação para atacar com arma ou Ataque Desarmado.', 'endless-dance-attack', NULL, 101),
('bard-choreography-endless-dodge', (SELECT id FROM rpg.phb_class WHERE slug = 'bard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'college-of-choreography'), 'Dança Infinita (esquivar)', 'bonus'::rpg.action_economy_bucket, 14, NULL, NULL, false, 'AB com Inspiração: Esquivar incluído', 'Pode Esquivar como Ação Bônus. Ao gastar dado de Inspiração como Ação Bônus, pode Esquivar como parte da mesma ação.', 'endless-dodge', NULL, 102),

-- Astral Domain
('cleric-astral-create-void', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'astral-domain'), 'Criar Vazio', 'bonus'::rpg.action_economy_bucket, 3, 'channelDivinity', NULL, true, 'AB: Canalizar — vácuo 4,5 m', 'Ação Bônus: gaste Canalizar Divindade. Esfera de 4,5 m de raio a até 18 m: salvaguarda de Destreza; falha = 1d8 + nível de Força e puxão 4,5 m.', 'create-void', NULL, 100),
('cleric-astral-planar-reach', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'astral-domain'), 'Alcance Planar', 'free'::rpg.action_economy_bucket, 3, 'planar-reach', NULL, true, 'Toque → 9 m (usos = Sabedoria)', 'Ao conjurar magia de alcance Toque, pode torná-la alcance 9 m. Usos = mod. de Sabedoria (mín. 1) / Descanso Longo.', 'planar-reach', NULL, 101),
('cleric-astral-spatial-exchange', (SELECT id FROM rpg.phb_class WHERE slug = 'cleric'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'astral-domain'), 'Troca Espacial', 'bonus'::rpg.action_economy_bucket, 6, 'channelDivinity', NULL, true, 'AB: Canalizar — Passo Nebuloso + troca', 'Conjura Passo Nebuloso gastando Canalizar Divindade. Pode trocar de lugar com criatura voluntária a até 9 m.', 'spatial-exchange', NULL, 102),

-- The Unbroken Circle
('druid-unbroken-wild-recovery', (SELECT id FROM rpg.phb_class WHERE slug = 'druid'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'the-unbroken-circle'), 'Recuperação Selvagem', 'bonus'::rpg.action_economy_bucket, 3, 'wildShape', NULL, true, 'AB: gasta Forma → cura 2d6+nível', 'Ação Bônus: gaste 1 Forma Selvagem e recupere PV = 2d6 + nível de Druida (+1d6 no nv. 10; +2d6 no 14).', 'wild-recovery', NULL, 100),

-- Couatl Herald
('fighter-couatl-benevolent-presence', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'couatl-herald'), 'Presença Benevolente', 'free'::rpg.action_economy_bucket, 3, 'mercy-dice', NULL, true, 'Teste: gasta Dados de Misericórdia', 'Em teste de Intuição ou Carisma (Atuação/Persuasão), gaste um ou mais Dados de Misericórdia e some ao resultado.', 'benevolent-presence', NULL, 100),
('fighter-couatl-merciless-strike', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'couatl-herald'), 'Golpe Implacável', 'free'::rpg.action_economy_bucket, 3, 'mercy-dice', NULL, true, '1×/turno no acerto: dano Radiante extra', 'Uma vez por turno ao acertar com arma ou Ataque Desarmado, gaste 1 Dado de Misericórdia: dano Radiante extra = valor do dado. Nv. 18+: 1×/turno sem gastar.', 'merciless-strike', NULL, 101),
('fighter-couatl-peaceful-ward', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'couatl-herald'), 'Proteção Pacífica', 'bonus'::rpg.action_economy_bucket, 3, 'mercy-dice', NULL, true, 'Ação Bônus: PV temp. = dado + Carisma', 'Ação Bônus: gaste 1 Dado de Misericórdia. PV temporários = valor do dado + mod. de Carisma (mín. 1).', 'peaceful-ward', NULL, 102),
('fighter-couatl-paragon', (SELECT id FROM rpg.phb_class WHERE slug = 'fighter'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'couatl-herald'), 'Paragona', 'bonus'::rpg.action_economy_bucket, 15, 'mercy-dice', NULL, true, 'Ação Bônus: comando + PV temp. + Reação aliado', 'Ação Bônus: ordene criatura a até 9 m que ouça você e gaste 1 Dado de Misericórdia. PV temporários = dado + mod. de Carisma (mín. 1); Reação para mover e atacar. Dano nocauteante.', 'paragon', NULL, 103),

-- Warrior of the Celestial
('monk-celestial-soul-strike', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'warrior-of-the-celestial'), 'Golpe de Busca da Alma', 'free'::rpg.action_economy_bucket, 3, 'focusPoints', NULL, false, 'No toque/acerto: 1 Foco — sonda alma', 'Ao tocar ou acertar com Ataque Desarmado, gaste 1 Ponto de Foco (sem ação) para sondar emoções/desejo e Vantagem no próximo ataque. Na Rajada de Golpes: sem gastar Foco.', 'soul-searching-strike', NULL, 100),
('monk-celestial-stabilizing-focus', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'warrior-of-the-celestial'), 'Foco Estabilizador', 'action'::rpg.action_economy_bucket, 6, 'focusPoints', NULL, false, 'Ação Mágica: cura 5 PV/Foco (máx. metade)', 'Toque criatura Ferida e gaste 1+ Pontos de Foco: cada ponto restaura 5 PV (máx. metade do máximo). 2 Focos: conjura Aprimorar Atributo, Restauração Menor ou Proteção sem espaço.', 'stabilizing-focus', NULL, 101),
('monk-celestial-stabilizing-focus-bonus', (SELECT id FROM rpg.phb_class WHERE slug = 'monk'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'warrior-of-the-celestial'), 'Foco Estabilizador (AB)', 'bonus'::rpg.action_economy_bucket, 17, 'focusPoints', NULL, false, 'AB: cura a até 9 m', 'Celestial Ascendente: Foco Estabilizador como Ação Bônus; alvo Ferido a até 9 m em vez de toque.', 'stabilizing-focus-bonus', NULL, 102),

-- Oath of the Hearth
('paladin-hearth-burning-weapon', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'oath-of-the-hearth'), 'Arma Flamejante', 'free'::rpg.action_economy_bucket, 3, 'channelDivinity', NULL, true, 'Ao Atacar: Canalizar — arma ígnea 10 min', 'Na ação Atacar, gaste Canalizar Divindade para incendiar arma corpo a corpo: +dano Ígneo = mod. Carisma (mín. 1) por acerto por 10 min. Luz 6 m/6 m.', 'burning-weapon', NULL, 100),
('paladin-hearth-burning-spirit', (SELECT id FROM rpg.phb_class WHERE slug = 'paladin'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'oath-of-the-hearth'), 'Espírito Flamejante', 'bonus'::rpg.action_economy_bucket, 20, 'burning-spirit', NULL, true, 'Ação Bônus: forma flamejante 10 min (1×/DL)', 'Ação Bônus: luz na aura, Velocidade +3 m, atravessa espaços ocupados, dano Ígneo em Emanação de 3 m no fim do turno. 1× / Descanso Longo (ou espaço de 5º círculo).', 'burning-spirit', NULL, 101),

-- Winter Trapper
('ranger-winter-magic-snare', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'winter-trapper'), 'Armadilha Mágica', 'bonus'::rpg.action_economy_bucket, 11, 'magic-snare', NULL, true, 'Ação Bônus: armadilha no chão (usos = Sabedoria)', 'Ação Bônus: armadilha imperceptível aos seus pés. Primeira criatura Grande ou menor que entrar no próximo minuto: salvaguarda de Destreza vs. CD de magia; falha = 2d8 Perfurante e Velocidade 0. Usos = mod. de Sabedoria (mín. 1) / Descanso Longo.', 'magic-snare', NULL, 100),
('ranger-winter-tripped-defenses', (SELECT id FROM rpg.phb_class WHERE slug = 'ranger'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'winter-trapper'), 'Defesas Tropeçadas', 'reaction'::rpg.action_economy_bucket, 15, NULL, NULL, false, 'Reação: erram → Caído ou metade Vel.', 'Quando criatura a 1,5 m erra ataque contra você: Reação para desequilibrá-la (Caído se Grande ou menor; senão metade da Velocidade). Depois ataque ou move metade da Velocidade.', 'tripped-defenses', NULL, 101),

-- Runetagger
('rogue-runetagger-impressionist', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'runetagger'), 'Impressionista (suprimentos)', 'action'::rpg.action_economy_bucket, 3, NULL, NULL, false, 'Ação Mágica: cria suprimentos/tinta', 'Ação Mágica: cria Suprimentos de Calígrafo ou Pintor numa mão livre e tinta ou tinta de qualquer cor. Objetos somem se saírem de você.', 'impressionist-supplies', NULL, 100),
('rogue-runetagger-rune-mark', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'runetagger'), 'Marcar com Runa', 'free'::rpg.action_economy_bucket, 3, 'rune-points', NULL, true, 'No acerto corpo a corpo: 1 Ponto de Runa', 'Ao acertar corpo a corpo, gaste 1 Ponto de Runa para marcar criatura por até 1 min (Crios, Maldíx ou Locus).', 'rune-mark', NULL, 101),
('rogue-runetagger-rune-hexxus', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'runetagger'), 'Runa Maldíx', 'reaction'::rpg.action_economy_bucket, 3, NULL, NULL, false, 'Reação: −1d6 em sucesso do alvo marcado', 'Reação quando criatura marcada com Maldíx passa em teste ou ataque a até 18 m: −1d6 no resultado.', 'rune-hexxus', NULL, 102),
('rogue-runetagger-escape-invisibility', (SELECT id FROM rpg.phb_class WHERE slug = 'rogue'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'runetagger'), 'Artista da Fuga (invisível)', 'bonus'::rpg.action_economy_bucket, 9, 'rune-points', NULL, true, 'Ação Bônus + 1 Runa: Invisível 10 min', 'A até 1,5 m de superfície sólida: Ação Bônus + 1 Ponto de Runa para ficar Invisível por 10 min (termina ao atacar, causar dano, conjurar ou sair do espaço).', 'escape-invisibility', NULL, 103),

-- Frost Sorcery
('sorcerer-frost-create-ice', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'frost-sorcery'), 'Criar Gelo', 'bonus'::rpg.action_economy_bucket, 3, NULL, NULL, false, 'AB: gelo em quadrados 1,5 m', 'Tocando superfície sólida, Ação Bônus: até cinco quadrados de 1,5 m contíguos viram terreno difícil até fim do seu próximo turno. Opcional: Pontos de Feitiçaria para +5 quadrados/ponto.', 'create-ice', NULL, 100),
('sorcerer-frost-cryomancy', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'frost-sorcery'), 'Criomancia', 'free'::rpg.action_economy_bucket, 6, 'sorceryPoints', NULL, false, 'Dano Gélido: PF reduzem Velocidade', 'Ao causar dano Gélido com magia em criatura Grande ou menor, gaste Pontos de Feitiçaria: −4,5 m de Velocidade por ponto até fim do turno dela; se Velocidade 0, +2d6 Gélido.', 'cryomancy-freeze', NULL, 101),
('sorcerer-frost-flash-freeze', (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'frost-sorcery'), 'Congelamento Súbito', 'reaction'::rpg.action_economy_bucket, 14, NULL, NULL, false, 'Reação: dano Gélido + Criar Gelo', 'Reação quando criatura a 1,5 m acerta você: dano Gélido = mod. Carisma + metade do nível de Feiticeiro. Pode usar Criar Gelo como parte da Reação.', 'flash-freeze', NULL, 102),

-- Astral Griffon Patron
('warlock-griffon-planar-escape', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'astral-griffon-patron'), 'Escape Planar', 'reaction'::rpg.action_economy_bucket, 6, NULL, NULL, false, 'Reação: metade dano + semiplano', 'Reação ao sofrer dano: metade do dano, desaparece em semiplano até fim do próximo turno ou retorno voluntário. 1× / Descanso Curto ou Longo.', 'planar-escape', NULL, 100),
('warlock-griffon-astral-clarity', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'astral-griffon-patron'), 'Clareza Astral', 'action'::rpg.action_economy_bucket, 10, 'astral-clarity', NULL, true, 'Ação Mágica: Visão Verdadeira 9 m (usos = Carisma)', 'Por 10 min: Vantagem em Percepção visual e Visão Verdadeira 9 m. Usos = mod. de Carisma (mín. 1) / Descanso Longo.', 'astral-clarity', NULL, 101),
('warlock-griffon-pocketeer-shunt', (SELECT id FROM rpg.phb_class WHERE slug = 'warlock'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'astral-griffon-patron'), 'Bolseiro (enviar)', 'action'::rpg.action_economy_bucket, 14, NULL, NULL, false, 'Ação Mágica: objeto ao bolso dimensional', 'Ação Mágica: envia objeto à vista a até 9 m (não vestido) ao bolso dimensional. Se carregado, salvaguarda de Sabedoria. Retorna no fim do seu próximo turno se não recuperado.', 'pocketeer-shunt', NULL, 102),

-- Materializer
('wizard-materializer-dismiss-cubes', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'materializer'), 'Dispersar Cubos', 'bonus'::rpg.action_economy_bucket, 3, NULL, NULL, false, 'AB: dispersa Cubos de Criação Menor', 'Ação Bônus: dispersa qualquer número de Cubos criados com Criação Menor. Pode detonar em vez de dispersar simples.', 'dismiss-cubes', NULL, 100),
('wizard-materializer-cube-detonation', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'materializer'), 'Detonação de Cubo', 'bonus'::rpg.action_economy_bucket, 3, 'cube-detonation', NULL, true, 'Ação Bônus: detona Cubo — salv. de Destreza', 'Ao dispersar, detona Cubo: raio 3 m, salvaguarda de Destreza vs. CD de magia, dano de Força = 1d6 + metade do nível de Mago. Usos = mod. de Inteligência (mín. 1) / Descanso Longo.', 'cube-detonation', NULL, 101),
('wizard-materializer-material-enhancement', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'materializer'), 'Aprimoramento Material', 'action'::rpg.action_economy_bucket, 6, NULL, NULL, false, 'Ação Mágica: toque objeto — até 2 benefícios', 'Ação Mágica: toque arma, armadura ou objeto e concede até 2 benefícios mágicos até fim do próximo Descanso Curto ou Longo. 2 usos por benefício / Descanso Curto ou Longo.', 'material-enhancement', NULL, 102),
('wizard-materializer-rematerialize', (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'), (SELECT id FROM rpg.phb_subclass WHERE slug = 'materializer'), 'Rematerializar', 'reaction'::rpg.action_economy_bucket, 14, 'rematerialize', NULL, true, 'Reação: guarda destroços; recria em 8 h', 'Reação ao ver objeto/estrutura Grande ou menor não mágico destruído a até 18 m: destroços somem. Até 8 h depois, ação Mágica recria intacto a até 18 m. 1× / Descanso Longo.', 'rematerialize', NULL, 103)
ON CONFLICT (action_id) DO UPDATE SET
  class_id = EXCLUDED.class_id,
  subclass_id = EXCLUDED.subclass_id,
  name = EXCLUDED.name,
  economy = EXCLUDED.economy,
  unlock_level = EXCLUDED.unlock_level,
  resource_slug = EXCLUDED.resource_slug,
  free_resource_slug = EXCLUDED.free_resource_slug,
  always_spends_resource = EXCLUDED.always_spends_resource,
  summary = EXCLUDED.summary,
  description = EXCLUDED.description,
  table_action = EXCLUDED.table_action,
  spend_amount = EXCLUDED.spend_amount,
  sort_order = EXCLUDED.sort_order;
