-- Economy actions — Grim Hollow Cap. 2 (piloto: Caçador de Monstros + guildas)

INSERT INTO rpg.phb_class_economy_action (
  action_id, class_id, subclass_id, name, economy, unlock_level,
  resource_slug, free_resource_slug, always_spends_resource,
  summary, description, table_action, spend_amount, sort_order
) VALUES
(
  'monster-hunter-studied-response',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  NULL,
  'Resposta Estudada',
  'reaction'::rpg.action_economy_bucket,
  2,
  NULL,
  NULL,
  false,
  'Reação: ataque antes do ataque inimigo (18 m)',
  'Quando uma criatura que você possa ver a até 18 m de você mirar em você ou outro com um ataque corpo a corpo ou à distância, você pode usar sua Reação antes da jogada de ataque para fazer um ataque com uma arma ou um Ataque Desarmado contra essa criatura. Se o ataque errar, você recupera o uso da Reação.',
  'studied-response',
  NULL,
  120
),
(
  'monster-hunter-slayer-aid',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  NULL,
  'Auxílio do Exterminador',
  'reaction'::rpg.action_economy_bucket,
  17,
  NULL,
  NULL,
  false,
  'Com Resposta Estudada: aliado também ataca',
  'Quando você usa Resposta Estudada, escolha um aliado que possa ver ou ouvir você. Ele pode usar a Reação para atacar o agressor (arma ou Ataque Desarmado). Se não tiver Reação, recupera-na e deve usá-la no ataque. O ataque do aliado ocorre após o seu e antes do ataque do alvo.',
  'slayer-aid',
  NULL,
  121
),
(
  'monster-hunter-grave-strike',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  NULL,
  'Golpe Sepulcral',
  'free'::rpg.action_economy_bucket,
  20,
  'grave-strike',
  NULL,
  true,
  'Crítico vs tipo do grimório: CD = dano (máx. 30)',
  'Em um Acerto Crítico contra um tipo do seu Grimório de Monstros, o alvo faz salvaguarda de Constituição (CD = dano causado, máx. 30). Falha: cai a 0 PV. Sucesso: dano normal. Usos = mod. Inteligência (mín. 1); recupera no Descanso Longo.',
  'grave-strike',
  NULL,
  122
),
(
  'monster-hunter-carver-close-quarters',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'carver-guild'),
  'Corpo a Corpo',
  'reaction'::rpg.action_economy_bucket,
  3,
  NULL,
  NULL,
  false,
  'Reação ao acertar corpo a corpo: +2d6 (4d6 nv. 11; 6d6 nv. 15)',
  'Ao acertar com arma corpo a corpo, Reação: +2d6 do mesmo tipo (4d6 no nv. 11; 6d6 no nv. 15). O alvo tem Desvantagem na próxima jogada de ataque antes do início do seu próximo turno.',
  'close-quarters',
  NULL,
  130
),
(
  'monster-hunter-devourer-consume-portion',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'devourer-guild'),
  'Consumir Porção',
  'bonus'::rpg.action_economy_bucket,
  3,
  'devourer-portion',
  NULL,
  true,
  'AB: gasta porção → benefício metabólico',
  'Ação Bônus para consumir uma porção de monstro (pool na Economia). Efeito conforme a porção preparada — marque na mesa.',
  'consume-portion',
  1,
  131
),
(
  'monster-hunter-devourer-harvest-portion',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'devourer-guild'),
  'Colher Porção',
  'action'::rpg.action_economy_bucket,
  3,
  NULL,
  NULL,
  false,
  'Ação: colhe porção de cadáver elegível',
  'Ação para colher uma porção de um cadáver de monstro elegível. Porções máximas ≈ 1 + mod. Inteligência (recupera no Descanso Longo).',
  'harvest-portion',
  NULL,
  132
),
(
  'monster-hunter-trapper-elemental-ammo',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'trapper-guild'),
  'Munição Elemental',
  'bonus'::rpg.action_economy_bucket,
  3,
  NULL,
  NULL,
  false,
  'AB: aplica gadget em munição',
  'Ação Bônus para aplicar um gadget de armadilheiro em munição (ver Trapper Gadgets).',
  'elemental-ammo',
  NULL,
  140
),
(
  'monster-hunter-trapper-runic-bomb',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'trapper-guild'),
  'Bomba Rúnica',
  'bonus'::rpg.action_economy_bucket,
  3,
  NULL,
  NULL,
  false,
  'AB: arremessa bomba rúnica',
  'Ação Bônus para arremessar uma Bomba Rúnica (gadget). CD do gadget = 8 + mod. Inteligência + Bônus de Proficiência.',
  'runic-bomb',
  NULL,
  141
),
(
  'monster-hunter-trapper-agile-response',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'trapper-guild'),
  'Resposta Ágil',
  'reaction'::rpg.action_economy_bucket,
  10,
  NULL,
  NULL,
  false,
  'Reação vs corpo a corpo: Desvantagem + Resposta Estudada',
  'Quando um inimigo faz ataque corpo a corpo contra você, Reação: impõe Desvantagem na jogada e usa Resposta Estudada na mesma Reação; depois move até metade da Velocidade.',
  'agile-response',
  NULL,
  142
),
(
  'monster-hunter-occultist-arcane-response',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'occultist-guild'),
  'Resposta Arcana',
  'action'::rpg.action_economy_bucket,
  18,
  NULL,
  NULL,
  false,
  'Com Resposta Estudada: conjura magia de ação no alvo',
  'Ao usar Resposta Estudada, você pode conjurar uma magia com tempo de conjuração de ação que tenha apenas aquele alvo.',
  'arcane-response',
  NULL,
  150
)
ON CONFLICT (action_id) DO UPDATE SET
  class_id = EXCLUDED.class_id,
  subclass_id = EXCLUDED.subclass_id,
  name = EXCLUDED.name,
  economy = EXCLUDED.economy,
  unlock_level = EXCLUDED.unlock_level,
  resource_slug = EXCLUDED.resource_slug,
  summary = EXCLUDED.summary,
  description = EXCLUDED.description,
  table_action = EXCLUDED.table_action,
  sort_order = EXCLUDED.sort_order;
