-- Economy actions — Grim Hollow Cap. 2 (piloto: Caçador de Monstros + guildas)

INSERT INTO rpg.phb_class_economy_action (
  action_id, class_id, subclass_id, name, economy, unlock_level,
  resource_slug, free_resource_slug, always_spends_resource,
  summary, description, table_action, spend_amount, sort_order
) VALUES
(
  'monster-hunter-studied-response',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  NULL,
  'Resposta Estudada',
  'reaction'::rpg.action_economy_bucket,
  2,
  NULL,
  NULL,
  false,
  'Reação: ataque antes do ataque inimigo (18 m)',
  'Quando uma criatura que você possa ver a até 18 m de você mirar em você ou outro com um ataque corpo a corpo ou à distância, você pode usar sua Reação antes da jogada de ataque para fazer um ataque com uma arma ou um Ataque Desarmado contra essa criatura. Se o ataque errar, você recupera o uso da Reação.',
  'studied-response',
  NULL,
  120
),
(
  'monster-hunter-slayer-aid',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  NULL,
  'Auxílio do Exterminador',
  'reaction'::rpg.action_economy_bucket,
  17,
  NULL,
  NULL,
  false,
  'Com Resposta Estudada: aliado também ataca',
  'Quando você usa Resposta Estudada, escolha um aliado que possa ver ou ouvir você. Ele pode usar a Reação para atacar o agressor (arma ou Ataque Desarmado). Se não tiver Reação, recupera-na e deve usá-la no ataque. O ataque do aliado ocorre após o seu e antes do ataque do alvo.',
  'slayer-aid',
  NULL,
  121
),
(
  'monster-hunter-grave-strike',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  NULL,
  'Golpe Sepulcral',
  'free'::rpg.action_economy_bucket,
  20,
  'grave-strike',
  NULL,
  true,
  'Crítico vs tipo do grimório: CD = dano (máx. 30)',
  'Em um Acerto Crítico contra um tipo do seu Grimório de Monstros, o alvo faz salvaguarda de Constituição (CD = dano causado, máx. 30). Falha: cai a 0 PV. Sucesso: dano normal. Usos = mod. Inteligência (mín. 1); recupera no Descanso Longo.',
  'grave-strike',
  NULL,
  122
),
(
  'monster-hunter-carver-close-quarters',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'carver-guild'),
  'Corpo a Corpo',
  'reaction'::rpg.action_economy_bucket,
  3,
  NULL,
  NULL,
  false,
  'Reação ao acertar corpo a corpo: +2d6 (4d6 nv. 11; 6d6 nv. 15)',
  'Ao acertar com arma corpo a corpo, Reação: +2d6 do mesmo tipo (4d6 no nv. 11; 6d6 no nv. 15). O alvo tem Desvantagem na próxima jogada de ataque antes do início do seu próximo turno.',
  'close-quarters',
  NULL,
  130
),
(
  'monster-hunter-devourer-consume-portion',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'devourer-guild'),
  'Consumir Porção',
  'bonus'::rpg.action_economy_bucket,
  3,
  'devourer-portion',
  NULL,
  true,
  'AB: gasta porção → benefício metabólico',
  'Ação Bônus para consumir uma porção de monstro (pool na Economia). Efeito conforme a porção preparada — marque na mesa.',
  'consume-portion',
  1,
  131
),
(
  'monster-hunter-devourer-harvest-portion',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'devourer-guild'),
  'Colher Porção',
  'action'::rpg.action_economy_bucket,
  3,
  NULL,
  NULL,
  false,
  'Ação: colhe porção de cadáver elegível',
  'Ação para colher uma porção de um cadáver de monstro elegível. Porções máximas ≈ 1 + mod. Inteligência (recupera no Descanso Longo).',
  'harvest-portion',
  NULL,
  132
),
(
  'monster-hunter-trapper-elemental-ammo',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'trapper-guild'),
  'Munição Elemental',
  'bonus'::rpg.action_economy_bucket,
  3,
  NULL,
  NULL,
  false,
  'AB: aplica gadget em munição',
  'Ação Bônus para aplicar um gadget de armadilheiro em munição (ver Trapper Gadgets).',
  'elemental-ammo',
  NULL,
  140
),
(
  'monster-hunter-trapper-runic-bomb',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'trapper-guild'),
  'Bomba Rúnica',
  'bonus'::rpg.action_economy_bucket,
  3,
  NULL,
  NULL,
  false,
  'AB: arremessa bomba rúnica',
  'Ação Bônus para arremessar uma Bomba Rúnica (gadget). CD do gadget = 8 + mod. Inteligência + Bônus de Proficiência.',
  'runic-bomb',
  NULL,
  141
),
(
  'monster-hunter-trapper-agile-response',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'trapper-guild'),
  'Resposta Ágil',
  'reaction'::rpg.action_economy_bucket,
  10,
  NULL,
  NULL,
  false,
  'Reação vs corpo a corpo: Desvantagem + Resposta Estudada',
  'Quando um inimigo faz ataque corpo a corpo contra você, Reação: impõe Desvantagem na jogada e usa Resposta Estudada na mesma Reação; depois move até metade da Velocidade.',
  'agile-response',
  NULL,
  142
),
(
  'monster-hunter-occultist-arcane-response',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'occultist-guild'),
  'Resposta Arcana',
  'action'::rpg.action_economy_bucket,
  18,
  NULL,
  NULL,
  false,
  'Com Resposta Estudada: conjura magia de ação no alvo',
  'Ao usar Resposta Estudada, você pode conjurar uma magia com tempo de conjuração de ação que tenha apenas aquele alvo.',
  'arcane-response',
  NULL,
  150
),
-- Carver Guild — completar AE (piloto)
(
  'monster-hunter-carver-true-grit',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'carver-guild'),
  'Determinação Inabalável',
  'reaction'::rpg.action_economy_bucket,
  7,
  NULL,
  NULL,
  false,
  'Ao acertar em Reação: encerra Amedrontado (18 m)',
  'Vantagem em salvaguardas contra Amedrontado; imune a Amedrontado de tipos do Grimório. Além disso, ao acertar com um ataque como parte de uma Reação, escolha uma criatura Amedrontada a até 18 m que possa vê-lo (incluindo você): a condição termina nela.',
  'true-grit',
  NULL,
  133
),
(
  'monster-hunter-carver-terrorize',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'carver-guild'),
  'Aterrorizar os Terrores',
  'reaction'::rpg.action_economy_bucket,
  10,
  NULL,
  NULL,
  false,
  'Ao acertar em Reação: alvo Sab ou Amedrontado',
  'Ao acertar com um ataque como parte de uma Reação, force o alvo a uma salvaguarda de Sabedoria (CD = 8 + mod. Inteligência + PB) ou fica Amedrontado até o fim do seu próximo turno.',
  'terrorize-the-terrors',
  NULL,
  134
),
(
  'monster-hunter-carver-controlled-footwork',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'carver-guild'),
  'Passos Controlados',
  'free'::rpg.action_economy_bucket,
  18,
  NULL,
  NULL,
  false,
  'Duas Reações por rodada',
  'Você pode usar Reação duas vezes por rodada, em vez de uma.',
  'controlled-footwork',
  NULL,
  135
),
-- Devourer Guild — completar AE
(
  'monster-hunter-devourer-synchronized-response',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'devourer-guild'),
  'Resposta Sincronizada',
  'free'::rpg.action_economy_bucket,
  7,
  NULL,
  NULL,
  false,
  'Após consumir porção: +1d6 em ataques de Reação (1 min)',
  'Ao consumir uma porção de monstro, por 1 minuto seus ataques feitos como parte de uma Reação causam +1d6 do mesmo tipo da arma ou Ataque Desarmado.',
  'synchronized-response',
  NULL,
  136
),
(
  'monster-hunter-devourer-destroy-decoction',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'devourer-guild'),
  'Destruir Decocção',
  'action'::rpg.action_economy_bucket,
  15,
  NULL,
  NULL,
  false,
  'Utilizar: destrói uma decocção ativa',
  'Ação Utilizar para destruir uma decocção não consumida. (Criar decocção: 1 h + 20 PO com Suprimentos de Alquimista; máx. 4 ativas.)',
  'destroy-decoction',
  NULL,
  137
),
(
  'monster-hunter-devourer-acquired-taste',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'devourer-guild'),
  'Paladar Adquirido',
  'free'::rpg.action_economy_bucket,
  18,
  NULL,
  NULL,
  false,
  '+1 porção segura; após consumir: Vantagem em ataques de Reação (1 min)',
  'Você pode consumir 1 porção adicional com segurança. Além disso, por 1 minuto após consumir uma porção, você tem Vantagem nas jogadas de ataque feitas como parte de uma Reação.',
  'acquired-taste',
  NULL,
  138
),
-- Trapper Guild — completar AE (gadgets + armadura + tinkerer)
(
  'monster-hunter-trapper-set-weretrap',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'trapper-guild'),
  'Armadilha Weretrap',
  'action'::rpg.action_economy_bucket,
  3,
  NULL,
  NULL,
  false,
  'Utilizar: arma a Weretrap (ou arremessa)',
  'Ação Utilizar para armar uma Weretrap em espaço desocupado a 1,5 m. Criatura que entrar: salvaguarda de Destreza ou 3d10 Contundente + Caído (metade só no sucesso). Também pode ser arremessada como arma leve (9 m / 18 m).',
  'set-weretrap',
  NULL,
  143
),
(
  'monster-hunter-trapper-scorpion-anchor',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'trapper-guild'),
  'Âncora Escorpião',
  'free'::rpg.action_economy_bucket,
  3,
  NULL,
  NULL,
  false,
  'Munição: alvo Restringido (Atletismo vs CD gadget)',
  'Dispare a Âncora Escorpião com arco/besta como parte de um Ataque. Ao acertar, o alvo fica Restringido até escapar (Força/Atletismo vs CD dos Gadgets) ou morrer.',
  'scorpion-anchor',
  NULL,
  144
),
(
  'monster-hunter-trapper-phase-leap',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'trapper-guild'),
  'Salto de Fase',
  'bonus'::rpg.action_economy_bucket,
  15,
  'trapper-phase-leap',
  NULL,
  true,
  'AB: teleporta até 18 m (3×/LR; mod. armadura)',
  'Com Armadura de Pele de Monstro e a modificação Salto de Fase: Ação Bônus para teletransportar até 18 m a um espaço desocupado que você possa ver. 3 usos; recupera no Descanso Longo.',
  'phase-leap',
  1,
  145
),
(
  'monster-hunter-trapper-armor-regen',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'trapper-guild'),
  'Regeneração da Armadura',
  'bonus'::rpg.action_economy_bucket,
  15,
  'trapper-regen-dice',
  NULL,
  true,
  'AB: gasta d10 da pool + mod. Constituição em PV',
  'Com a modificação Regeneração na Armadura de Pele de Monstro: Ação Bônus, gaste 1 dado da pool (6d10), some o mod. Constituição e recupere esse total em PV. Recupera a pool no Descanso Longo.',
  'armor-regen',
  1,
  146
),
(
  'monster-hunter-trapper-rapid-tinkerer',
  (SELECT id FROM rpg.phb_class WHERE slug = 'monster-hunter'),
  (SELECT id FROM rpg.phb_subclass WHERE slug = 'trapper-guild'),
  'Engenho Rápido',
  'action'::rpg.action_economy_bucket,
  18,
  'trapper-rapid-tinker',
  NULL,
  true,
  '1 min: cria gadget sem PO (2×/LR)',
  'Gaste 1 minuto para criar um Gadget de Armadilheiro sem gastar PO ou componentes. 2 usos; recupera no Descanso Longo.',
  'rapid-tinkerer',
  1,
  147
)
ON CONFLICT (action_id) DO UPDATE SET
  class_id = EXCLUDED.class_id,
  subclass_id = EXCLUDED.subclass_id,
  name = EXCLUDED.name,
  economy = EXCLUDED.economy,
  unlock_level = EXCLUDED.unlock_level,
  resource_slug = EXCLUDED.resource_slug,
  summary = EXCLUDED.summary,
  description = EXCLUDED.description,
  table_action = EXCLUDED.table_action,
  sort_order = EXCLUDED.sort_order;
