import type { FeatureGatesByOwnerSlug } from '../feature-gates';
import type { FeatureScheduleBand } from '../feature-schedule';
import type { SizeCategory } from "../equipment/creature-size";
import type { WeaponCharm } from "../equipment/weapon-charm";

export type EquippedWeaponPiece = {
  itemSlug: string;
  itemName: string;
  category: string;
  damage: string | null;
  damageType: string | null;
  versatileDamage: string | null;
  propertySlugs: string[];
  equipmentSlot: "main_hand" | "off_hand" | string;
  masterySlug?: string | null;
  masteryName?: string | null;
  reloadCapacity?: number | null;
  attachedCharmSlug?: string | null;
  attachedCharmName?: string | null;
  weaponCharm?: WeaponCharm | null;
  attachedCoverageSlug?: string | null;
  attachedCoverageName?: string | null;
  coverageAttackBonus?: number;
  coverageDamageBonus?: number;
};

export type WeaponAttackContext = {
  proficiencyBonus: number;
  weaponProficiencySlugs: readonly string[];
  featureSchedules: readonly FeatureScheduleBand[];
  featureGatesBySubclassSlug?: FeatureGatesByOwnerSlug;
  featSlugs?: readonly string[];
  fightingStyleSlugs?: readonly string[];
  sizeCategory?: SizeCategory;
  hasShield?: boolean;
  masteredWeaponSlugs?: readonly string[];
  itemAttackBonus?: number;
  itemDamageBonus?: number;
  classSlug?: string | null;
  level?: number;
  subclassSlug?: string | null;
  rageActive?: boolean;
  recklessActive?: boolean;
  unarmedDamageDie?: string | null;
  featEffects?: readonly import("@game/effects").CatalogEffect[];
};

export type WeaponAttackRole = "main" | "light_bonus" | "dual_bonus";

export type WeaponAttack = {
  itemSlug: string;
  itemName: string;
  mode: "melee" | "ranged";
  attackBonus: number;
  abilitySlug: "forca" | "destreza";
  proficient: boolean;
  damageDice: string;
  damageBonus: number;
  damageType: string | null;
  attackNote: string;
  damageNote: string;
  role: WeaponAttackRole;
  attackDisadvantage: boolean;
  omitsAbilityDamage: boolean;
  greatWeaponFighting: boolean;
  masteryActive: boolean;
  masterySlug: string | null;
  masteryName: string | null;
  nickUsesAttackAction: boolean;
  grazeOnMissDamage: number | null;
  isFirearm: boolean;
  critThreshold: number;
  overkillExtraDice: string | null;
  reloadCapacity: number | null;
  hasRecoil: boolean;
  rageDamageBonus: number;
  brutalStrikeDice: string | null;
  divineFuryDice: string | null;
  sneakAttackEligible: boolean;
  quickStrikeDice: string | null;
  ignoresReload: boolean;
  martialArtsDie: string | null;
  attachedCharmSlug: string | null;
  attachedCharmName: string | null;
  attachedCoverageSlug: string | null;
  attachedCoverageName: string | null;
};
