/**
 * Imports relativos para o NFT da Vercel incluir entities no bundle.
 * Carregado por main.ts apos register-path-aliases.
 */

import './phb-ability-generation-method.entity';
import './phb-ability.entity';
import './phb-alignment.entity';
import './phb-character-level.entity';
import './phb-edition.entity';
import './phb-eldritch-invocation.entity';
import './phb-feat-ref.entity';
import './phb-fighting-style.entity';
import './phb-item.entity';
import './phb-language.entity';
import './phb-metamagic.entity';
import './phb-option.entity';
import './phb-skill.entity';
import './phb-species-trait.entity';
import './phb-species.entity';
import './phb-subclass-ref.entity';
import './phb-weapon-mastery.entity';
import './phb-weapon-property.entity';
import './phb-weapon.entity';
import './views/v-class-spell-slots.entity';
import './views/v-phb-armor.entity';
import './views/v-phb-background-equipment.entity';
import './views/v-phb-background-language.entity';
import './views/v-phb-background-skill.entity';
import './views/v-phb-background-tool-option.entity';
import './views/v-phb-background.entity';
import './views/v-phb-battle-master-maneuver.entity';
import './views/v-phb-beastborne-aspect-benefit.entity';
import './views/v-phb-class-economy-action.entity';
import './views/v-phb-class-equipment.entity';
import './views/v-phb-class-feature.entity';
import './views/v-phb-class-granted-spell.entity';
import './views/v-phb-class-panel-action.entity';
import './views/v-phb-class-progression.entity';
import './views/v-phb-class-skill-choice.entity';
import './views/v-phb-class.entity';
import './views/v-phb-cunning-strike-effect.entity';
import './views/v-phb-dungeoneer-slayer-type.entity';
import './views/v-phb-feat-granted-spell.entity';
import './views/v-phb-feat.entity';
import './views/v-phb-gunslinger-maneuver.entity';
import './views/v-phb-hp-bonus-source.entity';
import './views/v-phb-persona-mask.entity';
import './views/v-phb-species-granted-spell.entity';
import './views/v-phb-species-trait-choices.entity';
import './views/v-phb-spell.entity';
import './views/v-phb-subclass-mechanics.entity';
import './views/v-phb-subclass-precaution-spell.entity';
import './views/v-phb-subclass-prepared-spell.entity';
import './views/v-phb-subclass-table-action.entity';
import './views/v-phb-subclass.entity';
import './views/v-phb-unarmored-defense.entity';
import './views/v-spell-by-class.entity';
import './views/v-subclass-spell-slots.entity';