-- Seed Valda spell ↔ class
-- Gerado de docs/sources/valda-spire-of-secrets/extracted.json

INSERT INTO rpg.phb_spell_class (spell_id, class_id)
VALUES
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'accelerate-decelerate'), (SELECT id FROM rpg.phb_class WHERE slug = 'bard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'accelerate-decelerate'), (SELECT id FROM rpg.phb_class WHERE slug = 'cleric')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'accelerate-decelerate'), (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'accelerate-decelerate'), (SELECT id FROM rpg.phb_class WHERE slug = 'wizard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'clue'), (SELECT id FROM rpg.phb_class WHERE slug = 'bard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'clue'), (SELECT id FROM rpg.phb_class WHERE slug = 'cleric')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'clue'), (SELECT id FROM rpg.phb_class WHERE slug = 'druid')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'clue'), (SELECT id FROM rpg.phb_class WHERE slug = 'paladin')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'clue'), (SELECT id FROM rpg.phb_class WHERE slug = 'ranger')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'clue'), (SELECT id FROM rpg.phb_class WHERE slug = 'wizard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'delay'), (SELECT id FROM rpg.phb_class WHERE slug = 'bard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'delay'), (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'delay'), (SELECT id FROM rpg.phb_class WHERE slug = 'wizard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'dire-warning'), (SELECT id FROM rpg.phb_class WHERE slug = 'cleric')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'dire-warning'), (SELECT id FROM rpg.phb_class WHERE slug = 'wizard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'defenestration'), (SELECT id FROM rpg.phb_class WHERE slug = 'bard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'defenestration'), (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'defenestration'), (SELECT id FROM rpg.phb_class WHERE slug = 'wizard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'mandy-s-feral-follower'), (SELECT id FROM rpg.phb_class WHERE slug = 'wizard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'finger-guns'), (SELECT id FROM rpg.phb_class WHERE slug = 'bard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'finger-guns'), (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'finger-guns'), (SELECT id FROM rpg.phb_class WHERE slug = 'wizard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'game-of-fate'), (SELECT id FROM rpg.phb_class WHERE slug = 'bard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'game-of-fate'), (SELECT id FROM rpg.phb_class WHERE slug = 'wizard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'hangover'), (SELECT id FROM rpg.phb_class WHERE slug = 'bard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'hangover'), (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'hangover'), (SELECT id FROM rpg.phb_class WHERE slug = 'wizard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'memorize'), (SELECT id FROM rpg.phb_class WHERE slug = 'bard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'memorize'), (SELECT id FROM rpg.phb_class WHERE slug = 'cleric')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'memorize'), (SELECT id FROM rpg.phb_class WHERE slug = 'wizard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'moment-to-think'), (SELECT id FROM rpg.phb_class WHERE slug = 'cleric')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'moment-to-think'), (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'moment-to-think'), (SELECT id FROM rpg.phb_class WHERE slug = 'wizard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'paradox'), (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'paradox'), (SELECT id FROM rpg.phb_class WHERE slug = 'warlock')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'paradox'), (SELECT id FROM rpg.phb_class WHERE slug = 'wizard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'polybrachia'), (SELECT id FROM rpg.phb_class WHERE slug = 'druid')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'polybrachia'), (SELECT id FROM rpg.phb_class WHERE slug = 'paladin')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'polybrachia'), (SELECT id FROM rpg.phb_class WHERE slug = 'ranger')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'polybrachia'), (SELECT id FROM rpg.phb_class WHERE slug = 'warlock')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'recall'), (SELECT id FROM rpg.phb_class WHERE slug = 'sorcerer')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'recall'), (SELECT id FROM rpg.phb_class WHERE slug = 'wizard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'rumor'), (SELECT id FROM rpg.phb_class WHERE slug = 'bard')),
  ((SELECT id FROM rpg.phb_spell WHERE slug = 'rumor'), (SELECT id FROM rpg.phb_class WHERE slug = 'wizard'))
ON CONFLICT DO NOTHING;
