-- Cantrips ofensivos PHB tipados para skirmish/duelo (PVE-1a)
INSERT INTO rpg.phb_spell_combat (
  spell_slug,
  resolution,
  label,
  damage_die,
  flat_per_die,
  auto_unit_base,
  auto_unit_per_slot_above_base,
  dice_count_base,
  dice_per_slot_above_base,
  spell_level,
  cantrip_scale,
  per_die_attack,
  include_spellcasting_mod,
  save_success_outcome,
  save_ability_slug,
  damage_type_slug
) VALUES
  ('chicote-de-espinhos', 'spell_attack', 'Chicote de Espinhos', 6, 0, NULL, NULL, NULL, NULL, 0, TRUE, FALSE, FALSE, NULL, NULL, 'piercing'),
  ('criar-chamas', 'spell_attack', 'Criar Chamas', 8, 0, NULL, NULL, NULL, NULL, 0, TRUE, FALSE, FALSE, NULL, NULL, 'fire'),
  ('explosao-elemental', 'spell_attack', 'Explosão Elemental', 8, 0, NULL, NULL, NULL, NULL, 0, TRUE, FALSE, FALSE, NULL, NULL, 'fire'),
  ('fagulha-estelar', 'spell_attack', 'Fagulha Estelar', 8, 0, NULL, NULL, NULL, NULL, 0, TRUE, FALSE, FALSE, NULL, NULL, 'radiant'),
  ('raio-de-gelo', 'spell_attack', 'Raio de Gelo', 8, 0, NULL, NULL, NULL, NULL, 0, TRUE, FALSE, FALSE, NULL, NULL, 'cold'),
  ('raio-mistico', 'spell_attack', 'Raio Místico', 10, 0, NULL, NULL, NULL, NULL, 0, TRUE, TRUE, FALSE, NULL, NULL, 'force'),
  ('rajada-de-veneno', 'spell_attack', 'Rajada de Veneno', 12, 0, NULL, NULL, NULL, NULL, 0, TRUE, FALSE, FALSE, NULL, NULL, 'poison'),
  ('toque-chocante', 'spell_attack', 'Toque Chocante', 8, 0, NULL, NULL, NULL, NULL, 0, TRUE, FALSE, FALSE, NULL, NULL, 'lightning'),
  ('toque-necrotico', 'spell_attack', 'Toque Necrótico', 10, 0, NULL, NULL, NULL, NULL, 0, TRUE, FALSE, FALSE, NULL, NULL, 'necrotic'),
  ('badalar-funebre', 'save_damage', 'Badalar Fúnebre', 8, 0, NULL, NULL, NULL, NULL, 0, TRUE, FALSE, FALSE, 'none', 'sabedoria', 'necrotic'),
  ('bolha-acida', 'save_damage', 'Bolha Ácida', 6, 0, NULL, NULL, NULL, NULL, 0, TRUE, FALSE, FALSE, 'none', 'destreza', 'acid'),
  ('chama-sagrada', 'save_damage', 'Chama Sagrada', 8, 0, NULL, NULL, NULL, NULL, 0, TRUE, FALSE, FALSE, 'none', 'destreza', 'radiant'),
  ('palavra-de-radiancia', 'save_damage', 'Palavra de Radiância', 6, 0, NULL, NULL, NULL, NULL, 0, TRUE, FALSE, FALSE, 'none', 'constituicao', 'radiant'),
  ('talho-mental', 'save_damage', 'Talho Mental', 6, 0, NULL, NULL, NULL, NULL, 0, TRUE, FALSE, FALSE, 'none', 'inteligencia', 'psychic'),
  ('trovao', 'save_damage', 'Trovão', 6, 0, NULL, NULL, NULL, NULL, 0, TRUE, FALSE, FALSE, 'none', 'constituicao', 'thunder'),
  ('zombaria-perversa', 'save_damage', 'Zombaria Perversa', 6, 0, NULL, NULL, NULL, NULL, 0, TRUE, FALSE, FALSE, 'none', 'sabedoria', 'psychic')
ON CONFLICT (spell_slug) DO UPDATE SET
  resolution = EXCLUDED.resolution,
  label = EXCLUDED.label,
  damage_die = EXCLUDED.damage_die,
  flat_per_die = EXCLUDED.flat_per_die,
  auto_unit_base = EXCLUDED.auto_unit_base,
  auto_unit_per_slot_above_base = EXCLUDED.auto_unit_per_slot_above_base,
  dice_count_base = EXCLUDED.dice_count_base,
  dice_per_slot_above_base = EXCLUDED.dice_per_slot_above_base,
  spell_level = EXCLUDED.spell_level,
  cantrip_scale = EXCLUDED.cantrip_scale,
  per_die_attack = EXCLUDED.per_die_attack,
  include_spellcasting_mod = EXCLUDED.include_spellcasting_mod,
  save_success_outcome = EXCLUDED.save_success_outcome,
  save_ability_slug = EXCLUDED.save_ability_slug,
  damage_type_slug = EXCLUDED.damage_type_slug;
