-- Condições tipadas via save (PVE-3b): Hold Person, Fear…
INSERT INTO rpg.phb_spell_combat (
  spell_slug,
  resolution,
  label,
  damage_die,
  flat_per_die,
  auto_unit_base,
  auto_unit_per_slot_above_base,
  dice_count_base,
  dice_per_slot_above_base,
  spell_level,
  cantrip_scale,
  per_die_attack,
  include_spellcasting_mod,
  save_success_outcome,
  save_ability_slug,
  damage_type_slug,
  condition_slug
) VALUES
  (
    'paralisar-pessoa',
    'apply_condition',
    'Paralisar Pessoa',
    NULL,
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    2,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    'sabedoria',
    NULL,
    'paralyzed'
  ),
  (
    'medo',
    'apply_condition',
    'Medo',
    NULL,
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    3,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    'sabedoria',
    NULL,
    'frightened'
  )
ON CONFLICT (spell_slug) DO UPDATE SET
  resolution = EXCLUDED.resolution,
  label = EXCLUDED.label,
  damage_die = EXCLUDED.damage_die,
  flat_per_die = EXCLUDED.flat_per_die,
  auto_unit_base = EXCLUDED.auto_unit_base,
  auto_unit_per_slot_above_base = EXCLUDED.auto_unit_per_slot_above_base,
  dice_count_base = EXCLUDED.dice_count_base,
  dice_per_slot_above_base = EXCLUDED.dice_per_slot_above_base,
  spell_level = EXCLUDED.spell_level,
  cantrip_scale = EXCLUDED.cantrip_scale,
  per_die_attack = EXCLUDED.per_die_attack,
  include_spellcasting_mod = EXCLUDED.include_spellcasting_mod,
  save_success_outcome = EXCLUDED.save_success_outcome,
  save_ability_slug = EXCLUDED.save_ability_slug,
  damage_type_slug = EXCLUDED.damage_type_slug,
  condition_slug = EXCLUDED.condition_slug;
