-- Maestrias de arma avançadas (Grim Hollow Cap. 5)

INSERT INTO rpg.phb_weapon_mastery (slug, name, description)
VALUES
  ('brutal', 'Brutal', 'Uma arma Brutal é feita para dano máximo. Armas Brutais marcam Acertos Críticos em 19 ou 20 natural. Se sua margem crítica já estiver aumentada, aumente-a em 1 ponto (de 19–20 para 18–20, por exemplo). Ao marcar um Acerto Crítico com uma arma Brutal contra uma criatura, a arma causa um dado de dano adicional.'),
  ('defending', 'Defensiva', 'Uma arma Defensiva é feita para aparar ou traz técnicas avançadas de parada. Ao empunhar uma arma Defensiva, você pode usar sua Reação quando for atingido por uma jogada de ataque corpo a corpo. Role 1d4 e some o resultado à sua CA contra o ataque que a disparou.'),
  ('disarming', 'Desarmar', 'Uma arma de Desarmar pode prender a arma do inimigo e arrancá-la de suas mãos. Ao usar a ação Atacar no seu turno e acertar com uma arma de Desarmar, você pode usar uma Ação Bônus ainda no mesmo turno para desarmar o alvo. Você e o alvo fazem jogadas de ataque opostas, ignorando Vantagem e Desvantagem. Se o seu resultado for maior e a arma puder ser largada, ela cai no espaço do alvo. Se o seu resultado vencedor foi um Acerto Crítico, você pode escolher que a arma caia em um espaço à sua escolha em até 4,5 m do alvo ou na sua mão livre.'),
  ('entangling', 'Enredar', 'Ao usar a ação Atacar no seu turno e acertar com uma arma de Enredar, você pode usar uma Ação Bônus ainda no mesmo turno para enredar o alvo. O alvo deve passar em uma salvaguarda de Destreza (CD 10 + seu Bônus de Proficiência) ou recebe a condição Agarrado até escapar ou até você soltar a arma. Alvos Enormes ou maiores passam automaticamente. Para escapar, o alvo usa uma ação para fazer um teste de Força (Atletismo) ou Destreza (Acrobacia) contra a mesma CD. Em sucesso, deixa de estar Agarrado. Enquanto uma criatura estiver Agarrada por esta arma, você não pode usá-la para atacar outra criatura.'),
  ('returning', 'Retorno', 'Uma arma de Retorno pode ser arremessada de modo a voltar para você. Ao fazer um ataque à distância com uma arma de Retorno, ela volta imediatamente após acertar ou errar. Você pode pegá-la se tiver uma mão livre.'),
  ('scatter', 'Dispersão', 'Armas de Dispersão podem devastar vários inimigos de uma vez. Ao usar a ação Atacar e acertar uma criatura com uma arma de Dispersão, meça o alcance de dispersão a partir do espaço do alvo (ou de um quadrado que uma criatura Grande ou maior ocupa). Criaturas além do alvo original dentro do alcance de dispersão sofrem dano igual a 1 + seu modificador de Destreza (mínimo 2), do mesmo tipo que você causou ao alvo original.'),
  ('set', 'Preparada', 'Armas com a propriedade Preparada permitem antecipar um ataque iminente. Se um alvo entrar no seu alcance enquanto você empunha uma arma com esta propriedade, você pode usar sua Reação para fazer um ataque corpo a corpo com a arma contra esse alvo.'),
  ('strong-draw', 'Tensão Forte', 'Uma arma com Tensão Forte exige grande força. Você tem Desvantagem em jogadas de ataque com uma arma de Tensão Forte, a menos que sua Força seja 13 ou superior. Você soma os modificadores de Força e Destreza ao dano com uma arma de Tensão Forte.'),
  ('swift', 'Rápida', 'Armas Rápidas ajudam a se recuperar rapidamente de ataques errados. Ao errar com uma arma Rápida, você tem Vantagem na primeira jogada de ataque com a mesma arma contra o mesmo alvo antes do fim do seu próximo turno. Se esse ataque acertar, causa 1d4 de dano extra do tipo normal da arma.')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description;
