-- Armas avançadas Grim Hollow (Cap. 5)

INSERT INTO rpg.phb_item (slug, item_type, name, cost, weight, description, properties)
VALUES
  ('catchpole', 'weapon'::rpg.item_type, 'Catchpole', '{"text":"500 PO"}'::jsonb, '2,5 kg', 'Arma avançada de Grim Hollow (Catchpole). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["hafted","reach","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"entangling"}'::jsonb),
  ('cavalry-flail', 'weapon'::rpg.item_type, 'Cavalry Flail', '{"text":"500 PO"}'::jsonb, '1,5 kg', 'Arma avançada de Grim Hollow (Cavalry Flail). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["momentum"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"swift","momentumDice":"1d12"}'::jsonb),
  ('cavalry-hammer', 'weapon'::rpg.item_type, 'Cavalry Hammer', '{"text":"500 PO"}'::jsonb, '1,5 kg', 'Arma avançada de Grim Hollow (Cavalry Hammer). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["armor-piercing","momentum"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"slow","momentumDice":"1d12"}'::jsonb),
  ('cavalry-pick', 'weapon'::rpg.item_type, 'Cavalry Pick', '{"text":"500 PO"}'::jsonb, '1,5 kg', 'Arma avançada de Grim Hollow (Cavalry Pick). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["armor-piercing","momentum"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"sap","momentumDice":"1d12"}'::jsonb),
  ('chakram', 'weapon'::rpg.item_type, 'Chakram', '{"text":"500 PO"}'::jsonb, '500 g', 'Arma avançada de Grim Hollow (Chakram). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["finesse","light","thrown"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"returning","range":{"normal":45,"max":180}}'::jsonb),
  ('claymore', 'weapon'::rpg.item_type, 'Claymore', '{"text":"500 PO"}'::jsonb, '3,5 kg', 'Arma avançada de Grim Hollow (Claymore). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["heavy","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"brutal"}'::jsonb),
  ('double-blade', 'weapon'::rpg.item_type, 'Double Blade', '{"text":"500 PO"}'::jsonb, '2,5 kg', 'Arma avançada de Grim Hollow (Double Blade). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["double","momentum","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"set","momentumDice":"1d10"}'::jsonb),
  ('double-spear', 'weapon'::rpg.item_type, 'Double Spear', '{"text":"500 PO"}'::jsonb, '2 kg', 'Arma avançada de Grim Hollow (Double Spear). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["double","momentum","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"set","momentumDice":"1d10"}'::jsonb),
  ('elite-rapier', 'weapon'::rpg.item_type, 'Elite Rapier', '{"text":"500 PO"}'::jsonb, '1 kg', 'Arma avançada de Grim Hollow (Elite Rapier). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["finesse"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"swift"}'::jsonb),
  ('fighting-chain', 'weapon'::rpg.item_type, 'Fighting Chain', '{"text":"500 PO"}'::jsonb, '1,5 kg', 'Arma avançada de Grim Hollow (Fighting Chain). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["double","finesse","reach","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"disarming"}'::jsonb),
  ('fighting-chain-brutal', 'weapon'::rpg.item_type, 'Fighting Chain, Brutal', '{"text":"750 PO"}'::jsonb, '3 kg', 'Arma avançada de Grim Hollow (Fighting Chain, Brutal). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["double","finesse","reach","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"brutal"}'::jsonb),
  ('fighting-chain-hook', 'weapon'::rpg.item_type, 'Fighting Chain, Hook', '{"text":"500 PO"}'::jsonb, '1,5 kg', 'Arma avançada de Grim Hollow (Fighting Chain, Hook). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["damage","double","finesse","reach","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"entangling","damageTypes":["Piercing"]}'::jsonb),
  ('fighting-chain-sickle', 'weapon'::rpg.item_type, 'Fighting Chain, Sickle', '{"text":"500 PO"}'::jsonb, '1,5 kg', 'Arma avançada de Grim Hollow (Fighting Chain, Sickle). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["damage","double","finesse","reach","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"entangling","damageTypes":["Slashing"]}'::jsonb),
  ('gladiator-net', 'weapon'::rpg.item_type, 'Gladiator Net', '{"text":"350 PO"}'::jsonb, '2,5 kg', 'Arma avançada de Grim Hollow (Gladiator Net). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["thrown"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"entangling","range":{"normal":15,"max":45}}'::jsonb),
  ('guardian-poleaxe', 'weapon'::rpg.item_type, 'Guardian Poleaxe', '{"text":"750 PO"}'::jsonb, '4,5 kg', 'Arma avançada de Grim Hollow (Guardian Poleaxe). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["damage","hafted","heavy","reach","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"set","damageTypes":["Piercing"]}'::jsonb),
  ('knightly-lance', 'weapon'::rpg.item_type, 'Knightly Lance', '{"text":"500 PO"}'::jsonb, '3 kg', 'Arma avançada de Grim Hollow (Knightly Lance). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["momentum","reach","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"set","momentumDice":"2d10"}'::jsonb),
  ('knightly-sword', 'weapon'::rpg.item_type, 'Knightly Sword', '{"text":"750 PO"}'::jsonb, '1,5 kg', 'Arma avançada de Grim Hollow (Knightly Sword). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["versatile"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"defending","versatileDamage":"1d10"}'::jsonb),
  ('military-fork', 'weapon'::rpg.item_type, 'Military Fork', '{"text":"500 PO"}'::jsonb, '4 kg', 'Arma avançada de Grim Hollow (Military Fork). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["hafted","heavy","reach","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"disarming"}'::jsonb),
  ('parrying-dagger', 'weapon'::rpg.item_type, 'Parrying Dagger', '{"text":"350 PO"}'::jsonb, '500 g', 'Arma avançada de Grim Hollow (Parrying Dagger). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["finesse","light","thrown"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"disarming","range":{"normal":30,"max":90}}'::jsonb),
  ('polearm', 'weapon'::rpg.item_type, 'Polearm', '{"text":"500 PO"}'::jsonb, '6 kg', 'Arma avançada de Grim Hollow (Polearm). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["hafted","heavy","reach","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"set"}'::jsonb),
  ('punching-dagger', 'weapon'::rpg.item_type, 'Punching Dagger', '{"text":"300 PO"}'::jsonb, '500 g', 'Arma avançada de Grim Hollow (Punching Dagger). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["armor-piercing","finesse","light"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"defending"}'::jsonb),
  ('returning-club', 'weapon'::rpg.item_type, 'Returning Club', '{"text":"300 PO"}'::jsonb, '1 kg', 'Arma avançada de Grim Hollow (Returning Club). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["light","thrown"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"returning","range":{"normal":30,"max":90}}'::jsonb),
  ('sabre', 'weapon'::rpg.item_type, 'Sabre', '{"text":"500 PO"}'::jsonb, '1 kg', 'Arma avançada de Grim Hollow (Sabre). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["finesse"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"swift"}'::jsonb),
  ('sheathed-staff', 'weapon'::rpg.item_type, 'Sheathed Staff', '{"text":"500 PO"}'::jsonb, '3 kg', 'Arma avançada de Grim Hollow (Sheathed Staff). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["double","versatile"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"topple","versatileDamage":"1d8"}'::jsonb),
  ('side-handle-baton', 'weapon'::rpg.item_type, 'Side-handle Baton', '{"text":"500 PO"}'::jsonb, '1 kg', 'Arma avançada de Grim Hollow (Side-handle Baton). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["finesse","light"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"swift"}'::jsonb),
  ('wrath-axe', 'weapon'::rpg.item_type, 'Wrath Axe', '{"text":"750 PO"}'::jsonb, '6 kg', 'Arma avançada de Grim Hollow (Wrath Axe). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["hafted","momentum","heavy","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"brutal","momentumDice":"2d8"}'::jsonb),
  ('wrath-maul', 'weapon'::rpg.item_type, 'Wrath Maul', '{"text":"750 PO"}'::jsonb, '7,5 kg', 'Arma avançada de Grim Hollow (Wrath Maul). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["hafted","momentum","heavy","two-handed"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"brutal","momentumDice":"2d8"}'::jsonb),
  ('arbalest', 'weapon'::rpg.item_type, 'Arbalest', '{"text":"750 PO"}'::jsonb, '10 kg', 'Arma avançada de Grim Hollow (Arbalest). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["heavy","two-handed","loading","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","range":{"normal":120,"max":450}}'::jsonb),
  ('blackpowder-pistol', 'weapon'::rpg.item_type, 'Blackpowder Pistol', '{"text":"200 PO"}'::jsonb, '2 kg', 'Arma avançada de Grim Hollow (Blackpowder Pistol). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["blackpowder","light","loading","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"vex","range":{"normal":30,"max":120}}'::jsonb),
  ('blackpowder-rifle', 'weapon'::rpg.item_type, 'Blackpowder Rifle', '{"text":"500 PO"}'::jsonb, '5 kg', 'Arma avançada de Grim Hollow (Blackpowder Rifle). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["blackpowder","two-handed","loading","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"slow","range":{"normal":120,"max":450}}'::jsonb),
  ('blunderbuss-grim-hollow', 'weapon'::rpg.item_type, 'Blunderbuss', '{"text":"750 PO"}'::jsonb, '5 kg', 'Arma avançada de Grim Hollow (Blunderbuss). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["blackpowder","cumbersome","two-handed","loading","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"scatter","range":{"normal":45,"max":135}}'::jsonb),
  ('blunderbuss-hand', 'weapon'::rpg.item_type, 'Blunderbuss, Hand', '{"text":"500 PO"}'::jsonb, '2 kg', 'Arma avançada de Grim Hollow (Blunderbuss, Hand). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["blackpowder","loading","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"scatter","range":{"normal":22.5,"max":90}}'::jsonb),
  ('composite-longbow', 'weapon'::rpg.item_type, 'Composite Longbow', '{"text":"750 PO"}'::jsonb, '1 kg', 'Arma avançada de Grim Hollow (Composite Longbow). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["heavy","two-handed","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","range":{"normal":300,"max":900}}'::jsonb),
  ('composite-shortbow', 'weapon'::rpg.item_type, 'Composite Shortbow', '{"text":"400 PO"}'::jsonb, '1 kg', 'Arma avançada de Grim Hollow (Composite Shortbow). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["two-handed","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","range":{"normal":150,"max":600}}'::jsonb),
  ('dragon-pistol', 'weapon'::rpg.item_type, 'Dragon Pistol', '{"text":"350 PO"}'::jsonb, '2 kg', 'Arma avançada de Grim Hollow (Dragon Pistol). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["blackpowder","loading","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"scatter"}'::jsonb),
  ('dragon-rifle', 'weapon'::rpg.item_type, 'Dragon Rifle', '{"text":"750 PO"}'::jsonb, '2 kg', 'Arma avançada de Grim Hollow (Dragon Rifle). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["blackpowder","loading","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"scatter"}'::jsonb),
  ('flame-bellows', 'weapon'::rpg.item_type, 'Flame Bellows', '{"text":"750 PO"}'::jsonb, '5,5 kg', 'Arma avançada de Grim Hollow (Flame Bellows). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["cumbersome","magazine","two-handed","loading","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"scatter","magazine":"20"}'::jsonb),
  ('repeater-crossbow', 'weapon'::rpg.item_type, 'Repeater Crossbow', '{"text":"750 PO"}'::jsonb, '3,5 kg', 'Arma avançada de Grim Hollow (Repeater Crossbow). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["magazine","repeater","two-handed","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"slow","range":{"normal":120,"max":450},"magazine":"6"}'::jsonb),
  ('repeater-crossbow-hand', 'weapon'::rpg.item_type, 'Repeater Crossbow, Hand', '{"text":"500 PO"}'::jsonb, '1,5 kg', 'Arma avançada de Grim Hollow (Repeater Crossbow, Hand). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["magazine","repeater","light","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"vex","range":{"normal":45,"max":180},"magazine":"3"}'::jsonb),
  ('repeater-crossbow-heavy', 'weapon'::rpg.item_type, 'Repeater Crossbow, Heavy', '{"text":"1,000 PO"}'::jsonb, '10 kg', 'Arma avançada de Grim Hollow (Repeater Crossbow, Heavy). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["magazine","repeater","heavy","two-handed","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","range":{"normal":150,"max":600},"magazine":"9"}'::jsonb),
  ('repeater-needler', 'weapon'::rpg.item_type, 'Repeater Needler', '{"text":"500 PO"}'::jsonb, '1,5 kg', 'Arma avançada de Grim Hollow (Repeater Needler). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["magazine","repeater","light","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"vex","range":{"normal":45,"max":180},"magazine":"6"}'::jsonb),
  ('repeater-slinger', 'weapon'::rpg.item_type, 'Repeater Slinger', '{"text":"750 PO"}'::jsonb, '4,5 kg', 'Arma avançada de Grim Hollow (Repeater Slinger). Requer proficiência em Armas Avançadas para usar propriedades especiais e maestria.', '{"propertyIds":["magazine","repeater","two-handed","ammunition"],"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","masteryId":"slow","range":{"normal":120,"max":450},"magazine":"9"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  cost = EXCLUDED.cost,
  weight = EXCLUDED.weight,
  description = EXCLUDED.description,
  properties = EXCLUDED.properties,
  item_type = EXCLUDED.item_type;

INSERT INTO rpg.phb_weapon (item_id, category, damage, damage_type, mastery_id)
VALUES
  ((SELECT id FROM rpg.phb_item WHERE slug = 'catchpole'), 'advanced'::rpg.weapon_category, '1d6', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'entangling')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'cavalry-flail'), 'advanced'::rpg.weapon_category, '1d8', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'swift')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'cavalry-hammer'), 'advanced'::rpg.weapon_category, '1d8', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'slow')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'cavalry-pick'), 'advanced'::rpg.weapon_category, '1d8', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'sap')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'chakram'), 'advanced'::rpg.weapon_category, '1d6', 'Cortante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'returning')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'claymore'), 'advanced'::rpg.weapon_category, '2d6', 'Cortante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'brutal')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'double-blade'), 'advanced'::rpg.weapon_category, '1d6', 'Cortante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'set')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'double-spear'), 'advanced'::rpg.weapon_category, '1d6', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'set')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'elite-rapier'), 'advanced'::rpg.weapon_category, '1d8', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'swift')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain'), 'advanced'::rpg.weapon_category, '1d4', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'disarming')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-brutal'), 'advanced'::rpg.weapon_category, '1d6', 'Cortante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'brutal')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-hook'), 'advanced'::rpg.weapon_category, '1d4', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'entangling')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-sickle'), 'advanced'::rpg.weapon_category, '1d4', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'entangling')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'gladiator-net'), 'advanced'::rpg.weapon_category, '1d6', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'entangling')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'guardian-poleaxe'), 'advanced'::rpg.weapon_category, '1d10', 'Cortante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'set')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'knightly-lance'), 'advanced'::rpg.weapon_category, '2d6', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'set')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'knightly-sword'), 'advanced'::rpg.weapon_category, '1d8', 'Cortante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'defending')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'military-fork'), 'advanced'::rpg.weapon_category, '2d6', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'disarming')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'parrying-dagger'), 'advanced'::rpg.weapon_category, '1d4', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'disarming')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'polearm'), 'advanced'::rpg.weapon_category, '1d12', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'set')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'punching-dagger'), 'advanced'::rpg.weapon_category, '1d4', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'defending')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'returning-club'), 'advanced'::rpg.weapon_category, '1d4', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'returning')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'sabre'), 'advanced'::rpg.weapon_category, '1d8', 'Cortante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'swift')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'sheathed-staff'), 'advanced'::rpg.weapon_category, '1d6', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'topple')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'side-handle-baton'), 'advanced'::rpg.weapon_category, '1d4', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'swift')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-axe'), 'advanced'::rpg.weapon_category, '2d6', 'Cortante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'brutal')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-maul'), 'advanced'::rpg.weapon_category, '2d6', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'brutal')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'arbalest'), 'advanced'::rpg.weapon_category, '2d6', 'Perfurante', NULL),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-pistol'), 'advanced'::rpg.weapon_category, '2d4', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'vex')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-rifle'), 'advanced'::rpg.weapon_category, '2d6', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'slow')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-grim-hollow'), 'advanced'::rpg.weapon_category, '2d6', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'scatter')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-hand'), 'advanced'::rpg.weapon_category, '2d4', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'scatter')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'composite-longbow'), 'advanced'::rpg.weapon_category, '1d8', 'Perfurante', NULL),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'composite-shortbow'), 'advanced'::rpg.weapon_category, '1d6', 'Perfurante', NULL),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'dragon-pistol'), 'advanced'::rpg.weapon_category, '2d4', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'scatter')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'dragon-rifle'), 'advanced'::rpg.weapon_category, '2d6', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'scatter')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'flame-bellows'), 'advanced'::rpg.weapon_category, '2d6', 'Fire', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'scatter')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow'), 'advanced'::rpg.weapon_category, '1d8', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'slow')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-hand'), 'advanced'::rpg.weapon_category, '1d6', 'Perfurante', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'vex')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-heavy'), 'advanced'::rpg.weapon_category, '1d10', 'Perfurante', NULL),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-needler'), 'advanced'::rpg.weapon_category, '1 Piercing', 'null', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'vex')),
  ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-slinger'), 'advanced'::rpg.weapon_category, '1d8', 'Contundente', (SELECT id FROM rpg.phb_weapon_mastery WHERE slug = 'slow'))
ON CONFLICT (item_id) DO UPDATE SET
  category = EXCLUDED.category,
  damage = EXCLUDED.damage,
  damage_type = EXCLUDED.damage_type,
  mastery_id = EXCLUDED.mastery_id;

INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'catchpole'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'hafted')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'catchpole'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'reach')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'catchpole'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'cavalry-flail'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'momentum')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'cavalry-hammer'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'armor-piercing')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'cavalry-hammer'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'momentum')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'cavalry-pick'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'armor-piercing')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'cavalry-pick'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'momentum')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'chakram'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'chakram'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'light')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'chakram'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'thrown')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'claymore'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'heavy')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'claymore'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'double-blade'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'double')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'double-blade'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'momentum')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'double-blade'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'double-spear'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'double')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'double-spear'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'momentum')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'double-spear'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'elite-rapier'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'double')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'reach')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-brutal'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'double')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-brutal'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-brutal'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'reach')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-brutal'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-hook'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'damage')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-hook'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'double')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-hook'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-hook'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'reach')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-hook'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-sickle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'damage')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-sickle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'double')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-sickle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-sickle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'reach')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'fighting-chain-sickle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'gladiator-net'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'thrown')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'guardian-poleaxe'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'damage')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'guardian-poleaxe'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'hafted')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'guardian-poleaxe'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'heavy')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'guardian-poleaxe'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'reach')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'guardian-poleaxe'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'knightly-lance'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'momentum')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'knightly-lance'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'reach')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'knightly-lance'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'knightly-sword'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'versatile')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'military-fork'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'hafted')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'military-fork'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'heavy')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'military-fork'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'reach')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'military-fork'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'parrying-dagger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'parrying-dagger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'light')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'parrying-dagger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'thrown')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'polearm'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'hafted')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'polearm'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'heavy')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'polearm'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'reach')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'polearm'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'punching-dagger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'armor-piercing')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'punching-dagger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'punching-dagger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'light')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'returning-club'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'light')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'returning-club'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'thrown')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'sabre'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'sheathed-staff'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'double')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'sheathed-staff'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'versatile')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'side-handle-baton'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'finesse')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'side-handle-baton'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'light')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-axe'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'hafted')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-axe'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'momentum')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-axe'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'heavy')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-axe'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-maul'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'hafted')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-maul'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'momentum')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-maul'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'heavy')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'wrath-maul'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'arbalest'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'heavy')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'arbalest'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'arbalest'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'loading')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'arbalest'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-pistol'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'blackpowder')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-pistol'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'light')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-pistol'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'loading')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-pistol'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-rifle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'blackpowder')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-rifle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-rifle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'loading')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blackpowder-rifle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-grim-hollow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'blackpowder')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-grim-hollow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'cumbersome')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-grim-hollow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-grim-hollow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'loading')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-grim-hollow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-hand'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'blackpowder')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-hand'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'loading')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'blunderbuss-hand'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'composite-longbow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'heavy')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'composite-longbow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'composite-longbow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'composite-shortbow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'composite-shortbow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'dragon-pistol'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'blackpowder')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'dragon-pistol'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'loading')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'dragon-pistol'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'dragon-rifle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'blackpowder')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'dragon-rifle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'loading')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'dragon-rifle'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'flame-bellows'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'cumbersome')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'flame-bellows'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'magazine')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'flame-bellows'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'flame-bellows'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'loading')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'flame-bellows'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'magazine')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'repeater')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-hand'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'magazine')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-hand'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'repeater')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-hand'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'light')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-hand'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-heavy'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'magazine')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-heavy'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'repeater')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-heavy'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'heavy')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-heavy'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-crossbow-heavy'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-needler'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'magazine')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-needler'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'repeater')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-needler'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'light')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-needler'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-slinger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'magazine')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-slinger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'repeater')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-slinger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'two-handed')) ON CONFLICT DO NOTHING;
INSERT INTO rpg.phb_weapon_property_link (weapon_id, property_id) VALUES ((SELECT id FROM rpg.phb_item WHERE slug = 'repeater-slinger'), (SELECT id FROM rpg.phb_weapon_property WHERE slug = 'ammunition')) ON CONFLICT DO NOTHING;
