-- Equipamento avançado Grim Hollow (Cap. 5)

INSERT INTO rpg.phb_item (slug, item_type, name, cost, weight, description, properties)
VALUES
  ('blessed-stake', 'gear'::rpg.item_type, 'Blessed Stake', '{"text":"250 PO"}'::jsonb, '50 g', 'Equipamento avançado de Grim Hollow (Blessed Stake).', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment"}'::jsonb),
  ('breath-of-beleth-poison', 'gear'::rpg.item_type, 'Breath of Beleth', '{"text":"150 PO"}'::jsonb, '125 g', 'Equipamento avançado de Grim Hollow (Breath of Beleth).', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment"}'::jsonb),
  ('buckler-grim-hollow', 'gear'::rpg.item_type, 'Buckler', '{"text":"20 PO"}'::jsonb, '2 kg', 'Equipamento avançado de Grim Hollow (Buckler).', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment"}'::jsonb),
  ('concealed-blade', 'gear'::rpg.item_type, 'Concealed Blade', '{"text":"50 PO"}'::jsonb, '1 kg', 'Equipamento avançado de Grim Hollow (Concealed Blade).', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment"}'::jsonb),
  ('fire-bomb', 'gear'::rpg.item_type, 'Fire Bomb', '{"text":"100 PO"}'::jsonb, '250 g', 'Equipamento avançado de Grim Hollow (Fire Bomb).', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment"}'::jsonb),
  ('grappling-gun', 'gear'::rpg.item_type, 'Grappling Gun', '{"text":"200 PO"}'::jsonb, '1,5 kg', 'Equipamento avançado de Grim Hollow (Grappling Gun).', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment"}'::jsonb),
  ('hunters-armor', 'gear'::rpg.item_type, 'Hunter’s Armor', '{"text":"+500 PO"}'::jsonb, NULL, 'Equipamento avançado de Grim Hollow (Hunter’s Armor).', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment"}'::jsonb),
  ('iron-net', 'gear'::rpg.item_type, 'Iron Net', '{"text":"150 PO"}'::jsonb, '10 kg', 'Equipamento avançado de Grim Hollow (Iron Net).', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment"}'::jsonb),
  ('mastercraft-instrument', 'gear'::rpg.item_type, 'Mastercraft Instrument', '{"text":"+250 PO"}'::jsonb, NULL, 'Equipamento avançado de Grim Hollow (Mastercraft Instrument).', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment"}'::jsonb),
  ('noisemaker', 'gear'::rpg.item_type, 'Noisemaker', '{"text":"50 PO"}'::jsonb, '2,5 kg', 'Equipamento avançado de Grim Hollow (Noisemaker).', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment"}'::jsonb),
  ('prosthetics', 'gear'::rpg.item_type, 'Prosthetics', '{"text":"500 PO"}'::jsonb, '5 kg', 'Equipamento avançado de Grim Hollow (Prosthetics).', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment"}'::jsonb),
  ('retractable-shield', 'gear'::rpg.item_type, 'Retractable Shield', '{"text":"300 PO"}'::jsonb, '3 kg', 'Equipamento avançado de Grim Hollow (Retractable Shield).', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment"}'::jsonb),
  ('seeing-glass', 'gear'::rpg.item_type, 'Seeing Glass', '{"text":"300 PO"}'::jsonb, '1,5 kg', 'Equipamento avançado de Grim Hollow (Seeing Glass).', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment"}'::jsonb),
  ('shadowsteel-focus', 'gear'::rpg.item_type, 'Shadowsteel Focus', '{"text":"500 PO"}'::jsonb, NULL, 'Equipamento avançado de Grim Hollow (Shadowsteel Focus).', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment"}'::jsonb),
  ('smoke-bomb', 'gear'::rpg.item_type, 'Smoke Bomb', '{"text":"50 PO"}'::jsonb, '1,5 kg', 'Equipamento avançado de Grim Hollow (Smoke Bomb).', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment"}'::jsonb),
  ('stitching-needle', 'gear'::rpg.item_type, 'Stitching Needle', '{"text":"250 PO"}'::jsonb, '25 g', 'Equipamento avançado de Grim Hollow (Stitching Needle).', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment"}'::jsonb),
  ('tower-shield-grim-hollow', 'gear'::rpg.item_type, 'Tower Shield', '{"text":"200 PO"}'::jsonb, '25 kg', 'Equipamento avançado de Grim Hollow (Tower Shield).', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment"}'::jsonb),
  ('watchers-candle', 'gear'::rpg.item_type, 'Watcher’s Candle', '{"text":"250 PO"}'::jsonb, '125 g', 'Equipamento avançado de Grim Hollow (Watcher’s Candle).', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  cost = EXCLUDED.cost,
  weight = EXCLUDED.weight,
  description = EXCLUDED.description,
  properties = EXCLUDED.properties,
  item_type = EXCLUDED.item_type;
