-- Munição avançada Grim Hollow (Cap. 5)

INSERT INTO rpg.phb_item (slug, item_type, name, cost, weight, description, properties)
VALUES
  ('arrows-and-bolts-bludgeoning-1', 'gear'::rpg.item_type, 'Bludgeoning (1)', '{"text":"5 CP"}'::jsonb, '50 g', 'Equipamento avançado de Grim Hollow (Bludgeoning (1)).', '{"ammunition":true,"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","propertyIds":[]}'::jsonb),
  ('arrows-and-bolts-ranging-1', 'gear'::rpg.item_type, 'Ranging (1)', '{"text":"1 SP"}'::jsonb, '13 g', 'Equipamento avançado de Grim Hollow (Ranging (1)).', '{"ammunition":true,"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","propertyIds":[]}'::jsonb),
  ('arrows-and-bolts-slashing-1', 'gear'::rpg.item_type, 'Slashing (1)', '{"text":"1 SP"}'::jsonb, '50 g', 'Equipamento avançado de Grim Hollow (Slashing (1)).', '{"ammunition":true,"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","propertyIds":[]}'::jsonb),
  ('arrows-and-bolts-whistling-1', 'gear'::rpg.item_type, 'Whistling (1)', '{"text":"1 SP"}'::jsonb, '25 g', 'Equipamento avançado de Grim Hollow (Whistling (1)).', '{"ammunition":true,"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","propertyIds":[]}'::jsonb),
  ('sling-bullets-piercing-1', 'gear'::rpg.item_type, 'Piercing (1)', '{"text":"1 CP"}'::jsonb, '50 g', 'Equipamento avançado de Grim Hollow (Piercing (1)).', '{"ammunition":true,"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","propertyIds":[]}'::jsonb),
  ('sling-bullets-ranging-1', 'gear'::rpg.item_type, 'Ranging (1)', '{"text":"5 CP"}'::jsonb, '25 g', 'Equipamento avançado de Grim Hollow (Ranging (1)).', '{"ammunition":true,"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","propertyIds":[]}'::jsonb),
  ('sling-bullets-whistling-1', 'gear'::rpg.item_type, 'Whistling (1)', '{"text":"5 CP"}'::jsonb, '25 g', 'Equipamento avançado de Grim Hollow (Whistling (1)).', '{"ammunition":true,"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","propertyIds":[]}'::jsonb),
  ('alchemical-ammunition-arrow-1', 'gear'::rpg.item_type, 'Arrow (1)', '{"text":"75 PO"}'::jsonb, '100 g', 'Equipamento avançado de Grim Hollow (Arrow (1)).', '{"ammunition":true,"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","propertyIds":[]}'::jsonb),
  ('alchemical-ammunition-bolt-1', 'gear'::rpg.item_type, 'Bolt (1)', '{"text":"75 PO"}'::jsonb, '100 g', 'Equipamento avançado de Grim Hollow (Bolt (1)).', '{"ammunition":true,"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","propertyIds":[]}'::jsonb),
  ('alchemical-ammunition-sling-bullet-1', 'gear'::rpg.item_type, 'Sling Bullet (1)', '{"text":"55 PO"}'::jsonb, '100 g', 'Equipamento avançado de Grim Hollow (Sling Bullet (1)).', '{"ammunition":true,"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","propertyIds":[]}'::jsonb),
  ('specialized-ammunition-arrow-5', 'gear'::rpg.item_type, 'Arrow (5)', '{"text":"100 PO"}'::jsonb, '125 g', 'Equipamento avançado de Grim Hollow (Arrow (5)).', '{"ammunition":true,"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","propertyIds":[]}'::jsonb),
  ('specialized-ammunition-bolt-5', 'gear'::rpg.item_type, 'Bolt (5)', '{"text":"100 PO"}'::jsonb, '250 g', 'Equipamento avançado de Grim Hollow (Bolt (5)).', '{"ammunition":true,"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","propertyIds":[]}'::jsonb),
  ('specialized-ammunition-paper-cartridge-bullet-10', 'gear'::rpg.item_type, 'Paper Cartridge Bullet (10)', '{"text":"250 PO"}'::jsonb, '250 g', 'Equipamento avançado de Grim Hollow (Paper Cartridge Bullet (10)).', '{"ammunition":true,"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","propertyIds":[]}'::jsonb),
  ('specialized-ammunition-sling-bullet-5', 'gear'::rpg.item_type, 'Sling Bullet (5)', '{"text":"100 PO"}'::jsonb, '250 g', 'Equipamento avançado de Grim Hollow (Sling Bullet (5)).', '{"ammunition":true,"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","propertyIds":[]}'::jsonb),
  ('other-ranged-ammunition-bellows-cannister', 'gear'::rpg.item_type, 'Bellows Cannister (20 shots)', '{"text":"5 PO"}'::jsonb, '2 kg', 'Equipamento avançado de Grim Hollow (Bellows Cannister (20 shots)).', '{"ammunition":true,"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","propertyIds":[]}'::jsonb),
  ('other-ranged-ammunition-dragon-shot', 'gear'::rpg.item_type, 'Dragon Shot (20)', '{"text":"5 PO"}'::jsonb, '1 kg', 'Equipamento avançado de Grim Hollow (Dragon Shot (20)).', '{"ammunition":true,"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","propertyIds":[]}'::jsonb),
  ('other-ranged-ammunition-magazine', 'gear'::rpg.item_type, 'Magazine', '{"text":"5 PO"}'::jsonb, '500 g', 'Equipamento avançado de Grim Hollow (Magazine).', '{"ammunition":true,"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","propertyIds":[]}'::jsonb),
  ('other-ranged-ammunition-paper-cartridge-bullet', 'gear'::rpg.item_type, 'Paper Cartridge Bullet (20)', '{"text":"3 PO"}'::jsonb, '1 kg', 'Equipamento avançado de Grim Hollow (Paper Cartridge Bullet (20)).', '{"ammunition":true,"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","propertyIds":[]}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  cost = EXCLUDED.cost,
  weight = EXCLUDED.weight,
  description = EXCLUDED.description,
  properties = EXCLUDED.properties,
  item_type = EXCLUDED.item_type;
