-- Munição avançada Grim Hollow (Cap. 5)

INSERT INTO rpg.phb_item (slug, item_type, name, cost, weight, description, properties)
VALUES
  ('arrows-and-bolts-bludgeoning-1', 'gear'::rpg.item_type, 'Flecha/Virote Contundente (1)', '{"text":"5 CP"}'::jsonb, '50 g', 'Munição avançada de Grim Hollow. Exige proficiência na arma que dispara a munição e nível 3 ou superior.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"ammunition","advancedRequirement":{"kind":"advanced-ammunition","minLevel":3,"requiresWeaponProficiency":true},"ammunition":true,"propertyIds":[],"section":"arrows-and-bolts","damageType":"bludgeoning","halvesMaxRange":true}'::jsonb),
  ('arrows-and-bolts-ranging-1', 'gear'::rpg.item_type, 'Flecha/Virote de Alcance Estendido (1)', '{"text":"1 SP"}'::jsonb, '13 g', 'Munição avançada de Grim Hollow. Exige proficiência na arma que dispara a munição e nível 3 ou superior.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"ammunition","advancedRequirement":{"kind":"advanced-ammunition","minLevel":3,"requiresWeaponProficiency":true},"ammunition":true,"propertyIds":["ranging"],"section":"arrows-and-bolts"}'::jsonb),
  ('arrows-and-bolts-slashing-1', 'gear'::rpg.item_type, 'Flecha/Virote Cortante (1)', '{"text":"1 SP"}'::jsonb, '50 g', 'Munição avançada de Grim Hollow. Exige proficiência na arma que dispara a munição e nível 3 ou superior.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"ammunition","advancedRequirement":{"kind":"advanced-ammunition","minLevel":3,"requiresWeaponProficiency":true},"ammunition":true,"propertyIds":[],"section":"arrows-and-bolts","damageType":"slashing","halvesMaxRange":true}'::jsonb),
  ('arrows-and-bolts-whistling-1', 'gear'::rpg.item_type, 'Flecha/Virote Assobiadora (1)', '{"text":"1 SP"}'::jsonb, '25 g', 'Munição avançada de Grim Hollow. Exige proficiência na arma que dispara a munição e nível 3 ou superior.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"ammunition","advancedRequirement":{"kind":"advanced-ammunition","minLevel":3,"requiresWeaponProficiency":true},"ammunition":true,"propertyIds":["whistling"],"section":"arrows-and-bolts","damageType":"bludgeoning","halvesMaxRange":true}'::jsonb),
  ('sling-bullets-piercing-1', 'gear'::rpg.item_type, 'Projétil de Funda Perfurante (1)', '{"text":"1 CP"}'::jsonb, '50 g', 'Munição avançada de Grim Hollow. Exige proficiência na arma que dispara a munição e nível 3 ou superior.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"ammunition","advancedRequirement":{"kind":"advanced-ammunition","minLevel":3,"requiresWeaponProficiency":true},"ammunition":true,"propertyIds":[],"section":"sling-bullets","damageType":"piercing","halvesMaxRange":true}'::jsonb),
  ('sling-bullets-ranging-1', 'gear'::rpg.item_type, 'Projétil de Funda de Alcance Estendido (1)', '{"text":"5 CP"}'::jsonb, '25 g', 'Munição avançada de Grim Hollow. Exige proficiência na arma que dispara a munição e nível 3 ou superior.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"ammunition","advancedRequirement":{"kind":"advanced-ammunition","minLevel":3,"requiresWeaponProficiency":true},"ammunition":true,"propertyIds":["ranging"],"section":"sling-bullets"}'::jsonb),
  ('sling-bullets-whistling-1', 'gear'::rpg.item_type, 'Projétil de Funda Assobiador (1)', '{"text":"5 CP"}'::jsonb, '25 g', 'Munição avançada de Grim Hollow. Exige proficiência na arma que dispara a munição e nível 3 ou superior.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"ammunition","advancedRequirement":{"kind":"advanced-ammunition","minLevel":3,"requiresWeaponProficiency":true},"ammunition":true,"propertyIds":["whistling"],"section":"sling-bullets","damageType":"bludgeoning","halvesMaxRange":true}'::jsonb),
  ('alchemical-ammunition-arrow-1', 'gear'::rpg.item_type, 'Flecha Alquímica (1)', '{"text":"75 PO"}'::jsonb, '100 g', 'Munição avançada de Grim Hollow. Exige proficiência na arma que dispara a munição e nível 3 ou superior.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"ammunition","advancedRequirement":{"kind":"advanced-ammunition","minLevel":3,"requiresWeaponProficiency":true},"ammunition":true,"propertyIds":[],"section":"alchemical-ammunition","alchemical":true}'::jsonb),
  ('alchemical-ammunition-bolt-1', 'gear'::rpg.item_type, 'Virote Alquímico (1)', '{"text":"75 PO"}'::jsonb, '100 g', 'Munição avançada de Grim Hollow. Exige proficiência na arma que dispara a munição e nível 3 ou superior.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"ammunition","advancedRequirement":{"kind":"advanced-ammunition","minLevel":3,"requiresWeaponProficiency":true},"ammunition":true,"propertyIds":[],"section":"alchemical-ammunition","alchemical":true}'::jsonb),
  ('alchemical-ammunition-sling-bullet-1', 'gear'::rpg.item_type, 'Projétil de Funda Alquímico (1)', '{"text":"55 PO"}'::jsonb, '100 g', 'Munição avançada de Grim Hollow. Exige proficiência na arma que dispara a munição e nível 3 ou superior.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"ammunition","advancedRequirement":{"kind":"advanced-ammunition","minLevel":3,"requiresWeaponProficiency":true},"ammunition":true,"propertyIds":[],"section":"alchemical-ammunition","alchemical":true}'::jsonb),
  ('specialized-ammunition-arrow-5', 'gear'::rpg.item_type, 'Flecha Especializada (5)', '{"text":"100 PO"}'::jsonb, '125 g', 'Munição avançada de Grim Hollow. Exige proficiência na arma que dispara a munição e nível 3 ou superior.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"ammunition","advancedRequirement":{"kind":"advanced-ammunition","minLevel":3,"requiresWeaponProficiency":true},"ammunition":true,"propertyIds":[],"section":"specialized-ammunition","specialized":true}'::jsonb),
  ('specialized-ammunition-bolt-5', 'gear'::rpg.item_type, 'Virote Especializado (5)', '{"text":"100 PO"}'::jsonb, '250 g', 'Munição avançada de Grim Hollow. Exige proficiência na arma que dispara a munição e nível 3 ou superior.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"ammunition","advancedRequirement":{"kind":"advanced-ammunition","minLevel":3,"requiresWeaponProficiency":true},"ammunition":true,"propertyIds":[],"section":"specialized-ammunition","specialized":true}'::jsonb),
  ('specialized-ammunition-paper-cartridge-bullet-10', 'gear'::rpg.item_type, 'Projétil de Cartucho de Papel (10)', '{"text":"250 PO"}'::jsonb, '250 g', 'Munição avançada de Grim Hollow. Exige proficiência na arma que dispara a munição e nível 3 ou superior.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"ammunition","advancedRequirement":{"kind":"advanced-ammunition","minLevel":3,"requiresWeaponProficiency":true},"ammunition":true,"propertyIds":[],"section":"specialized-ammunition","specialized":true}'::jsonb),
  ('specialized-ammunition-sling-bullet-5', 'gear'::rpg.item_type, 'Projétil de Funda Especializado (5)', '{"text":"100 PO"}'::jsonb, '250 g', 'Munição avançada de Grim Hollow. Exige proficiência na arma que dispara a munição e nível 3 ou superior.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"ammunition","advancedRequirement":{"kind":"advanced-ammunition","minLevel":3,"requiresWeaponProficiency":true},"ammunition":true,"propertyIds":[],"section":"specialized-ammunition","specialized":true}'::jsonb),
  ('other-ranged-ammunition-bellows-cannister', 'gear'::rpg.item_type, 'Cartucho de Fole (20 disparos)', '{"text":"5 PO"}'::jsonb, '2 kg', 'Munição avançada de Grim Hollow. Exige proficiência na arma que dispara a munição e nível 3 ou superior.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"ammunition","advancedRequirement":{"kind":"advanced-ammunition","minLevel":3,"requiresWeaponProficiency":true},"ammunition":true,"propertyIds":[],"section":"other-ranged-ammunition"}'::jsonb),
  ('other-ranged-ammunition-dragon-shot', 'gear'::rpg.item_type, 'Tiro Dragão (20)', '{"text":"5 PO"}'::jsonb, '1 kg', 'Munição avançada de Grim Hollow. Exige proficiência na arma que dispara a munição e nível 3 ou superior.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"ammunition","advancedRequirement":{"kind":"advanced-ammunition","minLevel":3,"requiresWeaponProficiency":true},"ammunition":true,"propertyIds":[],"section":"other-ranged-ammunition"}'::jsonb),
  ('other-ranged-ammunition-magazine', 'gear'::rpg.item_type, 'Pente', '{"text":"5 PO"}'::jsonb, '500 g', 'Uma arma com Pente também indica um número e um tipo de munição. A arma comporta essa quantidade e tipo, que você gasta antes de precisar recarregar. Como Ação Bônus, você pode remover um pente e recarregar com um pente novo. Uma arma com Pente vem com dois pentes vazios incluídos no custo e peso. Um pente vazio adicional custa 25 PO. Carregar um pente vazio leva 1 minuto.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"ammunition","advancedRequirement":{"kind":"advanced-ammunition","minLevel":3,"requiresWeaponProficiency":true},"ammunition":true,"propertyIds":[],"section":"other-ranged-ammunition"}'::jsonb),
  ('other-ranged-ammunition-paper-cartridge-bullet', 'gear'::rpg.item_type, 'Projétil de Cartucho de Papel (20)', '{"text":"3 PO"}'::jsonb, '1 kg', 'Munição avançada de Grim Hollow. Exige proficiência na arma que dispara a munição e nível 3 ou superior.', '{"source":"grim-hollow","editionSlug":"grim-hollow-players-guide-2024-en","citationSlug":"grim-hollow-players-guide-2024-en:chapter-5-advanced-weapons-equipment","catalogKind":"ammunition","advancedRequirement":{"kind":"advanced-ammunition","minLevel":3,"requiresWeaponProficiency":true},"ammunition":true,"propertyIds":[],"section":"other-ranged-ammunition"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  cost = EXCLUDED.cost,
  weight = EXCLUDED.weight,
  description = EXCLUDED.description,
  properties = EXCLUDED.properties,
  item_type = EXCLUDED.item_type;
