-- Grim Hollow Cap. 3 — atributos e perícias dos antecedentes

INSERT INTO rpg.phb_background_ability_option (background_id, ability_id, sort_order)
VALUES
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-agent-of-the-augustine'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-agent-of-the-augustine'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-agent-of-the-augustine'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-antiquarian'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-antiquarian'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-antiquarian'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-beast-hunter'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-beast-hunter'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-beast-hunter'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-beggar'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-beggar'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-beggar'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-chapter-knight'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-chapter-knight'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-chapter-knight'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-courtier'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-courtier'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-courtier'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-disgraced-raider'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-disgraced-raider'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-disgraced-raider'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-envoy'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-envoy'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-envoy'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-executioner'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-executioner'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-executioner'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-explorer'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-explorer'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-explorer'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-exterminator'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-exterminator'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-exterminator'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-fey-blessed'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-fey-blessed'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-fey-blessed'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-free-swords-mercenary'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-free-swords-mercenary'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-free-swords-mercenary'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-heretic'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-heretic'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-heretic'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-inquisitor-of-the-faithful'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-inquisitor-of-the-faithful'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-inquisitor-of-the-faithful'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-lapsed-inquisitor'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-lapsed-inquisitor'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-lapsed-inquisitor'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-one-of-the-taken'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-one-of-the-taken'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-one-of-the-taken'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-physician'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-physician'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-physician'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-pioneer'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-pioneer'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-pioneer'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-pit-fighter'), (SELECT id FROM rpg.phb_ability WHERE slug = 'forca'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-pit-fighter'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-pit-fighter'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-pox-touched'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-pox-touched'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-pox-touched'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-prisoner'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-prisoner'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-prisoner'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-released-thrall'), (SELECT id FROM rpg.phb_ability WHERE slug = 'constituicao'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-released-thrall'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-released-thrall'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-scion-of-the-thaumaturge'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-scion-of-the-thaumaturge'), (SELECT id FROM rpg.phb_ability WHERE slug = 'sabedoria'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-scion-of-the-thaumaturge'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-syndicate-smuggler'), (SELECT id FROM rpg.phb_ability WHERE slug = 'destreza'), 1),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-syndicate-smuggler'), (SELECT id FROM rpg.phb_ability WHERE slug = 'inteligencia'), 2),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-syndicate-smuggler'), (SELECT id FROM rpg.phb_ability WHERE slug = 'carisma'), 3)
ON CONFLICT (background_id, ability_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO rpg.phb_background_skill (background_id, skill_id)
VALUES
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-agent-of-the-augustine'), (SELECT id FROM rpg.phb_skill WHERE slug = 'history')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-agent-of-the-augustine'), (SELECT id FROM rpg.phb_skill WHERE slug = 'persuasion')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-antiquarian'), (SELECT id FROM rpg.phb_skill WHERE slug = 'arcana')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-antiquarian'), (SELECT id FROM rpg.phb_skill WHERE slug = 'history')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-beast-hunter'), (SELECT id FROM rpg.phb_skill WHERE slug = 'animal-handling')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-beast-hunter'), (SELECT id FROM rpg.phb_skill WHERE slug = 'survival')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-beggar'), (SELECT id FROM rpg.phb_skill WHERE slug = 'insight')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-beggar'), (SELECT id FROM rpg.phb_skill WHERE slug = 'persuasion')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-chapter-knight'), (SELECT id FROM rpg.phb_skill WHERE slug = 'animal-handling')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-chapter-knight'), (SELECT id FROM rpg.phb_skill WHERE slug = 'athletics')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-courtier'), (SELECT id FROM rpg.phb_skill WHERE slug = 'insight')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-courtier'), (SELECT id FROM rpg.phb_skill WHERE slug = 'persuasion')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-disgraced-raider'), (SELECT id FROM rpg.phb_skill WHERE slug = 'athletics')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-disgraced-raider'), (SELECT id FROM rpg.phb_skill WHERE slug = 'nature')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-envoy'), (SELECT id FROM rpg.phb_skill WHERE slug = 'insight')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-envoy'), (SELECT id FROM rpg.phb_skill WHERE slug = 'persuasion')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-executioner'), (SELECT id FROM rpg.phb_skill WHERE slug = 'athletics')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-executioner'), (SELECT id FROM rpg.phb_skill WHERE slug = 'medicine')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-explorer'), (SELECT id FROM rpg.phb_skill WHERE slug = 'athletics')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-explorer'), (SELECT id FROM rpg.phb_skill WHERE slug = 'survival')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-exterminator'), (SELECT id FROM rpg.phb_skill WHERE slug = 'animal-handling')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-exterminator'), (SELECT id FROM rpg.phb_skill WHERE slug = 'medicine')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-fey-blessed'), (SELECT id FROM rpg.phb_skill WHERE slug = 'arcana')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-fey-blessed'), (SELECT id FROM rpg.phb_skill WHERE slug = 'performance')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-free-swords-mercenary'), (SELECT id FROM rpg.phb_skill WHERE slug = 'acrobatics')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-free-swords-mercenary'), (SELECT id FROM rpg.phb_skill WHERE slug = 'athletics')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-heretic'), (SELECT id FROM rpg.phb_skill WHERE slug = 'deception')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-heretic'), (SELECT id FROM rpg.phb_skill WHERE slug = 'religion')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-inquisitor-of-the-faithful'), (SELECT id FROM rpg.phb_skill WHERE slug = 'intimidation')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-inquisitor-of-the-faithful'), (SELECT id FROM rpg.phb_skill WHERE slug = 'religion')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-lapsed-inquisitor'), (SELECT id FROM rpg.phb_skill WHERE slug = 'persuasion')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-lapsed-inquisitor'), (SELECT id FROM rpg.phb_skill WHERE slug = 'religion')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-one-of-the-taken'), (SELECT id FROM rpg.phb_skill WHERE slug = 'arcana')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-one-of-the-taken'), (SELECT id FROM rpg.phb_skill WHERE slug = 'nature')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-physician'), (SELECT id FROM rpg.phb_skill WHERE slug = 'medicine')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-physician'), (SELECT id FROM rpg.phb_skill WHERE slug = 'nature')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-pioneer'), (SELECT id FROM rpg.phb_skill WHERE slug = 'athletics')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-pioneer'), (SELECT id FROM rpg.phb_skill WHERE slug = 'survival')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-pit-fighter'), (SELECT id FROM rpg.phb_skill WHERE slug = 'athletics')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-pit-fighter'), (SELECT id FROM rpg.phb_skill WHERE slug = 'performance')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-pox-touched'), (SELECT id FROM rpg.phb_skill WHERE slug = 'intimidation')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-pox-touched'), (SELECT id FROM rpg.phb_skill WHERE slug = 'medicine')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-prisoner'), (SELECT id FROM rpg.phb_skill WHERE slug = 'deception')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-prisoner'), (SELECT id FROM rpg.phb_skill WHERE slug = 'sleight-of-hand')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-released-thrall'), (SELECT id FROM rpg.phb_skill WHERE slug = 'perception')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-released-thrall'), (SELECT id FROM rpg.phb_skill WHERE slug = 'stealth')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-scion-of-the-thaumaturge'), (SELECT id FROM rpg.phb_skill WHERE slug = 'arcana')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-scion-of-the-thaumaturge'), (SELECT id FROM rpg.phb_skill WHERE slug = 'insight')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-syndicate-smuggler'), (SELECT id FROM rpg.phb_skill WHERE slug = 'history')),
((SELECT id FROM rpg.phb_background WHERE slug = 'gh-syndicate-smuggler'), (SELECT id FROM rpg.phb_skill WHERE slug = 'stealth'))
ON CONFLICT (background_id, skill_id) DO NOTHING;
