import type { EffectKind } from '../catalog-effect';

export const EXECUTABLE_KINDS = new Set<EffectKind>([
  'temp_hp',
  'heal',
  'spend_resource',
  'recover_resource',
  'recover_resource_to_max',
  'toggle_combat_flag',
  'sync_companion',
  'companion_command',
  'table_roll',
  'feature_dc',
  'heal_from_dice_pool',
  'grant_inspiration',
  'check_boost',
  'catalog_maneuver',
  'catalog_metamagic',
  'convert_spell_points',
  'firearm_reload',
  'firearm_fire',
  'wild_resurgence',
  'set_starry_form',
  'strike_self_cost',
  'set_tracker',
  'start_concentration',
  'survive_at_zero',
  'recover_spell_slot',
  'missile_mage_arm',
  'resource_fallback_spend',
  'moon_combat_wild_shape',
  'restore_resource_from_slot',
  'bind_pact_weapon',
  'psychic_blade_attack',
]);
